### ISSUE TITLE
Individual Project: Commit Message Conventions

### ISSUE THREAD

**Issue by huizhuansam** [nus-cs2103-AY2122S1/forum#1]
Hi Prof, is there a specific convention we should follow for the commit messages? Or can we write whatever we want as long as we understand it for ourselves?

**Comment by damithc** [comment]
You are the the first one to ask a question in this forum @huizhuansam Thanks for that :-)
I think this is what you are looking for https://nus-cs2103-ay2122s1.github.io/website/admin/standardsAndConventions.html
But no need to follow it just yet. We'll be adding it as requirement in a later week.

**Comment by huizhuansam** [comment]
Thanks Prof!

**Comment by SkyBlaise99** [comment]
Sorry to bring this up again but I didn't see this at first when I'm attemping IP. I have already commited but all I wrote for the commit message is just "Level X completed". I'm new to using soursetree so I thought the message is just to tell myself what the commit is about. Also I tend to only commit once for each level is that supposed to be the case?

**Comment by wpinrui** [comment]
If I'm understanding the website instructions correctly, I think importantly is that the commit that signifies the completion of each level should be tagged, e.g. Level-1, Level-2 etc. I believe these can be done even after commits have been pushed. As for changing the commit message of pushed commits, I think this is more complicated and I have no idea how it might be done.

**Comment by damithc** [comment]
Not to worry about the commit message convention for now guys. Following it is not a requirement at this point of the module.
We'll let you know explicitly when you should start following it. IIRC, it becomes a requirement from week 3 onwards. 
There is no need to update past commits to follow the convention either.

**Comment by huizhuansam** [comment]
I'm pretty sure it is not a good practice to change commit messages, especially after it has been pushed to remote + there are multiple commits on top of the commit you want to edit since you are effectively rewriting history. However, it can be done, and especially easy with a GUI; check out this [article](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).

**Comment by huizhuansam** [comment]
> Sorry to bring this up again but I didn't see this at first when I'm attemping IP. I think I looked through all the info regarding ip under project in week 2 and did not see the part about conventions.
> 
> I have already commited but all I wrote for the commit message is just "Level X completed". I'm new to using soursetree so I thought the message is just to tell myself what the commit is about. Also I tend to only commit once for each level is that supposed to be the case?

I'm pretty sure it is not a good practice to change commit messages, especially after it has been pushed to remote + there are multiple commits on top of the commit you want to edit since you are effectively rewriting history. However, it can be done, and especially easy with a GUI; check out this [article](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).

**Comment by damithc** [comment]
> I'm pretty sure it is not a good practice to change commit messages, especially after it has been pushed to remote + there are multiple commits on top of the commit you want to edit since you are effectively rewriting history. However, it can be done, and especially easy with a GUI; check out this [article](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).

Thanks for sharing this @huizhuansam 
Indeed it's possible and usually not recommended, especially so in this module because we use the commit timestamps to track your progress over time. Updating past commits will change the timestamp that can affect the accuracy of the progress tracking.

**Comment by SkyBlaise99** [comment]
Thank you people and prof. I shall leave the current work untouched first. Luckily my tags should still be correctly done.

**Comment by damithc** [comment]
> Just curious, according to Git conventions, `Add README.md` is preferred than `Added README.md`. Is there some rational behind this because I find it more natural to say `I did this this this` as a comment for a commit.

Good question @SkyBlaise99 
As this issue was for raising a different question and is already closed, perhaps you can this question as new issue so that others can join in in the discussion?

**Comment by SkyBlaise99** [comment]
Yup sure thing
