### ISSUE TITLE
"No tests were found" while trying to use JUnit

### ISSUE THREAD

**Issue by lwj1711** [nus-cs2103-AY2122S1/forum#100]
Hi all,

I am currently having an issue when attempting Step 7 of "Using JUnit" (https://se-education.org/guides/tutorials/junit.html)

I have retried many times and am current stuck with a problem where my dummy test is not found by IntelliJ:

![image](https://user-images.githubusercontent.com/77188192/130815309-cc20850a-6894-4af4-a224-733afb9c4d71.png)

Attached are my file and project structures if they may help.

![image](https://user-images.githubusercontent.com/77188192/130815741-b0b0a577-048d-4393-b341-2b6501b241d4.png)

![image](https://user-images.githubusercontent.com/77188192/130815863-44700209-b764-4802-8da6-4b389c25e55f.png)

Does anyone know why I am encountering this problem and have a solution for it? Thank you very much.

**Comment by damithc** [comment]
@lwj1711 What happens if you click the green arrow at line 7 or 9? Same error?

**Comment by lwj1711** [comment]
@damithc Hi Prof, I get the same error when using either of the arrows too. :(

**Comment by lwj1711** [comment]
Hi, I managed to find the problem. Apparently I was running the tests under my 'test' module instead of my root module.

A small pop up appears briefly upon running the tests each time, and clicking on it has allowed the tests to be run under the root module and solved my problem.

Thank you!
