### ISSUE TITLE
JSON.simple

### ISSUE THREAD

**Issue by huizhuansam** [nus-cs2103-AY2122S1/forum#101]
## Library
[JSON.simple](https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple/1.1.1)

## Purpose
Parsing Java objects to JSON and vice versa.

## License
[Apache 2.0 License](https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple/1.1.1#:~:text=5.7.2-,Licenses,-License)

**Comment by damithc** [comment]
Approved.

**Comment by huizhuansam** [comment]
Thanks, @damithc. Closing this issue.
