### ISSUE TITLE
Automated-testing issue - Test output cut off and "dos2unix command not found" error

### ISSUE THREAD

**Issue by ramapriyan912001** [nus-cs2103-AY2122S1/forum#11]
Hi,
I followed all the instructions provided in the docs.
I have tried manually inputting the test commands, and see no issue in the outputs.
As such, I copied these outputs directly from the terminal and pasted them in my EXPECTED.txt file.
The corresponding inputs are in my input.txt file.

However, when I run the .sh script, I see the tests fail and the actual.txt file only shows a fraction of the output that should be seen.
I also see some kind of error "dos2unix command not found" pertaining to a command in the .sh file, in the terminal window.
I have included screenshots of my actual.txt, input.txt, expected.txt, and my terminal upon running the script.
Kindly help me resolve this issue.

**ACTUAL.txt**
<img width="1792" alt="Screenshot 2021-08-15 at 5 27 17 PM" src="https://user-images.githubusercontent.com/64624151/129479993-75a5a024-c1a3-4a7c-b9d7-42f95bec7086.png">

**EXPECTED.txt**
<img width="1792" alt="Screenshot 2021-08-15 at 5 27 32 PM" src="https://user-images.githubusercontent.com/64624151/129479997-0b8178a3-26e2-46d7-ba14-9c55546e6063.png">

**input.txt**
<img width="1792" alt="Screenshot 2021-08-15 at 5 27 37 PM" src="https://user-images.githubusercontent.com/64624151/129479999-0a4b2a5e-00ef-4d2d-be24-c3267765c8f1.png">

**Terminal output with errors displayed**
<img width="627" alt="Screenshot 2021-08-15 at 5 28 32 PM" src="https://user-images.githubusercontent.com/64624151/129480000-7b405e65-1360-4c02-a6e2-5df2fffa2e9f.png">

**Comment by marcuspeh** [comment]
Have you tried installing dos2unux?

https://brewinstall.org/install-dos2unix-on-mac-with-brew/

**Comment by ramapriyan912001** [comment]
Ah so turns out there was a version mismatch.
Fixed the version mismatch on dos2unix.
Still fails the test though.

**Comment by waynetee** [comment]
did you save input.txt?

**Comment by ramapriyan912001** [comment]
yeah of course

**Comment by marcuspeh** [comment]
> Ah so turns out there was a version mismatch.
> Fixed the version mismatch on dos2unix.
> Still fails the test though.

Is the output full now? Maybe can copy and out on those text difference checker website and see. Mine failed at first and it turns out is my actual output has an extra new line at the end of the file.

**Comment by waynetee** [comment]
can you run `cat input.txt`?

**Comment by ramapriyan912001** [comment]
ah never mind, found the issue.
The issue was that I kept reinitialising the scanner, and that meant the script would terminate early.
It's resolved now.
Thanks!

**Comment by damithc** [comment]
@ramapriyan912001 glad to hear you resolved the issue.
Thanks everyone who pitched in with suggestions. 💯
