### ISSUE TITLE
Pushing add-gradle-support branch

### ISSUE THREAD

**Issue by zhenxuantan** [nus-cs2103-AY2122S1/forum#111]
I was adding Gradle support and added the `add-gradle-support` branch. Then I couldnt push it using SourceTree because "Updates were rejected because the tip of your current branch is behind", even though there shouldn't be any updates. I merged back to master and pushed but SourceTree still did not allow me to do so. Then, I do not know what I did, but I managed to push it. But it got pushed to the original iP repository by Prof Damith, and it wasn't pushed to my forked repository.

This is how my SourceTree look like now.
![image](https://user-images.githubusercontent.com/1651302/131181330-3a4bb1e4-e5bb-4062-925e-d8db293f4a3c.png)

I think it somehow got merged into Prof's add-gradle-support branch.
![image](https://user-images.githubusercontent.com/1651302/131181388-5bf0a93c-2487-48df-9285-14bd328be050.png)

How do I fix this 🆘

**Comment by damithc** [comment]
> But it got pushed to the original iP repository by Prof Damith, and it wasn't pushed to my forked repository.

@zhenxuantan this is not possible, as you don't have write permissions to https://github.com/nus-cs2103-AY2122S1/ip

You seem to have reset the master branch to an earlier commit.
![image](https://user-images.githubusercontent.com/1673303/131203574-997f3dbd-10e2-49b3-b157-1561cd04d7f3.png)

Checkout the master branch, right-click on the merge commit (that is, the latest commit), and choose `reset current branch to this commit`. After that, push the master branch.

**Comment by zhenxuantan** [comment]
Hi Prof, thank you for the prompt reply! Yes I know that I cannot push into the repo, it instead asked me if I want to do a PR. The steps that you have given works! The red colour branch is still there, but I think it shouldn't affect anything. Thank You!
