### ISSUE TITLE
Giving credits to SE-EDU for Level-10 GUI Implementation

### ISSUE THREAD

**Issue by chrus-chong** [nus-cs2103-AY2122S1/forum#113]
As the title suggests, as someone with no prior experience with JavaFX, I have been heavily referring to the code provided by the [JavaFX tutorial @SE-EDU/guides](https://se-education.org/guides/tutorials/javaFx.html) as instructed by the Week 4 iP to create my Duke GUI. 

I would like to clarify if we are expected to formally give credit to SE-EDU as shown in the [Policy on reuse](https://nus-cs2103-ay2122s1.github.io/website/admin/appendixB-policies.html#policy-reuse) or will a simple "solution below adapted from ..." suffice?

Thank you very much

**Comment by damithc** [comment]
@chrus-chong You are welcome to but not strictly necessary in this case as all students are required to follow the tutorial, and the tutorial was created by the teaching team (not a third party).

**Comment by chrus-chong** [comment]
okay thank you very much!
