### ISSUE TITLE
Making Our own CheckStyle.xml

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#114]
I noticed that some of the restrictions in `CheckStyle.xml` from AB3 is not consisntent with our coding standard. Are we allowed to modify it and make it go according to our coding standard?

Some examples:

1. Separation between imports
![image](https://user-images.githubusercontent.com/69448615/131214081-01bca341-19ff-4907-b277-2831626b8d74.png)
![image](https://user-images.githubusercontent.com/69448615/131214108-74a4c172-e74a-4134-8d4e-127ba8d8f2f1.png)

1. Cannot declare variables in one line (idk whats the rational)
![image](https://user-images.githubusercontent.com/69448615/131214075-5b99bf6c-590a-4237-8235-315bbfa4d9ff.png)

1. Not letting me name the constants with all caps
![image](https://user-images.githubusercontent.com/69448615/131214161-fcd014e0-d936-421f-ac78-053abd4d2017.png)
![image](https://user-images.githubusercontent.com/69448615/131214174-9ad058d0-dc5e-491a-8adc-7caa62b839f9.png)

**Comment by damithc** [comment]
@SkyBlaise99 You may update the checkstyle config any way you see fit.

**Comment by SkyBlaise99** [comment]
Alright thx prof
