### ISSUE TITLE
Adapt gradle to initial project

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#115]
hi
as i start from scratch to adapt gradle to the individual project before, i found the given gradle tutorial not helpful, 
![image](https://user-images.githubusercontent.com/77196303/131218590-1f5d6938-4671-4483-8587-e39dc1ef8bdc.png)
as i run the command given in the picture in intellij's terminal, it doesn't recorgnize it as internal or external command.
then i just created a new gradle project and copy all the related stuff (build.gradle, settings.gradle)to my project, and i even don't know whether it works or not. 
![image](https://user-images.githubusercontent.com/77196303/131218748-3f4ddb32-26f1-476e-b12a-6424475bb094.png)
also, i don't know how to specify the main class name and just copy one from gradle tutorial, any one can give me more clarifications, thx

**Comment by damithc** [comment]
@qinguorui2001 were you following [this tutorial](https://se-education.org/guides/tutorials/gradle.html)? At which point of the tutorial did you get stuck?

**Comment by qinguorui2001** [comment]
> @qinguorui2001 were you following [this tutorial](https://se-education.org/guides/tutorials/gradle.html)? At which point of the tutorial did you get stuck?

I followed this tutorial, and i stuck at first step of Scenario 3

**Comment by SkyBlaise99** [comment]
my experience with the given gradle is just merge it to my main and change the `mainclass` which you showed. In my case, my `main` is in `Duke.java` which is `src/main/java/duke/Duke`, and i set it to `mainclass = 'duke.Duke'`

**Comment by damithc** [comment]
> > @qinguorui2001 were you following [this tutorial](https://se-education.org/guides/tutorials/gradle.html)? At which point of the tutorial did you get stuck?
> 
> I followed this tutorial, and i stuck at first step of Scenario 3

@qinguorui2001 Scenario 3 is given for completeness sake (not optimize for this module). You guys are supposed to follow Scenario 2 instead, as a branch with the required files is already present in the repo given to you.
![image](https://user-images.githubusercontent.com/1673303/131221489-e6093069-3082-4820-a14a-53269911cdd9.png)

**Comment by qinguorui2001** [comment]
oh, thx all, i click to the gradle tutorial link directly and miss this, i will be more careful in the future.
