### ISSUE TITLE
JavaFX Tutorial GUI returning weird text

### ISSUE THREAD

**Issue by itsyme** [nus-cs2103-AY2122S1/forum#118]
I am using a Mac Intel Big Sur. When I launch the application as per the tutorial I get this instead of "Hello World!"
<img width="65" alt="Screenshot 2021-08-28 at 10 19 58 PM" src="https://user-images.githubusercontent.com/71922282/131221054-9fcf1544-7896-4221-9c67-b98126577128.png">

**Comment by Jh123x** [comment]
Hi @itsyme I'm from your senior batch, just dropping by to help with tech issues.

Maybe you can try running `sudo xattr -d com.apple.quarantine com.apple.FinderInfo path/to/the/dylibs/lib*.dylib`  on your terminal

[Source](https://stackoverflow.com/questions/65368723/intellij-and-javafx-on-macos-big-sur)

Or try [this](https://stackoverflow.com/questions/66495254/opening-app-on-macos-11-big-sur-from-javafx-application-randomly-fails-with-klsn) if all else fails

**Comment by itsyme** [comment]
> Hi @itsyme I'm from your senior batch, just dropping by to help with tech issues.
> 
> Just checking, are you on M1 Mac or Intel Mac?
> 
> Maybe you can try running `sudo xattr -d com.apple.quarantine com.apple.FinderInfo path/to/the/dylibs/lib*.dylib` on your terminal
> 
> [Source](https://stackoverflow.com/questions/65368723/intellij-and-javafx-on-macos-big-sur)
> 
> Or try [this](https://stackoverflow.com/questions/66495254/opening-app-on-macos-11-big-sur-from-javafx-application-randomly-fails-with-klsn) if all else fails

Hi @Jh123x I am using an Intel Mac. Thanks I will try those and update here

**Comment by marcusleeeugene** [comment]
Hi @itsyme I'm from your senior batch as well, just dropping by to help with tech issues.

If the solution provided by @Jh123x doesn't work, maybe it could be an issue with the font on your system:
1) Test if the Segoe UI font is actually working correctly on your system, maybe in Microsoft Word
2) If not, you can reinstall the font family

Source: [Why JavaFX application and scene builder is showing garbled text?](https://stackoverflow.com/questions/66747171/why-javafx-application-and-scene-builder-is-showing-garbled-text)

**Comment by Jh123x** [comment]
> Hi @itsyme I'm from your senior batch as well, just dropping by to help with tech issues.
> 
> If the solution provided by @Jh123x doesn't work, maybe it could be an issue with the font on your system:
> 
> 1. Test if the Segoe UI font is actually working correctly on your system, maybe in Microsoft Word
> 2. If not, you can reinstall the font family
> 
> Source: [Why JavaFX application and scene builder is showing garbled text?](https://stackoverflow.com/questions/66747171/why-javafx-application-and-scene-builder-is-showing-garbled-text)

@itsyme This solution seems more matching to the problem than the solutions I have found

**Comment by itsyme** [comment]
I found the problem. The default font for JavaFX was not loading properly so I just manually changed the font to another font that works. Thanks all!!

**Comment by wangpeialex** [comment]
@itsyme Hi can I ask how to change the default font for javaFX 🤔 ? I am using a intel macOS BigSur too.

**Comment by xlzior** [comment]
@wangpeialex I used the top solution [here](https://stackoverflow.com/questions/18408884/set-font-globally-in-javafx) but I'm not sure how @itsyme did it.

**Comment by willyamped** [comment]
Hi, @itsyme . Could you please let me know how you changed the font? I am running into an error when I type `scene.getStylesheets().add(getClass().getResource("stylesheet.css").toExternalForm());`

This is what I have in stylesheet.css:
```java
.root{
    -fx-font-size: 16pt;
    -fx-font-family: "Courier New";
}
```

This is where I place my `stylesheet.css` file.
<img width="295" alt="Screenshot 2021-08-31 at 10 32 01 AM" src="https://user-images.githubusercontent.com/66423703/131432181-9bbf8e55-d85f-435b-bad2-96319d21e793.png">

This is my current code in my main:

```java
...
AnchorPane mainLayout = new AnchorPane();
        mainLayout.getChildren().addAll(scrollPane, userInput, sendButton);
        scene = new Scene(mainLayout);
        scene.getStylesheets().add(getClass().getResource("stylesheet.css").toExternalForm());
        stage.setScene(scene);
        stage.show();
...
```

Thank you so much!

**Comment by marcusleeeugene** [comment]
> Hi, @itsyme . Could you please let me know how you changed the font? I am running into an error when I type `scene.getStylesheets().add(getClass().getResource("stylesheet.css").toExternalForm());`
> 
> This is what I have in stylesheet.css:
> 
> ```java
> .root{
>     -fx-font-size: 16pt;
>     -fx-font-family: "Courier New";
> }
> ```
> 
> This is where I place my `stylesheet.css` file.
> <img alt="Screenshot 2021-08-31 at 10 32 01 AM" width="295" src="https://user-images.githubusercontent.com/66423703/131432181-9bbf8e55-d85f-435b-bad2-96319d21e793.png">
> 
> This is my current code in my main:
> 
> ```java
> ...
> AnchorPane mainLayout = new AnchorPane();
>         mainLayout.getChildren().addAll(scrollPane, userInput, sendButton);
>         scene = new Scene(mainLayout);
>         scene.getStylesheets().add(getClass().getResource("stylesheet.css").toExternalForm());
>         stage.setScene(scene);
>         stage.show();
> ...
> ```
> 
> Thank you so much!
Hi, @willyamped, what error are you getting? You can try moving your stylesheet.css into the resources folder and see if it works.

**Comment by willyamped** [comment]
Hi @marcusleeeugene. Thank you for the reply. Attached is a screenshot of the error message

<img width="1380" alt="Screenshot 2021-08-31 at 2 17 39 PM" src="https://user-images.githubusercontent.com/66423703/131451850-6b8cb54b-fdea-484a-983a-84e1ffbf8ff4.png">

**Comment by xlzior** [comment]
Yep, I think `stylesheet.css` needs to be in the resources folder, since the method is called `getResource`.

**Comment by willyamped** [comment]
Hi @marcusleeeugene, @xlzior. Thanks for the suggestions. I have moved my `.css` file into the `resources` folder. However, I am still running into the same problem. It seems that `.toExternalForm()` may return null pointer exception

<img width="1032" alt="Screenshot 2021-08-31 at 2 38 04 PM" src="https://user-images.githubusercontent.com/66423703/131454336-74b77729-b133-4b85-a9b7-8b93dc8912e1.png">


<img width="298" alt="Screenshot 2021-08-31 at 2 40 09 PM" src="https://user-images.githubusercontent.com/66423703/131454424-219e57a5-5ce4-4d03-8275-8a4ed00fa701.png">

**Comment by wangpeialex** [comment]
> @wangpeialex I used the top solution [here](https://stackoverflow.com/questions/18408884/set-font-globally-in-javafx) but I'm not sure how @itsyme did it.

Thank you very much! @xlzior

**Comment by mokdarren** [comment]
@willyamped  try using this instead to add the .css file:

`scene.getStylesheets().add("application.css");`

**Comment by SkyBlaise99** [comment]
Or you can simply add the css using a scene builder here
![image](https://user-images.githubusercontent.com/69448615/131769464-5bbbcc94-40e1-42d7-b8a8-33962c44685f.png)
