### ISSUE TITLE
IntelliJ: Unable to run Duke main and Test files after trying to set up Gradle

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#119]
After adding gradle files (build.gradle, gradlew, gradle.bat) and trying to build, I noticed that I can no longer select the main method to run:

![image](https://user-images.githubusercontent.com/40263305/131223492-37783b65-8f8d-45c2-9908-73669f64a493.png)
<br />

Additionally, in the test files, IntelliJ is unable to find the imports correctly:

![image](https://user-images.githubusercontent.com/40263305/131223590-87b24383-8e99-42e5-b8c3-ab2968fbdad4.png)

<br />

This is the project structure currently (after deleting the gradle files):

![image](https://user-images.githubusercontent.com/40263305/131223658-2b08d849-6d7f-40e2-95e3-628c40bdd160.png)

<br/>

### What I Tried
I cloned my repo and opened it in IntelliJ, but got a similar result (unable to run main and tests):
 
<img width="860" alt="Screenshot 2021-08-28 at 11 36 39 PM" src="https://user-images.githubusercontent.com/40263305/131223422-b23cc51d-f8c1-4e75-9cd5-5ece89e49578.png">

When setting up Gradle I used the following as my `build.gradle` as recommended by IntelliJ [here](https://www.jetbrains.com/help/idea/gradle.html#convert_project_to_gradle):

```java
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}
sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}
dependencies {
    compile 'junit:junit:4.12'
}
```

**Comment by zacharylwy** [comment]
Hi Alard, do you mind sharing what were the steps you went through (commands that you used) to add the gradle files (build.gradle, gradlew, gradle.bat? And when you said that you tried cloning from your repo, did you also just clone from your latest commit?

**Comment by AllardQuek** [comment]
> Hi Alard, do you mind sharing what were the steps you went through (commands that you used) to add the gradle files (build.gradle, gradlew, gradle.bat)? 

Hi! I used `brew install gradle` and copied the build.gradle snippet above. Then, I loaded the Gradle project by clicking on this pop up:

![image](https://user-images.githubusercontent.com/40263305/131226629-0746ca21-5042-44b6-a482-dc2c441fce3a.png)

Once loaded, I tried `gradle clean` which worked fine, but it seems after doing `gradle clean build` did the errors start showing up.

<br /> 

> And when you said that you tried cloning from your repo, did you also just clone from your latest commit?

Yes I cloned the latest commit from the master branch.

**Comment by tanjiaxian99** [comment]
I got a similar problem after setting up Gradle. You can try clicking on `File`, then `Invalidate Caches / Restart`, followed by `INVALIDATE AND RESTART`.

**Comment by uyencfi** [comment]
I think you can try merging the branch `add-gradle-support` to add the Gradle files instead of adding them by yourself (that's how I did it following the [SE-EDU tutorial](https://se-education.org/guides/tutorials/gradle.html) given on the cs2103 web page).

**Comment by AllardQuek** [comment]
Thanks @tanjiaxian99 and @uyencfi! Seems to work fine now, I can run the files, and run `gradle clean build` with no issues. 
<hr>

I first invalidated the cache and reassigned the source and test folders, which allowed me to run the main and test files.

![image](https://user-images.githubusercontent.com/40263305/131227536-935150f2-072b-42ad-acee-a04ae150ffd4.png)

After merging the `add-gradle-support` branch, I was to load the gradle project in intelliJ and run a few gradle commands.
