### ISSUE TITLE
Available time of iP progress dashboard

### ISSUE THREAD

**Issue by HolmesJJ** [nus-cs2103-AY2122S1/forum#12]
May I please ask when the grading scripts will be available? It shows that it will run once a day but still doesn't have any data at the link below:
https://nus-cs2103-ay2122s1.github.io/dashboards/contents/ip-progress.html

**Comment by fans2619** [comment]
I think it's from Week 3 onwards. Correct me if I'm wrong.

**Comment by damithc** [comment]
> I think it's from Week 3 onwards. Correct me if I'm wrong.

Correct, it will be around week 3. We'll let you know when it is ready. Still waiting for some students to submit their GitHub usernames, which we need to set up the iP dashboard.

**Comment by HolmesJJ** [comment]
> > I think it's from Week 3 onwards. Correct me if I'm wrong.
> 
> Correct, it will be around week 3. We'll let you know when it is ready. Still waiting for some students to submit their GitHub usernames, which we need to set up the iP dashboard.

Thank you so much Prof. Damith. And may I please have one more inquiry how I can know whether I pushed my work properly now if I cannot check on the website?

**Comment by damithc** [comment]
> Thank you so much Prof. Damith. And may I please have one more inquiry how I can know whether I pushed my work properly now if I cannot check on the website?

Not to worry @HolmesJJ Once the dashboard is up, you can detect any issues and fix them. There is no penalty for mistakes as long as you fix them after being detected.

**Comment by damithc** [comment]
BTW, I have started updating the iP progress dashboard, although I haven't formally announced it to the class yet.
https://nus-cs2103-ay2122s1.github.io/dashboards/contents/ip-progress.html
