### ISSUE TITLE
Running Duke using Gradle throws NoSuchElementException at Scanner.nextLine

### ISSUE THREAD

**Issue by Tanishq4331** [nus-cs2103-AY2122S1/forum#120]
Development Environment:
- Java Version 11 (WSL)
- WSL2
- IntelliJ 2021.2
- JUnit Version 4.13.1

I recently added Gradle to my iP by merging `add-gradle-support` into `master`. The project builds successfully but while running it, Scanner.nextLine throws a NoSuchElementException. Here's the stack trace for the issue:

![image](https://user-images.githubusercontent.com/62829987/131237295-5fbb359e-dc99-475e-b586-0240e42877e1.png)

This is the build.gradle file.
```
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '5.1.0'
}

repositories {
    mavenCentral()
}

dependencies {
    testCompile 'junit:junit:4.12'
    compile 'junit:junit:4.12'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"
        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClassName = "duke.Duke"
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
}

checkstyle {
    toolVersion = '8.29'
}

run {
    standardInput = System.in
}

```
Thanks for the help!

**Comment by jiarong15** [comment]
Hi maybe can take a look at your UI class?

**Comment by Tanishq4331** [comment]
Sure, here are the relevant parts

```
package duke.main;

import duke.task.Task;
import duke.task.TaskList;

import java.util.List;
import java.util.Scanner;

public class Ui {
    private final Scanner inputScanner;

    /**
     * Constructor for Duke UI
     */
    public Ui() {
        this.inputScanner = new Scanner(System.in);
        greetOnStart();
    }

    /**
     * Gets the next input from the user.
     *
     * @return String input.
     */
    public String getNextInput() {
        return inputScanner.nextLine();
    }

    /**
     * Stops taking inputs from the user.
     */
    public void closeInput() {
        inputScanner.close();
    }

    ...
}
```

**Comment by SkyBlaise99** [comment]
I looked at your `UI.java`, it is almost the same as mine and mine is working so yours should be as well. Hence I looked at ur `Duke.java`. I see that in your `run()`, you have your input outside the while loop at line 44. Not sure if that is the cause but maybe you can try to do this?
``` java
while (true) {
    String input = ui.getNextInput();
    // ur codes
}

**Comment by Tanishq4331** [comment]
I tried the suggestion but the issue still remains. I think it has something to do with the config since the same exception is thrown when I try this

```
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String input = scanner.nextLine();
    }
```

**Comment by waynetee** [comment]
![image](https://user-images.githubusercontent.com/17681226/131246685-b4626326-e1e9-42d0-970f-271f0c521724.png)
Do you see something like this? Could you click the green run arrow and show us what happens?

**Comment by Tanishq4331** [comment]
It still results in the same error. Here's the stack trace for it.

![image](https://user-images.githubusercontent.com/62829987/131255174-b3c7d563-10d9-43f2-87af-3db3fa93c8c2.png)

**Comment by waynetee** [comment]
It's pretty interesting that you are running this on wsl.

I suspect it's hard for intelij to pipe your input all the way to the wsl process.

Perhaps you can try `./gradlew run` on the wsl terminal and see if it works.

Later on, you might run into further problems when you start adding a gui on wsl.

Unless you are confident to proceed, can I suggest you use windows instead? Perhaps this would be the easier way out. :)

**Comment by damithc** [comment]
@Tanishq4331 is your problematic code already on your fork? If so, someone can clone it and try to troubleshoot the problem based on your exact code.

**Comment by Tanishq4331** [comment]
I couldn't resolve the issue on WSL, but using Windows like @waynetee suggested fixed the issue. 

Thanks everyone!
