### ISSUE TITLE
gradlew is not recognized as internal or external command,and build fails

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#121]
hi
i used intellij(2021,02), java 11.after merging add gradle branch to my master branch, i changed main class name to the correct one, and then i tried to run some tasks like build in gradle  panel, but gradlew is not recognized in intellij terminal and build fails.
![image](https://user-images.githubusercontent.com/77196303/131238331-cffc8bd4-8123-4b68-a76b-6f7f33c41342.png)

```
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '5.1.0'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClassName = "duke.Duke"
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
}

checkstyle {
    toolVersion = '8.29'
}

run{
    standardInput = System.in
    enableAssertions = true
}
```

any clarification

**Comment by rohit0718** [comment]
according to your screenshot, gradle seems to be working fine. ure missing the checkstyle file that you need to add yourself

**Comment by qinguorui2001** [comment]
> according to your screenshot, gradle seems to be working fine. ure missing the checkstyle file that you need to add yourself

i am not sure whether  u encountered this before or not, how you add the file not given, and i don't know why some variables in test logging shows No candidates found for method call. (I reload all gradle projects already)

**Comment by rohit0718** [comment]
yup i got this before, added the `checkstlye.xml` and `suppresions.xml` from this project https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle.
maybe u can post some screenshots for the "no cadidates found" problem? didnt run into that one.

**Comment by qinguorui2001** [comment]
> yup i got this before, added the `checkstyle.xml` and `suppressions.xml` from this project https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle.
> maybe u can post some screenshots for the "no cadidates found" problem? didnt run into that one.

![image](https://user-images.githubusercontent.com/77196303/131240699-16597c23-b7dd-4e73-89d0-a5a07ddab430.png)

**Comment by rohit0718** [comment]
haha realised i have this as well. seems to be some indexing issue with intellij as the syntax is correct as per https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.logging.TestLoggingContainer.html.
anyway shd be safe to ignore this warning as your gradle tasks are working just fine.

**Comment by qinguorui2001** [comment]
> haha realised i have this as well. seems to be some indexing issue with intellij as the syntax is correct as per https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.logging.TestLoggingContainer.html.
> anyway shd be safe to ignore this warning as your gradle tasks are working just fine.
thx for pointing out, last issue is when i try to run gradlew xxx(some command) in intellij terminal, it shows gradlew is not an internal or external command...

**Comment by rohit0718** [comment]
u can run `./gradlew` from the project root since the project root is not in ur PATH

**Comment by qinguorui2001** [comment]
> u can run `./gradlew` from the project root since the project root is not in ur PATH

Thank you very much. You solved all my issues completely, very precious to your work!
