### ISSUE TITLE
Proper way to write jUnit tests for methods that may throw more than 1 error

### ISSUE THREAD

**Issue by jiarong15** [nus-cs2103-AY2122S1/forum#122]
Wish to check on how do I write such tests? For example, in my case, creating an instance of object A may throw error 1 or error 2. 

Assuming that in my test that I wrote, if I supply the correct inputs in the instantiation, no exceptions will be thrown and hence what should I include in the catch block in my test class?
However, if I supply 1 erroneous input which will cause either error 1 or error 2, what do I include in the expected outcome in the assertEquals(expected, actual) method in the try block in the test class?

**Comment by pss-coder** [comment]
Hi @jiarong15,

there is plenty of ways to use testing exceptions in this case. 

To test for exceptions: 

1. You can use assertThrows, for example: 

```
// expecting an Exception to be thrown when initialising Object A

assertThrows(Exception.class, () ->
            { 
                 Object A = new Object();
            });
```

2. Using try, catch and assertTrue:

```
try{
        Object A = new Object();
        boolean caught = false;

        } catch (NullPointerException e) {
             caught = true;
            // true if NullPointerException is caught, otherwise show message
            //assertTrue(caught, "null pointer exception NOT thrown");
            
        } catch (SomeOtherException e1) {
             caught = true;
           // true if SomeOtherException is caught, otherwise show message
            assertTrue(caught, "exception NOT thrown");
        }
```

> Assuming that in my test that I wrote, if I supply the correct inputs in the instantiation, no exceptions will be thrown and hence what should I include in the catch block in my test class?

My view on this would then be to create a method and not use a try catch and use the throws keyword on the method signature. Given that you ensured your inputs are correct.

There are many other assert methods besides `assertEquals()` that can help in your test cases.

I hope this helps.

**Comment by jiarong15** [comment]
alright thanks! Found the documentation!
