### ISSUE TITLE
JUnit import statements not working anymore

### ISSUE THREAD

**Issue by houtenteo** [nus-cs2103-AY2122S1/forum#123]
After merging the add-gradle-support branch, my JUnit tests do not work anymore. Anyone knows why and how can I fix this?

![import](https://user-images.githubusercontent.com/77191381/131241011-e19ed066-aa9a-4275-9252-687d719089f8.jpg)

**Comment by rohit0718** [comment]
have u followed the guide in scenario 2 as well? https://se-education.org/guides/tutorials/gradle.html

**Comment by houtenteo** [comment]
@rohit0718 yea I followed the guide to scenario 2

**Comment by damithc** [comment]
@houtenteo try File -> Invalidate cache

**Comment by houtenteo** [comment]
@damithc nope the problem is still there

**Comment by rohit0718** [comment]
have u configured ur `build.gradle` for junit tests?

**Comment by houtenteo** [comment]
@rohit0718 i followed the [guide](https://docs.gradle.org/current/userguide/java_testing.html#using_junit5)

![dependencies](https://user-images.githubusercontent.com/77191381/131242620-15033d15-4f21-41d2-8c35-a5627ce92c51.jpg)

**Comment by SkyBlaise99** [comment]
> @rohit0718 i followed the [guide](https://docs.gradle.org/current/userguide/java_testing.html#using_junit5)
> 
> ![dependencies](https://user-images.githubusercontent.com/77191381/131242620-15033d15-4f21-41d2-8c35-a5627ce92c51.jpg)

I have a similar display on my Intelij (altho I dun have the issue). You can try hover your mouse on the yellow high-lighted parts, and intelij will give you suggestion to use the latest builds I believe.

**Comment by rohit0718** [comment]
@houtenteo u need to update ur `mainClassName` var to the right file as well https://github.com/houtenteo/ip/blob/master/build.gradle#L32

**Comment by houtenteo** [comment]
Ok I think I found my problem. Didn't realise I had to create a test folder. Rip my past 3hrs.
Thx guys @rohit0718 @SkyBlaise99
