### ISSUE TITLE
Gradlew clean fails to build, gives exception: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

### ISSUE THREAD

**Issue by clyveycui** [nus-cs2103-AY2122S1/forum#124]
## Issue
I merged the `add-gradle-support` branch and following the steps as described here under scenario 2. Tried running some of the tasks on the Intellij interface and most of the tasks worked (except runShadow for some reason, and the ones that require checkstyle.xml to run)

> These tasks work

![image](https://user-images.githubusercontent.com/38873431/131248683-496af658-e965-4df0-a6d5-178689974812.png)

I then tried running `gradlew clean` from the command line, and encountered this exception:
![image](https://user-images.githubusercontent.com/38873431/131248849-a2eecf81-0714-42e8-bca7-4962aa98878a.png)

And any follow up attempts to run `gradlew clean` again hits me with this:
![image](https://user-images.githubusercontent.com/38873431/131248877-3691d183-df1e-420c-9742-0a8c594db021.png)

Weirdly enough, running clean from the Intellij GUI works, so I have no idea what's going on.

Here is gradle version:
![image](https://user-images.githubusercontent.com/38873431/131249117-1de48965-8661-45d6-8c31-427efe59dff9.png)

SDK version: 11.0.9

### following the [tutorial](https://se-education.org/guides/tutorials/gradle.html#using-gradle-to-do-some-common-project-activities) scenario 2.

1. Merge `add-gradle-support` into main
2. Close the project
3. Delete .idea folder in project root
4. Let project rebuild after restarting
5. File > Invalidate Caches / Restart > INVALIDATE CACHE AND RESTART
6. Update build.gradle's application mainClassName 
```java
application {
    mainClassName = "duke.Duke"
}
```
7. Build project
8. Use windows command prompt and navigate to project root
9. run command `gradlew clean`

**Comment by damithc** [comment]
I tried the steps and could not reproduce the problem. Let's wait to see if anyone else encounters it.

**Comment by waynetee** [comment]
Hi @clyveycui 

As you can see in your last screenshot, you are using JVM version 16

Try something like this `gradlew run -Dorg.gradle.java.home="C:\Program Files\Java\jdk-11.0.9"`

**Comment by clyveycui** [comment]
Good spot! Turns out it runs on the ide because the ide is configured to use the 11.0.9 jdk, but from the command line uses the default jdk on the system which is the 16.0.2 version. Gradle 6.2 does not support the newer jdks, so it doesn't build correctly.

Thanks for the help.

**Comment by damithc** [comment]
> As you can see in your last screenshot, you are using JVM version 16

Good catch indeed @waynetee 💯

**Comment by zzybluebell** [comment]
Thanks, @clyveycui  I faced the same issues, solved by changing the Java JDK version  to 11:

https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos
