### ISSUE TITLE
JavaFX NoSuchMethodException when using launcher

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#125]
If you are facing this issue when following part 1 of javaFX tutorial, you need to make sure that your main program's constructor has no parameters. 
i.e. change
```java
public Duke(String filePath) {
        ...
}
```
to
```java
public Duke() {
        ...
}
```

**Comment by kleonang** [comment]
Just to add on, the NoSuchMethodException should disappear if you just add the empty constructor to your main class (e.g. Duke.java) so that you have 2 constructors, don't have to delete your existing constructor 😉

**Comment by softmagnet** [comment]
@kleonang i think adding is much better changing. Thanks for the tip!
