### ISSUE TITLE
Error in merging and processing gradle file: Could not install Gradle distribution

### ISSUE THREAD

**Issue by hmanhduc2k** [nus-cs2103-AY2122S1/forum#126]
Hi guys, I'm currently trying to merge my IP with the add-gradle branch, but when I try to reload gradle project, there is this error coming up on gradle sync issues:

`Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-6.2-bin.zip'.`

I've tried to download the file manually, but I couldn't understand how to actually import the zip file or whichever file is required. Moreover, when I deleted the .idea file, it automatically reinstated itself when I reopened my project, and the error messages keep repeat even after many times closing-reopening.

Can anyone give some suggestions?

Thank you!

**Comment by damithc** [comment]
@hmanhduc2k this could be a temporary issue on the gradle.org side. Could you try again?
You can also try using a fresh clone of duke, just to see if the problem happens even when you don't have any code change on your side.

**Comment by hmanhduc2k** [comment]
Hi Prof, I have successfully resolved the issue although I'm not really sure how I resolve it. I deleted a few files, reimport and reinstall dependencies and it somehow work. Thank you for your help!
