### ISSUE TITLE
can't seem to run my jar file

### ISSUE THREAD

**Issue by jiarong15** [nus-cs2103-AY2122S1/forum#127]
Have used this command: gradlew shadowJar and jar file name duke.jar is placed in my folder build > libs  > duke.jar. However, can't seem to run it with the command java -jar duke.jar. it say unable to access jarfile. Even after  I cd into the directory, it says seedu.duke.Duke classNotFoundException

**Comment by NicolasCwy** [comment]
Hi Jia Rong, from the sounds of it you have merged add-gradle-support into your branch.

Do you have a package called seedu? Since the build.gradle file was meant to have a package structure seedu > duke > Duke, if you don't follow this it would cause an error

Could you check your `<project root dir>/build.gradle` and under `application`change `mainClassName`to somePackage.another.Mainclass. I have included an example below.

<img width="274" alt="image" src="https://user-images.githubusercontent.com/25302138/131276197-a5cd1b48-6695-4060-ac02-94fee9075ece.png">

My package structure to get to my main class, is kermit.Kermit, so I would change it to the following
```
    application {
         mainClassName = "kermit.Kermit"
   }
```

**Comment by jiarong15** [comment]
I've gotten rid of that file and instead manually build a jar artifact. my new jar file not locates at
<project root dir>/out/ip_jar/ip.jar. However it still doesn't seem to work when I call java -jar ip.jar 
it throws classNotFoundException: duke.LaunchDuke

application {
    mainClassName = "duke.LaunchDuke"
}

**Comment by NicolasCwy** [comment]
Could you follow this [tutorial](https://se-education.org/guides/tutorials/jar.html) and see if you still face the same issue?

Were you able to use the .jar file previously or is this the first time you are trying to create and run one?

**Comment by jiarong15** [comment]
My first time trying to create one! Anyways I seem to be only able to build it within the ip/src/main/out dir. Is it supposed to be as such? I tried building in ip/out nothing seems to appear. Additionally, now everytime I run the jar file it seems like the old inputs keyed into duke won't be stored into local disk anymore. Is this the correct functionality?

**Comment by damithc** [comment]
> Have used this command: gradlew shadowJar and jar file name duke.jar is placed in my folder build > libs > duke.jar. However, can't seem to run it with the command java -jar duke.jar. it say unable to access jarfile. Even after I cd into the directory, it says seedu.duke.Duke classNotFoundException

@jiarong15 try these steps again:

1. In your build.gradle, update this part to match your package structure.
   ```
    application {
         mainClassName = "duke.Duke"
   }
   ```
2. Create the JAR file using `gradlew shadowJar` command.
3. cd into `build/libs` and run `java -jar duke.jar` (adjust to match the jar file name)

**Comment by jiarong15** [comment]
yeap works! But the application don't seem to be able to read in previous tasks stored in it. And always returns "Error in loading task in local disk!". Is this supposed to happen?

**Comment by damithc** [comment]
> But the application don't seem to be able to read in previous tasks stored in it. And always returns "Error in loading task in local disk!". Is this supposed to happen?

@jiarong15 note the following instruction:
![image](https://user-images.githubusercontent.com/1673303/131285732-10d3ed0c-ed76-4106-ba03-c9d87582e48c.png)
