### ISSUE TITLE
Project directory marked as excluded

### ISSUE THREAD

**Issue by LuoZhijie-tom** [nus-cs2103-AY2122S1/forum#128]
I followed the instruction of creating JUnit and delete the module with the name ip. But then the entire project directory is marked as excluded and I can't run gradle, I'm really confused, does anyone know what's wrong with my configuation?
![Screenshot 2021-08-30 100317](https://user-images.githubusercontent.com/77223932/131275383-70581d2f-7219-4795-ad1e-43c839401bc3.jpg)
![Screenshot 2021-08-30 095608](https://user-images.githubusercontent.com/77223932/131275389-9910b0ba-af79-4329-9a76-57d07901df8c.jpg)

**Comment by damithc** [comment]
@LuoZhijie-tom After adding Gradle by following scenario 2 given [here](https://se-education.org/guides/tutorials/gradle.html#adding-gradle-to-the-project), you are supposed to delete the `.idea` folder which means the modules you created manually (as you described above) will be no more. They are not needed anymore as Gradle will take care of JUnit support anyway.

**Comment by LuoZhijie-tom** [comment]
But each time I delete the .idea folder and close the project and open it again, .idea folder is created automatically, is this supposed to be correct?
![Screenshot 2021-08-30 115702](https://user-images.githubusercontent.com/77223932/131283481-25d45558-8f1f-4def-a0ee-e08d9ec25bc4.jpg)

**Comment by damithc** [comment]
> But each time I delete the .idea folder and close the project and open it again, .idea folder is created automatically, is this supposed to be correct?

Yes @LuoZhijie-tom, Intellij will recreate the project structure when you reopen the project, but this time, it will be based on the Gradle requirements.

**Comment by LuoZhijie-tom** [comment]
Ok thanks prof! But there's still some error in my configuration when I click build, I still don't know how to fix it. May I ask how to fix this problem?
![Screenshot 2021-08-30 144236](https://user-images.githubusercontent.com/77223932/131299426-d8b83af9-8f08-4a06-8cde-7ae2410dd96c.jpg)

**Comment by damithc** [comment]
> Ok thanks prof! But there's still some error in my configuration when I click build, I still don't know how to fix it. May I ask how to fix this problem?

@LuoZhijie-tom as this is a different problem, you have a better chance of receiving a solution from others if you post a fresh issue with a matching title. I suspect some other students faced this problem and found a solution already. One of them might be able to share the solution with you.

**Comment by LuoZhijie-tom** [comment]
OK, Thank you Prof!
