### ISSUE TITLE
gradlew test gives "Test events not received"

### ISSUE THREAD

**Issue by Chesterwongz** [nus-cs2103-AY2122S1/forum#129]
After running gradlew test:
![image](https://user-images.githubusercontent.com/70138507/131280363-26a9c266-2250-4caa-92b7-9186251fd5b3.png)

My project structure:
![image](https://user-images.githubusercontent.com/70138507/131280567-8f2b427f-d5f7-41f4-bd1e-0f9d19a22eb7.png)

my tests have been annotated with @Test as well
```java
@Test
public void testConvertToDoToData() {
     String commandDesc = "NEW TODO";
     ToDo task = new ToDo(commandDesc);
     String expected = "T| |NEW TODO";
     assertEquals(expected, task.toData());
}
```

**Comment by damithc** [comment]
@Chesterwongz are you able to run individual test files? i.e., by clicking on the green play button in each test file

**Comment by Chesterwongz** [comment]
@damithc I am not able to run them individually. Clicking the green play button gives "No tasks available"
![image](https://user-images.githubusercontent.com/70138507/131286205-c3d66f14-4be4-45be-86f4-0a16966b9d8d.png)

**Comment by damithc** [comment]
@Chesterwongz Have you tried File -> Invalidate cache ?

**Comment by Chesterwongz** [comment]
@damithc just tried, still doesn't work

**Comment by damithc** [comment]
@Chesterwongz perhaps you can push the current state of the code to your fork so that someone else can clone it and try to find out if they can replicate the problem?

BTW, I noticed that your first screenshot has `NO SOURCE` for tasks related to tests. Perhaps you can share the content of your build.gradle file here as well?

**Comment by Chesterwongz** [comment]
@damithc Ok, I have pushed the code into my gradle branch [here](https://github.com/Chesterwongz/ip/tree/branch-A-Gradle)
Here is my build.gradle file:
```
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '5.1.0'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClassName = "duke.Duke"
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
}

checkstyle {
    toolVersion = '8.29'
}

run{
    standardInput = System.in
}
```

**Comment by Chesterwongz** [comment]
@damithc Thanks for the help, I have found a solution to the issue after looking for difference between my project and others.
It seems that the path to the tests need to be exactly `/src/test/java/test.java`.
Like this:
![image](https://user-images.githubusercontent.com/70138507/131327438-98c98899-a5c3-43bb-8ba8-958632bb0bdd.png)

**Comment by damithc** [comment]
> @damithc Thanks for the help, I have found a solution to the issue after looking for difference between my project and others.
> It seems that the path to the tests need to be exactly `/src/test/java/test.java`.

Ah, yes. Gradle follows the 'convention over configuration' philosophy, and expect the project structure to be a certain way.
