### ISSUE TITLE
Execution failed for task checkstyleMain

### ISSUE THREAD

**Issue by LuoZhijie-tom** [nus-cs2103-AY2122S1/forum#130]
I encountered this problem when I click build on gradle
![Screenshot 2021-08-30 144236](https://user-images.githubusercontent.com/77223932/131303038-27b5278b-f8c0-4fd0-874b-b4312683523d.jpg)
This is my project folder:
![Screenshot 2021-08-30 153558](https://user-images.githubusercontent.com/77223932/131303258-70fa0717-47d1-4d45-a700-bfd45053126e.jpg)

**Comment by marcuspeh** [comment]
For your suppression.xml, is your file path correct? Shld be ./* Instead of .\*

**Comment by yucheng11122017** [comment]
https://se-education.org/guides/tutorials/checkstyle.html
Did you follow the steps here? I had this issue until I imported everythign properly haah

**Comment by rohit0718** [comment]
ure missing the config checkstyle and suppresion files. see the discussion here #121

**Comment by rickyaandrew** [comment]
you need to add these two files in the following location

{projectFolder}/config/checkstyle/checkstyle.xml
{projectFolder}/config/checkstyle/suppressions.xml

checkstyle.xml and suppressions.xml can be retrieve it from the addressbook repo

**Comment by LuoZhijie-tom** [comment]
OK! I followed the steps and it works now! Thank you so much!
