### ISSUE TITLE
MainWindow class not found for Level 10 in Main file

### ISSUE THREAD

**Issue by yucheng11122017** [nus-cs2103-AY2122S1/forum#131]
Hi I am getting a java.lang.ClassNotFoundException: MainWindow in Main file. I am trying to implement the GUI (level 10) using fxml. Not very sure why I am getting it as I have been copying the tutorial exactly. Is my MainWindow placed in the correct path?

Thank you for any help! Please see below for my current project files and the code for my Main class. 

Project files: 
![image](https://user-images.githubusercontent.com/77204346/131307036-2f7ab077-f921-4618-a6de-ca9a9356041d.png)

Code for main: 
```
package duke;

import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

/**
 * A GUI for Duke using FXML.
 */
public class Main extends Application {

    private Duke duke = new Duke();

    @Override
    public void start(Stage stage) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(Main.class.getResource("/view/MainWindow.fxml"));
            AnchorPane ap = fxmlLoader.load();
            Scene scene = new Scene(ap);
            stage.setScene(scene);
            fxmlLoader.<MainWindow>getController().setDuke(duke);
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by frederickpek** [comment]
Hi yucheng! I encountered the same issue as you.
Your MainWindow.fxml needs to update where ur MainWindow class is in ur package. The default assumes its in the same directory.
![image](https://user-images.githubusercontent.com/66522537/131308281-0aea3316-6cef-4048-865f-c58fc81ebb9d.png)

**Comment by yucheng11122017** [comment]
@frederickpek thank you so much! You are a life saver 😄
