### ISSUE TITLE
Error: JavaFX runtime components are missing, and are required to run this application

### ISSUE THREAD

**Issue by ngjiayuan** [nus-cs2103-AY2122S1/forum#132]
I am unable to run my Duke after I have made the following changes according to the guide:
```
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class Duke extends Application {
    
    // ...

    @Override
    public void start(Stage stage) {
        Label helloWorld = new Label("Hello World!"); // Creating a new Label control
        Scene scene = new Scene(helloWorld); // Setting the scene to be our Label

        stage.setScene(scene); // Setting the stage to show our screen
        stage.show(); // Render the stage.
    }
}
```

I have followed online troubleshooting from
https://stackoverflow.com/questions/51478675/error-javafx-runtime-components-are-missing-and-are-required-to-run-this-appli
and
https://stackoverflow.com/questions/52467561/intellij-cant-recognize-javafx-11-with-openjdk-11
but to no avail

I have also tried adding 
```
javafx {
    version = "11.0.2"
    modules = [ 'javafx.controls' ]
}
```
into my ``build.gradle`` as seen from https://openjfx.io/openjfx-docs/#gradle
but it shows this error:
Could not find method javafx() for arguments [build_4b7ubfp23qi517fy9o3xlfn8j$_run_closure2@499baaf0] on root project 'ip' of type org.gradle.api.Project.

any advice would be greatly appreciated!

**Comment by waynetee** [comment]
How are you running the app? Try pressing the green run arrow on your Launcher class
![image](https://user-images.githubusercontent.com/17681226/131323149-ee67458f-5bcc-49bb-89c4-2c451b0694c3.png)

**Comment by ngjiayuan** [comment]
I tried that and I got these errors:
![image](https://user-images.githubusercontent.com/68689883/131329748-568e6317-ed7a-4458-bf27-0fe91240e4d2.png)
I also tried running using ``gradlew run`` and I got this error:
![image](https://user-images.githubusercontent.com/68689883/131329869-ffd28992-28a7-4105-974d-a96f17ed7567.png)
Also my project structure is using JDK 11.0.9, I am not sure why it says jdk-16.0.2

**Comment by waynetee** [comment]
The error on your first screenshot seems really weird, is this purely the result of following the guide, or did you change anything when you tried to fix the original error?

Try `gradlew run -Dorg.gradle.java.home="C:\Program Files\Java\jdk-11.0.9"` on the command line

**Comment by ngjiayuan** [comment]
> The error on your first screenshot seems really weird, is this purely the result of following the guide, or did you change anything when you tried to fix the original error?

ah yes, I did add this line as suggested by stackoverflow:
``--module-path /Users/<user>/Downloads/javafx-sdk-11/lib --add-modules=javafx.controls,javafx.fxml``
in my VM options under Run >> Edit Configurations

reverting my changes, I am getting:
![image](https://user-images.githubusercontent.com/68689883/131334530-259af4aa-304d-4cba-8ccf-ff9333ba056c.png)

> Try `gradlew run -Dorg.gradle.java.home="C:\Program Files\Java\jdk-11.0.9"` on the command line

Still facing the same error:
![image](https://user-images.githubusercontent.com/68689883/131334651-ea18c777-768e-4997-bc09-c8dfbb7dcafb.png)

**Comment by clyveycui** [comment]
I previously encountered the same issue. I solved it by splitting the main method and the javafx application class into 2 separate classes:
```java
public class Duke {
    // ...
    //This is where I launch the application
    public static void main(String[] args) {
        Application.launch(DukeUi.class, args);
    }
}
```
```java
public class DukeUi extends Application {
    // This class extends javafx.application.Application
    @Override
    public void start(Stage primaryStage) {
        // Your start function code goes here
    }
}
```
And it worked for me

**Comment by waynetee** [comment]
In your build.gradle make sure you specify the main class correctly, also refer to #125 , hope this helps

**Comment by ngjiayuan** [comment]
> refer to #125
this worked thank you!
