### ISSUE TITLE
Week 4 Level 10 branch

### ISSUE THREAD

**Issue by sunjc826** [nus-cs2103-AY2122S1/forum#133]
In week 4's ip instructions, there was no explicit requirement to branch out, so I did all my changes on the main branch. The ip dashboard shows all tags except the branch-Level-10 tag. 

Is this alright or do I need to create a branch-Level-10 branch (and merge it) just for show?

**Comment by marcuspeh** [comment]
Yup the branch is needed.
![image](https://user-images.githubusercontent.com/54053213/131347625-49b3871e-ce39-4970-9d73-7f0adb400235.png)

**Comment by yucheng11122017** [comment]
I believe you need the branch, pushing the tag wont be enough. The marking script seems to checking for the branch in this case. 
If you havent committed yet, I think you can still check out now to a new branch without much issue. 

(Also, I think if you just create the branch after the changes, should be good enough to pass the marking script)

**Comment by sunjc826** [comment]
> Yup the branch is needed.
> ![image](https://user-images.githubusercontent.com/54053213/131347625-49b3871e-ce39-4970-9d73-7f0adb400235.png)

Thanks Marcus and Yucheng! I'll create the branch then.
