### ISSUE TITLE
Font Issue with JavaFX

### ISSUE THREAD

**Issue by Jai2501** [nus-cs2103-AY2122S1/forum#135]
* Development Environment:
Java Version 11.0.12
MacOS Big Sur (M1)
IntelliJ 2021.2
JUnit Version 5.5.0

I followed this [guide](https://se-education.org/guides/tutorials/javaFxPart1.html), but when I run my program,
I get such an output:
<img width="205" alt="Screenshot 2021-08-30 at 10 01 51 PM" src="https://user-images.githubusercontent.com/52578354/131351549-dd4f954e-0d81-4386-b220-a22ef2a73174.png">

and this is the log:
```
10:01:38 PM: Executing task ':Launcher.main()'...

> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes

> Task :Launcher.main()
2021-08-30 22:01:42.508 java[55504:3038655] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2021-08-30 22:01:42.508 java[55504:3038655] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2021-08-30 22:01:42.512 java[55504:3038655] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2021-08-30 22:01:42.739 java[55504:3038698] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
```

On searching the internet, I found a solution to use `Font` like:
```Java
        Font defaultFont = new Font("Arial", 15);
        Label helloWorld = new Label("Hello World!");
        helloWorld.setFont(defaultFont);
        Scene scene = new Scene(helloWorld);
        stage.setScene(scene);
        stage.show();
```
and this works fine.
output:
<img width="109" alt="Screenshot 2021-08-30 at 10 05 19 PM" src="https://user-images.githubusercontent.com/52578354/131351987-f5f6224d-d5b8-4480-b3aa-8c4915591269.png">

and the log doesn’t show any error:
```
10:05:14 PM: Executing task ':Launcher.main()'...

> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :Launcher.main()
```

I have a workaround, but is there any possible way to fix this and avoid using `Font`, which works just fine?

Thank You!

**Comment by xlzior** [comment]
I'm on Catalina, but facing the same problem. #118 also discusses this issue, and the original poster of that issue fixed it this way:
> I found the problem. The default font for JavaFX was not loading properly so I just manually changed the font to another font that works. Thanks all!!

I followed these instructions [here](https://stackoverflow.com/questions/18408884/set-font-globally-in-javafx) to set my default font via a CSS stylesheet, but honestly not sure if that's the best way.

**Comment by Jai2501** [comment]
> #118

I as well saw the CSS method, but wasn’t sure if that’s the right way to go about it...

**Comment by sivayogasubramanian** [comment]
I think the best way to not have any font issues is to package the font together with the application. 

See https://github.com/se-edu/addressbook-level3/pull/106 for the changes make to AB3 to fix the font problem. We probably should do something similar for iP.

**Comment by Jai2501** [comment]
> I think the best way to not have any font issues is to package the font together with the application.
> 
> See [se-edu/addressbook-level3#106](https://github.com/se-edu/addressbook-level3/pull/106) for the changes made to AB3 to fix the font problem. We probably should do something similar for iP.
> 
> Another solution is just to use the SceneBuilder to set the font to some common font in all OSes.

Thanx...

**Comment by willyamped** [comment]
Hi, @xlzior. Could you please let me know how did you change the font? I am running into an error when I type `scene.getStylesheets().add(getClass().getResource("stylesheet.css").toExternalForm());`

This is what I have in stylesheet.css:
```java
.root{
    -fx-font-size: 16pt;
    -fx-font-family: "Courier New";
}
```

This is where I place my `stylesheet.css` file.
<img width="295" alt="Screenshot 2021-08-31 at 10 32 01 AM" src="https://user-images.githubusercontent.com/66423703/131432181-9bbf8e55-d85f-435b-bad2-96319d21e793.png">

This is my current code in my main:

```java
...
AnchorPane mainLayout = new AnchorPane();
        mainLayout.getChildren().addAll(scrollPane, userInput, sendButton);
        scene = new Scene(mainLayout);
        scene.getStylesheets().add(getClass().getResource("stylesheet.css").toExternalForm());
        stage.setScene(scene);
        stage.show();
...
```

Thank you so much!

**Comment by leezhixuan** [comment]
Hey, I encountered the same problem and I managed to fix it without relying on CSS.

```
AnchorPane mainLayout = new AnchorPane();
        mainLayout.getChildren().addAll(scrollPane, userInput, sendButton);
        scene = new Scene(mainLayout);
        scene.getRoot().setStyle("-fx-font-family: 'serif'"); //fix
        stage.setScene(scene); 
        stage.show();
```

**Comment by SkyBlaise99** [comment]
Why not go to scene builder and just apply your .css in it?

**Comment by solarrabbit99** [comment]
Updating javafx version 16 fixed the problem for me.

```groovy
String javaFxVersion = '16'

implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
```

**Comment by waynetee** [comment]
I encountered this issue when testing on mac too, here's my fix:

https://github.com/waynetee/ip/commit/103147554f1ad8b2c58a4a3bea9f8ef7c104b1a0#diff-bcdae9022558f780b3bf59f9f4a02d0674901b4ec6c17ce1162b4e19faa86ff0R7

**Comment by zzybluebell** [comment]
@Jai2501 
agree with @willyamped 
I think go scene builder build own .css file, which works for me also
Such as :

.root{
    -fx-font-size: 12pt;
    -fx-font-family: "Courier New";
}

**Comment by kouyk** [comment]
Hi everyone, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). For those who have ran into similar issues, perhaps it will be beneficial to take a look at #231 and follow the instructions there. Do report back as well so that these issues can be ironed out!
