### ISSUE TITLE
TextUITesting issues

### ISSUE THREAD

**Issue by eezj35** [nus-cs2103-AY2122S1/forum#14]
Hi everyone, for the textuitesting, the tutorial of this testing technique told us to run this command: java AddressBook < input.txt > output.txt to automate testing, which in the context of the iP, i think the command should be: java Duke < input.txt > ACTUAL.TXT. May i ask if i am wrong about this? because when running this in the terminal it tell me "The system cannot find the file specified."
May i know what should be the correct command line?

Thanks for taking the time to help!

**Comment by VimuthM** [comment]
Yes, it should be changed to Duke. Both `runtest.sh` and `runtest.bat` shown [here](https://se-education.org/guides/tutorials/textUiTesting.html) have been updated to Duke. Maybe your visiting an older version of the website?

**Comment by chownces** [comment]
@eezj35 I think you are referring to [Week 2's textbook content](https://nus-cs2103-ay2122s1.github.io/website/schedule/week2/topics.html#quality-assurance-testing-test-automation-automated-testing-of-cli-applications). You can take a look at the [iP tasks this week](https://nus-cs2103-ay2122s1.github.io/website/schedule/week2/project.html#1-learn-about-the-project) instead. The test scripts are provided as mentioned by @VimuthM

**Comment by eezj35** [comment]
i think my issue is, should i be editing/changing the file path in the javac and java commands? Because the terminal is telling me it cant find the file specified. And if i am supposed to edit/change it, what should i change it to?

**Comment by marcuspeh** [comment]
> i think my issue is, should i be editing/changing the file path in the javac and java commands? Because the terminal is telling me it cant find the file specified. And if i am supposed to edit/change it, what should i change it to?

I think you need to cd into the directory with terminal then either ./runtest.sh for mac or ./runtest.bat for windows

**Comment by SkyBlaise99** [comment]
If u r using intelij it has a terminal which can run the script. And yeah remeber to cd to the test folder first.

**Comment by eezj35** [comment]
ah ok i think i got it! thanks so much everyone, appreciate it!
