### ISSUE TITLE
Jar file cannot run

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#143]
So after completing the GUI I thought it will be nice to have a jar file for it. So I ran the `shadowJar` function in gradle but the jar file it produced does not work. The program is able to run on Intelij, and shadowJar is able to work when I disabled the GUI.

![image](https://user-images.githubusercontent.com/69448615/131475482-819d3eaf-bed3-496c-a9ce-714cd282d2df.png)

As the screenshot suggests, somehow `shadowJar` did not pack my `javafx` stuffs into the `jar` file? Any fix for this?

Attached `build.gradle` if anyone needs it for info.
``` gradle
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '5.1.0'
    id 'org.openjfx.javafxplugin' version '0.0.9'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.2'

    String javaFxVersion = '11'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClassName = "sora.Main"
}

shadowJar {
    archiveBaseName = "sora"
    archiveVersion = "2.0"
    archiveClassifier = null
}

checkstyle {
    toolVersion = '8.29'
}

run {
    standardInput = System.in
}

javafx {
    version = "11"
    modules = ['javafx.controls', 'javafx.fxml']
}
```

**Comment by rohit0718** [comment]
perhaps when it was creating the jar file it missed out the needed libraries. can you can try adding the modules as per the solution [here](https://stackoverflow.com/questions/64273767/showing-error-javafx-runtime-components-are-missing-and-are-required-to-run-t)?.

**Comment by SkyBlaise99** [comment]
As in follow the manual installation of javafx? Those steps seem to be the same as given in tutorial.

**Comment by SkyBlaise99** [comment]
I cant edit my `Project Structure` settings cuz of this error.
![image](https://user-images.githubusercontent.com/69448615/131512176-8aed97b6-aa77-48e4-b404-82d0f515e6f5.png)

**Comment by kouyk** [comment]
Hi @SkyBlaise99, I'm from the previous batch (dropping by in this forum to see if I can help you guys with tech problems). Taking a quick look at your source code I found that your `Main` class which inherits from `javafx.application.Application` is set to be the main class to be launched. This seemed to have introduced dependency issues that you saw.

https://se-education.org/guides/tutorials/javaFxPart1.html#writing-your-first-program does show that it is necessary to create an additional `Launcher` class to avoid any circular dependencies, you might want to give that a shot. Do remember to update your `build.gradle` to point at the launcher class instead!

**Comment by SkyBlaise99** [comment]
Thanks for the reply, it works!

Regarding this, 
> does show that it is necessary to create an additional `Launcher` class to avoid any circular dependencies

I did not see in the docs that a `Launcher` class is required to avoid circular dependencies tho. Maybe you are referring to the comment `A launcher class to workaround classpath issues.`?

I thought that my `Main` can just call the `main` method to launch the app. Maybe it is because `Main.main()` calls `launch` which in turn call another `new Main()`, hence the circular dependencies?

**Comment by kouyk** [comment]
> I did not see in the docs that a `Launcher` class is required to avoid circular dependencies tho. Maybe you are referring to the comment `A launcher class to workaround classpath issues.`? Not sure what exactly is a `classpath issue`.

I think I wasn't quite right saying it's a circular depenency, but you got the right section.
 
> I thought that my `Main` can just call the `main` method to launch the app. Maybe it is because `Main.main()` calls `launch` which in turn call another `new Main()`, hence the circular dependencies? This also explains why we need to just create an empty constructor for people have the other issues?

https://stackoverflow.com/questions/52569724/javafx-11-create-a-jar-file-with-gradle/52571719#52571719
https://stackoverflow.com/questions/52653836/maven-shade-javafx-runtime-components-are-missing/52654791#52654791

Check out the two links above, they give a more in depth breakdown of the problem. Hope that helps!

**Comment by SkyBlaise99** [comment]
Thx for the links, shall be closing this then.
