### ISSUE TITLE
Error running JavaFX Launcher on M1 Macbook

### ISSUE THREAD

**Issue by Xiaoyunnn** [nus-cs2103-AY2122S1/forum#146]
**Development Environment**
- IntelliJ 2021.1.3 (Community)
- M1 Macbook Air (BigSur OS 11.5)

I followed the JavaFX tutorial here to set up JavaFX with Gradle [here](https://se-education.org/guides/tutorials/javaFxPart1.html). When I run the launcher, I got this error message `Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found`. 

So I executed the code again with `--scan` and got the following error messages this time.

![image](https://user-images.githubusercontent.com/76084739/131486538-90128fa5-3499-4a50-9f5e-a8c0eb59ecc2.png)

May I know if there is any way to resolve this issue? 🥲 Thanks!

**Comment by sivayogasubramanian** [comment]
You are using the ARM version of java i think. Try to uninstall java using `brew uninstall java` and install the x86 version from [oracle website](https://www.oracle.com/sg/java/technologies/javase-jdk11-downloads.html).

**Comment by rohit0718** [comment]
@sivayogasubramanian i think u mean the reverse, since @Xiaoyunnn is using an m1 mac. do download the arm version instead of the x86 one that u are currently using.

**Comment by sivayogasubramanian** [comment]
@rohit0718 You have to run java under rosetta 2. Java ARM works fine but dependencies might not be updated yet. I faced this issue when i was running AB3 for the first time. Deleted ARM java and installed Java x86 one and it worked. 

![Screenshot 2021-08-31 at 7 46 13 PM](https://user-images.githubusercontent.com/53614454/131496916-b59efcac-cfe8-4f37-a8e2-1bdd858a2e5f.png)

**Comment by rohit0718** [comment]
@sivayogasubramanian oh i see, apologies for the confusion!

**Comment by Xiaoyunnn** [comment]
@sivayogasubramanian Thanks for the help! I downloaded and installed Oracle JDK but did not delete Java ARM and then changed the JDK in IntelliJ project structure and it also worked.
