### ISSUE TITLE
Cannot find or load main class seedu.duke.Duke

### ISSUE THREAD

**Issue by Gordon25** [nus-cs2103-AY2122S1/forum#147]
I followed scenario 2 of the [tutorial](https://se-education.org/guides/tutorials/gradle.html) given from the start 
and successfully imported Gradle, but when i imported my ip again (as per step 4) and run the Gradle task, i encountered this error. 

![image](https://user-images.githubusercontent.com/73068242/131500470-5c58e21d-e185-4d00-b905-44aaff780303.png)

Would appreciate some help on this, thank you.

**Comment by marcuspeh** [comment]
In build.gradle, replace sedu.duke.duke with duke.duke

**Comment by NicolasCwy** [comment]
Can follow #127 as part of the solution is the same

**Comment by Gordon25** [comment]
Thank you! @marcuspeh @NicolasCwy
