### ISSUE TITLE
JavaFX Styling: How to increase DialogBox size based on amount of text?

### ISSUE THREAD

**Issue by wpinrui** [nus-cs2103-AY2122S1/forum#148]
When listing a large number of tasks, most of them get cut off due to the height constraint of the dialog box. Is there any way to make it scale based on the length of text? 

I've tried setting the Max Height of the dialog box to 'Use Computed Size' but that didn't do it, as the height was still constrained by the main window itself. 

![Qn](https://user-images.githubusercontent.com/77185900/131503905-fef7e711-f7e5-4184-87ec-8c7a64471bec.png)

**Comment by zognin** [comment]
Perhaps you could [try](https://stackoverflow.com/questions/35114338/how-do-i-make-my-vbox-and-label-resize-according-to-texts-in-label-in-javafx) setting `maxHeight="Infinity"` to the relevant component?
I managed to prevent my list from being cut off by adding `minHeight="-Infinity" maxHeight="Infinity"` to my `<Label>` 

e.g.
`<Label fx:id="dialog" text="Label" wrapText="true" minHeight="-Infinity" maxHeight="Infinity" prefWidth="260"/>
`

**Comment by SkyBlaise99** [comment]
I used `Text` instead of `Label`. `Text` will sort of auto expand downwards and allows you to put a `wrap width` for the width. So far no problem handling like 15+ lines for me.

**Comment by xlzior** [comment]
Can check out [mine](https://github.com/xlzior/ip/commit/048fd6118acb6642c74093c93a395ec8c7b030b0) if you need a reference for how to change from `Label` to `Text`. Besides changing the FXML, remember to change the type of `dialog` in `DialogBox` to `Text` as well.

**Comment by wpinrui** [comment]
Thanks everyone! Ended up going with the maxHeight="Infinity" solution and it worked a treat!
