### ISSUE TITLE
Can't load checkstyle.xml

### ISSUE THREAD

**Issue by houtenteo** [nus-cs2103-AY2122S1/forum#149]
Hi. When I tried to load my local checkstyle.xml file I get this. Anyone knows why?

![checkstyle](https://user-images.githubusercontent.com/77191381/131504599-3059b231-bd87-4245-8e3b-fb7b9f13997c.jpg)

**Comment by NicolasCwy** [comment]
Hi houten, are you using the adb3 checkstyle sheet or did you create your own?

Could you take a pic of your project dir, to show where the checkstyle folder is, and if you followed [this guide](https://se-education.org/guides/tutorials/checkstyle.html)?

**Comment by houtenteo** [comment]
@NicolasCwy I took it from the .idea directory. I know the guide mentioned to take it from the config file. But I don't see the config directory anywhere. Am I supposed to create one on my own and copy paste the file over?

![dir](https://user-images.githubusercontent.com/77191381/131515393-5feeb1cf-aa56-4f88-b09b-64663a766b9f.jpg)

**Comment by xlzior** [comment]
You can create your own `config/checkstyle` directory! Then copy and paste the `checkstyle.xml` and `suppressions.xml` files over from AB3.

**Comment by houtenteo** [comment]
@xlzior I don't seem to have the suppressions.xml file. I also tried creating my own config directory but still getting the same error. Just to confirm, is this what it is supposed to look like?

![dir1](https://user-images.githubusercontent.com/77191381/131517761-a2a782b2-b238-4d3d-a138-9125305a10b5.jpg)

**Comment by xlzior** [comment]
Full instructions for configuring checkstyle are [here](https://se-education.org/guides/tutorials/checkstyle.html#configuring-checkstyle-rules)

> Checkstyle expects configuration files for checkstyle (e.g., files that specify which style rules to follow) to be in ./config/checkstyle/ by convention.
> The set of code style rules are put in the **config/checkstyle/checkstyle.xml**. To enable exceptions to code styles, you can add in the comment //CODESTYLE.OFF: RuleName at the start of the section and //CODESTYLE.ON: RuleName at the end of the section. Alternatively, you can specify which rules to suppress in a config file `config/checkstyle/suppressions.xml`

Rename your file to `checkstyle.xml` and copy the content over from [AB3](https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle).

**Comment by houtenteo** [comment]
@xlzior ah... I overlooked the filename and you asking me to copy over from AB3. Sorry about that. 
Thanks a lot, @NicolasCwy as well.
