### ISSUE TITLE
Bug with checkstyle or are lambda functions supposed to have a different indentation/format from CS2030S?

### ISSUE THREAD

**Issue by yzhilong** [nus-cs2103-AY2122S1/forum#150]
I currently have code written in the following format, but I a checkstyle violation saying that `Checkstyle: '(' should be on the previous line`, referring to the open bracket of the lambda function. Is this supposed to occur? Since this style seems to be pretty normal and there was no mention about this being a violation in the java coding standards.

```java
someMethod(
    someValue,
    () -> someOtherValue
);
```

**Comment by bharathcs** [comment]
Just checking btw, is there a comma after someValue?

**Comment by yzhilong** [comment]
@bharathcs Yes there should be, thanks for pointing it out! I forgot to write it in my question here. That wasn't the error though. I edited my question to show that comma.

**Comment by damithc** [comment]
@yzhilong As the coding standard doesn't mention any rules for lambda functions, you can decide which style to follow. You can edit the checkstyle file accordingly or suppress checkstyle for the code in concern.

**Comment by yzhilong** [comment]
@damithc Ah ok thanks for the clarification!
