### ISSUE TITLE
Issue with reloading all gradle projects

### ISSUE THREAD

**Issue by Wilfredwongkc** [nus-cs2103-AY2122S1/forum#151]
## Development Environment ## 
* IntelliJ 2020.3.1 (Community)
* Windows 10
## ##
Hi friends,

I was referring to [#144](https://github.com/nus-cs2103-AY2122S1/forum/issues/144) as my javafx is not being recognised. However, my "Reload all Gradle Projects" is greyed out. Does anyone know why is this so?

![Greyed](https://user-images.githubusercontent.com/66736794/131530164-f7343fff-f384-48b0-910f-86c782daf69e.jpg)

Thanks!

**Comment by damithc** [comment]
Try deleting the .idea folder again and opening the project again?

**Comment by Wilfredwongkc** [comment]
Hi Prof,

I tried it and it works. 

Thanks!
