### ISSUE TITLE
Run Launcher failed with error messages

### ISSUE THREAD

**Issue by sueann-chua** [nus-cs2103-AY2122S1/forum#152]
I followed the JavaFX tutorial part 1 but am unable to run Launcher. Running Launcher results in the following message: 
![image](https://user-images.githubusercontent.com/77190772/131532421-bed88d84-d5da-40c6-8b24-ad66c58746b8.png)

What can I do?

**Comment by wengYing227** [comment]
Hi, I got the same error message now.
May I know how you solved it?

**Comment by damithc** [comment]
@sueann-chua do you remember the solution?

@wengYing227 it might help to share the code of the build.gradle file. Also, I suggest you post a new issue for better visibility, as this one is closed already.

**Comment by wengYing227** [comment]
> @sueann-chua do you remember the solution?
> 
> @wengYing227 it might help to share the code of the build.gradle file. Also, I suggest you post a new issue for better visibility, as this one is closed already.

Thanks! I have posted a new issue [here](https://github.com/nus-cs2103-AY2122S1/forum/issues/186)
