### ISSUE TITLE
Issue with graddle

### ISSUE THREAD

**Issue by LeopardMerkava** [nus-cs2103-AY2122S1/forum#153]
I merged the `add-graddle-support` branch and deleted the `.idea` folder as suggested in the tutorial. However, when I reopen it, I am hit with the following error:

```
FAILURE: Build failed with an exception.
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/plugins/gradle/tooling/ModelBuilderService$Ex
```

**Comment by damithc** [comment]
@LeopardMerkava check if you are using the latest version of Intellij and the Gradle plugin is not disabled.
![image](https://user-images.githubusercontent.com/1673303/131536754-b456b57c-7004-48e6-9cd4-0a9c27524944.png)

**Comment by LeopardMerkava** [comment]
Thank you prof. I ended up doing a complete reinstall.
