### ISSUE TITLE
Issue with run `gradlew`

### ISSUE THREAD

**Issue by hungkhoaitay** [nus-cs2103-AY2122S1/forum#154]
I tried to run class `Launcher` but facing this error
```
Execution failed for task ':Launcher.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

I also tried to type `./gradlew run`
```

> Task :run FAILED
Error: JavaFX runtime components are missing, and are required to run this application

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date
```

Please help me 😢 Thanks

**Comment by sivayogasubramanian** [comment]
Have you refreshed gradle after adding javafx dependencies? You should see the small elephant when `build.gradle` is open.

**Comment by simonjulianl** [comment]
I think it might be related to your main launcher ? usually for JavaFX you have a main function that has an entry point to another main stage launcher, which works for me

**Comment by ziqing26** [comment]
I also got the sample problem. Have you solved the issue?

**Comment by hungkhoaitay** [comment]
@sivayogasubramanian I refreshed!
@ziqing26 I haven't solved the problem yet 😢

**Comment by VimuthM** [comment]
Run the `Launcher` class and can you put a screenshot of the detailed log when you click `Run with --scan`

**Comment by hungkhoaitay** [comment]
```
> Task :Launcher.main()
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class duke.Duke
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:890)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodException: duke.Duke.<init>()
Caused by: java.lang.NoSuchMethodException: duke.Duke.<init>()

	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:801)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

> Task :Launcher.main() FAILED
```

Here is the error

**Comment by VimuthM** [comment]
Your `Duke` class might be having only one constructor that takes in filepath as a parameter. Your `Launcher` seems to be trying to initialize `Duke` with no parameters.

**Comment by pss-coder** [comment]
Hi @hungkhoaitay, 

Check to ensure you have this: 

1. Launcher Class that runs your Duke Class 
2. your Duke class should be the one where `Duke extends Application`

A possible issue even if you have resolve the above, is if you have a module-info.java file, removing it worked for me.
Also trying cleaning and building your gradle and afterwards restart your intelliJ. 
Sometimes a restart might resolve some file issues.

**Comment by Yukun99** [comment]
I think I might have had this problem when I was using the wrong jdk version. Make sure you have `11.0.12` installed.

**Comment by hungkhoaitay** [comment]
Hi, thanks everyone for helping me. Finally I can launch the window by just restructure the package, and let not make `Launcher` as the part of `Duke` package.
```
src/main/java
├── Launcher.java
├── META-INF
│   └── MANIFEST.MF
├── Main.java
└── duke
    ├── Command.java
    ├── Duke.java
    ├── DukeException.java
    ├── Storage.java
    ├── Task.java
    └── Ui.java
```
I restructured as @VimuthM PR. Thank you
