### ISSUE TITLE
Any coding standard for FXML files?

### ISSUE THREAD

**Issue by uyencfi** [nus-cs2103-AY2122S1/forum#156]
Right now I just wrap the line at 120 characters, indent with 2 spaces, and don't use any spaces around attributes. But still my fxml files are kind of messy. Is there a general guideline on how to align the tag attributes, where to put blank lines, etc.?

**Comment by damithc** [comment]
@uyencfi We don't have a coding standard for FXML files https://nus-cs2103-ay2122s1.github.io/website/admin/standardsAndConventions.html

You are free to adopt one from elsewhere.

**Comment by SkyBlaise99** [comment]
Also if you use SceneBuilder it auto formats the fxml file in some styles. Perhaps just leave it as it is.

**Comment by uyencfi** [comment]
Okay, thanks Prof and everyone!
