### ISSUE TITLE
Linkage error while loading main class duke.Launcher

### ISSUE THREAD

**Issue by nicolej2122** [nus-cs2103-AY2122S1/forum#157]
Development Environment: 
- IntelliJ 2021.2
- MacBook Pro (BigSur OS 11.5.2)
<img width="1440" alt="Screenshot 2021-09-01 at 12 56 46 AM" src="https://user-images.githubusercontent.com/60281524/131545671-c17bc27e-1537-4f4a-9bc6-955f69c6d5de.png">

I've been encountering the following issue when trying to run the Launcher, does anyone know how to change the class file version?

**Comment by sivayogasubramanian** [comment]
What is the output of `java --version` in your terminal?

**Comment by marcuspeh** [comment]
> Development Environment:
> 
> * IntelliJ 2021.2
> * MacBook Pro (BigSur OS 11.5.2)
> 
> <img alt="Screenshot 2021-09-01 at 12 56 46 AM" width="1440" src="https://user-images.githubusercontent.com/60281524/131545671-c17bc27e-1537-4f4a-9bc6-955f69c6d5de.png">
> 
> I've been encountering the following issue when trying to run the Launcher, does anyone know how to change the class file version?

Not really a fix but my friend had this issue too. I pulled his files from github on my laptop and i was able to run without this issue. Perhaps you can try pulling from your github and see if it fixes the issue

**Comment by nicolej2122** [comment]
> What is the output of `java --version` in your terminal?

java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

**Comment by NoraYUuu** [comment]
I encountered a similar problem. You may want to check the Gradle JVM in setting (change it to project sdk solved my problem)

**Comment by sivayogasubramanian** [comment]
> java 13.0.2 2020-01-14
> Java(TM) SE Runtime Environment (build 13.0.2+8)
> Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

You can try using java 11 and set it in the project structure in intellj. It might fix the problem

**Comment by nicolej2122** [comment]
> I encountered a similar problem. You may want to check the Gradle JVM in setting (change it to project sdk solved my problem)

This worked! Thank you :)

**Comment by nicolej2122** [comment]
Thank you to everyone who helped out. I was able to resolve the issue!
