### ISSUE TITLE
ScnenBuilder uses JavaFX 16

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#159]
Following the tutorial, it asks us to use JavaFX 11. However, SceneBuilder seems to be using JavaFX 16 instead, and hence always shows a lot of warning messages when I run my program.

Currently I found a fix which is to manually edit the fxml files generated by ScnenBuilder to switch it to JavaFX 11. Is there any easier way such as telling SceneBuilder to use JavaFX11 instead? Or can we use JavaFX 16 in our project?

**Comment by kaushikkrdy** [comment]
Hi can I ask how are you editing the files to switch to JavaFX 11? I'm running into the same problem

**Comment by damithc** [comment]
My guess is it should be OK to use JavaFX 16 as long as it works with Java 11. I'll check with SE-EDU devs if they foresee any problems down that path.

**Comment by waynetee** [comment]
@SkyBlaise99 just wondering, do you happen to be using the scene builder inside intelij?

**Comment by SkyBlaise99** [comment]
@kaushikkrdy so in your `.xml` files, search for `xmlns = "http://javafx.com/javafx/16"` and change the 16 to 11.
![image](https://user-images.githubusercontent.com/69448615/131637289-b0f4b4d7-3c9f-4610-8241-9c20a3cc1297.png)

**Comment by SkyBlaise99** [comment]
@damithc thanks for i'll wait for further updates then, should i close this then?

**Comment by SkyBlaise99** [comment]
@waynetee i'm using the scene builder downloaded from the tutorial [link](https://gluonhq.com/products/scene-builder/#download)

**Comment by waynetee** [comment]
![image](https://user-images.githubusercontent.com/17681226/131637880-fdecffa4-ac08-46f9-a497-805555dc6a95.png)
Do you see this in your intelij?

**Comment by damithc** [comment]
> @damithc thanks for i'll wait for further updates then, should i close this then?

@SkyBlaise99 We can leave this open for the time being.

**Comment by SkyBlaise99** [comment]
Oh I followed the tutorial which downloads this
![image](https://user-images.githubusercontent.com/69448615/131647425-9a142274-2af5-4af0-ab71-7e455c6b915b.png)

Perhaps I can try installing it in Intelij also

**Comment by SkyBlaise99** [comment]
I think I found the way, it's the button at the bottom left right?
![image](https://user-images.githubusercontent.com/69448615/131648181-1f422b0c-4b67-46e0-93bf-6ba9af57aecb.png)

**Comment by waynetee** [comment]
yep!

**Comment by wpinrui** [comment]
The top answer from [this StackOverflow question](https://stackoverflow.com/questions/65987397/how-to-set-preferred-version-in-scene-builder) might help. 

This way, SceneBuilder stops overriding the part of the fxml file that determines the version. So far, I haven't had any issues doing this.
