### ISSUE TITLE
pull request for independent project

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#16]
do i have to do pull request for independent project or push directly to remote master (my own forked repo master)?
The latter sounds like an extremely bad practice, as i have heard from online forums.
Also in general i am curious about the workflow.
My current idea of what should happen is:
    1. create new branch locally
    2. after a commit on that branch, push it to a remote branch 
    3. make a pull request to master 
    4. merge into master
    5. at local master use git pull to update my local files

Is this correct? 
Can someone  enlighten me on this area in general.

**Comment by marcuspeh** [comment]
I believe for this week one we just need to push directly to master. We need to do branch only in the other weeks

**Comment by xlzior** [comment]
I believe pushing to master is fine for small projects with only 1 contributor, which is what the individual project currently is.

Also, it's probably better to learn to walk (push to master) before you learn to run (create branches and pull requests).

**Comment by damithc** [comment]
@softmagnet you are right; we should move towards a more scalable workflow. We'll be learning those things along the way, in the next few weeks. The iP instructions will tell you know at which point to use branches, PRs, etc.
