### ISSUE TITLE
Unable to run JUnit test using Gradle

### ISSUE THREAD

**Issue by Gordon25** [nus-cs2103-AY2122S1/forum#161]
I wanted to use gradle to run JUnit tests.

After clicking on test, i got this: 
![image](https://user-images.githubusercontent.com/73068242/131637647-6c95de95-d09a-48d0-b113-634275aa7744.png)

So, i tried adding the following include statement in build.gradle, 
![image](https://user-images.githubusercontent.com/73068242/131639057-b2c6d7bd-1f52-4d00-8dad-d56bf51ef095.png)

However, 
![image](https://user-images.githubusercontent.com/73068242/131639161-92590a85-3cae-4210-974d-41c49be0aea6.png)

**Comment by yucheng11122017** [comment]
Why do you have the include statement? 🤔 Also is your Duke in package of IP.duke.main?

**Comment by Gordon25** [comment]
I followed [this](https://docs.gradle.org/current/userguide/java_testing.html#using_junit5).
Yes, my Duke is in IP.duke.main

**Comment by Gordon25** [comment]
I removed testNG from build.gradle and it works now, thanks.
