### ISSUE TITLE
Unable to run gradlew tasks

### ISSUE THREAD

**Issue by jiayi1129** [nus-cs2103-AY2122S1/forum#162]
Development Environment
- OS: Windows
- Intellij 2020.3.1

I managed to setup Gradle and run my application as per level `A-Gradle`, however when I try to run 
`gradlew checkstyleMain checkstyleTest` and `gradlew clean build` the following error happens.

![image](https://user-images.githubusercontent.com/35002411/131661182-5bd12f48-a541-4ff4-95e6-e86b511a4397.png)
![image](https://user-images.githubusercontent.com/35002411/131661245-baa89f52-1ab8-44ad-bb2e-19c7268ae12a.png)

**Comment by yucheng11122017** [comment]
Did you follow the steps for installing checkstyle? 😄

**Comment by jiayi1129** [comment]
I'm going to close the issue. The issue was that I was using Java SDK 15, which is incompatible with gradle 6.2. The project settings strangely does not affect the Terminal's java version. You have to point the environment PATH variable in Settings > Terminal > Environment variables to the correct Java SDK version for this to work.
