### ISSUE TITLE
TreeWalker as parent of LineLength error  

### ISSUE THREAD

**Issue by samyipsh** [nus-cs2103-AY2122S1/forum#163]
Details:
> "TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard." - intellij error message
- Reference doc: [github forum](https://github.com/jshiell/checkstyle-idea/issues/458)
- So I know the issue (_TreeWalker component shouldnt be parent of LineLength component_) but I'm quite tentative to change it cos I don't think we're suppose to change the checkstyle.xml, just import it wholesale? Also, if I was to change it, I also don't know what to change it to 😢 

Context:
- just setup Gradle and copied over .xml checkstyle
- was using JDK 15, now swapped back to JDK 11
- Gradle run, build works (if I comment out `id 'checkstyle'` & the checkstyle block)
- I had a previous issue with _unable to Instantiate FileContentHolder_ error but followed [link](https://github.com/checkstyle/checkstyle/issues/5132) to just comment out the message. Supposedly, its due to the upgraded version of checkstyle.

Relevant Code:
```xml
<module name="TreeWalker">

<!-- Required for SuppressionCommentFilter to work -->
<!--    <module name="FileContentsHolder"/>-->

... other code

    <module name="LineLength">
      <!-- Checks if a line is too long. -->
      <property name="max" value="120"/>
    </module>

... other code
```

**Comment by KohHanMing** [comment]
Hi @samyipsh, I'm from your senior batch. Just dropping in to share some thoughts! For your first concern, don't be too worried about having to change files! Bugs happen all the time so if an error message shows up just rectify it as best you can. It's also a good learning experience on how to trace and troubleshoot errors :)

For the second concern about what to change, take a look at the documentation link (https://checkstyle.org/config_sizes.html#LineLength) as mentioned [in the forum post you mentioned](https://github.com/jshiell/checkstyle-idea/issues/458).

Your relevant code shows LineLength to be under TreeWalker. However the documentation states that the parent module for LineLength should be Checker, not TreeWalker.

Your code might currently look something like this:
<module name="Checker">
     ---- some code ----
     <module name="TreeWalker">
         ---- some code ----
         <module name="LineLength">
             ---- some code ----
         </module>
    </module>
</module>

Move the LineLength module out of TreeWalker to be directly under Checker and you should be good to go!

**Comment by samyipsh** [comment]
Hi Han Ming, thanks for the advice :)

Agreed that I shouldn't be too worried on having to change files, but was concerned cos no one else reported this issue although everyone should have copied over the exact same checkstyle file. So in all likelihood the problem is me.

Anyhow faced a few issues before this and commented them out as per some stackoverflow comments. After shifting the LineLength up i faced yet another 4/5 issued on deprecated properties and I kinda give up commenting them out (cos who knows how many more there are). 

Will probably leave out the checkstyle now and come back to it later if I have time, thanks for the advice nonetheless.
If anyone knows how to get it to work without changing the code please lemme know :).

**Comment by SkyBlaise99** [comment]
Apart from the `id` part, did you add this to `build.gradle`?

``` gradle
checkstyle {
    toolVersion = '8.29'
}
```

Another thing you might wanna check is if you have the correct settings for checkstyle?

![image](https://user-images.githubusercontent.com/69448615/131999127-ffd94034-790c-4553-9299-e1dcc5c35e35.png)

I followed the exact steps given and did not encounter any errors so I believe that you need not comment them out. If you need to you can copy my `checkstyle.xml` [here](https://github.com/SkyBlaise99/ip/tree/master/config/checkstyle) if it helps.

**Comment by samyipsh** [comment]
@SkyBlaise99 thanks sky :) although I have had this error like 3 days ago and reloaded the checkstyle.xml like multiple times... loading in your checkstyle file works haha thanks.

**Comment by SkyBlaise99** [comment]
I think I did not change the checkstyle much apart from small changes to the rules and auto formatting done by Intelij. But glad that it works.
