### ISSUE TITLE
Problem on Gradle

### ISSUE THREAD

**Issue by wengYing227** [nus-cs2103-AY2122S1/forum#164]
Hi, I always failed to set up Gradle.
It showed that _Plugin [id: 'com.github.johnrengelman.shadow', version: '5.1.0'] was not found_
I have no idea why this happened. Can anyone help me with it?

This is part of the error message printed out:
```java
Build file '/Users/admin/Desktop/codes/ip/build.gradle' line: 5

Plugin [id: 'com.github.johnrengelman.shadow', version: '5.1.0'] was not found in any of the following sources:

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.github.johnrengelman.shadow', version: '5.1.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:5.1.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:268)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$100(DefaultPluginRequestApplicator.java:63)
        ...
```

**Comment by damithc** [comment]
@wengYing227 could be due to a temporary network/server outage. Could you try again?

**Comment by wengYing227** [comment]
> @wengYing227 could be due to a temporary network/server outage. Could you try again?

It still doesn't work

**Comment by marcuspeh** [comment]
Could it be your antivirus software or something? Maybe can try disabling it and try.

**Comment by damithc** [comment]
In the interest of troubleshooting, you can also try changing the shadow plugin version number in the build.gradle file to a later version (see https://github.com/johnrengelman/shadow/releases) to see if that makes a difference.

**Comment by wengYing227** [comment]
> Could it be your antivirus software or something? Maybe can try disabling it and try.

Thanks for your suggestions. But I didn't install any antivirus software.
Is there any other possible reason?

**Comment by wengYing227** [comment]
> @wengYing227
> Do you have these lines in your build.gradle?
> 
> ```
> repositories {
>     mavenCentral()
> }
> ```

Yes. I do have

**Comment by damithc** [comment]
> > @wengYing227
> > Do you have these lines in your build.gradle?
> > ```
> > repositories {
> >     mavenCentral()
> > }
> > ```
> 
> Yes. I do have

How about change the version number to 5.2.0? Any difference?

**Comment by wengYing227** [comment]
> In the interest of troubleshooting, you can also try changing the shadow plugin version number in the build.gradle file to a later version (see https://github.com/johnrengelman/shadow/releases) to see if that makes a difference.

I tried version 7.0.0, 6.1.0 and 6.0.0 just now. But it still doesn't work

**Comment by wengYing227** [comment]
> > > @wengYing227
> > > Do you have these lines in your build.gradle?
> > > ```
> > > repositories {
> > >     mavenCentral()
> > > }
> > > ```
> > 
> > 
> > Yes. I do have
> 
> How about change the version number to 5.2.0? Any difference?

it still prints out the same error

**Comment by damithc** [comment]
Strange, because no one else in the class has reported this error. Confirmed you are using the given build.gradle file and latest Intellij? If yes, can you try the following?:
1. Close Intellij
2. Delete .idea folder of the project
3. Open the project again

**Comment by wengYing227** [comment]
> Strange, because no one else in the class has reported this error. Confirmed you are using the given build.gradle file and latest Intellij? If yes, can you try the following?:
> 
> 1. Close Intellij
> 2. Delete .idea folder of the project
> 3. Open the project again

I tried again, but it's still the same. 
Besides, I opened the same project in a Windows computer, then it worked well.
Is it possible that the problem may be due to some Mac configuration?

**Comment by marcuspeh** [comment]
Maybe you can try deleting the .grade folder on top of what Prof meintioned

**Comment by damithc** [comment]
> Is it possible that the problem may be due to some Mac configuration?

@wengYing227 Yes, possible. Let's see if other Mac users can pitch in (I'm a Windows user).
As a baseline litmus test, you can do the following:
* clone a fresh copy of duke upstream repo https://github.com/se-edu/duke
* merge the add-gradle-support branch to master
* open project in intellij

**Comment by pss-coder** [comment]
HI @wengYing227 , could share your build.gradle file ? 

I am also a mac user, sometimes I get plugin not found too. 
What I would then do is I would go to my terminal under the ip directory and run: 
`./gradlew clean` and then `./gradlew build`.

Afterwards, you could try running it.

**Comment by wengYing227** [comment]
> @wengYing227 can you check that gradle jvm is set correctly here?
> ![image](https://user-images.githubusercontent.com/17681226/131788082-357477e1-a2fb-4443-bba7-0676f7c1679e.png)
> 
> Furthermore, can you check that these links work?
> https://plugins.gradle.org/api/gradle/2.14.1/plugin/use/com.github.johnrengelman.shadow/5.1.0
> https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/5.1.0/

Thanks for your suggestions!
JVM Setting is the same as your picture.
And I can open the two links, if that's what you mean.
But, it still cannot work

**Comment by waynetee** [comment]
![image](https://user-images.githubusercontent.com/17681226/131835872-b21ef23c-5fed-4896-bf1a-5cff9db10b2a.png)
can I check what subversion of java are you using?

**Comment by wengYing227** [comment]
> ![image](https://user-images.githubusercontent.com/17681226/131835872-b21ef23c-5fed-4896-bf1a-5cff9db10b2a.png)
> can I check what subversion of java are you using?

Same SDK and language level setting as your picture shows

**Comment by waynetee** [comment]
Weird, you can try doing what the others said above. Can you try running `gradle run --debug` to get more details?

**Comment by damithc** [comment]
@wengYing227 any progress on resolving this issue?

**Comment by wengYing227** [comment]
@damithc I've tried various ways but failed to make it work on my mac. So I decided to use another Windows computer to catch up ip project. But I will still try to look for what's going wrong. Once I figure it out, I may update the issue later.
As there is no one else facing this problem, I'm going to close this issue now.
