### ISSUE TITLE
Cannot resolve symbol 'javafx'

### ISSUE THREAD

**Issue by rgbpokka** [nus-cs2103-AY2122S1/forum#166]
I have updated my build.gradle as explained in the tutorial here: https://se-education.org/guides/tutorials/javaFxPart1.html

I am able to run my Launcher.java just fine (the GUI shows up). However, I am getting the error "Cannot resolve symbol 'javafx'". 

![image](https://user-images.githubusercontent.com/66720042/131782877-48f802d6-982e-4597-a527-30fa72088a4f.png)

I have attempted to update my project structure but to no avail:

![image](https://user-images.githubusercontent.com/66720042/131782853-b85ef978-804e-47f9-a1f2-1bf7f4862592.png)

Help is sincerely appreciated.

**Comment by marcuspeh** [comment]
Close and open intellij should solve it. If it doesn't work, delete your .idea folder too

**Comment by rgbpokka** [comment]
Thank you! Deleting my .idea folder and reopening intellij worked :)
