### ISSUE TITLE
Cut Dialog Boxes

### ISSUE THREAD

**Issue by LeopardMerkava** [nus-cs2103-AY2122S1/forum#168]
Hi everyone!

I am currently working on the GUI and I noticed that my dialog boxes are being cut. However, I already set the max height to be MAX_VALUE. I realized that the boxes are only cut if the scroll pane is engaged. 

For example, this is not cut:
![No clip](https://user-images.githubusercontent.com/9478572/131803491-ee2bb552-cc18-4c26-9438-91132282533a.PNG)

But this is:
![Yes Overrun](https://user-images.githubusercontent.com/9478572/131803466-31100b8e-9ff5-412f-a51c-1bcf3d883890.PNG)

Anyone know what I can do to prevent that?

**Comment by waynetee** [comment]
Heres what I did
https://github.com/waynetee/ip/commit/0b329b7f31da419aafd4532f901837dc00e05d20

**Comment by ganhongyao** [comment]
Hi, I fixed this by adding `minHeight="-Infinity"` as an attribute to `Label` in `DialogBox.fxml`.

Found this [here](https://github.com/nus-cs2103-AY2021S1/forum/issues/125#issuecomment-683547168).

**Comment by zzybluebell** [comment]
@ganhongyao thx a lot solved same issue
