### ISSUE TITLE
The issue with java.lang.NoSuchMethodException: Duke Duke

### ISSUE THREAD

**Issue by zzybluebell** [nus-cs2103-AY2122S1/forum#169]
Hi Guys,

I have faced the issue when loading Launcher and Duke in javaFX.
faced the issues below

I have changed the "build.gradle" as below, but still faced the issues

application {
//mainClassName = "seedu.duke.Duke"
mainClassName = "Duke.Duke"
}

Thank you so much

![Screenshot 2021-09-02 at 3 47 46 PM](https://user-images.githubusercontent.com/37359804/131803945-1dce201a-7209-4f5e-a486-375d906d1feb.png)

**Comment by marcuspeh** [comment]
If your Duke class is not in pakage Duke, it will not work. Just replace the first Duke with whatever your package is. For example, if my package is duke and a subpackage run, i will replace it with duke.run.Duke

**Comment by zzybluebell** [comment]
Hi @marcuspeh , Thanks for your time.

But My Duke class is in Package Duke

**Comment by SkyBlaise99** [comment]
Maybe you can try by adding the following into your `Duke.java`
``` java
public Duke() {
    this(your whatever parameters);
}

// rest of codes
}
```

**Comment by austenjs** [comment]
Hi, I am from your senior batch. Maybe you can try this since it worked for me last time.

application {
    mainClassName = "Launcher"
}

**Comment by bharathcs** [comment]
Sorry, this wouldn't really help your current situation, but just FYI: package names are supposed to be all in lowercase, so it should be the package `duke` not `Duke`. (So the package name is `duke.Duke`, not `Duke.Duke`). Remember to change the folder name too!

**Comment by GabrielSimbingyang** [comment]
Hi @zzybluebell ,

An ex-student of CS2103T here. May I know if the issue has been fixed? If it was fixed, perhaps you could let us know of the solution before closing the issue to keep the forum tidy. Thank you!

Regards,
Gabriel Sim
