### ISSUE TITLE
Gradle does not recognise my test folder

### ISSUE THREAD

**Issue by clementkfj** [nus-cs2103-AY2122S1/forum#170]
Hello! My project was running smoothly before I installed gradle, and the tests were able to run without any problems and always passed. However after I built with gradle, the test files suddenly did not work(could not be run).
<img width="1440" alt="Screenshot 2021-09-02 at 4 46 19 PM" src="https://user-images.githubusercontent.com/77266065/131813535-a6e62327-9dd7-4187-8881-328565a2f5ae.png">

I could not import anything related to junit and even when I tried to create a new Test file by using IntelliJ's in built auto test creator, the new Test file was not created in the allocated duke test file and was created in the same path as the class that I was meant to test.
<img width="1440" alt="Screenshot 2021-09-02 at 4 49 11 PM" src="https://user-images.githubusercontent.com/77266065/131813504-355356e8-702d-4d75-886c-19d2ede25dff.png">

I tried to delete and rewrite import statements of junit packages as well as duke classes but they do not even light up as suggestions when I type half of it and it still cannot be found. 
If anyone can help me I would be very appreciative thank you!

**Comment by damithc** [comment]
@clementkfj In addition, https://github.com/nus-cs2103-AY2122S1/forum/issues/129 may be of relevance. The problem stated is different but the solution might apply here as well.

**Comment by clementkfj** [comment]
@simonjulianl @damithc thank you so much! I managed to fix it by changing test root files and thus the test file becoming a module!
