### ISSUE TITLE
Rebase label after attempting rebase 

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#171]
I tried rebasing children of some commit interactively and clicked on some buttons (I wanted to squash initially but dk why i went there) but anyways nothing happened when i clicked on those buttons in the pop up window and then now whenever i open up to sourcetree repo list this shows:
![Screenshot 2021-09-02 at 9 12 58 PM](https://user-images.githubusercontent.com/59001819/131849761-46795a29-07ac-4ab4-8e8b-50192baafb87.png)
Even though the repo seems to be perfectly normal i get this yellow rebase label, anyone knows why it is there and how i can get rid of it?

**Comment by damithc** [comment]
@softmagnet you can try `git rebase --abort` command to abort any interactive rebase session that is in progress.

**Comment by softmagnet** [comment]
Thanks prof! I will close this now.
