### ISSUE TITLE
💡 Closing JavaFX after bye command

### ISSUE THREAD

**Issue by alissayarmantho** [nus-cs2103-AY2122S1/forum#172]
In MainWindow.java,
```import javafx.application.Platform;```

then,  in handleUserInput function (in MainWindow.java), you can manually check:
``` 
        if (response == <byeMessage>) {
            Platform.exit();
        }
```

This will close the application after bye command..., however your bye message may not be printed out / seen before the application closes. Please let me know if there is a better way of doing this :')

**Comment by kaushikkrdy** [comment]
What I did was I printed out the bye message, and then used Java's Timer class to set a delay on the Platform.exit() command. That way you can have the bye message be visible to the user for as long you wish before closing the application.

https://stackoverflow.com/questions/21974415/how-to-close-this-javafx-application-after-showing-a-message-in-a-text-area-elem/21996863

**Comment by NicolasCwy** [comment]
I tried to listen to the userInput command instead as I thought it would be easier but it never triggered any ideas why?
[Gist](https://gist.github.com/NicolasCwy/1514e2c447bb65ea436a10dae77c6f44.js)

```
if (userInput == "bye") {
            Platform.exit();
}
```

**Comment by kaushikkrdy** [comment]
@NicolasCwy 
Try using `input.equals("bye")`

**Comment by NicolasCwy** [comment]
@kaushikkrdy oops thanks for the simple fix, since `response == <byeMessage>` worked for me I assumed `input == "bye"` would work as well.

**Comment by Yukun99** [comment]
> @kaushikkrdy oops thanks for the simple fix, since `response == <byeMessage>` worked for me I assumed
> `input == "bye"` would work as well.

In general do not use `==` for non primitive types, since java treats instances of classes as different objects for that. Where possible, opt for the `equals()` method.

**Comment by VimuthM** [comment]
To answer OP's question, I initially tried to use the `Thread.sleep()` as well as a `Timer` class. It did not work as expected because it caused the program to sleep immediately preventing the previous lines of code which showed the bye message to run and display on the GUI.

Instead, I ended up using `CompletableFuture` as shown in [this](https://stackoverflow.com/a/58707945/10996783) stackoverflow answer!

**Comment by alissayarmantho** [comment]
Actually along this thought, we should also try to exit javafx cleanly (disable textfield and button, set textfield text to "exiting..." to indicate the disabled textfield and button is not a bug, and disable the enter key from doing anything after user sent bye command, otherwise unintended behaviour may occur.

**Comment by alissayarmantho** [comment]
> > @kaushikkrdy oops thanks for the simple fix, since `response == <byeMessage>` worked for me I assumed
> > `input == "bye"` would work as well.
> 
> In general do not use `==` for non primitive types, since java treats instances of classes as different objects for that. Where possible, opt for the `equals()` method.

Yap I agree, this sounds good.

> What I did was I printed out the bye message, and then used Java's Timer class to set a delay on the Platform.exit() command. That way you can have the bye message be visible to the user for as long you wish before closing the application.
> 
> https://stackoverflow.com/questions/21974415/how-to-close-this-javafx-application-after-showing-a-message-in-a-text-area-elem/21996863

This works for me. Thanks!
