### ISSUE TITLE
javaFX runtime components are missing

### ISSUE THREAD

**Issue by jiarong15** [nus-cs2103-AY2122S1/forum#173]
When I tried running my gradle project I'm encountering the error:
"JavaFX runtime components are missing, and are required to run this application"

In my build.gradle I already have added the following

String javaFxVersion = '11'
implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win' implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac' implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'

**Comment by kaushikkrdy** [comment]
Does this help? #132

**Comment by Agentum07** [comment]
Try checking your SDK in File > Project Structure. It should be 11.

**Comment by pss-coder** [comment]
Hi @jiarong15, could you try checking at this -> [`issue  #154 `](https://github.com/nus-cs2103-AY2122S1/forum/issues/154#issuecomment-911202288)

**Comment by jiarong15** [comment]
Now I'm getting Location not set error
![image](https://user-images.githubusercontent.com/75774103/132044183-318c720b-a341-46eb-b264-7cdb6de98118.png)

**Comment by samyipsh** [comment]
hi, had the same error and someone pointed out I typed in the fileName wrongly 😭 
If your file name is correct, could try following following the folder structure. 
![image](https://user-images.githubusercontent.com/72609722/132081035-e42269d7-7479-473e-b4ea-68be23bb4a8e.png)

Credits @SkyBlaise99

**Comment by SkyBlaise99** [comment]
Did you miss out the folder name? Mine looks like this
![image](https://user-images.githubusercontent.com/69448615/132081346-3979dd69-c71e-409a-9976-d12f31d88c63.png)

**Comment by Agentum07** [comment]
I suggest you move your `thanos.jpg` and `ironman.jpg` to a different folder and then follow the guide.

**Comment by jiarong15** [comment]
I've changed the folder structure and now am receiving the error "couldn't delete C:\Users\65964\Desktop\Modules\Sem1\CS2103\ip\build\resources\main\images\ironman.jpg"

really unsure what's wrong
