### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by ramapriyan912001** [nus-cs2103-AY2122S1/forum#176]
Hi all,

I tried to reorganise my code upon the addition of gradle.
I created a test folder under <src/main> subdirectory and marked it as a test sources root.
I moved my ParserTest class to this folder from the duke package (where it was previously).

The screenshot below indicates part of the folder structure and my ParserTest class.
<img width="1792" alt="Screenshot 2021-09-03 at 6 45 20 PM" src="https://user-images.githubusercontent.com/64624151/131993750-ff3db377-3081-4084-aff6-efe02736a692.png">

However, whenever I try to run the class, the tests do not run and a message (as seen in the screenshot) saying "No tasks available" shows. Furthermore when I try to run the tests from the gradle menu on the side, the same result is observed.

My build.gradle has the following code (which I believe is sufficient to run tests): -
```
test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}
```

Any suggestions on how to rectify this?

**Comment by AllardQuek** [comment]
Is your program still working fine? Maybe check if your test output path is set correctly? This is what it looks like for me:

![telegram-cloud-photo-size-5-6165531575131942239-y](https://user-images.githubusercontent.com/40263305/131997922-e8679af9-f211-4ebf-8bdf-effee2b5d2e2.jpg)

**Comment by damithc** [comment]
This may be relevant https://github.com/nus-cs2103-AY2122S1/forum/issues/129#issuecomment-908292548

**Comment by ramapriyan912001** [comment]
<img width="1792" alt="Screenshot 2021-09-04 at 2 42 00 PM" src="https://user-images.githubusercontent.com/64624151/132085474-9e7d087d-d13c-47c7-b8f2-8539eeb60503.png">

Still does not work after restructuring the project...

**Comment by simonjulianl** [comment]
Have you tried to `invalidate cache/restart` and may I know whether you are using JUnit 5/4, and which version of it specifically, not only that maybe you can try to run using IntelliJIdea test runner and check whether there has been any compilation error

**Comment by darrenhoon** [comment]
Hi Rama, could you try removing the static from the method names? Since the method is currently greyed out which means the method is not being used. I tried replicating your issue and I got the same error when I used static for my methods too.

When I use static methods:
![image](https://user-images.githubusercontent.com/34526101/132113339-b9b27fe7-454b-455d-9679-fa1fbfa7138c.png)

non-static methods:
![image](https://user-images.githubusercontent.com/34526101/132113347-e6c16306-3d9e-4576-bd3b-c2fa4fa252fb.png)

**Comment by damithc** [comment]
> Hi Rama, could you try removing the static from the method names? Since the method is currently greyed out which means the method is not being used. I tried replicating your issue and I got the same error when I used static for my methods too.

Good catch @darrenhoon

**Comment by ramapriyan912001** [comment]
Image below shows the console when I try to run the tests.

<img width="1792" alt="Screenshot 2021-09-06 at 8 44 10 AM" src="https://user-images.githubusercontent.com/64624151/132146311-e3b8509f-eafa-4e9f-8201-319d2ebfff35.png">

@darrenhoon @damithc

**Comment by damithc** [comment]
@ramapriyan912001 in case this is a caching problem, try File -> Invalidate cache

**Comment by ramapriyan912001** [comment]
@damithc @darrenhoon no change after doing that either.
Same error.

**Comment by VimuthM** [comment]
@ramapriyan912001 maybe you can push this version to a temporary branch so we can take a look?

**Comment by ramapriyan912001** [comment]
Here's my project structure
I'm not sure why there are 2 main modules there.

<img width="1792" alt="Screenshot 2021-09-06 at 2 17 07 PM" src="https://user-images.githubusercontent.com/64624151/132169444-eb38498d-903c-4eec-8983-6bb009fe52d8.png">

I tried deleting the CS2103.ip.test directory but when I try to apply the changes, the following message pops up and blocks me from doing so.

![Uploading Screenshot 2021-09-06 at 2.20.25 PM.png…]()

**Comment by ramapriyan912001** [comment]
> @ramapriyan912001 maybe you can push this version to a temporary branch so we can take a look?

@VimuthM sure will do so

**Comment by ramapriyan912001** [comment]
Do I just make a new branch in my cloned repo?
If so, here's the branch: https://github.com/ramapriyan912001/ip/tree/Test-Issue-Branch

Please let me know if you're looking for something else.

**Comment by damithc** [comment]
> I'm not sure why there are 2 main modules there.

Try deleting the .idea folder and reopen the project in Intellij -- see if that gets rid of extra modules.

**Comment by marcuspeh** [comment]
I think it could be due to this line in your build.gradle
```
    implementation 'junit:junit:4.12'
    implementation 'org.testng:testng:7.1.0'
```
Once I remove it from your build.gradle, it is able to get the test files (even though it says all the junit test are not found).

**Comment by ramapriyan912001** [comment]
Thank you Marcus, works now!
