### ISSUE TITLE
A-Assertions

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#177]
I have attempted this and found out that `assert` throws an `AssertionException`, and this causes errors in my unit testing as I expect my own exceptions (the `DukeException` that we made) to be thrown.

Any tips on what to do in this case? Such as making gradle's test to ignore `AssertionException`?

From the notes it mentioned that `assert` is __disabled__ by default on `java` and we need to use a `-ea` flag to activate it so I wonder if it is the same case for testing? Or should I just remove those `assert` that interferes with my own exception throwing?

Also, any suggestions on how many `assert` to add? Or this level is just to let us get familiar with it so any number is ok?

**Comment by damithc** [comment]
@SkyBlaise99 An `assert` failure indicates a bug in the production code (that's what they are supposed to detect). They should not overlap with conditions already handled by your own exceptions.  If they interfere your testing, most likely you are not using them correctly.


> From the notes it mentioned that `assert` is **disabled** by default on `java` and we need to use a `-ea` flag to activate it so I wonder if it is the same case for testing? Or should I just remove those `assert` that interferes with my own exception throwing?

I believe assertions are auto enabled during testing. Good thing too, as you wouldn't have found the above problem otherwise :-)

**Comment by SkyBlaise99** [comment]
But if my code pretty much handled all the cases I can think of, what should I put for `assert`? Should I use `assert` to double check that my code indeed handled all the cases?

**Comment by Ruofan1023** [comment]
My understanding of the diff btw exception and assertion is that exception is triggered by a user mistake but the assertion by a programmer mistake? So for some potentially programmer-induced mistake, if you have used exception, can consider use assertion instead? 

> * The raising of an exception indicates an unusual condition created by the user (e.g. user inputs an unacceptable input) or the environment (e.g., a file needed for the program is missing).
> * An assertion failure indicates the programmer made a mistake in the code (e.g., a null value is returned from a method that is not supposed to return null under any circumstances).

**Comment by SkyBlaise99** [comment]
Can't really find some places to insert `assert` as most of the places Intelij will highlight it as `unreachable code` due to `exception` handling the cases, but I managed to put it somewhere in my codes... I hope they are fine with just 1 `assert`...

**Comment by yucheng11122017** [comment]
I think its just more to confirm some stuff. Maybe you can change some void functions to return true or false to indicate if it is executed correctly. Not very sure if this is advisable though.

**Comment by SkyBlaise99** [comment]
That's an interesting idea. What I put in my code currently is to ensure that the list of tasks to be saved to local storage cannot be `null`, although inside my code this technically will never happen. I guess I'm treating `assert` as some ways to double check.

**Comment by yucheng11122017** [comment]
@SkyBlaise99 On that note, I also used assert to double check that the format of my file that tasks are saved to is right. Eg if it assumes that each task should be prefixed with its type, it will throw an error if the first word isnt a task type. Maybe this could work?

**Comment by SkyBlaise99** [comment]
Thx for all your helps and suggestions @yucheng11122017. I managed to slip in a few `assert`. I shall close the issue alr.
