### ISSUE TITLE
A-Streams

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#178]
I had previously used `streams` in my code already so what should I do for this level? I noticed that if I make a branch but no edits, I can't make a pull request to my own repo? Is this the case or did I do something wrong in my steps.

Steps I did:

1. Open SourseTree & branch from master
1. Right click `branch-A-Streams` and select `Create pull request...`
1. Redirects me to the website
![image](https://user-images.githubusercontent.com/69448615/132001789-feb93922-d994-4616-b720-fc546fd50c21.png)
1. Change base repo to my own
![image](https://user-images.githubusercontent.com/69448615/132001876-b613ffbf-43a7-4508-a9f7-344d2e9ec9ae.png)
1. The `Create pull request` part disappeared

Can I just add a branch and add a tag for this level if there is nothing to do?

**Comment by damithc** [comment]
> Can I just add a branch and add a tag for this level if there is nothing to do?

Yes, that should be fine too. BTW, it's an optional increment. You can skip it entirely.

**Comment by SkyBlaise99** [comment]
Ok thx prof

**Comment by uyencfi** [comment]
Hi @SkyBlaise99, I also used `stream` already in my code a few levels back. Can I check that I just need to create a branch and tag the commit? And I cannot merge that branch right? Thanks!

**Comment by marcuspeh** [comment]
> Hi @SkyBlaise99, I also used `stream` already in my code a few levels back. Can I check that I just need to create a branch and tag the commit? And I cannot merge that branch right? Thanks!

I think Prof mentioned something about the script cannot detect tags on branches. What i did was to edit abit of the comments so that i can merge it and tag

**Comment by damithc** [comment]
> I think Prof mentioned something about the script cannot detect tags on branches. What i did was to edit abit of the comments so that i can merge it and tag

@marcuspeh It can detect tags on branches, as long as the branch has been merged to the master branch.
@SkyBlaise99 If you have done the work in a previous commit, just tag that commit and push the tag.

**Comment by SkyBlaise99** [comment]
What I did is just add a tag into my master, since as prof said, it is optional and the grader actually does not detect the branch if you check the ip tracker website
