### ISSUE TITLE
IP week 2 adding task functionality (Level 2, Level 4)

### ISSUE THREAD

**Issue by clyveycui** [nus-cs2103-AY2122S1/forum#18]
Hi, just to clarify, upon implementing level 4 which is support for the 3 different task types, can we drop support for adding a generic task (i.e. tasks added without being preceded by any keywords such as "todo", "deadline", and "event"), or should we continue to allow users to add such generic tasks? 

```
read book
    ____________________________________________________________

     added: read book
    ____________________________________________________________
```

If we continue to support adding of generic tasks, this will conflict with the example as seen in the error handling, 
```
blah
    ____________________________________________________________

     ☹ OOPS!!! I'm sorry, but I don't know what that means :-(
    ____________________________________________________________
```
Here "blah" would have been interpreted as just another generic task if we continued to support adding of generic tasks.

**Comment by SkyBlaise99** [comment]
Has to be dropped so the blah will not be considered as a task.

**Comment by clyveycui** [comment]
So it would probably be fine if we were to make Task an abstract class I guess?

**Comment by damithc** [comment]
Yes, you may drop that type of task entry. You are free to keep supporting it too, if you figure out a good way to do so. The requirements given are just a baseline -- you are free to tweak or do more. In particular, you can tweak the command format as you see fit.

**Comment by SkyBlaise99** [comment]
But if we tweak the command format will the auto grader still works? Say if we change the format from `deadline xxx /by yyy` to `deadline xxx /at yyy`, later the auto grader inputs `deadline xxx /by yyy` format and we return the bot a `Sorry I don't know the command` etc.

**Comment by damithc** [comment]
> But if we tweak the command format will the auto grader still works?

There is no 'auto grader' as such @SkyBlaise99 
Our scripts simply check if the expected tags are present, just to track your progress (as 'self-declared' by you using tags).
So, you have freedom to make the iP 'your own' by tweaking its behavior as you wish.

**Comment by SkyBlaise99** [comment]
Oh ic. I thought auto grader means it will give us a grade, so it is just a tracker in a sense. Thank you prof!
