### ISSUE TITLE
Font error: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font.

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#180]
My font got messed up after running shadowJar like this:
![Screenshot 2021-09-04 at 4 12 14 PM](https://user-images.githubusercontent.com/59001819/132087788-13e22c0f-a83e-4bf3-9b2b-f03bb0ffffe6.png)
and i followed this:
https://stackoverflow.com/questions/67893273/javafx-font-not-being-rendered-correctly
by setting all font to serif.

# update: new problem
But then i run into another problem, when i click in and out of the chatbox main vertical panel, the text size resizes automatically...any one able to help? 

https://user-images.githubusercontent.com/59001819/132088362-e2d274db-db7d-493b-aef6-183f0354c7e8.mov

Also how do i change the label for a thread like this? want to change to asking question

**Comment by SkyBlaise99** [comment]
I guess you can close this and repost again if you wish to

**Comment by softmagnet** [comment]
ok i will close this and repost, thanks!
