### ISSUE TITLE
Addition of GUI renders old UI class obsolete

### ISSUE THREAD

**Issue by BryannYeap** [nus-cs2103-AY2122S1/forum#181]
Previously my UI class involved methods that printed the logo, single and double divider lines,  and obtaining user input using `Scanner`. Since the addition of the GUI, we no longer need UI elements like divider lines, and no longer need to obtain user input using `Scanner`. Thus I deleted the UI class altogether. But do I technically now fall short of the minimal requirements for week 3's `A-MoreOOP`? It mentioned that one of the minimal requirements was to have a UI class, or does it just mean at that point of time (when u check the tag), the commit should have the UI class.

**Comment by damithc** [comment]
@BryannYeap It's OK to remove unused features/code.  It does not affect your marks, provided the removed code is still in past commits.

**Comment by AllardQuek** [comment]
> provided the removed code is still in past commits.

How will we be graded if the code is removed? Is the grader going to look at the tagged commits?

**Comment by SkyBlaise99** [comment]
Or you can just keep it there and have 2 `main()`, 1 for GUI and 1 for CLI 😄

**Comment by simonjulianl** [comment]
You can always get your old class by looking at the `git` history, so I think removing unused code is fine to keep the code-base relevant, that's my take

**Comment by BryannYeap** [comment]
I see! Thanks guys!
