### ISSUE TITLE
How to/Better implementation for compareTo

### ISSUE THREAD

**Issue by VimuthM** [nus-cs2103-AY2122S1/forum#184]
Raising this issue to see if there are good ways to implement the following:

I'm trying to implement sort functionality by adding a `compareTo` method in my `Task` class. Inside this method, I saw duplicated code for my `Event` and `Deadline` classes and tried to extract this out to a `compareDateTime` method.

The issue is that instance variables `date` /`time` are specific to `Event`/`Deadline` classes only and not to `Task` and therefore casting is needed. But I'm not sure how to do this :(

Using generics crossed my mind, but my 2030S knowledge has failed me in my hour of need 😫

> TLDR: `compareDateTime` accepts either 2 `Event` or `Deadline` objects. They need to be cast accordingly to access their variables.

![image](https://user-images.githubusercontent.com/62249192/132105349-afa3fb2a-3c47-4710-8001-d6eb7068e499.png)

**Comment by XXJJXJ** [comment]
How about creating an abstract class that extends from Task, and let it contain the Date and Time class fields and the compareTo method. Then let Deadline and Event extend from this new class? (Not sure if this is better, but this kinda reduces the "code duplication" problem)

**Comment by yucheng11122017** [comment]
Otherwise, you can use overloading to implement compareTask function in task. 
 
Ie. have compareTask(Event, Deadline) and compareTask(Deadline, Deadline) etc. 
So if its Event vs Deadline then you compare the time. 
If its Todo vs Deadline then you just return toDo. 

Still think @XXJJXJ's solution is the best haha. Since you have to implement for many different permutations and if another class of Task is added you have to add even more. 

By the way, you can't use generics for this since it's meant for things like ArrayList Hashmap and so on. Maybe you are thinking about how Event are subclass of Task and hence can be passed into the function that takes in Task. 😄

**Comment by SkyBlaise99** [comment]
You can take a look at my code. I also did `C-Sort`. It can give you a better idea what exactly you should do.

**Comment by VimuthM** [comment]
Yeah seems like I will have to modify my OOP implementation like @XXJJXJ mentioned. Thanks @yucheng11122017 for explaining why generics is not applicable!

@SkyBlaise99 we seem to be doing it in a very similar way haha but I've allowed Events and Deadlines to have an optional Time value. This introduces the additional chunk of duplicated code which would go inside the ternary op you used. 

Thanks guys for the input! 😄

**Comment by SkyBlaise99** [comment]
If they are optional, you can add a method which returns a dummy value if they do not have time stored.

**Comment by VimuthM** [comment]
In the sense, since ToDo doesn't have date time, I didn't make them part of the Task class -> Separate casting required for each.

Its exactly like your ternary op [here](https://github.com/SkyBlaise99/ip/blob/1100320edd2a9338c3727a16d929aaf9699fdea7/src/main/java/sora/task/Task.java#L100). I just have a lot more duplicated code similar to your `.extractDateTime` call in both the consequent and alternative.

**Comment by SkyBlaise99** [comment]
Didn't look at your code so I'm not sure what is your situation exactly. I've just updated my code to be cleaner in a sense that my `compareTo` is now much shorter. You can take a look at it again and maybe it is what you needed.

In my case I'm comparing 2 `Tasks` objects. `Task` has this abstarct method called `extractDateTime()` which runs depending on how the child class implements it.

**Comment by VimuthM** [comment]
Yes, your new implementation was what I was planning to go ahead with. I'm not sure if [this](https://github.com/SkyBlaise99/ip/blob/1ac685b0f7e6b71a03f56588241af4cb8d618e8e/src/main/java/sora/task/Todo.java#L21) is a good way since I don't want my ToDo class to have anything to do with date, time.

I might also just implement `compareTo` separately in the Event and Deadline classes. Seems simpler and OOP-friendly as well.

**Comment by VimuthM** [comment]
@SkyBlaise99 [this](https://github.com/VimuthM/ip/commit/23d3cce6295b389b17ff17a2a52837416349ba16) is how I ended up implementing it! Thanks for the input :)
