### ISSUE TITLE
"Tasks" in PR list

### ISSUE THREAD

**Issue by kawaiigabrielneko** [nus-cs2103-AY2122S1/forum#189]
When looking at the PRs of the master ip, I've noticed that some people have "n tasks" or "n of m tasks" next to their name. What does that mean?

**Comment by yongxiangng** [comment]
![image](https://user-images.githubusercontent.com/60974969/132128960-269bbb7c-d706-4a33-8996-6d503820fcf3.png)
![image](https://user-images.githubusercontent.com/60974969/132128968-3ea9221f-5043-47f1-b4c9-77f441fde3ce.png)
I believe it is the task list in the GFMD which you can add with the following
```
Features:
- [x] Managing tasks
- [ ] Managing deadlines (*coming soon*)
- [ ] Reminders (*coming soon*)
```

**Comment by VimuthM** [comment]
I think that GitHub wants feedback on it's implementation of the checklists in markdown. 

The "n of m" tasks simply indicates how many tasks have been checked already and it links you to a feedback page/forum iirc.

**Comment by Smanmos** [comment]
This was very interesting and insightful. Thank you!
