### ISSUE TITLE
💡"Copy" over the EXACT content of the ACTUAL.TXT to EXPECTED.TXT

### ISSUE THREAD

**Issue by GnohChengYi** [nus-cs2103-AY2122S1/forum#19]
I encountered an issue where my `ACTUAL.TXT` and `EXPECTED.TXT` differ by a few trailing spaces (in the logo area).

Hence, I manually add the missing trailing spaces to `EXPECTED .TXT` in **Intellij**. The newly added trailing spaces are there after I saved the file. However, they always disappear after I run `runtest.bat`.

I tried copy over the content from `ACTUAL.TXT` to `EXPECTED.TXT` using `Ctrl + a`, `Ctrl + c` and `Ctrl + v`, but those spaces were somehow not copied over, i.e. the difference between the files remains the same.

To solve this, I changed `line 18` of `runtest.bat` from
`java -classpath ..\bin Blue < input.txt > ACTUAL.TXT`
to 
`java -classpath ..\bin Blue < input.txt > EXPECTED.TXT`
so that the outputs were printed to `EXPECTED.TXT` directly.

This will result in the following error in console:
`FC: cannot open ACTUAL.TXT - No such file or folder`
but it will disappear in the next run after we change `line 18` of `runtest.bat` back to its original form.

Note that I couldn't replicate the issue after getting the correct content into my `EXPECTED.TXT`. 
I am not sure how the issue happened, but I hope this tip can help those who face a similar situation.

**Comment by damithc** [comment]
@GnohChengYi Perhaps your Intellij is configured to trim trailing spaces automatically?

**Comment by tenebrius1** [comment]
To add on, if you are sure that your `ACTUAL.txt` and `EXPECTED.txt` only differs because of trailing spaces or due to some UNIX vs Windows formatting issue, one way to "copy EXACTLY" is by using the command `cp ACTUAL.txt EXPECTED.txt`. I faced similar issues and this worked for me.

**Comment by GnohChengYi** [comment]
> @GnohChengYi Perhaps your Intellij is configured to trim trailing spaces automatically?

Oh ya, it is!
But if I remembered correctly, the newly added trailing spaces are there (in the opened file) after I saved using `Ctrl + s`.
Anyways, not a big issue I guess.
