### ISSUE TITLE
Naming conventions for a method that returns a string but doesn't print it

### ISSUE THREAD

**Issue by wpinrui** [nus-cs2103-AY2122S1/forum#191]
I have gotten a few comments pointing out that my method below is not named as a verb:

```java
public static String outOfBoundsString(int index) {
    return String.format("Out of bounds: %d", index);
}
```
One suggestion I've been given is to name it `printOutOfBoundsString`, however I feel that this might give the impression that the method might look something like this:

```java
public static void printOutOfBoundsString(int index) {
    System.out.println(
            String.format("Out of bounds: %d", index));
}
```
Furthermore, I think the original name makes more sense when I do something like `System.out.print(outOfBoundsString(index))` as opposed to `System.out.print(printOutOfBoundsString(index))`.

Is there a better way of naming this method / any method that returns a string but doesn't print it?

**Comment by VimuthM** [comment]
I agree with the reviewer that naming can be better, but `print` might not be suitable. According to the coding standard;

![image](https://user-images.githubusercontent.com/62249192/132134732-1c903029-f804-4819-ac04-a195b9ded748.png)

I think something along the lines of `getOutOfBoundsString` might be appropriate!

**Comment by xlzior** [comment]
Not sure what class this belongs to, but maybe `formatOutOfBoundsString`?

**Comment by s7u4rt99** [comment]
I named mine by adding a `get` in front, to make it sound like a getter. So in this case it would be `getOutOfBoundsString`. But not sure if this is the best way.

**Comment by yucheng11122017** [comment]
I think get<The string name> is probably the best! The function that starts with print is a bit misleading haha

**Comment by ganhongyao** [comment]
I personally feel that prefixing `get` in your case here may be a bit misleading since we usually associate `getX` with a method returning field `X` from the instance.

Since you are kind of formatting a string in the method, I think that using "format" as the verb here would be appropriate. 

Additionally, `outOfBoundsString` sounds like it is the string that is out-of-bounds, but actually it is the `index` that is out-of-bounds.

I would suggest `formatIndexOutOfBoundsString`, but since the strings are actually messages to be displayed to the user, how about `formatIndexOutOfBoundsMessage`?

**Comment by damithc** [comment]
> I personally feel that prefixing `get` in your case here may be a bit misleading since we usually associate `getX` with getters, which are methods returning field `X` from the instance.

Good point. Another option is to use `getAs...` which hints that you are retrieving a value that is calculated on the fly. It also tells the reader that this is a _query_ type operation that doesn't change the state of the object.

**Comment by marcuspeh** [comment]
What I did was to add in a ```format``` in front of my methods that is similar the example you shown

**Comment by SkyBlaise99** [comment]
Going by the `printOutOfBoundsString()` idea, maybe this
``` java
public static void printIndexOutOfBoundsError(int index) {
    System.out.printf("Out of bounds: %d\n", index);
}
```

**Comment by wpinrui** [comment]
Thanks everyone! 😀 I think I will go with format, as I am using `String.format` to format the string after all. I feel that this is less misleading than `print` and `get`.
