### ISSUE TITLE
Self-explanatory magic literals

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#192]
Should i replace strings like  `", "` in:
```java
currStrArr = currLine.split(", ");
```
Since it is quite self-explanatory, is this still considered magic literal?

**Comment by damithc** [comment]
The main benefit of avoiding magic literal is that it makes the meaning of the literal clear by giving it a descriptive name. That no longer applies if the meaning is clear from the literal itself.
A secondary benefit of this practice is to ensure all usages of the literals are consistent. By defining it in one place and using it everywhere, you can avoid problems such as accidentally missing out the space after the comma in some places.

**Comment by yucheng11122017** [comment]
Unless you are consistently using this as a separator I don't think so. 

This means that for example your tasks are always seperated by ", " in your file saved. Then you will use it in more than one instance (when accessing it and when saving it). Then maybe it's worth replacing just in case you change it in one instance but not the other.

**Comment by SkyBlaise99** [comment]
What about this case: say I wish to perform `str.substring(4)` only once, should I make an `int xxx = 4;` just for this and explain what xxx is?

**Comment by wpinrui** [comment]
I had the same problem with the substring, what I did was to declare a constant for my operation name and then do `str.substring(operationString.length() + 1)`. My rationale is that this magic number depends on the name of the operation.

**Comment by yucheng11122017** [comment]
@SkyBlaise99 nah i think thats overkill.. unless you are gonna keep using it

**Comment by SkyBlaise99** [comment]
I feel that too I got it in the comment from others abt magic literals...

**Comment by BryannYeap** [comment]
Yea I got that in the comments too so I added a local constant. Not sure either...

**Comment by wpinrui** [comment]
I think it is a magic literal though. If someone else looks at it, can they tell why `substring(4)` and not 5 or some other number? I think if they can then it's fine to use it but in this case, someone who doesn't have any context might not understand the number which makes it 'magic'.

**Comment by qinguorui2001** [comment]
So for a number that should be used in a large scope we can give it a descriptive name and for a number used only in particular method, could adding some comment instead be an alternative way?
