### ISSUE TITLE
Facing issues with Github when pushing .yml file for CI task

### ISSUE THREAD

**Issue by huyuxin0429** [nus-cs2103-AY2122S1/forum#195]
Using Intellij ver 2021.2.1 (Community Edition) on Windows machine.

I am facing the error message 

"! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow \`.github/workflows/duke.yml\` without \`workflow\` scope)" 

when attempting to push the workflow yml to github. I have followed instructions from [here](https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on) and changed my Intellij github API link to a personal access token with workflow enabled, but the issue still persists.

Any help will be appreciated!

**Comment by SkyBlaise99** [comment]
Not exactly a solution but you can create the `.yml` file in Github and edit it in there first. I also can't figure how to do it via Intelij and pushing the commit.

**Comment by marcuspeh** [comment]
Maybe you can have a look at [this](https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on). It's probs the authentication token permissions

**Comment by kevin9foong** [comment]
Hi, I previously faced the same issue and resolved it using this [guide](https://jessehouwing.net/cannot-push-to-github-without-workflow-scope/) - just need to add a github token to your credentials manager.

**Comment by litone01** [comment]
Hi @huyuxin0429, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). Can I kindly check if the issue has been resolved? If yes, do you mind kindly closing the issue? Otherwise, do you mind sharing an update on the current issue? Thanks!
