### ISSUE TITLE
Getting this issue called `InvocationTargetException`

### ISSUE THREAD

**Issue by rish-16** [nus-cs2103-AY2122S1/forum#198]
Hey everyone, 

> I'm using IntelliJ 2021.2 Community Edition on macOS.

I get this exception called the `InvocationTargetException` when I try to run the `Launcher.java` that powers the whole chat app. I am not sure of the source of the error, which is why I can't really attach any code snippets.

![image](https://user-images.githubusercontent.com/20137995/132230678-8975d5b6-b502-4849-947e-016d04d6c767.png)

Has anyone else gotten this exception before? What are some possible things I can do to troubleshoot the problem? I'm down to provide any other details.

Any help appreciated :D

**Comment by VimuthM** [comment]
Hi Rishabh, 

Not exactly a solution but I've gotten this exact exception a couple of times. I usually focus on fixing the errors beneath this one, after which this does not show up (at least not yet). For example, from the snippet shown, try fixing the `ArrayIndexOutOfBoundsException` (You can select the exception and run with --scan for more details, which I found helpful).

I assume the `InvocationTargetException` is a result of exceptions propagating out of Duke to the GUI segments.

**Comment by rish-16** [comment]
Hey @VimuthM, thanks for reaching out!

I managed to resolve the issue 😄  Turns out one of my `switch` blocks was causing some problems. Who would have though 😅 

Appreciate the help, though!

**Comment by Agentum07** [comment]
Hi @rish-16, how did you figure out which class was throwing the error?
I'm getting the same error but can't figure out the class.

**Comment by Agentum07** [comment]
Hi @rish-16 
How did you figure out which class threw the error?
