### ISSUE TITLE
💡SourceTree "Display a column guide ..." checkbox disabled

### ISSUE THREAD

**Issue by GnohChengYi** [nus-cs2103-AY2122S1/forum#199]
In the [Git conventions](https://se-education.org/guides/conventions/git.html#commit-message-body), under "Commit message: Body", the tips for SourceTree users include:

> * Enable the column guide option to help you keep the commit message width to a 72 characters:
> 1. Choose `Tools` -> `Options`.
> 2. Click on the `General` tab, scroll down to the `Commit settings` section.
> 3. Tick the `Display a column guide at commit message at [72] characters` option.

For me, the checkbox is disabled, i.e. it was not checked and cannot be checked.

It turns out that I need to check "Use fixed-size font for commit messages" option as well, which is just a few checkboxes underneath.

![image](https://user-images.githubusercontent.com/19379090/132232216-380e37de-ec0a-40c6-8aab-0abee4494c83.png)

**Comment by damithc** [comment]
Thanks for sharing this @GnohChengYi 
I'll update the relevant se-edu guide to mention this tip as well.
