### ISSUE TITLE
Fast forward vs Rebasing

### ISSUE THREAD

**Issue by waynetee** [nus-cs2103-AY2122S1/forum#2]
https://www.youtube.com/watch?v=v40b3ExbM0c&t=581s

At this point in the video, it seems to me that the animation is showing a rebasing (manual process) instead of just an automated fast forward merge as labelled. Could anyone clarify?

**Comment by VimuthM** [comment]
I agree. If I understand right, for a fast forward merge to occur, the latest commit of the branch being merged into must be an ancestor in the history of the other branch. 
Since `C4` is a new commit on `master` not within the history of `coolfeature` branch, this should a rebasing.

**Comment by damithc** [comment]
Good catch guys! I think visualization of the last part of that video needs to be corrected (will do once I find the time, provided I can still locate the original source files :-p)

**Comment by softmagnet** [comment]
![IMG_A7D551987AE1-1 2](https://user-images.githubusercontent.com/59001819/129446730-000688a6-15e1-4e7e-a377-94e7eb5d8a79.jpeg)

Hi can i clarify that this is the right concept. thanks!

**Comment by softmagnet** [comment]
![IMG_A7D551987AE1-1 2](https://user-images.githubusercontent.com/59001819/129446730-000688a6-15e1-4e7e-a377-94e7eb5d8a79.jpeg)

Hi can i clarify that this is the right concept. thanks!

**Comment by damithc** [comment]
> <img alt="" width="482" height="650" src="https://user-images.githubusercontent.com/59001819/129446730-000688a6-15e1-4e7e-a377-94e7eb5d8a79.jpeg">
> 
> Hi can i clarify that this is the right concept. thanks!

Yes, it looks correct (assuming different colors indicate different branches)

**Comment by GabrielSimbingyang** [comment]
Hi @waynetee ,

This is Gabriel, a student from one of your senior batch. As this issue has been resolved, please be reminded to close the thread in order to keep the forum neat and tidy.

Thank you!

Regards,
Gabriel

**Comment by waynetee** [comment]
@GabrielSimbingyang I'm not sure if the root issue has actually been resolved, but I can close the thread.

**Comment by damithc** [comment]
> I'm not sure if the root issue has actually been resolved, but I can close the thread.

Yes, can close. I've already taken note of the problem. A fix is unlikely to come during this semester as it will take some time to create an updated video. If I manage to fix it sooner, I'll post here.
