### ISSUE TITLE
Error when running runtest.sh

### ISSUE THREAD

**Issue by willyamped** [nus-cs2103-AY2122S1/forum#20]
Hi profs, I encountered this error when running the _runtest.sh_ file. Please let me know what to do. Attached is the screenshot of the error message. Thank you. 

<img width="1039" alt="Screenshot 2021-08-16 at 10 21 03 PM" src="https://user-images.githubusercontent.com/66423703/129578726-6065072e-9102-49a0-be1f-1fa32eeafaaa.png">

**Comment by simonjulianl** [comment]
The error message indicates the java is not configured properly in your zsh. You can check this [first](https://superuser.com/questions/1636321/how-to-solve-unable-to-locate-a-java-runtime-that-supports-error) and another way is to test by openning Intellij Terminal and just type java -version or javac -version. If there command not recognized, I think should install the java and configure the JAVA_HOME path first

**Comment by willyamped** [comment]
Hi thanks for the help. I tried method 1 and still does not work :(. I'm using the M1 chip Macbook Air, not sure if it's a problem

**Comment by simonjulianl** [comment]
em, I don't think its because of the M1 but not sure, also have you tried this```java -version or javac -version.``` and what does it say in your zsh

**Comment by willyamped** [comment]
Hi thanks for the follow up. Attached are the screenshots

### java -version
<img width="657" alt="Screenshot 2021-08-17 at 8 01 36 AM" src="https://user-images.githubusercontent.com/66423703/129643644-76509fbf-00c6-491f-9e42-2cb3ce151572.png">


### javac -version
<img width="804" alt="Screenshot 2021-08-17 at 8 02 33 AM" src="https://user-images.githubusercontent.com/66423703/129643675-44a58f50-f220-49c4-8366-e9d535330275.png">

Thank you

**Comment by junghon3709** [comment]
Does this [link](https://stackoverflow.com/questions/44009058/even-though-jre-8-is-installed-on-my-mac-no-java-runtime-present-requesting-t) help? If you have brew, you might also want to install it using brew as described by [this](https://stackoverflow.com/a/65951339/9721336) answer.

**Comment by willyamped** [comment]
Thank you @junghon3709 for the link. I scrolled down a little bit more and found the problem with most M1 Macbook laptops. I solved the issue by running the following command 

`brew install temurin`

Thank you to @simonjulianl for the help too. I shall close the issue now :)

**Comment by damithc** [comment]
> Hi thanks for the follow up. Attached are the screenshots
> 
> ### java -version
> <img alt="Screenshot 2021-08-17 at 8 01 36 AM" width="657" src="https://user-images.githubusercontent.com/66423703/129643644-76509fbf-00c6-491f-9e42-2cb3ce151572.png">

@willyamped also make sure you install Java 11. This screenshot shows Java 8.

**Comment by willyamped** [comment]
Hi prof @damithc thank you for the comment. After installing _temurin_, I can't seem to change the java version even after installing Java 11. Attached is the screenshot of my current version. Thank you.

<img width="807" alt="Screenshot 2021-08-17 at 10 12 00 AM" src="https://user-images.githubusercontent.com/66423703/129652830-8b5b30fb-0b62-47f9-8331-ab0fb6078652.png">

**Comment by damithc** [comment]
@willyamped it's important that you switch to Java 11. Let's see if other Mac users can help.

**Comment by damithc** [comment]
@willyamped perhaps open a new issue for the Java 16 -> 11 problem?

**Comment by willyamped** [comment]
Thank you prof. I have managed to find the way to switch Java versions by following the steps [here](https://medium.com/@devkosal/switching-java-jdk-versions-on-macos-80bc868e686a).
