### ISSUE TITLE
Conflicts when moving Duke.java to duke package

### ISSUE THREAD

**Issue by wengYing227** [nus-cs2103-AY2122S1/forum#201]
I tried to move Duke.java to duke package, because I cannot import Duke if it's in a default package.
But it shows conflicts when I move the java file.

```
Class Duke, referenced in file README.md, will not be accessible from module ip  
Class Duke, referenced in file runtest.bat, will not be accessible from module ip  
Class Duke, referenced in file EXPECTED.TXT, will not be accessible from module ip 
```

As I'm not familiar with bat file, I have no idea how to solve the conflict.

**Comment by yucheng11122017** [comment]
What is module ip? Could you send your project files? (the right side of intellij)

**Comment by wengYing227** [comment]
> What is module ip? Could you send your project files? (the right side of intellij)

![image](https://user-images.githubusercontent.com/66865950/132295538-0dd1f7e6-b86a-42f9-9bf0-9d9721279bea.png)
Not sure if this is what you meant

**Comment by damithc** [comment]
@wengYing227 If a dialog like this comes up while you are trying to move, untick these two options:
![image](https://user-images.githubusercontent.com/1673303/132298048-db8a9e04-09f0-43df-80b5-dc559839ce78.png)

**Comment by wengYing227** [comment]
> @wengYing227 If a dialog like this comes up while you are trying to move, untick these two options:
> ![image](https://user-images.githubusercontent.com/1673303/132298048-db8a9e04-09f0-43df-80b5-dc559839ce78.png)

Thanks, it works!

But is there a side effect by doing so?

**Comment by damithc** [comment]
> But is there a side effect by doing so?

@wengYing227 This means references to `Duke` in comments and other files (e.g., the three files mentioned in you first post) need to be updated by hand, as appropriate (Intellij will not update them automatically). Updating those occurrences need some manual oversight anyway, given `Duke` in comments/text might not even refer to the Duke class, and hence, auto-updating them to `duke.Duke` might not be desirable in some cases.
