### ISSUE TITLE
Pull request from parallel to main branch. Is this an intended effect?

### ISSUE THREAD

**Issue by limzk126** [nus-cs2103-AY2122S1/forum#202]
![image](https://user-images.githubusercontent.com/88614036/132309373-9361a90a-9775-420b-9c1e-d3d04720f0d3.png)
I noticed that the main branch automatically merges itself to the CodeQuality branch after I merged the Assertion branch using a pull request. Is it an intended or just a harmless side-effect?

**Comment by simonjulianl** [comment]
I think its fine, its how `GitHub` detect conflicts by merging your target branch first to the source branch and check whether there are any conflicts or not

**Comment by damithc** [comment]
> I think its fine, IIRC, its how `GitHub` detect conflicts by merging your target branch first to the source branch and check whether there are any conflicts or not

I don't think it's automatic though. While GitHub might use that technique to check for conflicts, such a 'trial' merge is kept out of our view as it is for GitHub's own internal checking. An actual merge is more likely a result of a dev clicking the 'update branch' button on GitHub UI.
![image](https://user-images.githubusercontent.com/1673303/132322843-4e67bf72-1838-46df-8edb-12955cd17f7b.png)

But yes, it should be fine to do so.

**Comment by simonjulianl** [comment]
I see, thank you prof!

**Comment by limzk126** [comment]
So by right, I shouldn't be able to see the actual merging from master to parallel branch?

**Comment by damithc** [comment]
> So by right, I shouldn't be able to see the actual merging from master to parallel branch in Sourcetree?

@limzk126 If you clicked the `Update branch` button, you should be able to see the merge in SourceTree after fetching/pulling the latest version of the branch from GitHub. Otherwise, no.

**Comment by SkyBlaise99** [comment]
I guess in a sense, accepting a pull request is like performing a merge branch on GitHub. Hence after the operation and resolving merge conflicts, the things from the pull request are merged into your master (or other branch you merging to). Hence in SourceTree it shows as if you performed a merge branch.

Personally, after I accept my pull request, my SourceTree updates to some what similar to yours after I call for a pull request on my master to see the update.
![image](https://user-images.githubusercontent.com/69448615/132440112-9180a19a-f8a7-45c0-ae53-b5600dcd358a.png)

**Comment by limzk126** [comment]
> > So by right, I shouldn't be able to see the actual merging from master to parallel branch in Sourcetree?
> 
> @limzk126 If you clicked the `Update branch` button, you should be able to see the merge in SourceTree after fetching/pulling the latest version of the branch from GitHub. Otherwise, no.

ok, thanks Prof.
