### ISSUE TITLE
.jar file is smaller than 10MB

### ISSUE THREAD

**Issue by xiongjya** [nus-cs2103-AY2122S1/forum#203]
Hello, I need some help regarding generating a new JAR file for this week's iP.

I referred to the Gradle tutorial that was linked in the description of the task. I tried to delete the `'.idea` file and ran `shadow jar` multiple times. Still, my `.jar` is < 10MB. It runs as expected on my machine but I feel it probably won't on someone else's system if they dont have `javafx`. 

Any help would be appreciated! 😃 

Thank you!

**Comment by damithc** [comment]
@xiongjya what size is it? See #205

**Comment by HolmesJJ** [comment]
I added the code below at build.grade, it works for me.

Remember change 'duke.Main' to your GUI Launcher name.

```
jar {
    manifest {
        attributes 'Main-Class': 'duke.Main'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```

**Comment by xiongjya** [comment]
> @xiongjya what size is it? See #205

It is 8.7MB in size. I have referred to #205 and I think it might be due to the size of my images. 

Thank you for referring me to the previous query!
