### ISSUE TITLE
Question on naming Private final variable

### ISSUE THREAD

**Issue by random689** [nus-cs2103-AY2122S1/forum#204]
Hi,

I have a silly question but can i check for below which naming convention is right?

(a)
`
private final Storage storage;
`
or 

(b)
`
private final Storage STORAGE:
`

I know that static final will have to be like (b) cause they are constant, but in this case the storage can be manipulated (E.g adding stuff/removing stuff from the storage) does it still count as a constant?

Thanks in advance!

**Comment by damithc** [comment]
> but in this case the storage can be manipulated (E.g adding stuff/removing stuff from the storage) does it still count as a constant?

We can take _constant_ as referring to the object reference -- even if the object itself it points to is mutable, the reference remains constant?

**Comment by qinguorui2001** [comment]
correct me if wrong, just like final int[] arr = {1,1,1}, you can still modify the element in the array, but you can't assign a new array {1,2,2} to arr since arr is final. so storage is ok to be final

**Comment by random689** [comment]
> 
> 
> correct me if wrong, just like final int[] arr = {1,1,1}, you can still modify the element in the array, but you can't assign a new array {1,2,2} to arr since arr is final. so storage is ok to be final

Hi, I understand this but I'm just confused about the naming convention for such a case. Thank you for explaining though!!




> 
> 
> > but in this case the storage can be manipulated (E.g adding stuff/removing stuff from the storage) does it still count as a constant?
> 
> We can take _constant_ as referring to the object reference -- even if the object itself it points to is mutable, the reference remains constant?

Oh okay I understand, so for this I will have to name it as STORAGE as the storage object stored in this will always be the same for that class. Thank you!
