### ISSUE TITLE
How do I know that the jar file contains JavaFx libraries?

### ISSUE THREAD

**Issue by Agentum07** [nus-cs2103-AY2122S1/forum#205]
Hello, the size of my jar file is 10.28MB.
The website says 
> If the .jar file is smaller than 10MB, most likely JavaFX libraries are not inside it.

And mine is barely above the size specified.
Is there some way to check whether the file contains the required libraries?

**Comment by damithc** [comment]
Close to 10MB should still be fine, unless you put very large images inside. Without JavaFX and without images, the size is less than 1MB IIRC.

**Comment by qinguorui2001** [comment]
my jar file uploaded for the previous required release is only 117 kb, and then i follow instruction to add dependency related to javafx, it becomes to 9 MB, just like the prof said, the difference depend on size of images

**Comment by Agentum07** [comment]
Okay. Thank you prof and Guorui!

**Comment by rish-16** [comment]
@xiongjya tagging for reference
