### ISSUE TITLE
Requesting permission to use a third party gradle plugin

### ISSUE THREAD

**Issue by sivayogasubramanian** [nus-cs2103-AY2122S1/forum#206]
## Library

[git-hooks-gradle-plugin](https://github.com/jakemarsden/git-hooks-gradle-plugin)

## Purpose

To run the given scripts and gradle's `clean check` before a push is made for the team project.

## License

MIT (https://github.com/jakemarsden/git-hooks-gradle-plugin/blob/master/LICENSE)

**Comment by damithc** [comment]
Approved.

**Comment by sivayogasubramanian** [comment]
> Approved.

Thanks Prof @damithc!
