### ISSUE TITLE
💡 Some Git Techniques

### ISSUE THREAD

**Issue by huizhuansam** [nus-cs2103-AY2122S1/forum#207]
Fireship just released a video on [advanced Git techniques and shortcuts](https://www.youtube.com/watch?v=ecK3EnyGD8o). Hope this helps for your future iP and tPs!

**Comment by yucheng11122017** [comment]
Thanks!

**Comment by pss-coder** [comment]
Adding on also to @huizhuansam , not really on Git techniques but more focused on writing a Git Commit Message which I find it really insightful.

[Take a look here](https://chris.beams.io/posts/git-commit/)

**Comment by huizhuansam** [comment]
Feel free to add more git tips here! Closing this issue to keep the forum clean.
