### ISSUE TITLE
Branches not detected on iP progress dashboard

### ISSUE THREAD

**Issue by kwokieee** [nus-cs2103-AY2122S1/forum#210]
Hi! Both my branch-A-Assertions and branch-A-CodeQuality are not detected on the iP progress dashboard, and it has been a few days since they have been pushed to my fork. I have also managed to complete all of this week's tasks and they all show up as tracked on the iP progress dashboard.

In addition, I have also tried locally merging my master branch into branch-A-Assertions and branch-A-CodeQuality last night (after completing BCD-Extension) before pushing them to my fork again. However, the most recent update of the iP progress dashboard still does not detect them.

Could anyone provide some help?

**Comment by damithc** [comment]
@kwokieee As per the screenshot below, the three branches are not merged to master yet. They will be detected after being merged to master.
![image](https://user-images.githubusercontent.com/1673303/132505445-b221ad06-2c29-4fa1-9fbd-ef26994cee8c.png)

**Comment by kwokieee** [comment]
Ah I see, thanks so much for the help prof! 😄
