### ISSUE TITLE
no main manifest attribute in jar

### ISSUE THREAD

**Issue by SajalVaishnav** [nus-cs2103-AY2122S1/forum#212]
I can successfully build a jar file but when I try to run it, I just get no main manifest in jar. I have updated the mainClassName in build.gradle so I'm really not sure what's going wrong.

```java
application {
    mainClassName = "duke.Launcher"
}
```

**Comment by rldefa** [comment]
Problem seems to lie in this [file](https://github.com/SajalVaishnav/ip/blob/master/src/main/java/META-INF/MANIFEST.MF).

Try changing the Main-Class to duke.Launcher as well? Not sure if you have to rebuild it.

I referred to this [link](https://stackoverflow.com/questions/9689793/cant-execute-jar-file-no-main-manifest-attribute).

**Comment by SajalVaishnav** [comment]
Ohh thank you!
