### ISSUE TITLE
Implementing a static abstract method

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#214]
Hi all, before you read on! I know such a thing does not exist in Java! Would like to hear your suggestions on how I can solve this issue.

I am trying to add a `String getSyntax()` abstract method to the Command Abstract class. All commands inherit from this class. This method returns how the command should be used. Furthermore I wanted this to be static as there should be no need to initialise a class to get its syntax! 

How would you guys go about doing this?

**Comment by yucheng11122017** [comment]
No idea if im sprouting nonsense but maybe you can just implement the method in the command class then inside you just assert fail? then in the other command classes you can override it? 

this kind of sacrifices the advantage of inheritance though I feel, because future programmers might not realise that you need to override until they run it. 

Alternatively, just give up on the static part HAHAHA

**Comment by waynetee** [comment]
Interesting question, how exactly are you going to call this method?

**Comment by NicolasCwy** [comment]
@waynetee I was planning on creating a Help Command that provides the syntax usage for commands. Therefore in the help command, there would be the switch statement (this is a small extract), that would retrieve the syntax based on the command that is being queried.

``` java
switch (command) {
case "bye":
  return ExitCommand.getSyntax();
case "list":
  return ListTasksCommand.getSyntax();
case "done":
  return CompleteTaskCommand.getSyntax();
}
```

**Comment by waynetee** [comment]
In that case, why don't you just implement the methods directly in the commands? Why do you need it in the parent class?

**Comment by NicolasCwy** [comment]
@waynetee My current implementation implements the methods directly into the commands as I find a solution to this. 

Because of the same method signature and return type of the getSyntax method, I thought it would be better to put it in the parent class to ensure that future commands are checked by the compiler to ensure the method is implemented.

**Comment by waynetee** [comment]
I guess if you did call the method in your code, then the compiler will check it for you. If you didn't, then there would be no need to ensure it was implemented.

**Comment by Chesterwongz** [comment]
Should a static method even be overridden? Static means the method can be called without an instance, and with no object instance theres no dynamic binding or calling of overridden methods taking place

**Comment by NicolasCwy** [comment]
@waynetee Hmm I was hoping for like an extra safety net but I guess it isn't required, thank you for the replies.
