### ISSUE TITLE
Starting Tp early

### ISSUE THREAD

**Issue by Chesterwongz** [nus-cs2103-AY2122S1/forum#215]
Are we allowed to start working on Tp features already? Or must we wait for an official start date?

**Comment by damithc** [comment]
@Chesterwongz Most module activities (e.g., lectures, topics, quizzes, tutorials, project tasks) are designed to follow a specific sequence and to go lockstep with each other. Hence, not recommended to jump ahead to tP coding while others threads of the module are lagging behind.
But it should be OK to try immediate upcoming week's tasks ahead of time if you have time left after current week's tasks.
