### ISSUE TITLE
Using custom fonts for iP, how to give credit?

### ISSUE THREAD

**Issue by junghon3709** [nus-cs2103-AY2122S1/forum#216]
Hello,

I am planning to use a font called [Victor Mono](https://rubjo.github.io/victor-mono/) for my iP project. On the website, under FAQ > Usage, the author said that he'd "appreciate it if you referred others to this web site rather than serving the font files from elsewhere". Would a line in the `Readme` file crediting the author of the font suffice? Since a font is not a 3rd party library, do I have to submit a third party request to use the font?

**Comment by damithc** [comment]
@junghon3709 Yes, you can mention it in the README.
No need to submit a request for permission to reuse.

**Comment by junghon3709** [comment]
Ah, thank you!
