### ISSUE TITLE
In-Video quizzes participation

### ISSUE THREAD

**Issue by rickyaandrew** [nus-cs2103-AY2122S1/forum#217]
hi understand that in-video quizzes are bonus marks, but in order for us to be eligible for the in-video quiz participation, do we have to get all questions right or attempting the questions will make us eligible as well? because it is not reflected in my participation even when i have completed them.

**Comment by damithc** [comment]
@rickyaandrew just attempting is enough, but you need to do them before the normal quiz deadline (i.e., before the next lecture). If you did, email me which week and which quiz you did.
