### ISSUE TITLE
Is there a Balsamiq license for CS2103T

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#220]
Realised that Balsamiq, the UI wireframing tool recommended on the [course website](https://nus-cs2103-ay2122s1.github.io/website/schedule/week6/project.html#2-draft-the-ug) has a 30 day trial. Is there some kind of license our class has access to?

**Comment by damithc** [comment]
They used to have a free version. If there is no free version anymore, I'll remove it from the website. Let me know if you come across any free alternatives.
For this modules though, just PowerPoint should be enough.

**Comment by NicolasCwy** [comment]
@damithc seems like there's some [license which you could apply for](https://balsamiq.com/givingback/free/classroom/) if you like your future classes to continue to use it!

**Comment by huizhuansam** [comment]
There are many alternative free(mium) tools for UI wireframing such as Figma and Adobe XD. They are better built for the job than MS PowerPoint but do come with their own learning curve.

**Comment by damithc** [comment]
> @damithc seems like there's some [license which you could apply for](https://balsamiq.com/givingback/free/classroom/) if you like your future classes to continue to use it!

Thanks for the info @NicolasCwy I don't think I'll pursue that option, as the need for wireframe diagrams is minimal in this module, given both iP and tP are CLI-centric.
