### ISSUE TITLE
Third Party Libraries for Storage & Reusing Snippets from Own Past Project

### ISSUE THREAD

**Issue by solarrabbit99** [nus-cs2103-AY2122S1/forum#223]
## Library

SQLite JDBC Driver: [org.xerial:sqlite-jdbc:3.36.0.1](https://github.com/xerial/sqlite-jdbc)

## Purpose

It is embarrassing that I have only seen the [Policy on Reuse](https://nus-cs2103-ay2122s1.github.io/website/admin/appendixB-policies.html#policy-on-reuse) this week when I have already used the third party library for my storage. Can I include the `README` file? I adapted the storage classes from my past projects, do I also have to mention it in a comment?

## License

SQLite JDBC Driver: [Apache 2.0](https://github.com/xerial/sqlite-jdbc/blob/master/LICENSE)

**Comment by damithc** [comment]
@zhenghanlee Approved for the iP but note that for the tP we have a constraint against the use of relational databases.
No need to mention reusing your own past code, unless it was a team project and other people contributed to the code in concern.
