### ISSUE TITLE
Unable to open team members' jar file

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#224]
i used windows and intellij, when i download the jar file from my team members' release it always showed,though other members test them and all works fine. any clarification? thx
![image](https://user-images.githubusercontent.com/77196303/133047778-6a809922-4f44-408a-9e9c-ee5a9bb5e4cd.png)

**Comment by damithc** [comment]
@qinguorui2001 Are you able to run it using `java -jar` command (rather than double-click?) See [duke/A-Jar](https://nus-cs2103-ay2122s1.github.io/website/se-book-adapted/projectDuke/index.html#a-jar) for more info.

**Comment by marcuspeh** [comment]
Are you able to open it by using `java -jar?`

**Comment by qinguorui2001** [comment]
In intellij, i use the terminal inside, and this what i got
![image](https://user-images.githubusercontent.com/77196303/133051192-f0d43e76-277a-4ce4-ba5a-53008f813010.png)

**Comment by qinguorui2001** [comment]
also,when my team member runs my jar file, this happens
![image](https://user-images.githubusercontent.com/77196303/133055268-25e43d50-a808-4874-b7fc-dc723c61ebac.png)
this is my gradle build
https://github.com/qinguorui2001/ip/blob/master/build.gradle

**Comment by qinguorui2001** [comment]
i deleted this : id 'org.openjfx.javafxplugin' version '0.0.9'  in build.gradle
also delete below in build.gradle
![image](https://user-images.githubusercontent.com/77196303/133061892-5de1ae6d-31b1-41ea-88fd-8079b7377ac1.png)
this works as my team member can open it

**Comment by qinguorui2001** [comment]
and for the first question i raised, since the jar file is downloaded  to the wrong directory and intellij can't search it, when it moves to build/libs folder, i can open it
