### ISSUE TITLE
Enabling Assertions when running jar file

### ISSUE THREAD

**Issue by ramapriyan912001** [nus-cs2103-AY2122S1/forum#226]
Hi all,
Small doubt. When I simply click a jar file and attempt to open it, java assertions are disabled by default.
This means that one of the error handling mechanisms I have in place is not active.

however, when the jar file is opened from the terminal or command line with assertions activated, everything works fine.
is this acceptable?

Finally, I use a Mac, and I have no issues opening the jar file on my system. However, a friend of mine was unable to open the file on her computer due to her jvm being older than version 58. Is it necessary for me to do something to make the jar file compatible?

if so, what can I do?

![DB082ECE-3096-4473-930A-9DFDEAFB5E2A](https://user-images.githubusercontent.com/64624151/133190939-6afe43a4-3375-47e8-9514-2f529c8b2b84.jpeg)

The error message from my friend’s terminal stating that her jvm is outdated.

**Comment by damithc** [comment]
> however, when the jar file is opened from the terminal or command line with assertions activated, everything works fine.
> is this acceptable?

@ramapriyan912001 Yes, that's fine. 

> Finally, I use a Mac, and I have no issues opening the jar file on my system. However, a friend of mine was unable to open the file on her computer due to her jvm being older than version 58. Is it necessary for me to do something to make the jar file compatible?

Make sure you are creating the JAR file using Java 11. If you use a later version, it may not work in other computers that only has Java 11.

**Comment by ramapriyan912001** [comment]
The project is using java 11 as can be seen in the screenshot below.
<img width="1792" alt="Screenshot 2021-09-14 at 5 44 57 PM" src="https://user-images.githubusercontent.com/64624151/133235233-089604eb-4028-482e-b97c-406ba3c1ff3f.png">

However, the issue with respect to JVM version continues to occur.
Is the JVM issue separate to the java version?
And do I have to do anything to rectify this issue with compatibility?

**Comment by damithc** [comment]
@ramapriyan912001 can you share a screenshot of the following setting page as well? It's under `File` -> `Settings` 
![image](https://user-images.githubusercontent.com/1673303/133256571-fc01ea0e-4fbe-447b-a928-0fb06cc2a015.png)

**Comment by ramapriyan912001** [comment]
Here it is Prof

<img width="1792" alt="Screenshot 2021-09-14 at 11 08 23 PM" src="https://user-images.githubusercontent.com/64624151/133283712-52b4b8a3-5b22-4f33-a57f-89fdbcea3dee.png">

**Comment by damithc** [comment]
@ramapriyan912001 perhaps you can post your jar file here so that someone can try to verify if it works in their computer?

**Comment by ramapriyan912001** [comment]
I can't upload the jar file directly; github doesn't support uploading a jar file.
Here is a zip folder containing the jar file.

[duke.jar.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7163129/duke.jar.zip)

**Comment by waynetee** [comment]
Hi @ramapriyan912001 , how did you create the jar file? Did you do it through the IDE?

**Comment by ramapriyan912001** [comment]
gradle shadowJar through the command line when inside my IDE

Not sure what difference it would make but I tried ./gradlew shadowJar as well

Tried gradle clean before gradle shadowJar
Tried ./gradlew clean shadowJar too

Another thing is, now the error message is that my jar file is of version 59.0 instead of 58.0... (see picture below)
I haven't changed any settings...
Not sure if it's worth mentioning, but I have the premium version of intellij (free for students)

![IMG_20210914_233305_692.jpg](https://user-images.githubusercontent.com/64624151/133288081-49b683e6-f8db-4bb3-8c10-79173545e38f.jpg)

**Comment by waynetee** [comment]
I suggest you do it through the GUI like this
![image](https://user-images.githubusercontent.com/17681226/133289073-09a7e327-e143-49bc-9304-4f6ef9f1c401.png)

if you want to use the command line, you can try `./gradlew --version` and debug from there.

**Comment by damithc** [comment]
> Here is a zip folder containing the jar file.
> 
> [duke.jar.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7163129/duke.jar.zip)

Doesn't work in my Windows machine either; gives a similar error. So, it's something to be fixed. 

On an unrelated note, you have included a 7MB image file which can easily be replaced with a much smaller lower-resolution version.

**Comment by ramapriyan912001** [comment]
Could you try the 3 of these?
I've tried to mirror the gradle properties in @waynetee project.

[duke.jar.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7165949/duke.jar.zip)
[duke.jar.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7165951/duke.jar.zip)
[duke.jar.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7166008/duke.jar.zip)


However, now my gradle version is 15.0 instead of 14...
I don't know how or why this is happening.
<img width="579" alt="Screenshot 2021-09-15 at 9 16 12 AM" src="https://user-images.githubusercontent.com/64624151/133354828-5c093885-ddb5-4ea2-9a4a-a83398203f1b.png">

I've tried to delete the repo on my local and re-clone into it too, to no avail.


Starting to get a little concerned. What happens if I can't get this issue resolved by Friday 2359 @damithc?

**Comment by damithc** [comment]
> Could you try the 3 of these?
> I've tried to mirror the gradle properties in @waynetee project.
> 
> [duke.jar.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7165949/duke.jar.zip)
> [duke.jar.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7165951/duke.jar.zip)
> [duke.jar.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7166008/duke.jar.zip)

all three failed with the same error.


> I suggest you do it through the GUI like this
> ![image](https://user-images.githubusercontent.com/17681226/133289073-09a7e327-e143-49bc-9304-4f6ef9f1c401.png)

Did you try doing this? i.e., using the Intellij GUI to run the shadowJar task, instead of the terminal

**Comment by ramapriyan912001** [comment]
Yes, that is how I got those 3 jar files.
Did not use the terminal to do so.

Tried a fix suggested on a forum and remade the jar file
Does it work on your system?

Apologies for asking and bothering you guys, I genuinely have no idea why this problem persists :(

[duke.jar.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7167957/duke.jar.zip)

**Comment by damithc** [comment]
> I don't know how or why this is happening.
> <img alt="Screenshot 2021-09-15 at 9 16 12 AM" width="579" src="https://user-images.githubusercontent.com/64624151/133354828-5c093885-ddb5-4ea2-9a4a-a83398203f1b.png">

Gradle seems to be using JVM 15 (it should use 11 instead).

Perhaps try to uninstall JVMs later than 11?
You can also try to point the `JAVA_HOME` variable to the JDK 11 folder.

**Comment by ramapriyan912001** [comment]
Prof, does the jar from the previous comment work?
It seems to be working on my friends' systems now (the ones who had issues with opening the earlier files).

If not, will look into trying to uninstall the JVMs.

**Comment by damithc** [comment]
> Tried a fix suggested on a forum and remade the jar file
> Does it work on your system?
> 
> Apologies for asking and bothering you guys, I genuinely have no idea why this problem persists :(
> 
> [duke.jar.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7167957/duke.jar.zip)

Good news. This one worked for me. 👍

**Comment by damithc** [comment]
@ramapriyan912001 BTW, what fix did you apply exactly? It'll be good to know in case something similar happens to someone else.

**Comment by ramapriyan912001** [comment]
I have no idea honestly what it was exactly that worked!

From some friends, I gather that I'm not alone in facing this issue too.
Between the last 3 ones that failed and this one, I did a bunch of things.
I think the one that worked was just deleting the build folder and idea folder and using the GUI to create the jar.

**Comment by ramapriyan912001** [comment]
Thank you for your patience in getting this sorted Prof @damithc!
