### ISSUE TITLE
JAR file cannot locate duke.txt

### ISSUE THREAD

**Issue by willyamped** [nus-cs2103-AY2122S1/forum#228]
Hi everyone, I tried creating the new JAR file using Gradle for the final submission. However, the JAR file could not locate my `duke.txt` file where my program saves to and reads from. This is the filepath that I specified:

`./data/duke.txt`

Thank you!

**Comment by damithc** [comment]
@willyamped perhaps provide the following info? That info might help someone to troubleshoot your problem better.
Which OS are you using?
Are you running the JAR file using the command line or double-clicking?
Have you handled the following?
![image](https://user-images.githubusercontent.com/1673303/133208795-28e65111-f904-44c8-8e91-ce95e5a898c0.png)

**Comment by willyamped** [comment]
Hi prof, thank you for the prompt reply. I am using MacOS and running the JAR file using the command line. Below is a snippet of my code. 

```java
public Duke() {
        taskList = new TaskList(new ArrayList<Task>());
        storage = new Storage("./data/duke.txt");
        ui = new Ui();
        storage.readFile(taskList);
    }
```

```java
public void readFile(TaskList ls) {
        try {
            File myObj = new File(filepath);
            Scanner myScanner = new Scanner(myObj);
            while (myScanner.hasNextLine()) {
                String data = myScanner.nextLine();
                arr = data.split(" ");
                String task = arr[0];
                String description = getDescription(arr);
                int counter = getCounter(arr, 0);
                if (task.charAt(2) == 'D') {
                    createDeadlineTask(counter, arr, ls, description);
                } else if (task.charAt(2) == 'E') {
                    createEventTask(counter, arr, ls, description);
                } else {
                    createTodoTask(arr, ls, description);
                }
            }
            myScanner.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }
```

**Comment by simonjulianl** [comment]
> Hi prof, thank you for the prompt reply. I am using MacOS and running the JAR file using the command line. Below is a snippet of my code.
> 
> ```java
> public Duke() {
>         taskList = new TaskList(new ArrayList<Task>());
>         storage = new Storage("./data/duke.txt");
>         ui = new Ui();
>         storage.readFile(taskList);
>     }
> ```
> 
> ```java
> public void readFile(TaskList ls) {
>         try {
>             File myObj = new File(filepath);
>             Scanner myScanner = new Scanner(myObj);
>             while (myScanner.hasNextLine()) {
>                 String data = myScanner.nextLine();
>                 arr = data.split(" ");
>                 String task = arr[0];
>                 String description = getDescription(arr);
>                 int counter = getCounter(arr, 0);
>                 if (task.charAt(2) == 'D') {
>                     createDeadlineTask(counter, arr, ls, description);
>                 } else if (task.charAt(2) == 'E') {
>                     createEventTask(counter, arr, ls, description);
>                 } else {
>                     createTodoTask(arr, ls, description);
>                 }
>             }
>             myScanner.close();
>         } catch (IOException e) {
>             System.out.println(e.getMessage());
>         }
>     }
> ```

I don't think these lines of code create the dir and the file if they don't exist before. Maybe you can use a Java `File` Object and then use the method `mkdirs` and `createNewFile` to create the file and directory first

**Comment by marcuspeh** [comment]
Base on what i see in your codes, u did not handle the thing prof mentioned

**Comment by willyamped** [comment]
Hi @simonjulianl @marcuspeh thank you for the suggestion. I have decided to remove the folder to create less trouble haha. Still, thanks for the help!
