### ISSUE TITLE
Unable to open Jar file, possibly due to error in MainWindow images

### ISSUE THREAD

**Issue by e0543978** [nus-cs2103-AY2122S1/forum#229]
Hi everyone,

I successfully managed to create a jar file. However, upon trying to run by double-clicking the file, there was no response.

I then tried to run the file from the terminal but was met with this error.

![image](https://user-images.githubusercontent.com/77733221/133232203-80b7ca4e-9669-44bc-973d-52cf43a5be7a.png)

It seems like there's an issue with the Image object in my MainWindow class,  
```java
Caused by: java.lang.NullPointerException: Input stream must not be null
```
Though I did not make any changes to the code provided in the tutorial.
![image](https://user-images.githubusercontent.com/77733221/133231611-39afed9f-d6da-4766-bbe6-779e9ee29a61.png)

I was wondering if anyone faced a similar issue before and knows how to overcome this issue. Thank you so much!

**Comment by marcuspeh** [comment]
Whats on top of `index 0 out of bounds for length 0`? Anyways, double check the type of your pic. Are u sure its .png and not .jpg?

**Comment by e0543978** [comment]
I just double-checked the picture file name and turns out it was a typo lmaoo. Wrongly capitalised "DaUser" and "DaDuke". Nonetheless, thanks for your help Marcus, it works now!

**Comment by marcuspeh** [comment]
> I just double-checked the picture file name and turns out it was a typo lmaoo. Wrongly capitalised "DaUser" and "DaDuke". Nonetheless, thanks for your help Marcus, it works now!

Thats great! I think you change the file extension too right? It was .jpg instead of .png
