### ISSUE TITLE
Marking of iP levels - Code quality

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#23]
#22
Relating to my other issue, is iP marked based on the level tags or the final product, the last level for the week?

> The **code quality** meets the following conditions:
> Reasonable use of OOP e.g., at least some use of inheritance, code divided into classes in a sensible way`

Want to know if at every level, our code should be encapsulated properly, with code not just being dumped in main()?

**Comment by damithc** [comment]
@NicolasCwy You are expected to write good quality code (as per what has been covered in the module at that point) all along. However, we also want to give you the space to improve, which means we will not penalize if you made mistakes at first (e.g., write poor quality code) but corrected them later. So yes, strive to encapsulate code properly all along. Later if you found that there is an even better ways to encapsulate your code, go ahead and improve the code in that way too.
That said, we don't grade the code at every level other than to verify that you are progressing as expected. So, your marks are unlikely to be affected even if you chose to write low quality code in the initial levels.

**Comment by NicolasCwy** [comment]
Noted prof
