### ISSUE TITLE
Is there midterms?

### ISSUE THREAD

**Issue by jiarong15** [nus-cs2103-AY2122S1/forum#232]
Wish to check if there is midterms?

**Comment by zzybluebell** [comment]
i think there is no midterm

iP 15 % 
tP 50%
Participation: 5%
Final Quiz: 30%

**Comment by marcuspeh** [comment]
Dont think so

**Comment by Agentum07** [comment]
No midterms, refer to the screenshot attached. Taken from [here](https://nus-cs2103-ay2122s1.github.io/website/admin/exams.html)

![Capture](https://user-images.githubusercontent.com/62797335/133430012-e4ec9511-997a-4db4-84b0-d9b8aa2a8f38.PNG)

**Comment by damithc** [comment]
> Wish to check if there is midterms?

No midterm :-)

**Comment by yucheng11122017** [comment]
@damithc Thank you very much 😄
