### ISSUE TITLE
Is the GFMD supposed to work on my user guide website as well?

### ISSUE THREAD

**Issue by BryannYeap** [nus-cs2103-AY2122S1/forum#235]
Features such as emoji, image, and table seems to work when the [`docs/README.md`](https://github.com/BryannYeap/ip/blob/master/docs/README.md) is viewed in github. But when opening my [user guide website](https://bryannyeap.github.io/ip/), they do not work. 

The emoji should be at the top, the image is under "Quick start" and the table should be at the very bottom under "Command summary"

The CS2103T website did say this could happen, but not really about how to solve it.

**Comment by marcuspeh** [comment]
Not exactly a solution but I guess u could copy the 🐌  and paste it in instead of using `:snail:`

**Comment by rish-16** [comment]
Yup, agree with @marcuspeh ⬆️  

Check out this: [https://gist.github.com/rxaviers/7360908](https://gist.github.com/rxaviers/7360908)

---

Also, your UI image is not rendering in this section on the website but it shows in your `README.md`:

![image](https://user-images.githubusercontent.com/20137995/133556320-1c89601c-5657-48bb-b5f6-32af0299f695.png)

May be some dead URL. Tested on Chrome and Safari, and doesn't show either way.

**Comment by damithc** [comment]
I don't think Jekyll (the tool GitHub uses to generate the GitHub pages from .md files) supports emoji syntax by default but it can be added on via a plugin. IIRC, AB3 website has that plugin enabled.
![image](https://user-images.githubusercontent.com/1673303/133557240-555af5b9-72b8-4d5d-ae95-88f62038bbf9.png)

If you poke around in the AB3 code base, you'll be able to find out how to enable it.

**Comment by BryannYeap** [comment]
> Yup, agree with @marcuspeh ⬆️
> 
> Check out this: https://gist.github.com/rxaviers/7360908
> 
> Also, your UI image is not rendering in this section on the website but it shows in your `README.md`:
> 
> ![image](https://user-images.githubusercontent.com/20137995/133556320-1c89601c-5657-48bb-b5f6-32af0299f695.png)
> 
> May be some dead URL. Tested on Chrome and Safari, and doesn't show either way.

Yea I'm not sure whats going on with that either...

**Comment by BryannYeap** [comment]
Hmm what about the `Command Summary` table at the bottom? It also works on the `Readme.md` but not on my website

**Comment by BryannYeap** [comment]
Oh yea and I'm not sure if this has anything to do with my image not working but the link in the CS2103T website that they said should contain my image: [https://BryannYeap.github.com/ip/Ui.png](https://BryannYeap.github.com/ip/Ui.png)
following this format: `https://{your user name}.github.com/{repo name}/Ui.png`
This link does not work for me.

For my image I used this link: [https://github.com/BryannYeap/ip/blob/master/docs/Ui.png](https://github.com/BryannYeap/ip/blob/master/docs/Ui.png)

**Comment by damithc** [comment]
> Hmm what about the `Command Summary` table at the bottom? It also works on the `Readme.md` but not on my website

The markdown parser used by GitHub pages is less forgiving than the Markdown preview feature of GitHub. The former requires a blank line to separate the table from the content above it.

**Comment by damithc** [comment]
> Oh yea and I'm not sure if this has anything to do with my image not working but the link in the CS2103T website that they said should contain my image: https://BryannYeap.github.com/ip/Ui.png
> following this format: `https://{your user name}.github.com/{repo name}/Ui.png`
> This link does not work for me.

@BryannYeap it should be `github.io`, not `github.com`. Will fix soon.

**Comment by BryannYeap** [comment]
@marcuspeh Thanks the copy and pasting of the emoji works!
@damithc Thanks my table works now too! And yes the link: [https://BryannYeap.github.io/ip/Ui.png](https://BryannYeap.github.io/ip/Ui.png) works as well, which seems to have fixed the image!

Thanks a lot guys!
