### ISSUE TITLE
Unable to run debugging

### ISSUE THREAD

**Issue by weichang18** [nus-cs2103-AY2122S1/forum#236]
![Untitled](https://user-images.githubusercontent.com/77260240/133558077-deae8766-b7a9-43f1-9919-0510e1428e01.png)
I have set the breakpoint just before my program even starts its 1st method, however it was shown this message. The same messages come out when i try to debug with different breakpoints as well.

**Comment by simonjulianl** [comment]
Maybe you can try to `invalidate` the cache first, and is it possible to take a screenshot of the console of the debugger (under the `iP[Launcher.main()]`)

**Comment by yucheng11122017** [comment]
Sorry whats the message thats being shown?

**Comment by marcuspeh** [comment]
Try delete the `.idea` and `.gradle` folder  and try again. Btw, theres some error in your `Main.java`. Maybe that's what causing the problem.

**Comment by damithc** [comment]
This suggests your code might have compile errors?
![image](https://user-images.githubusercontent.com/1673303/133649175-d35045c6-9081-4112-aa9a-2d9496feb7ba.png)

**Comment by weichang18** [comment]
@simonjulianl this is the console, I have tried to invalidate the cache but it did not help
![Untitled](https://user-images.githubusercontent.com/77260240/133775296-cda2bd48-d87e-4b7b-912f-9925f3196a3f.png)
 @damithc sorry it was a code style error that I forgot to remove

**Comment by simonjulianl** [comment]
Looks like the debugger works fine, but according to this seems that there are missing dependency [here](https://www.google.com/url?sa=t&source=web&rct=j&url=https://discuss.gradle.org/t/native-integration-unavailable-exception-for-projectbuilder/11619&ved=2ahUKEwinw5-B-IXzAhVUaCsKHfX2DUYQFnoECAcQAQ&usg=AOvVaw2QcisasI5k533Q9o3v7uBI) but im also not sure

**Comment by litone01** [comment]
Hi @weichang18, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). Can I kindly check if the issue has been resolved? If yes, do you mind kindly closing the issue? Otherwise, do you mind sharing an update on the current issue? Thanks!
