### ISSUE TITLE
Query on condition for Images iP

### ISSUE THREAD

**Issue by didymusne** [nus-cs2103-AY2122S1/forum#237]
Hello! Was wondering on this condition of the images

![telegram-cloud-photo-size-5-6203844405694147963-y](https://user-images.githubusercontent.com/51285113/133589016-18d0911d-75c4-47ed-9d65-ab36ae9835fc.jpg)

Can we use an image if it says "free for personal use"? 

E.g. png images from this website: https://toppng.com/

Thank you!

**Comment by damithc** [comment]
> Can we use an image if it says "free for personal use"?

@didymental It's debatable if this is really 'personal use'. But you should cite the source nevertheless.

**Comment by didymusne** [comment]
@damithc thank you prof! May I kindly clarify, do we cite the source under our README.md? Thank you!

**Comment by damithc** [comment]
> @damithc thank you prof! May I kindly clarify, do we cite the source under our README.md? Thank you!

Yes, that would be good -- it might help drive traffic to the original source, which is a nice way to pay back for reusing their work.

**Comment by didymusne** [comment]
@damithc roger that, thank you prof!
