### ISSUE TITLE
getClass().getResource(...) always returns null

### ISSUE THREAD

**Issue by houtenteo** [nus-cs2103-AY2122S1/forum#238]
Hi, does anyone know why getClass().getResource(...) always returns null? I can't seem to be able to load my MainWindow.fxml file.

![image](https://user-images.githubusercontent.com/77191381/133595285-9bf35a13-9834-4cf8-a461-c124110cd4cc.png)

Initially I did: 
`URL url = new File("src/main/resources/MainWindow.fxml").toURI().toURL();`
`Parent root = FXMLLoader.load(url);`

to get around the problem. But I realised that doing it this way would cause problems in my jar file.

Was wondering if anyone knew what the problem is.

**Comment by zognin** [comment]
@houtenteo Does using a forward slash before the path work? For e.g. `.getResource("/MainWindow.fxml")`

**Comment by houtenteo** [comment]
@zognin BRUH. THANK YOU SO MUCH MAN. Rip my whole afternoon though HAHAHAHAH
