### ISSUE TITLE
Is there a way to move a tag from one commit to another?

### ISSUE THREAD

**Issue by HongshuW** [nus-cs2103-AY2122S1/forum#24]
Hi,
I intended to tag the last commit but accidentally tagged the second last commit of level 1.
Is there a way to move this tag to the latest commit? If not, what should I do to tell the grader which commit is the correct version for level 1?

**Comment by HolmesJJ** [comment]
If it is possible to delete the tag from your local and remote repository then tag to your last commit again?

**Comment by marcuspeh** [comment]
Yup there's a way to delete and retag.  Have a look at [this](https://devconnected.com/how-to-delete-local-and-remote-tags-on-git/#:~:text=In%20order%20to%20delete%20a%20remote%20Git%20tag%2C%20use%20the,and%20specify%20the%20tag%20name.&text=To%20delete%20a%20remote%20Git%20tag%2C%20you%20can%20also%20use,name%20using%20the%20refs%20syntax.) .

**Comment by kevin9foong** [comment]
Yes, simply delete the tag and then reassign it to the new commit. 

1. If the tag has been pushed to remote repository, run 'git push origin --delete <tagname>' to delete the tag in the remote. 
2. Then you can do 'git tag -d <tagname>' which deletes the tag on your local repo. 
3. Assign the tag to the correct commit-id 'git tag <tagname> <commitId>' 
4. Then you can push your reassigned tags to the remote repo with 'git push --tags'

**Comment by HongshuW** [comment]
I have moved the tag to the correct version.
Thank you all for helping!
