### ISSUE TITLE
Question regarding creating tables using GFMD

### ISSUE THREAD

**Issue by Wilfredwongkc** [nus-cs2103-AY2122S1/forum#240]
Hi friends,

I am trying to create a table using GFMD. It looks good when I view it on GitHub preview.

![question1](https://user-images.githubusercontent.com/66736794/133621838-36b0a2a6-c73a-4e76-8489-6bb354c958b2.jpg)

But when I view it on the User Guide which we are supposed to create, the table did not appear and it looks like this and have formatting errors. 

![question2](https://user-images.githubusercontent.com/66736794/133622059-5402b9f7-27f1-4df2-a23c-35ffb73a40ad.jpg)

Does anyone know how to create a table on the User Guide page?

Thanks!

**Comment by Jai2501** [comment]
Put a line break between the heading and where the table starts in the markup code.

**Comment by Wilfredwongkc** [comment]
Thanks for your help! It works now!
