### ISSUE TITLE
Unable to run `java -jar Duke.jar`, encountering `NullPointerException`

### ISSUE THREAD

**Issue by Agentum07** [nus-cs2103-AY2122S1/forum#242]
Latest version of intelliJ, working on windows 10.

My code works, and when I run `Launcher.java`, it builds.

However when I run `.\gradlew shadowJar` and then run the `Duke.jar` file generated, I get these errors - 
![Capture](https://user-images.githubusercontent.com/62797335/133638380-013b1422-5beb-43b5-878b-72543067b67e.PNG)

it seems as if my images are not being read properly, the `.jar` file thinks they don't exist.

**Comment by xlzior** [comment]
How are you specifying the image paths?

**Comment by Agentum07** [comment]
In my `MainWindow.java`
![Capture](https://user-images.githubusercontent.com/62797335/133639325-efb4aeac-7d34-4934-8c20-e21ae44a0103.PNG)
The images are located in `src/main/resources/images/`

**Comment by xlzior** [comment]
Your [images](https://github.com/Agentum07/ip/tree/master/src/main/resources/Images) folder seems to be named with a capital `I`

**Comment by Agentum07** [comment]
Aaah I see. Thank you so much!
