### ISSUE TITLE
How to adjust size of text message for GUI? 

### ISSUE THREAD

**Issue by yucheng11122017** [nus-cs2103-AY2122S1/forum#243]
Currently, if the message is too long, it becomes truncated with "...". Is there a way to extend the length of the textbox or to have a see more button? 
Thank you!

**Comment by zognin** [comment]
@yucheng11122017 Does [this](https://github.com/nus-cs2103-AY2122S1/forum/issues/148) help?

**Comment by Agentum07** [comment]
In your `dialogBox.fxml`
you can add a `style` attribute in the `<Label>`
Something like - 
```
<Label ....... style=-fx-font-size: 16;"/>
```
Hope this helps!

**Comment by marcuspeh** [comment]
I added `minHeight="-Infinity"` to the label.

**Comment by yucheng11122017** [comment]
Thank you so much! Sorry I didn't notice there was a duplicate issue 😿
