### ISSUE TITLE
Problems with java stack

### ISSUE THREAD

**Issue by nniiggeell** [nus-cs2103-AY2122S1/forum#244]
Hi, I am trying to implement undo for more than 1 task, using a stack<TaskList> or linkedlist<TaskList>. 
However, it seems like whenever I push a TaskList into the stack, all of the elements change to the one that I am pushing. 
Referencing https://stackoverflow.com/questions/45008792/listt-add-changes-everything-in-list , where it says that stacks and linkedlists hold pointers, I have tried to create new TaskLists, but this still does not solve the issue.

My Undo method
```java
private void commandUndo() throws LebronException {
        try {
            this.previousStates.pop();
            storage.saveToFile(getLatestState()); //getLatestState just peeks at the top of stack
        } catch (EmptyStackException e) {
            throw new LebronException("    OOPS! I have no memory of your last action! Try doing something first!");
        }
    }
```

My done method (the other commands follow similar structure)
```java
private String commandDone(String[] splitWords) throws LebronException {
        try {
            int pos = Integer.parseInt(splitWords[1]);
            TaskList newTaskList = getLatestState().getCopy(getLatestState());
            Task task = getLatestState().markDone(pos - 1);
            previousStates.push(newTaskList);
            storage.saveToFile(getLatestState());
            return ui.replyMarkDone(task);
        }
        catch (NumberFormatException e) {
            throw new LebronException("    :( OOPS! Make sure you input a valid number!");
        }
    }
```

Please let me know if you have any idea where the issue is!!

**Comment by NicolasCwy** [comment]
I have a feeling it is a problem in your commandDone. Specifically when you do getCopy(). Could you tell me what class getLatestState returns I couldn't find it in your repo.

**Comment by nniiggeell** [comment]
Hi, I haven't pushed any new updates as I still can't get Undo to work properly.

TaskList::getCopy(TaskList taskList) , takes in a taskList object, and return a new TaskList.

getLatestState simply returns the top of the stack (previousStates.peek()) which is a TaskList object.

**Comment by NicolasCwy** [comment]
Could you show how getCopy makes a copy of taskList then?

**Comment by nniiggeell** [comment]
```java
public TaskList getCopy(TaskList taskList) {
    return new TaskList(taskList.getLst()); //getLst() just returns the arraylist<Task> field inside a TaskList
}
```

**Comment by damithc** [comment]
@nniiggeell others will be able to help you better if they have a full view of your code. Perhaps you can push the current code to a branch and share it here?

**Comment by NicolasCwy** [comment]
Ok I think this is the cause of the problem. You are making a shallow copy of taskList, this means that all your taskLists are pointed to the same arrayList instance.

for example:
ArrayList: [ElemA, ElemB, ElemC]

taskList -> ArrayList -> [ElemA, ElemB, ElemC]
taskListCpy -> ArrayList -> [ElemA, ElemB, ElemC]  (Which is the same 3 elments!)

if I do taskListCpy delete index 2
taskListCpy -> ArrayList -> [ElemA, ElemB] 
taskList -> ArrayList -> [ElemA, ElemB]


Solution: Make a deep copy! Do something like a for loop that create new instances of each task in the taskList and return a new taskList

**Comment by nniiggeell** [comment]
@damithc Thanks prof for the suggestion. I will try Nicolas' solution and upload the branch if necessary. 

@NicolasCwy I will try that now! Hope it works!!!!!!!! Thanks for the help.

**Comment by nniiggeell** [comment]
Thanks @NicolasCwy , making a deep copy worked!!
