### ISSUE TITLE
Refactor entire tP Codebase - aka can we build the code from scratch ?

### ISSUE THREAD

**Issue by pss-coder** [nus-cs2103-AY2122S1/forum#245]
Hi Prof @damithc,

given that teams are going to either morph or evolve the tP, can we also be allowed to rebuild the tP codebase from the start and not continue from the current codebase we are given ?

**Comment by damithc** [comment]
> given that teams are going to either morph or evolve the tP, can we also be allowed to rebuild the tP codebase from the start and not continue from the current codebase we are given ?

That wouldn't be _brownfield_, right? So, no. :-) Both morph and evolve has an implicit _the current codebase_ e.g., morph/evolve the current codebase.

**Comment by pss-coder** [comment]
Understood, thanks prof.
