### ISSUE TITLE
Double click duke.jar can't run duke

### ISSUE THREAD

**Issue by Jay-luozhijie** [nus-cs2103-AY2122S1/forum#247]
When I double click the duke.jar file, it won't run duke but instead is opened in intellij, but I can run it in cmd.

![Screenshot 2021-09-17 131036](https://user-images.githubusercontent.com/77223932/133728181-bbde821a-a52a-4af7-a20d-5a9afcc0adb2.jpg)

**Comment by NicolasCwy** [comment]
Hi I'm a mac user, but I think it may be because of your computer's default application to open .jar files, is set to Intellij

Could you check if you could change it to jar launcher?

![image](https://user-images.githubusercontent.com/25302138/133728446-4cbe0351-d1c0-4ffb-9faa-c16315e1d027.png)

**Comment by LuoZhijie-tom** [comment]
but I can't find javaLauncher option, do we need to download it?

**Comment by Jay-luozhijie** [comment]
but I can't find javaLauncher in my computer, do we need to download it?

**Comment by NicolasCwy** [comment]
Maybe other windows users can advise better. For the mac this came with the installation of JDK

**Comment by Jay-luozhijie** [comment]
I changed it to open with Java Platform SE binary, I have java runtime environment, but still can't run it.

**Comment by Jay-luozhijie** [comment]
> Maybe other windows users can advise better. For the mac this came with the installation of JDK

Ok, Thanks!

**Comment by Jay-luozhijie** [comment]
When I first double click the jar, it let me choose how to open the file
![微信图片_20210917192900](https://user-images.githubusercontent.com/77223932/133775555-ff1bde61-5210-44b7-a387-38f1d572508b.jpg)
But I really don't know which software to choose. The Java platform SE binary is the javaw file I found in JDK, but it didn't work

**Comment by marcuspeh** [comment]
I opened mine with Java Platform binary.
![image](https://user-images.githubusercontent.com/54053213/133778783-a802add7-fec0-4e03-a051-8b1c7df1cef0.png)

**Comment by Jay-luozhijie** [comment]
Ok, thanks!
