### ISSUE TITLE
Auto-created git commit subject longer than 72 characters

### ISSUE THREAD

**Issue by CraveToCode** [nus-cs2103-AY2122S1/forum#248]
I received this feedback from the cs2103-bot.
![image](https://user-images.githubusercontent.com/77500075/133731395-dbeeeb66-1cb5-43ee-a667-f25d5405b0d4.png)

However, I believe this commit message was created automatically. This commit was also done 15 commits ago, so I'm not sure how exactly I can change this the commit message in a safe manner. 

Do I have to change this to less than 72 characters? If so, how can I go about doing this safely?

**Comment by damithc** [comment]
@CraveToCode There is no need to change commit messages of past commits. Just follow the convention for future commits.

**Comment by CraveToCode** [comment]
Got it, thank you prof!
