### ISSUE TITLE
Unable to push to remote repo using Sourcetree

### ISSUE THREAD

**Issue by Harry-Gao-H** [nus-cs2103-AY2122S1/forum#25]
My local repo was connected to remote GitHub repo but I was not able to push my code to Github with the following error message: 
```
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: unable to access 'https://github.com/Harry-Gao-H/cs2103-ip.git/': The requested URL returned error: 403
```

Then I tried to re-login my GitHub account with OAuth and reconnect to the remote repo. The error still exists.

Because I am overseas so I tried to turn on VPN,  and sometimes the error messages became the following. 
```
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags --set-upstream origin master:master
fatal: unable to access 'https://github.com/Harry-Gao-H/cs2103-ip/': Failed to connect to github.com port 443: Timed out
Pushing to https://github.com/Harry-Gao-H/cs2103-ip
Completed with errors, see above.
```
```
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags --set-upstream origin master:master
fatal: unable to access 'https://github.com/Harry-Gao-H/cs2103-ip/': OpenSSL SSL_read: Connection was aborted, errno 10053
Pushing to https://github.com/Harry-Gao-H/cs2103-ip
Completed with errors, see above.
```

I have no idea what caused the error. Did anyone meet the same problem?

**Comment by Harry-Gao-H** [comment]
There is a red exclamation mark on Remote icon, but I can access the remote repo by clicking the Remote icon.

**Comment by marcuspeh** [comment]
Did you create a personal access token?

**Comment by damithc** [comment]
@Harry-Gao-H [This is not a solution to your problem] FYI, our scripts will not be able to find your iP work unless you keep the fork name as `ip` (I see you have renamed it as `cs2103-ip`

**Comment by damithc** [comment]
@Harry-Gao-H try the following:

Go to the Tools -> Options -> Authentications:
![image](https://user-images.githubusercontent.com/1673303/129661353-bd377e89-32af-4c85-83a8-cceca299f2b9.png)

Then, delete any GitHub authentications listed there and create a new one using OAuth option.
![image](https://user-images.githubusercontent.com/1673303/129661534-c326c53c-b2f2-44fd-acfe-3455c7bc54d3.png)

**Comment by Harry-Gao-H** [comment]
@damithc I have tried the way but it did not work.

**Comment by Harry-Gao-H** [comment]
> Did you create a personal access token?
> Github removed the usgae of password so you need to create a personal acess token. Have a look at [this](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) to setup

I have already used the OAuth access token, which functions like PAT.

**Comment by damithc** [comment]
@Harry-Gao-H Which OS are you on?

**Comment by Harry-Gao-H** [comment]
@damithc I'm on Windows.

**Comment by rohit0718** [comment]
@Harry-Gao-H what steps did u use to generate this OAuth access token?

**Comment by Harry-Gao-H** [comment]
I doubt whether the VPN (V2ray) I am using could cause the problem.

**Comment by Harry-Gao-H** [comment]
@rohit0718 I clicked the "Refresh OAuth Token", and a website popped out. Then it shows "Authentication OK ".

**Comment by rohit0718** [comment]
@Harry-Gao-H maybe u can try some of the solutions here https://stackoverflow.com/questions/48938235/cant-login-to-github-from-sourcetree-anymore/53624774. might be an issue with the incorrect git version configured on ST.

**Comment by frederickpek** [comment]
Hi harry, #13 this worked for me!

**Comment by Harry-Gao-H** [comment]
@frederickpek @marcuspeh Thank you so much. The problem is solved by using Personal access tokens as instructed in this link:
https://stackoverflow.com/questions/68780819/when-try-to-pull-or-push-in-github-i-am-getting-an-error-message-please-use-a
I thought it was sufficient to use OAuth. 
Also thanks prof @damithc and @rohit0718

**Comment by s7u4rt99** [comment]
Hi all, I am also unable to push to github using sourcetree. The error message is as follows:
`Pushing to https://github.com/s7u4rt99/ip.git
remote: Permission to s7u4rt99/ip.git denied to s7u4rt99.
fatal: unable to access 'https://github.com/s7u4rt99/ip.git/': The requested URL returned error: 403`

It seems I am able to push from intellij but not sourcetree.
