### ISSUE TITLE
Checkstyle build error

### ISSUE THREAD

**Issue by willyamped** [nus-cs2103-AY2122S1/forum#253]
Hi all. I ran into this issue when running `./gradlew checkstyleMain checkstyleTest` or `gradlew checkstyleTest`. Could someone who faced a similar problem before help to see what the issue is? I have added the config files and installed the plugin too. Thank you!

<img width="1440" alt="Screenshot 2021-09-17 at 7 45 15 PM" src="https://user-images.githubusercontent.com/66423703/133777344-f299531e-e512-4c63-9146-a68d5472839e.png">

Below is my checkstyle plugin
<img width="1440" alt="Screenshot 2021-09-17 at 8 55 49 PM" src="https://user-images.githubusercontent.com/66423703/133785952-1c1bb415-4cc1-4f74-bde9-0be06fcde802.png">

**Comment by damithc** [comment]
@willyamped I remember seeing a few similar cases in the forum before e.g., https://github.com/nus-cs2103-AY2122S1/forum/issues/158
tip: search the forum and check among closed issues too

**Comment by waynetee** [comment]
@willyamped try running gradle from the gui instead of the terminal

**Comment by willyamped** [comment]
Hi prof @damithc and @waynetee, thanks for the suggestion. I have referred to the post and it does not seem solve my issue. What I did in the end was to run the checkstyle manually for each and every class I have by clicking the run checkstyle button. Thank you for the help!
