### ISSUE TITLE
Intellij doesn't allow cases on the same indentation as switch statement. How to fix?

### ISSUE THREAD

**Issue by yucheng11122017** [nus-cs2103-AY2122S1/forum#255]
I tried changing the code style in settings for java but intellij still doesn't allow. 
Would really appreciate help for this!
![image](https://user-images.githubusercontent.com/77204346/133800615-1f275b8c-9d74-4374-98c3-a726c57beb77.png)
![image](https://user-images.githubusercontent.com/77204346/133800678-2a95537c-6e1d-491a-84f9-4f2a1ec45008.png)

**Comment by rish-16** [comment]
Hey yah, I just manually shifted them back by one level. You gotta "fight" against the editor by manually deleting one tab-worth of space behind the `case` lines 😅 

Example:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/20137995/133817098-7e5ee78f-fe94-47f1-abaa-c5c2caf44af1.png">

Haven't found any other way sadly

**Comment by waynetee** [comment]
You can configure intellij to auto-format on save like this
![image](https://user-images.githubusercontent.com/17681226/133818396-0da6779f-77a4-4ab0-a00e-11a0b5cf3bf3.png)

**Comment by SkyBlaise99** [comment]
There is an option in Intelij to remove the indentation for `switch case`

I think you unticked the `indent 'case' branches` option alr, perhaps you can refresh Intelij and try again? It is working on my Intelij after I unticked that option

**Comment by damithc** [comment]
@yucheng11122017 Somewhat tangential: you can duplicate the default scheme to create a custom scheme for the project, and modify that (instead of modifying the default scheme).
![image](https://user-images.githubusercontent.com/1673303/133881041-a5578b7a-dbca-45ba-a5b4-3f2dabcd1808.png)

**Comment by yucheng11122017** [comment]
Thank you very much everyone! It is working now 😄
