### ISSUE TITLE
Admin question: Developer Guide requirements for v1.1

### ISSUE THREAD

**Issue by wpinrui** [nus-cs2103-AY2122S1/forum#258]
![Qn](https://user-images.githubusercontent.com/77185900/133891718-c8322099-bd95-4d41-b9b3-5957ef30dde2.jpg)

My team saw this in the module website for this week - does this mean that our Developer Guide must consist all the features planned for v1.2 and v1.3? Or is it just that we must remember to update the use cases and user stories along the way as we add more features?

**Comment by damithc** [comment]
> My team saw this in the module website for this week - does this mean that our Developer Guide must consist all the features planned for v1.2 and v1.3? Or is it just that we must remember to update the use cases and user stories along the way as we add more features?

@wpinrui add everything you have at the start and update along the way too. If you remember, you first brainstorm for user stories and then select _some_ of them to implement, which means the rest will not be implemented by v1.3. But those should still be in the DG, for future developers' reference.

**Comment by wpinrui** [comment]
@damithc That makes sense, thank you Prof!
