### ISSUE TITLE
What is the recommended casing for non static finals in Java

### ISSUE THREAD

**Issue by mrmrinal** [nus-cs2103-AY2122S1/forum#259]
From my understanding of Java, and the check style, Java recommends using `SCREAMING_SNAKE_CASE` for static final constants.

On the other hand, many documents, and the check style we are using recommends `camelCase` for naming non-static final variables. 

The SE-EDU website however recommends `SCREAMING_SNAKE_CASE` for non-static final variables.
![image](https://user-images.githubusercontent.com/77235299/133894219-2fed159a-32cc-4fb2-9fe1-310c0dd34009.png)

I wanted to clarify this module's stance on naming non-static final variables, as the standards on the SE-EDU websites, and the checkstyle we are using are contradictory.

**Comment by damithc** [comment]
Good catch @mrmrinal 

The `static` keyword must have been left out from this example by mistake. I've updated as follows:
![image](https://user-images.githubusercontent.com/1673303/133896017-1ed4864c-eb4f-466c-8e7b-8d6d40e119ca.png)
