### ISSUE TITLE
Individual Project: Gradle Support

### ISSUE THREAD

**Issue by huizhuansam** [nus-cs2103-AY2122S1/forum#26]
Hi @damithc, there is a branch `Add Gradle support` in git, I suppose it will be used for week 3's project? If so is it safe to merge the branch to `master` once I am done with this week's IP?

**Comment by damithc** [comment]
@huizhuansam, it will be used in Week 4. Yes, you may merge it early if you are already familiar with Gradle.

**Comment by huizhuansam** [comment]
Thanks prof!
