### ISSUE TITLE
cs2103-bot Detects Tab Usage Problems

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#260]
The bot raises highlights this issue:
![image](https://user-images.githubusercontent.com/40263305/133896399-c2c17b4a-77b4-4e4d-b5ef-752b1a570c11.png)

I am using these tab settings on IntelliJ:
![image](https://user-images.githubusercontent.com/40263305/133896375-81ceaae5-bca5-4f24-a121-5bb10202738e.png)

I've tried re-typing the spaces for the instances flagged out, but I don't have a way of verifying if that works. Additionally, the bot says that "at-most three examples are given", so I am not sure where else this problem exists in my project. Does anyone have any tips on how to resolve this?

**Comment by Yukun99** [comment]
You can try running the checkstyle on your code, and if the issue still shows up maybe do code cleanup on your project.
![image](https://user-images.githubusercontent.com/16715421/133913902-ec6b0d78-7d9b-4d0b-b5ce-7c26e9cad5f2.png)
If your Java code style is setup correctly to follow the convention IntelliJ will format it all correctly for you

**Comment by SkyBlaise99** [comment]
Adding on to @Yukun99's answer on top, you can try to reformat the whole code of your ip provided you have the correct settings.

![image](https://user-images.githubusercontent.com/69448615/133914282-2804459b-0299-4726-bcaa-d8dc1927a42c.png)

![image](https://user-images.githubusercontent.com/69448615/133914286-8f481cbb-8294-4921-9cb8-cce0fc51a480.png)

**Comment by damithc** [comment]
Leaving this here in case someone else has a similar problem in future ... this s/o post seem to have a bunch of remedies worth trying https://stackoverflow.com/questions/41532061/shortcut-for-changing-tabs-spaces-tabs-in-intellij-idea

**Comment by AllardQuek** [comment]
Thanks everyone! Have tried your suggestions and everything seems fine :)
