### ISSUE TITLE
On the issue of mentioning Access Modifiers

### ISSUE THREAD

**Issue by mrmrinal** [nus-cs2103-AY2122S1/forum#266]
Hi, my team wanted to check what this course's stance is on the EXPLICIT mention of access modifiers.

Back in CS2030s we were marked down if the access modifiers were not explicitly stated as for the most part we were only expected to use ```private``` or ```public``` access modifiers. 

In this module, since we are dealing with packages, we wanted to check if it would be okay to not have an access modifier to connote that a field is package-private, or are we encouraged to use the ```protected``` which is the closest to package-private also gives the field access to subclasses, as it is explicitly mentioned.

**Comment by damithc** [comment]
@mrmrinal Our default stance on code style related matters is that,
* if covered by the coding standard, follow that
* otherwise, it is up to the team to decide

**Comment by yucheng11122017** [comment]
I don't think it is mentioned by the coding standard. 
Anyway, I do believe it is pretty good practise to explicitly name it but to each his own I guess!
