### ISSUE TITLE
GitHub Table

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#267]
From the Markdown guide, I see that we create a table in the following way
```
First Header | Second Header
------------ | -------------
Content      | Content
```

My question is what if the `Content` is very long? I'm not sure if the 120 characters limit applies here, but I find it hard to read and edit anyways.

Example 1:

```
First Header | Second Header
------------ | -------------
Content      | Super super super super super super super super super super super super super super super super super super super super super super super super super super super super super super super super super super long text
```

Below is the output of it, which GitHub automatically made it into 2 lines.

Output of Example 1:

First Header | Second Header
------------ | -------------
Content      | Super super super super super super super super super super super super super super super super super super super super super super super super super super super super super super super super super super long text

But is there a way to write it such that I can add newlines yet keeping it in the same box? Like in my editor I can type the following, and still displaying as it is on top.

Example 2:

```
First Header | Second Header
------------ | -------------
Content      | Super super super super super super super super super super super super 
             | super super super super super super super super super super super super 
             | super super super super super super super super super super long text
```

Currently typing this way result in the following output, which is not what I wanted

Output of Example 2:

First Header | Second Header
------------ | -------------
Content      | Super super super super super super super super super super super super 
             | super super super super super super super super super super super super 
             | super super super super super super super super super super long text

I tried to add `|` in front also which turn into this

First Header | Second Header
------------ | -------------
Content      | Super super super super super super super super super super super super 
|             | super super super super super super super super super super super super 
|             | super super super super super super super super super super long text

**Comment by damithc** [comment]
> My question is what if the `Content` is very long? I'm not sure if the 120 characters limit applies here, but I find it hard to read and edit anyways.

The 120 char limit doesn't apply to markdown files.

**Comment by SkyBlaise99** [comment]
Ah ok good to know that, thx prof

**Comment by chunweii** [comment]
```
<table>
<tr><th>First Header</th><th>Second Header</th></tr>
<tr>
<td>Content</td>
<td>Super super super super super super super super super
 super super super super super super super super super super
 super super super super super super super super super super
 super super super super super long text</td>
</tr>
</table>
```

I think this is another way to create a table in markdown. You can have new lines in the super long text.
<table>
<tr><th>First Header</th><th>Second Header</th></tr>
<tr>
<td>Content</td>
<td>Super super super super super super super super super
 super super super super super super super super super super
 super super super super super super super super super super
 super super super super super long text</td>
</tr>
</table>

**Comment by SkyBlaise99** [comment]
Ah thank you so much. I never thought about html haha.
