### ISSUE TITLE
Can't preview GFMD in intellij

### ISSUE THREAD

**Issue by Jay-luozhijie** [nus-cs2103-AY2122S1/forum#268]
I have installed the Markdown plugin, but still can't preview .md files
![Screenshot 2021-09-23 103436](https://user-images.githubusercontent.com/77223932/134447905-8aceb82d-14b3-4997-a91b-57047008d6f9.jpg)

This is my markdown setting:

![Screenshot 2021-09-23 105046](https://user-images.githubusercontent.com/77223932/134448177-20176b89-e267-46e2-9321-b656db36d2d4.jpg)

**Comment by damithc** [comment]
Perhaps try 'File -> Invalidate cache' option?

**Comment by Jay-luozhijie** [comment]
Oh it works! Thank you!
