### ISSUE TITLE
Refactoring iP codebase after submission - Limitations

### ISSUE THREAD

**Issue by YeluriKetan** [nus-cs2103-AY2122S1/forum#269]
@damithc 
I have completed all deliverables for the iP on time. But now I wish to perform some major refactoring to the iP codebase. For instance, apply more OOP, add more tests, add features. According to the extract from module website below, these changes "can be done after the semester is over". Does this imply that I have to wait until the semester is done before I can do any major changes? Or can we proceed to make the changes anytime thanks to the power of version control?

Also a recent email from the teaching team says we can make another release in Week 7. What are the limitations/constraints on this release (e.g. limited to bug fixes, etc.) ?

![Screenshot 2021-09-24 003850](https://user-images.githubusercontent.com/77260609/134549417-09e820af-9bf1-419f-8578-fc0dd7accdf9.png)

**Comment by damithc** [comment]
> Also a recent email from the teaching team says we can make another release in Week 7. What are the limitations/constraints on this release (e.g. limited to bug fixes, etc.) ?

@YeluriKetan you can do another release until Thursday of Week 7.
