### ISSUE TITLE
how to run .bat file in intellij terminal

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#27]
hi
Is there any installation required to run .bat file in intellij terminal, or it can't be done , or there are simpler ways? thx

**Comment by marcuspeh** [comment]
Cd into the folder in intellij terminal and ./file.bat to run it

**Comment by qinguorui2001** [comment]
> Cd into the folder in intellij terminal and ./file.bat to run it

PS D:\individual project> cd text-ui-test
PS D:\individual project\text-ui-test> ./runtest.bat
'javac is not recognized as an internal command
********** BUILD FAILURE **********
PS D:\individual project\text-ui-test>
![image](https://user-images.githubusercontent.com/77196303/129693377-18dc7f6c-0f2a-4574-8f96-3121729061a3.png)

**Comment by qinguorui2001** [comment]
what should i do next? thx

**Comment by rohit0718** [comment]
u need to add java binaries to your path. check out https://stackoverflow.com/questions/7709041/javac-is-not-recognized-as-an-internal-or-external-command-operable-program-or.

**Comment by damithc** [comment]
@qinguorui2001 In addition to what @rohit0718 mentioned above, note that recent versions of Intellij terminal defaults to PowerShell. You can try to change it to a  normal command console instead as the given batch file doesn't work in PowerShell, IIRC.

File -> Settings -> Tools -> Terminal
![image](https://user-images.githubusercontent.com/1673303/129694750-9ae2925a-c9af-4e24-9aba-85ff83964979.png)

**Comment by qinguorui2001** [comment]
thx all, i got it
