### ISSUE TITLE
Permission to use CalendarFX in tp

### ISSUE THREAD

**Issue by Chesterwongz** [nus-cs2103-AY2122S1/forum#271]
## Library

[CalendarFX](https://github.com/dlsc-software-consulting-gmbh/CalendarFX)

## Purpose

We intend to use it to display a read-only schedule as shown in this mockup:
![image](https://user-images.githubusercontent.com/70138507/134773109-2b8b2372-c813-41e6-8684-d14be5de2c85.png)

## License

[Apache License 2.0](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/blob/master-11/LICENSE)

**Comment by damithc** [comment]
Approved.
