### ISSUE TITLE
Question about Forking workflow

### ISSUE THREAD

**Issue by Nature711** [nus-cs2103-AY2122S1/forum#272]
According to the forking workflow, after my pull request has been reviewed and approved by my teammate and get merged to the team's master branch, I need to pull the changes to my local repo, then push to my remote fork. This is illustrated in the image below:
![image](https://user-images.githubusercontent.com/77217430/134844772-870875d4-bf3e-43be-bdab-6dda5b4acff0.png)

However, I was wondering if this alternative workflow would also work:
1. After my PR get merged, instead of pulling to my local repo, I used the "``fetch upstream``" feature in GitHub, so my remote fork becomes in sync with the upstream team repo.
2. Then I pull the changes from my remote fork to my local repo, so my local repo would also be in sync with the latest changes.

I don't think there's a difference between the two workflows. I wonder why the first is recommend while the second is not mentioned. 

Thanks for looking at my question!

**Comment by damithc** [comment]
@Nature711 Yes, that would work too. 
'fetch upstream' is a new GitHub feature. That's why it is not mentioned in the lecture.
Isn't pull-and-push is easier though, as you can do both using a single UI, whether it is SourceTree or git CLI?

**Comment by Nature711** [comment]
OK I see, and I agree pull-and-push is easier. Thanks prof :D

**Comment by charliemoweng** [comment]
Thank you for the question @Nature711 and thanks prof @damithc for the clarification. Was having the same doubt.
