### ISSUE TITLE
Feature Branch Workflow

### ISSUE THREAD

**Issue by huizhuansam** [nus-cs2103-AY2122S1/forum#273]
Hi prof @damithc, my team has decided that the forking workflow is too cumbersome and wishes to adopt the feature branch workflow. Are there any special instructions we need to follow for the autograder to pick up our contributions, i.e. branch naming conventions?

**Comment by damithc** [comment]
@huizhuansam note the following:
![image](https://user-images.githubusercontent.com/1673303/134906187-bf13d0cc-6b3a-400d-bcca-e4ddcb83c87f.png)

So, for v1.1 and v1.2, the script will only count PRs that follow the forking workflow. But all merged code will be counted as contributions irrespective of the workflow.
