### ISSUE TITLE
`tp` Contributions are not showing

### ISSUE THREAD

**Issue by rish-16** [nus-cs2103-AY2122S1/forum#276]
Hey everyone,

I've been dilligently doing my `tp` and contributing with the rest of my group. However, my contribution graph on [`reposense`](https://nus-cs2103-ay2122s1.github.io/tp-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs~functional-code~test-code~other&since=2021-09-17&tabOpen=true&tabType=authorship&tabAuthor=rish-16&tabRepo=AY2122S1-CS2103-W14-1%2Ftp%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=&authorshipIsBinaryFileTypeChecked=false) shows nothing under my name (**5.** on list).

![image](https://user-images.githubusercontent.com/20137995/135009312-3a49138f-81cb-4f64-aaae-59387a584ada.png)

I have had Issues assigned to me and my documentation work is part of the larger `master` branch. I've also finished some of the tutorials like `tutorial-adding-command` and have also merged a PR for a teammate. 

- [Issue 2](https://github.com/AY2122S1-CS2103-W14-1/tp/issues/27)
- [Issue 1](https://github.com/AY2122S1-CS2103-W14-1/tp/issues/14)

My work last week:

- [PR 2](https://github.com/AY2122S1-CS2103-W14-1/tp/pull/34)
- [PR 1](https://github.com/AY2122S1-CS2103-W14-1/tp/pull/32)

If not for actual code, at least the `docs` tag must show something given my contributions to our User Guide? 

The odd thing is my teammates' work has been registered. I don't want it to seem like I'm freeloading off them haha 😅 😅 

Any help appreciated. Thank you!

(cc. @damithc)

**Comment by damithc** [comment]
@rish-16 this is usually caused by a you using a Git author name not known to RepoSense before (i.e., you did not use that Git author name for the iP). We detected such a case for you and will be updating the tP code dashboard config soon. Please check again after 24 hours and let us know if the code is still not picked up.

**Comment by rish-16** [comment]
Thank you, Prof. @damithc!

Though, my GitHub username is the same as the one on reposense. I'll wait for some more time then.

Appreciate the help 😃
