### ISSUE TITLE
What does @code mean in documentation

### ISSUE THREAD

**Issue by Zzhiwei** [nus-cs2103-AY2122S1/forum#277]
![Screenshot 2021-09-28 at 10 20 01 AM](https://user-images.githubusercontent.com/59001819/135011812-0fbacbdc-aa00-4069-b25b-369ac51e1487.png)

I see a lot of {@code ...} usage in the tutorial, what does it mean exactly? and how can we use it?

**Comment by xlzior** [comment]
> `{@code ...}` is a Javadoc tag that tells Javadoc that the text inside the braces is source code and should not be treated as HTML. Javadoc should also format the text in a code block differently than the other text.

https://stackoverflow.com/questions/19302183/what-does-the-code-java-annotation-do

```
/**
     * Parses {@code userInput} into a command and returns it.
     * @throws ParseException if {@code userInput} does not conform the expected format
     */
```

renders as

![image](https://user-images.githubusercontent.com/30801910/135012509-435622e2-e389-4561-8d3a-4ec5efd2354b.png)

with the `userInput` formatted in a different font

**Comment by Zzhiwei** [comment]
@xlzior got it, thank you!
