### ISSUE TITLE
Are modifications to the UG considered as "code" ?

### ISSUE THREAD

**Issue by ramaven** [nus-cs2103-AY2122S1/forum#278]
Dear Prof,

In w8's tp guidelines on the cs2103 website, it says " From this point onwards each member is expected to contribute some code to each milestone, preferably each week; only merged code is considered as contributions (Reason)." 

I'd like to ask whether modifications to the user guide are considered as "code"? Since it is not done using a programming language. Or is only Java/Javafx code considered as code?

Thank you!

**Comment by damithc** [comment]
> I'd like to ask whether modifications to the user guide are considered as "code"? Since it is not done using a programming language. Or is only Java/Javafx code considered as code?

Code that goes into the product, not the documentation. Given we are following a breadth-first iterative approach, it's not desirable that one would be doing documentation only in a milestone.

**Comment by ramaven** [comment]
Okay, thank you Prof!
