### ISSUE TITLE
Working together on a feature with fork workflow

### ISSUE THREAD

**Issue by Chesterwongz** [nus-cs2103-AY2122S1/forum#279]
In branching workflow, helping each other out is as easy as making a new branch from the other person's feature branch. However, I would like to know how this is done in forking workflow. One way I can think of is simply cloning the other person's fork, but there may be potential issues then, with tracking work. Is there any other way?

**Comment by damithc** [comment]
@Chesterwongz by 'helping' do you mean to help with debugging or do you also see you pushing updates to a team member's branch?

Note that you _can_ pull a branch from a team members fork to your local repo. You just need to add the team member's fork as another remote in your local repo.

**Comment by Chesterwongz** [comment]
Oic, thanks!
