### ISSUE TITLE
what to do if I wrote wrong commit message 

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#28]
I am really curious if  there is a way to change commit message of previous commits?
I mistook TextUiTesting for level 5 and wrote the wrong commit message, is there a way to change it?

**Comment by NicolasCwy** [comment]
If it is your most recent commit, you can try `git commit --amend  New message` or `git commit --amend` if you want to open an editor to write the message.

Can find out more [here](https://www.atlassian.com/git/tutorials/rewriting-history)
