### ISSUE TITLE
Github Pages fails to build

### ISSUE THREAD

**Issue by zhuoyang125** [nus-cs2103-AY2122S1/forum#280]
Hi all,

After completing the "update project website" task, Github pages issued a generic "page build failed" error, even though our markdown files are updated and displayed correctly. We have already followed the Github pages set up and updated _config.yml to our team repo. This is from [the provided tutorial](https://se-education.org/guides/tutorials/jekyll.html).

Not sure if we are missing out on any steps. Thank you!

**Comment by damithc** [comment]
Does the project website appears as expected? GitHub is known to issue an occasional page build errors incorrectly although the build succeeded.

**Comment by vimuthm** [comment]
Hi!

After checking the commit history, the build first fails at [this](https://github.com/AY2122S1-CS2103-F10-4/tp/commit/e1ee6e2fa71806ba0b411deb567b57c20ea369a1) commit. A possible issue would be this change here; (layout and title are probably a required header and its absence is causing the break)

![image](https://user-images.githubusercontent.com/62249192/135566939-682e2334-e1cb-465f-9ea4-cde75dbf4d13.png)

**Comment by zhuoyang125** [comment]
Alright we'll look into it. Thanks a lot for the help!
