### ISSUE TITLE
UML Diagram - Alternative Paths

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#281]
Following the [website](https://nus-cs2103-ay2122s1.github.io/website/se-book-adapted/chapters/uml.html#alternative-paths), I do not see any restrictions of having just 1 alt path.

It is also mentioned that
> That is, it is acceptable for none of the alternative partitions to be executed but it is not acceptable for multiple partitions to be executed.

So is it possible for `alt` box to have just 1 condition, acting the same way as `opt`?

**Comment by damithc** [comment]
> So is it possible for `alt` box to have just 1 condition, acting the same way as `opt`?

Given there is already an `opt`, I don't think there is any reason to use an `alt` with one path 🤔 (_alternatives_ imply more than one)

**Comment by SkyBlaise99** [comment]
I see. Thx prof.
