### ISSUE TITLE
Auto fix style of code

### ISSUE THREAD

**Issue by hungkhoaitay** [nus-cs2103-AY2122S1/forum#283]
Guys, sometimes I got these error related to check style. Is there any command to automatically fix these error? Thanks 😄 

![Screenshot 2021-10-03 at 12 41 01 PM](https://user-images.githubusercontent.com/77202230/135740288-a9974d87-c5f5-4a84-a3c9-87cf7d84a70a.png)

**Comment by NicolasCwy** [comment]
You can check out the  [Intellij auto import](https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#automatically-add-import-statements). After configuring, deleting the offending import statements should automatically be reimported, unless there are a few classes/ variables that have a similar name. 

If it is ambiguous there is some manual work, where you can look at the context actions for the missing classes and reimport using keyboard shortcuts (check out the same link, first section)

**Comment by hungkhoaitay** [comment]
Thanks @NicolasCwy, it works 😄
