### ISSUE TITLE
Hyperlink bug in `Tutorial: Adding a command`

### ISSUE THREAD

**Issue by hungkhoaitay** [nus-cs2103-AY2122S1/forum#284]
https://nus-cs2103-ay2122s1.github.io/tp/tutorials/AddRemark.html

The hyperlink of section `Hook RemarkCommand into the application` [this](https://github.com/se-edu/addressbook-level3/commit/35eb7286f18a029d39cb7a29df8f172a001e4fd8#diff-34ace715a8a8d2e5a66e71289f017b47)
and `Make the command accept parameters` seems to be the same [this](https://github.com/se-edu/addressbook-level3/commit/35eb7286f18a029d39cb7a29df8f172a001e4fd8#diff-34ace715a8a8d2e5a66e71289f017b47)

Screenshots of where are they:

![Screenshot 2021-10-03 at 12 47 52 PM](https://user-images.githubusercontent.com/77202230/135740390-a483129e-2dc4-42e6-8f45-3c930962c86d.png)

![Screenshot 2021-10-03 at 12 49 36 PM](https://user-images.githubusercontent.com/77202230/135740411-7a0ee70d-fe64-497e-9d4b-5daf4f29e422.png)

**Comment by damithc** [comment]
Good catch @hungkhoaitay 
I'll let the se-edu dev team know so that it can be fixed before the next semester.
