### ISSUE TITLE
Java Pattern Regex

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#286]
Hi guys can anyone explain what this code means? What is this supposed to match?

``` java
Pattern.compile("(?<arg1>\\S+)(?<arg2>.*)");
```

From tests and trials, I observed:

Given input: `abc de fgh...`

`arg1` = `abc`
`arg2` = `de fgh...`

What I wanted to do is to split it further into 3 parts and obtain the following results.

`arg1` = `abc`
`arg2` = `de`
`arg3` = `fgh...`

The way how I currently did is to use the Pattern again on arg2 to separate out arg3, but I wonder if there is a more elegant way to tweak the Pattern somehow and give all 3 args in 1 shot.

**Comment by xlzior** [comment]
Are you familiar with regex?

There's a couple things going on here:

`\S+`
* `\s` refers to any whitespace character
* `\S` refers to any non-whitespace character (regex convention is to use capital letters to denote "not")
* `+` refers to a sequence of 1 or more characters

So, `\S+` refers to a sequence of **1 or more non-whitespace** characters

`.*`
* `.` refers to any character
* `*` refers to a sequence of 0 or more characters (same as the `*` in UML multiplicity)

So, `.*` refers to any sequence of **0 or more of any character**, aka the remainder of the string basically

`(?<name>...)`
* save whatever was captured in the "..." to be referenced later using the `name`

> The way how I currently did is to use the Pattern again on arg2 to separate out arg3, but I wonder if there is a more elegant way to tweak the Pattern somehow and give all 3 args in 1 shot.

Yes, you should be able to do it in 1 shot. Is `arg2` definitely going to be 1 word? I think you can do something along the lines of `Pattern.compile("(?<arg1>\S+)\s(?<arg2>\S+)(?<arg3>.*)");`

**Pro-tip**: you can use websites like [regex101](https://regex101.com/) to learn and test out regex expressions easily. It even has a Java mode that would help greatly here.

![image](https://user-images.githubusercontent.com/30801910/136011807-d5f15605-cd93-48dd-b2fc-04f7c5f88d38.png)

I'm not super familiar with regex in Java specifically, so do correct me if I'm wrong!
