### ISSUE TITLE
Should we push failing tests to GitHub?

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#287]
Hi all, my team is changing the person model into 2 models, a guest and a staff. Since these are large changes, should we delete the tests that are failing, or amend them to test the new model.

Currently one person is making the conversion and we would like to split the work, therefore we don't really want to amend the tests now.

**Comment by damithc** [comment]
For the test code, you can choose whichever works for you. For the functional code, ensure you are _evolving_ the code rather than rewriting.

**Comment by NicolasCwy** [comment]
Thanks prof!
