### ISSUE TITLE
Is it considered bad practice to have instance attributes in the main class?

### ISSUE THREAD

**Issue by uyencfi** [nus-cs2103-AY2122S1/forum#29]
Initially, class `Duke` only contains the `main` method. Now I want to have some instance attributes in `Duke`, so I can instantiate it inside `main()` like this:

```java
public class Duke {
  private String someAttribute;

  private Duke(String s) {
    someAttribute = s;
  }

  public static void main(String[] args) {
    // print logo
    Duke d = new Duke("Hello");
    // do other things...
  }
}
```
Is this considered bad practice? I think it might be OK as long as I set the attributes and constructor as `private`, but I've read elsewhere that the class containing `main` -- in this case, class `Duke` -- should only serve as the entry point of the programme and have no other methods or attributes.

**Comment by SkyBlaise99** [comment]
If you are afraid of this then one way you can do is probably add a `Main.java` to hold that `main()` function which calls `new Duke().run()`. But as far as I know this is fine, with the stuff set to `private`.

**Comment by uyencfi** [comment]
I also thought of adding another class like that, but I’m wondering if it will make the programme unnecessarily complicated?

Also can you explain why you would leave the constructor `public`? My rationale is using `private` can prevent it from being called outside the class.

**Comment by SkyBlaise99** [comment]
Oh as in if u are to make a new 'Main.java' then u will need to make it public cuz u r calling it from another class.

**Comment by uyencfi** [comment]
Oh ic haha, then I'll close the issue here
