### ISSUE TITLE
Issues with Codecov report and Java CI

### ISSUE THREAD

**Issue by ZhaoPeiduo** [nus-cs2103-AY2122S1/forum#290]
Hi all, when our group created PRs for this week, we noticed that some of the PRs did not have the Codecov reports although all the java CI checks have been done. Is there anything we can do to generate the Codecov report in PR? 

On a side note, as compared to previous weeks,  it took  much longer for java CI to recongise the new PRs and perform checks on them. Does anyone encounter similar issues?
<img width="358" alt="1" src="https://user-images.githubusercontent.com/77187494/136141624-481baaa6-d9b5-4f03-8240-0d88ad8e8060.png">

**Comment by damithc** [comment]
> On a side note, as compared to previous weeks, it took much longer for java CI to recongise the new PRs and perform checks on them. Does anyone encounter similar issues?

Could be due to the 'incident' with GitHub actions y'day https://www.githubstatus.com/history

**Comment by ZhaoPeiduo** [comment]
Thank you!
