### ISSUE TITLE
Contributing to another branch which is merged into master

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#291]
My team is working on a W.I.P branch on our org repo until the product is ready for us to merge with master. Will the commits and PRs for all individuals be reflected after we merge this W.I.P branch to master? Or is it advised for us to make changes to the master branch for the contributions to be tracked

**Comment by damithc** [comment]
@NicolasCwy Commits will be recognized after the W.I.P branch is merged to the master branch. PRs will be recognized after they are merged (irrespective of the receiving branch).

**Comment by NicolasCwy** [comment]
Noted thanks prof!
