### ISSUE TITLE
tp: Alternative UML drawing tools?

### ISSUE THREAD

**Issue by huizhuansam** [nus-cs2103-AY2122S1/forum#293]
Hi prof @damithc, are we allowed to use other UML drawing software instead of PlantUML? I am thinking [diagrams.net](https://app.diagrams.net/), it is a free and open-source diagramming tool that has a drag and drop interface.

**Comment by damithc** [comment]
@huizhuansam yes you can use a different tool but follow the advice given in https://nus-cs2103-ay2122s1.github.io/website/admin/tp-deliverables.html#dg-tips about diagramming tools
