### ISSUE TITLE
Codecov report not showing anymore

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#294]
Recently due to updating of code for v1.2, our code starts to fail CI. Now that we fixed it and it is passing CI, the Codecov does not seem to appear anymore. This is what was shown on the [Codecov ](https://app.codecov.io/gh/AY2122S1-CS2103T-T12-1/tp/) side

![image](https://user-images.githubusercontent.com/69448615/136401162-86d270b7-c58a-4963-9307-6ffa32f1e74b.png)

Anything we can do to fix the issue and let Codecov leave a comment on the PR again?

**Comment by damithc** [comment]
While waiting for a solution, you can continue without worrying about this too much -- coverage is not a high priority at this stage of the project.

**Comment by SkyBlaise99** [comment]
Ok thx prof. Just curious why is it not showing up, afraid that we might have broken something while editing the code.
