### ISSUE TITLE
Table of Contents textbook from Luminus issue

### ISSUE THREAD

**Issue by pss-coder** [nus-cs2103-AY2122S1/forum#3]
Hi, I downloaded the textbook from Luminus, but the table of content seems to be all over the place. 

Here is a screenshot of the 1st page of the textbook:
![textbook toc](https://user-images.githubusercontent.com/22881285/129372465-088ef1f4-8ead-4e24-80c9-c1f0d02ca7c7.png)

Are others also facing this issue?

**Comment by damithc** [comment]
hmm... looks like this on my Win 10 comp, using Adobe Acrobat Pro:
![image](https://user-images.githubusercontent.com/1673303/129374015-5f41dab5-e47f-4992-9606-aa26331636a7.png)

**Comment by kleonang** [comment]
I'm encountering this issue too on macOS's default Preview app. However, the Table of Contents can be viewed as intended when using another PDF viewer like the free [Adobe Acrobat Reader DC](https://get.adobe.com/uk/reader/).

**Comment by huizhuansam** [comment]
I think it is an issue with macOS' Preview app. Seeing the same jumbled-up text as well.

**Comment by waynetee** [comment]
I think it's probably a font issue, considering how "Table of Contents", which has a different font, is not jumbled.

**Comment by pss-coder** [comment]
> I'm encountering this issue too on macOS's default Preview app. However, the Table of Contents can be viewed as intended when using another PDF viewer like the free [Adobe Acrobat Reader DC](https://get.adobe.com/uk/reader/).

Yup, using Preview I had this issue, but is now resolved when I open the file using Reader DC. 

Thank you.

**Comment by GabrielSimbingyang** [comment]
Hi @pss-coder,

This is Gabriel, a student from one of your senior batch. As this issue has been resolved, please be reminded to close the thread in order to keep the forum neat and tidy.

Thank you!

Regards,
Gabriel

**Comment by damithc** [comment]
@pss-coder and others, thanks for reporting this. Will take note and look for a solution but unlikely it will be fixed this semester. For the time being, please use a different PDF viewer.

**Comment by AllardQuek** [comment]
@damithc Could you send over the full contents page as images? While there are issues viewing it as a PDF, we could still copy and paste images into a Notes app on our computer or tablet. Thank you!

**Comment by waynetee** [comment]
[Textbook.pdf](https://github.com/nus-cs2103-AY2122S1/forum/files/6996474/Textbook.pdf)
@AllardQuek does this work?

**Comment by AllardQuek** [comment]
Works for me on Mac's Preview, thank you @waynetee!

**Comment by damithc** [comment]
Thanks for the alternative PDF @waynetee How did you make it work in the Mac's Preview?

**Comment by waynetee** [comment]
I manually changed the font from Nimbus Sans to Arial

**Comment by damithc** [comment]
> I manually changed the font from Nimbus Sans to Arial

Nice work @waynetee
