### ISSUE TITLE
iP review: file to store tasks is not automatically created upon first time app launch

### ISSUE THREAD

**Issue by eezj35** [nus-cs2103-AY2122S1/forum#302]
Hi prof @damithc , just wanted to check, if the duke app does not automatically create a new txt file to save the inputted tasks upon first time start up, but everything else works after the user manually creates a `data ` folder within the same directory as the jar file, with a txt file inside, it is still ok right when considering functionality requirements being met?

**Comment by damithc** [comment]
I think this will have to count as a major bug as it'll make the product inoperable from the very beginning. We also mentioned this twice, once when the feature was supposed to be added, and once when we described how to smoke-test the product. 

So, you can rate it as functionality being met but major bugs found.

**Comment by eezj35** [comment]
Hi prof @damithc  what if thrs an error message telling users to first create the relevant file and folder first? Wld tht still be counted as a bug since technically its considered "handling" such a scenario? If not will this lead to loss in overall iP marks?

**Comment by damithc** [comment]
> Wld tht still be counted as a bug since technically its considered "handling" such a scenario? 

Not ideal, but might be acceptable if there are no other problems.

>If not will this lead to loss in overall iP marks?

No, we'll give a chance to fix the problems found.

**Comment by eezj35** [comment]
> > Wld tht still be counted as a bug since technically its considered "handling" such a scenario?
> 
> Not ideal, but might be acceptable if there are no other problems.
> 
> > If not will this lead to loss in overall iP marks?
> 
> No, we'll give a chance to fix the problems found.

Ok thanks for the clarification prof!!
