### ISSUE TITLE
serious merging issue

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#305]
hi,
java 11, windows
i update my part of adding test methods in my local repo, and didn't make a pull request to team repo and then before pulling the master branch of team repo, i merged my test methods branch to my local master branch, and then i pull the master branch from the team repo, the terrible things happened, i failed many test cases and then even i copied the whole part of my team mates repo, the same issue happen.
![image](https://user-images.githubusercontent.com/77196303/136698485-cb571079-bf96-4f1b-96fb-744685ea7062.png)

**Comment by damithc** [comment]
> i merged my test methods branch to my local master branch

@qinguorui2001 Are you not following the forking workflow? If you are, you should not merge code to the master branch locally.

**Comment by qinguorui2001** [comment]
> > i merged my test methods branch to my local master branch
> 
> @qinguorui2001 Are you not following the forking workflow? If you are, you should not merge code to the master branch locally.

so how to solve this issue, revert the process? i think this time i merged my part to my local master branch before pulling the master of team repo

**Comment by damithc** [comment]
> so how to solve this issue, revert the process? i think this time i merged my part to my local master branch before pulling the master of team repo

You can try the following:
1. hard-reset the master branch to the commit just before you merged your code (this will undo the rogue merge)
2. pull the master branch again
3. merge master to your branch, to update your branch with upstream code
4. de-conflict, if necessary
5. get your branch to pass tests i.e., fix failing tests
6. after that, you can create a PR from your branch, if you are following the forking workflow.

**Comment by qinguorui2001** [comment]
the issue persists, i think this is not related to the source tree, since even if i copied all stuff from my team mate repo in another package, and i did it locally ,the problem about failing tests exist.

**Comment by damithc** [comment]
> the issue persists, i think this is not related to the source tree, since even if i copied all stuff from my team mate repo in another package, and i did it locally ,the problem about failing tests exist.

Your team repo is passing CI, which means you should be able to get a clean start using fresh clone of the team repo. After that, copy over the stuff from your branch incrementally.

**Comment by qinguorui2001** [comment]
hi,prof,so i need to create a new folder locally and just clone the repo there, without deleting my original local team repo(which considered as discarded)? if so, the following picture represents the correct link i tend to paste?
![image](https://user-images.githubusercontent.com/77196303/136700956-0de6a9de-b787-49f9-8a05-d05d7910a954.png)

**Comment by damithc** [comment]
> hi,prof,so i need to create a new folder locally and just clone the repo there, without deleting my original local team repo(which considered as discarded)? if so, the following picture represents the correct link i tend to paste?
> ![image](https://user-images.githubusercontent.com/77196303/136700956-0de6a9de-b787-49f9-8a05-d05d7910a954.png)

Yes @qinguorui2001 . After cloning, its `origin` will point to the team repo (as that's where you cloned from). You may want to change that to point to your fork, and add another remote (e.g., `upstream`) to point to the team repo.

**Comment by qinguorui2001** [comment]
sorry,prof, when i build this happened
![image](https://user-images.githubusercontent.com/77196303/136701720-8ad0a7a9-b2f3-467e-b908-4b736d0e177e.png)

**Comment by qinguorui2001** [comment]
when i run the tests, the same number of test cases fail

**Comment by damithc** [comment]
> when i run the tests, the same number of test cases fail

Sounds like something wrong with your local environment (as the CI is passing on GitHub and I assume your team members are not facing a similar issue). Let's wait to see if anyone else faced a similar problem.

In the meantime, do a `File -> Invalidate Cache` just in case.

**Comment by qinguorui2001** [comment]
hi,prof, when i went to a past commit when we just start the team project, i ran the tests and this happened, do i need to fix it first?
![image](https://user-images.githubusercontent.com/77196303/136719751-b9cd8703-32ba-4183-a6e7-5a17e80e4d11.png)

**Comment by qinguorui2001** [comment]
hi prof, i actually found after i merge the save and load branch made by my ios team mate, the issue occured

**Comment by qinguorui2001** [comment]
but it seems my windows team mate can run those tests successfully after their merge, so this means just my setting is incompatible with their settings ? but they can work on my past commits as well, maybe just the save and loading part incompatible?

**Comment by vimuthm** [comment]
> i ran the tests and this happened, do i need to fix it first? ![image](https://user-images.githubusercontent.com/77196303/136719751-b9cd8703-32ba-4183-a6e7-5a17e80e4d11.png)

Hi Guo Rui, the issues in the screenshot provided here are not actually errors. This is the logger output when you run the testcases some of which are supposed to fail. 

If intellij, shows say 238/238 testcases passed for example, that means you're good to go.

**Comment by damithc** [comment]
> Hi Guo Rui, the issues in the screenshot provided here are not actually errors. This is the logger output when you run the testcases some of which are supposed to fail.
> 
> If intellij, shows say 238/238 testcases passed for example, that means you're good to go.

Yup, that's correct.

**Comment by qinguorui2001** [comment]
hi prof, it seems the final issue comes to java version, i used java 11 they used java 11.09
![image](https://user-images.githubusercontent.com/77196303/136724884-bd423e07-5ce3-4ffc-9a8f-63915bb61e49.png)
![image](https://user-images.githubusercontent.com/77196303/136724896-e2fd1292-c2a1-49d3-bc87-84d559d709d3.png)

**Comment by qinguorui2001** [comment]
which is supposed to use?

**Comment by damithc** [comment]
> which is supposed to use?

Any variation of 11 should be fine. 

@qinguorui2001 Some follow up questions:
* Were you ever able to run all tests locally?
* If yes, can you check past commits in the master branch to see at which commit the problem started happening? If you found such a commit, you can share the link to that commit (in your team repo) here so that others can take a look.

**Comment by marcuspeh** [comment]
> sorry,prof, when i build this happened ![image](https://user-images.githubusercontent.com/77196303/136701720-8ad0a7a9-b2f3-467e-b908-4b736d0e177e.png)

Do u have the link to the branch/repo to the exact codes you are running?

**Comment by qinguorui2001** [comment]
sorry the issue fixed,  my team member pushed a bug...

**Comment by marcuspeh** [comment]
> sorry the issue fixed, my team member pushed a bug...

What caused the issue? Perhaps if the others faced the same issue, they will be able to solve it too with this thread

**Comment by qinguorui2001** [comment]
this is project specific, just like the formatting of command is incompatible with saving the command and its related tests
