### ISSUE TITLE
tP: Are we allowed to deprecate test cases that are not useful to our modification of AB3?

### ISSUE THREAD

**Issue by didymusne** [nus-cs2103-AY2122S1/forum#306]
Hi! Wanted to check if we could deprecate test cases that are not useful to our modification of AB3. Or more generally, can we deprecate test cases? If so, under what scenario would you advise for us to deprecate existing test cases. 

Thank you!

**Comment by damithc** [comment]
> Hi! Wanted to check if we could deprecate test cases that are not useful to our modification of AB3. Or more generally, can we deprecate test cases? If so, under what scenario would you advise for us to deprecate existing test cases.

@didymental Yes, you may discard existing test cases if they are not useful. It is up to you to decide which ones are not useful.

**Comment by didymusne** [comment]
@damithc noted, thank you so much!
