### ISSUE TITLE
IP: Possible cause for different behaviors of Jar file on different PC

### ISSUE THREAD

**Issue by jackgugz** [nus-cs2103-AY2122S1/forum#308]
I just came to realise that my IP JAR file will have different GUI behaviors on others' PC than mine. 
Mine works just fine as shown:
![image](https://user-images.githubusercontent.com/75773252/136885519-6a96a4e2-fa17-4940-a4af-7a37257261a7.png)

But the dialog will be stacked on top and overlap each other when my friends try it, as shown below:
![image](https://user-images.githubusercontent.com/75773252/136885601-88bd99cc-b27c-4650-843c-19cc7f5a2c79.png)

I do not quite understand what can be the cause of this discrepancy as it is the exact same jar file we are using, just on different pc. 

thank you so much if you have anything in mind!

**Comment by marcuspeh** [comment]
Could it be the height?  Perhaps if you try to make the GUI height smaller on ur PC, it might be the same

**Comment by jackgugz** [comment]
> Could it be the height? Perhaps if you try to make the GUI height smaller on ur PC, it might be the same

Hi Marcus, may I clarify with you what height are you referring to specifically?

**Comment by marcuspeh** [comment]
> > Could it be the height? Perhaps if you try to make the GUI height smaller on ur PC, it might be the same
> 
> Hi Marcus, may I clarify with you what height are you referring to specifically?

What i meant was the GUI window height. Maybe ur friends made the GUI window shorter so the contents overlapped

**Comment by jackgugz** [comment]
> > > Could it be the height? Perhaps if you try to make the GUI height smaller on ur PC, it might be the same
> 
> > 
> 
> > Hi Marcus, may I clarify with you what height are you referring to specifically?
> 
> 
> 
> What i meant was the GUI window height. Maybe ur friends made the GUI window shorter so the contents overlapped

Oh it was not the height of the window. He did not alter the window height
