### ISSUE TITLE
How to interpret Codecov Report

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#309]
Sample Codecov Report:

![image](https://user-images.githubusercontent.com/40263305/136890356-40f78481-3486-42e0-b2c8-5fa2185403de.png)

In particular, what do 'hits', 'misses' and 'partials' mean?

**Comment by pss-coder** [comment]
Hi @AllardQuek,

you can take a look at the code coverage site [here](https://docs.codecov.com/docs/about-code-coverage)

Extracting the main bit from the site it basically states: 

`hit` indicates that the source code was executed by the test suite.

`partial` indicates that the source code was not fully executed by the test suite; there are remaining branches that were not executed.

`miss` indicates that the source code was not executed by the test suite.

I hope this helps.

**Comment by AllardQuek** [comment]
Thanks @pss-coder!
