### ISSUE TITLE
IP: Different behaviors of Jar file on different PC

### ISSUE THREAD

**Issue by jackgugz** [nus-cs2103-AY2122S1/forum#310]
* Development environment:

1. IntelliJ version: 2021.2.2 community edition runtime version: 11.0.12+7-b1504.28 amd64 VM: OpenJDK 64-bit Server VM by JetBrains s.r.o
2. java version: openjdk 11.0.7 2020-04-14 LTS OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)
3. OS:  Windows 10 Pro 20H2

Description of the problem can be found here:
https://github.com/nus-cs2103-AY2122S1/forum/issues/308
The jar file can be downloaded from here:
https://github.com/jackgugz/ip/releases

update: 
attempt in changing jdk to oracle version as follows but still does not work
```
java 11.0.11 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)
```

**Comment by damithc** [comment]
FYI, I'm facing the said problem in my PC (Win 10)
java version (oracle) "11.0.11" 2021-04-20 LTS

**Comment by kouyk** [comment]
Hi @jackgugz, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). I see that you have installed the Amazon build of JDK, would you like to uninstall your current JDK and switch to either [Oracle](https://www.oracle.com/sg/java/technologies/javase/jdk11-archive-downloads.html) or [AdoptOpenJDK](https://adoptium.net/releases.html?variant=openjdk11&jvmVariant=hotspot)'s version? Those might be more commonly used and less prone to compatibility issues, not to mention more update-to-date as well.

Personally on my laptop I'm running the following and I don't observe the same issue. Might be a useful datapoint to help find the cause.

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)
```

**Comment by jackgugz** [comment]
> Hi @jackgugz, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). I see that you have installed the Amazon build of JDK, would you like to uninstall your current JDK and switch to either [Oracle](https://www.oracle.com/sg/java/technologies/javase/jdk11-archive-downloads.html) or [AdoptOpenJDK](https://adoptium.net/releases.html?variant=openjdk11&jvmVariant=hotspot)'s version? Those might be more commonly used and less prone to compatibility issues, not to mention more update-to-date as well.
> 
> Personally on my laptop I'm running the following and I don't observe the same issue. Might be a useful datapoint to help find the cause.
> 
> ```
> openjdk version "11.0.11" 2021-04-20
> OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
> OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)
> ```

@kouyk Hi Senior!! Thank you so much for the help!! I tried what you suggested to me and changed my jdk to oracle one so my configurations are now 
```
java 11.0.11 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)
```

However, it still does not solve the problem according to my friend originally with the problem.

**Comment by kouyk** [comment]
> However, it still does not solve the problem according to my friend originally with the problem.

Hmm, at least we have ruled out one possibility with a buggy JDK. I would assume you compiled another JAR file after the installation and remove all traces of the old one such that Intellij doesn't use the wrong version. Base on that assumption, perhaps we can confirm whether this is a JAR file issue or a code issue. You might want to ask your friend to run your iP from source on their device and see if they encounter similar problems.

**Comment by samuelfangjw** [comment]
Hi @jackgugz, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems).

Can I check if you have solved this issue already? Your latest [commit](https://github.com/jackgugz/ip/commit/ed3cbe90e4a82832db8f2bc279a30f5cd82f07bf) to the master branch seems to have fixed the issue for me.

**Comment by jackgugz** [comment]
> Hi @jackgugz, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems).
> 
> Can I check if you have solved this issue already? Your latest [commit](https://github.com/jackgugz/ip/commit/ed3cbe90e4a82832db8f2bc279a30f5cd82f07bf) to the master branch seems to have fixed the issue for me.

Hi @samuelfangjw Senior! Thank you for checking in with me! Yes with help from @Chang-CH, he spotted an erroneous line from the `DialogBox `Class: 
`this.setPrefHeight(dialog.getMaxHeight());`
After we remove this line, the code seems to perform consistently across machines.
But we are still thinking what could be the possible causes of this inconsistent behaviours from different PC and that is why I have not made an update here. 
My guess is that the `this` is interpreted differently at different machines as either the `DialogBox` or the `Vbox`. For the former, it simply sets the `preHeight` of the `DialogBox`  to be `MaxHeight` of the `Label` text, whereas for the latter, the entire `Vbox` is changed and therefore causes all the messages to stack up in the shrunk space of `Vbox`. 
However, even if this is the case, I am not exactly certain of what could be the trigger of this issue on different machines. 
What do you think of the explanations and the causes Samuel? 😄

**Comment by Chang-CH** [comment]
Basically, @jackgugz had the `dialog` label set to a max height of 1.7976931348623157E308 in the [fxml file](https://github.com/jackgugz/ip/blob/master/src/main/resources/view/DialogBox.fxml). `this.setPrefHeight(dialog.getMaxHeight())` set the preferred height of `DialogBox` to that value. The compatibility issue was likely due to the behavior of `prefHeight`.

**Comment by samuelfangjw** [comment]
> But we are still thinking what could be the possible causes of this inconsistent behaviours from different PC and that is why I have not made an update here.

Great that you managed to solve it! In future, do try to update the post so that others have more information to help.

> My guess is that the `this` is interpreted differently at different machines as either the `DialogBox` or the `Vbox`.

I believe this is unlikely. `this` refers to a `DialogBox` object on both the bugged and fixed versions for me. 

> Basically, @jackgugz had the `dialog` label set to a max height of 1.7976931348623157E308 in the [fxml file](https://github.com/jackgugz/ip/blob/master/src/main/resources/view/DialogBox.fxml). `this.setPrefHeight(dialog.getMaxHeight())` set the preferred height of `DialogBox` to that value. The compatibility issue was likely due to the behavior of `prefHeight`.

Agree with this! Not sure what the issue is, but seems to be related to `prefHeight` and how this affects the calculation of where to place each child object in the layout. For some reason things start to go haywire once this value gets too large.
