### ISSUE TITLE
Running tp in CLI mode

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#311]
The [tp constraints](https://nus-cs2103-ay2122s1.github.io/website/admin/tp-constraints.html#recommendation-cli-first) recommends for a CLI-first approach, but I had some trouble figuring out how to run the TP without the GUI. Has anyone done this before?

Seems like the MainApp does all the setup but this is tied to the UI.

**Comment by damithc** [comment]
@NicolasCwy in this context, CLI != Text-UI
The GUI is already a CLI application as it's primary mode of input is text commands.

**Comment by NicolasCwy** [comment]
@damithc I see prof thanks for the clarification!
