### ISSUE TITLE
UML activity diagram: Is this type of nested parallel paths correct?

### ISSUE THREAD

**Issue by fans2619** [nus-cs2103-AY2122S1/forum#313]
Is something like this correct in an activity diagram? Or it must be simplified? <br>
![SoWkIImgAStDuTBGqbJGrRLJiBMrTJ844bmWZb90Ob5YJavgZe9ZSabcVfw2eH8NJ94HI14NJ3bShp5ElKO8lIOWHJ3L2bXL6wEgHhKMp0EwcCiXDIy5w7e0](https://user-images.githubusercontent.com/68739475/137060758-b687f792-8bc4-464c-a0d0-ec38bf0a82ec.png)

**Comment by damithc** [comment]
@fans2619 While not incorrect, I can't see a reason for doing it this way, as it can be misleading at first glance (two things happening in parallel? oh wait, it's actually three things happening in parallel).

**Comment by fans2619** [comment]
Ah okay. Maybe it should be simplified then. Thanks prof!
