### ISSUE TITLE
Failing CI because of "no newline at EOF" error

### ISSUE THREAD

**Issue by BenjaminLHR** [nus-cs2103-AY2122S1/forum#314]
Hi everyone,

For the tp, our team is failing CI due to a "no newline at EOF" error for our json files.

> ERROR:../bin/src/test/data/JsonGameBookStorageTest/invalidAndValidGameEntryGameBook.json:18: no newline at EOF.

![image](https://user-images.githubusercontent.com/48859735/137085917-52a567de-005a-4e02-a0f8-438628e7c957.png)

We're not sure why this error is happening.
Firstly, line 18 is not the last line of this file. 
Secondly, we already have a new line after the last line of our file.

**Comment by vimuthm** [comment]
Hi, I can't seem to reproduce the same issue on local, but I can see that CI is indeed failing on your team branch. 

One thing I notice is that the path given in the error is actually `..bin/src/test/../..` and not the actual file you have open in the screenshot. This means the checkstyle seems to be running against a compiled version somehow, and I'm not sure if this is intended usage.

Edit:

I notice that the issue starts from the commit `Finish second round of checkstyle fix` :

![image](https://user-images.githubusercontent.com/62249192/137095200-652ffcc9-cafb-4fcc-ab3b-1c646eb952a5.png)

I suspect [this](https://github.com/AY2122S1-CS2103T-W13-3/tp/blob/54cf247b324ef5dd122573d86277d269d69747f9/build.gradle#L21) line addition might be affecting the checkstyle runs by github actions

**Comment by BenjaminLHR** [comment]
Hi Vimuth, those are really sharp observations! We'll look into the issue!

**Comment by pss-coder** [comment]
Hi @BenjaminLHR, not too sure regarding your failing CI. But in IntelliJ there is a setting that could prevent you from getting the "no newline at EOF" error. 

I managed to stop having that error so far after enabling that setting.
Go to `intelliJ preferences > Editor > General > enable ensure every saved file ends with a line break`.

Here is a screenshot:
I hope it helps. 😄 

![Screenshot 2021-10-18 at 11 13 39 AM](https://user-images.githubusercontent.com/22881285/137663968-88f6f957-7932-4127-a643-7957ff54888f.png)
