### ISSUE TITLE
Java CI issue where one of the checks do not run

### ISSUE THREAD

**Issue by wilburrito** [nus-cs2103-AY2122S1/forum#315]
Hey folks, has anyone encountered a problem when merging their PRs where one of the CI checks just does not run? It has been about 30 minutes since I made the PR and it still says it is "Queued -- Waiting to run this check..."

![62cdfd5aee29350c9e1e066f89a40a5d](https://user-images.githubusercontent.com/77230639/137090986-34ef4c63-2a52-499b-8a14-a6179158d8ab.png)
.

Any advice on this would be greatly appreciated!

**Comment by damithc** [comment]
@wilburrito Could be a temporary issue on GitHub Actions. Try re-running (if you have admin access) or push an empty commit to trigger CI again.

**Comment by simonjulianl** [comment]
Hi facing this issue too, checking from this page https://www.githubstatus.com/, everything seems to work fine from github side  but the `windows-build` failed, even after changing explicitly to various windows version (e.g. `windows-2016`, `windows-2019`)

**Comment by bharathcs** [comment]
Same here, its just the windows runner that is failing to build. And there's an update from github on the issue: [We are investigating reports of degraded performance for GitHub Actions](https://www.githubstatus.com/incidents/81lpnf07bm1q)

**Comment by wilburrito** [comment]
Hey guys, might wanna try rerunning those checks now. Seems to be working again. @bharathcs @simonjulianl 

Let me know if it is working for you, then I can just close this issue.

**Comment by fans2619** [comment]
Thanks for the update!

**Comment by simonjulianl** [comment]
yup working perfectly for me now @wilburrito

**Comment by wilburrito** [comment]
Ok for me the issue has resurfaced (as of 11:38AM, 14/10/2021), do you have any issues right now? @simonjulianl

**Comment by wilburrito** [comment]
Ok guys, false alarm. I had to rerun the checks 2 times for it to work, so try rerunning the checks if you guys have any issues. Consider this matter closed.
