### ISSUE TITLE
Are JavaFX warnings counted as bugs, even if it does not actually affect the application? 

### ISSUE THREAD

**Issue by hmanhduc2k** [nus-cs2103-AY2122S1/forum#316]
Hi everyone, I have a question with regards to this error here when I run the code:
```
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5f3f7cad'
```
Basically, there is nothing wrong with our application, logically and front-end wise, at least so far. However, this warning keeps popping up, which might be due to me importing an external library for use with JavaFX. Does it count as a bug even if users are not affected by it, and in general, what actually counts as a bug?
On another note, anyone knows how to suppress the above warning? I have tried the class path adding solution but that doesn't seem to work as well, considering that AB3 is not modular based.
Thanks for any help!

**Comment by damithc** [comment]
@hmanhduc2k we will not penalize this warning, if it is caused by AB3 not using modules.

**Comment by hmanhduc2k** [comment]
Thank you Prof!
