### ISSUE TITLE
How to prevent merges if the CI does not pass?

### ISSUE THREAD

**Issue by sivayogasubramanian** [nus-cs2103-AY2122S1/forum#317]
In the master branch protection rule, there is this section
![image](https://user-images.githubusercontent.com/53614454/137120262-8aa22aee-f11f-4685-984b-b33f4de1a506.png)

According to [this post](https://stackoverflow.com/questions/58654530/how-to-reject-a-pull-request-if-tests-are-failed-github-actions#:~:text=The%20best%20way%20to%20%22reject,selecting%20your%20workflow%20as%20required.) the workflow file should appear here. Why does it not appear and has any team managed to figure out a way to prevent merges if CI fails?

**Comment by vimuthm** [comment]
Search for the individual names of the jobs (workflows)!

Our team rules look like this for reference:

![image](https://user-images.githubusercontent.com/62249192/137122491-0122d56a-e1ac-41fa-99fc-54a5a3270745.png)

**Comment by sivayogasubramanian** [comment]
@VimuthM Thanks!
