### ISSUE TITLE
Cannot load font

### ISSUE THREAD

**Issue by marcuspeh** [nus-cs2103-AY2122S1/forum#318]
Hi everyone, 

Does anyone else encounter this issue? My teammates and I encountered this issue since we forked AB3 and we are unsure of how to solve this.

We are using Windows 10 and MacOs (Intel version). All our device are using Java 11

![image](https://user-images.githubusercontent.com/54053213/137252809-9c3df71e-99bc-446f-b8ce-90eb002d0389.png)

**Comment by damithc** [comment]
@marcuspeh _All_ your team members?

**Comment by marcuspeh** [comment]
> @marcuspeh _All_ your team members?

Nope sorry. I mean 3 out of 5 of us have this issue.

**Comment by damithc** [comment]
> Nope sorry. I mean 3 out of 5 of us have this issue.

I see. Hmm... what's common among you three? Do you all three have spaces (or other special characters) in the project path?

**Comment by marcuspeh** [comment]
Thanks Prof. I realise the issue with all 3 of us was because our project path contains space.
