### ISSUE TITLE
Requesting Permission to use JFoenix library

### ISSUE THREAD

**Issue by mrmrinal** [nus-cs2103-AY2122S1/forum#320]
## Library

JFoenix (http://www.jfoenix.com/)

## Purpose

We intend to use this library to create an enhanced table that allows for editing, grouping and filtering, and to create a Tab Sidebar.

## License

Apache License
http://www.jfoenix.com/documentation.html#License

**Comment by damithc** [comment]
Approved. As always, use at your own risk :-)
