### ISSUE TITLE
Requesting Permission to use TestFx

### ISSUE THREAD

**Issue by bharathcs** [nus-cs2103-AY2122S1/forum#321]
## Library

[TestFX](https://www.github.com/TestFX)

## Purpose

Automated GUI Testing (Like how AB4 does it)

## License

[TestFX license](https://testfx.github.io/TestFX/#license) is EUPL (FOSS type)

**Comment by bharathcs** [comment]
By the way Prof, if we use SE-EDU code in our codebase, do we have to attribute it like stated in the [website](https://nus-cs2103-ay2122s1.github.io/website/admin/appendixB-policies.html#policy-on-reuse) or is it not necessary because it came from the teaching team? 

We intend to use the structure and code from a number of files in the [`ab4/src/test/java/guitests/`](https://github.com/se-edu/addressbook-level4/tree/master/src/test/java/guitests) folder as a template and adapt it to our codebase.

**Comment by damithc** [comment]
Use of TestFx approved.
If you use code from AB4, it is better to acknowledge. But no need to acknowledge AB3.

**Comment by bharathcs** [comment]
Okay, thanks prof!
