### ISSUE TITLE
Error : Line separator causing ubuntu build fail

### ISSUE THREAD

**Issue by HalphasX** [nus-cs2103-AY2122S1/forum#323]
For tp, I tried updating the UserGuide.md. However, I encountered the following error on the CI for the ubuntu build :
`ERROR:../docs/UserGuide.md:1: prohibited \r\n line ending, use \n instead.`

I have tried to edit the UG so that it uses \n as the line separator (From `File > Settings > Editor > Code Style > Line Separator`), however when I tried PR-ing the file again I still encountered the same issue. Does anyone know how to fix this? Thank you!
![Screenshot (547)](https://user-images.githubusercontent.com/70026153/137620848-57bf0198-c26a-40b8-aca6-41816de8067e.png)

**Comment by bharathcs** [comment]
Hey there does this work for you: [Intellij IDEA: Change line separator for a file currently opened in the editor﻿](https://www.jetbrains.com/help/idea/configuring-line-endings-and-line-separators.html#e26fb78e)

**Comment by HalphasX** [comment]
> Hey there does this work for you: [Intellij IDEA: Change line separator for a file currently opened in the editor﻿](https://www.jetbrains.com/help/idea/configuring-line-endings-and-line-separators.html#e26fb78e)

It works perfectly. Thanks for the help! :)
