### ISSUE TITLE
CI checkstyle fails on `trailing whitespace` and `no newline at EOF`

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#324]
After editing the DeveloperGuide and pushing the changes in a PR, the CI for checkstyle starts failing (despite no changes being made regarding the error/warnings raised). 

Does anyone have any idea how to resolve [this](https://github.com/AY2122S1-CS2103-F09-3/tp/pull/151/checks?check_run_id=3923901326)?

![image](https://user-images.githubusercontent.com/40263305/137696538-a591ec7d-2d29-4c44-b69e-84596cbca470.png)

**Comment by SkyBlaise99** [comment]
I just looked at your DG, there are indeed trailing whitespace as shown [here](https://github.com/AY2122S1-CS2103-F09-3/tp/pull/151/files#diff-1a95edf069a4136e9cb71bee758b0dc86996f6051f0d438ec2c424557de7160bR521). Probably do a reformat on your DG

**Comment by AllardQuek** [comment]
They don't show up on Intellij though. I tried committing my changes for the DG and code separately and it works now. Thanks @SkyBlaise99!

**Comment by SkyBlaise99** [comment]
You can take a look at #314 the post by @pss-coder for automatically `adding line breaks at EOF` in Intellij. Intellij also offers a way to automatically `remove trailing whitespace` in `formatting` options. And all these can be linked to save by enabling `format on save` option

**Comment by AllardQuek** [comment]
Ah, thank you! 🙇‍♂️

**Comment by shermannws** [comment]
![image](https://user-images.githubusercontent.com/77196403/138300848-50448209-60ea-4d1a-9c31-e50e7f45ee78.png)

This settings work for me to overcome the `trailing whitespace` issue. Particularly, I used `All lines` instead of `Modified lines`. Try doing a force save after this settings has been applied.
