### ISSUE TITLE
What approach should we take with testing rapidly changing codebase?

### ISSUE THREAD

**Issue by huyuxin0429** [nus-cs2103-AY2122S1/forum#325]
Currently, our group has been making incremental changes to the core classes of the TP files. However, after each change, all of the test cases would have to be updated to reflect the new methods/functionalities of the changes (especially integration test code). Due to a large number of test cases, this process has been exhausting. I am wondering if there are better ways to still conform to testing/CI practices while reducing the effort required?

**Comment by andrewbaruch** [comment]
This may not be very useful, but what I do is the method recommended in IP. I would first change the code, then run the test and ensure all the parts I expect to fail is the ones that fails. This saves me quite a bit of time as compared to re-writing and thinking of all the changes first. Then, add the new test-cases as needed.

**Comment by damithc** [comment]
Some more ideas:
* When doing this kind of changes with widespread impact on tests, you can make the PRs slightly bigger than usual (i.e., do more in one PR). Change the code first, and update the tests lasts i.e., no need to update tests in every commit.
* When there is a series of such changes to do but they are too much to do in one PR (or by one person), you can do them using what's known as a 'long-lived feature branch'. e.g., 
  1. start a new branch in your team repo e.g., `major-overhaul`, to serve as the _long-lived feature branch_
  2. do the series of changes as a series of PRs against the above branch, not the master branch. These PRs don't need to update the tests.  You can merge those PRs even if the tests are failing. This will not break the product as these PRs are not in the master branch yet.
  3. After the functional code has been changed as needed, do one more PR to update the tests (and possibly, docs). After merging this PR, the feature branch should pass CI as well.
  4. Merge the feature branch to master, either directly, or as another PR form the feature branch to the master branch.
