### ISSUE TITLE
how do you add  "throws" to a lambda function ?

### ISSUE THREAD

**Issue by Zzhiwei** [nus-cs2103-AY2122S1/forum#326]
I am using stream to  check the validity of an array of student indices
and if an index is not valid, I want to throw the exception and pass the buck.
However, it gives an error as intellij suggests I wrap the lambda function body in a try catch block.
```
 studentIndices.stream().forEach(index -> {
      if (index.getZeroBased() >= lastShownStudentList.size()) {
          throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
      }
  });
```

How do i pass the buck outside i.e. add 'throws' keyword to a lambda function?

**Comment by vimuthm** [comment]
The `forEach` method takes a parameter of type `Consumer` . This Java interface's abstract `accept` method is not defined to throw exceptions. That should be why IntelliJ forces you to catch the thrown exception without allowing propagation. 

One way to go about this (probably overkill), is to first externally create a sub-interface (is this a word?)  of `Consumer` that overrides the `accept` method to one that can throw exceptions. Then simply type-casting your current consumer to this new interface should do it. 

Check out [this SO post](https://stackoverflow.com/questions/18198176/java-8-lambda-function-that-throws-exception)

But personally, I would just not streamify it and use a loop;

```
for (int x : studentList) {
            if (x.getZeroBased() >= lastShownStudentList.size()) {
                throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
            }
}
```

**Comment by Zzhiwei** [comment]
@VimuthM That would probably be an overkill, looks like I should just use loops
