### ISSUE TITLE
Usage scenarios in implementation documentation

### ISSUE THREAD

**Issue by eezj35** [nus-cs2103-AY2122S1/forum#327]
Hi prof @damithc, for updating of the developer guide, is it compulsory to have descriptions and diagrams for the usage scenario, as in the undo operation documentation in the un updated developer guide?

**Comment by damithc** [comment]
@eezj35 You can decide yourself. The criteria to use is if such documentation will be useful to the target audience of the DG i.e., future developers.  So, the answer will be yes for some cases and no for others.

**Comment by eezj35** [comment]
> @eezj35 You can decide yourself. The criteria to use is if such documentation will be useful to the target audience of the DG i.e., future developers. So, the answer will be yes for some cases and no for others.

ok thanks for the clarification prof!
