### ISSUE TITLE
How to get UI to respond to changes in model?

### ISSUE THREAD

**Issue by Justinhoejj** [nus-cs2103-AY2122S1/forum#328]
* I have implemented a method that processes and return a list of person sorted by birthdays.
* The UI successfully displays this list on initial load. 
* Subsequent edits or add command updates the addressbook person card but does not update the birthday reminder card.
* Question: What should my implementation be like if i want the UI (in this case birthday reminder card) to update when a person in the address book is updated?
* I have tried tracing the following method in PersonListViewCell which is the method that runs when the person changes but am unable to find any meaningful usages.

```java
class PersonListViewCell extends ListCell<Person> {
        @Override
        protected void updateItem(Person person, boolean empty) {
            super.updateItem(person, empty);

            if (empty || person == null) {
                setGraphic(null);
                setText(null);
            } else {
                setGraphic(new PersonCard(person, getIndex() + 1).getRoot());
            }
        }
    }
```

My implementation is as follows i have added  a new FilteredLis of birthdayRemindners
![image](https://user-images.githubusercontent.com/68779715/138039105-854b3830-b78e-4faa-92b1-855fb6f8d56b.png)

Code for the UI aspect. Copy of the personList and card UI code.
![image](https://user-images.githubusercontent.com/68779715/138039777-385cf66e-a35d-4d76-98d2-a09d9a2d592c.png)

![image](https://user-images.githubusercontent.com/68779715/138039391-eaba1979-b110-4993-89de-b6b842fac9f3.png)

Attached pull request 

For code relating to UI with the defaults filteredList as a placeholder:
https://github.com/AY2122S1-CS2103-F09-4/tp/pull/81

For code relating to logic:
https://github.com/AY2122S1-CS2103-F09-4/tp/pull/85

Been stuck on this for a few hours now. Would appreciate any advice or new direction to explore. 🥲

**Comment by charliemoweng** [comment]
So you have two lists of Persons, one is the regular one, one is for those with birthday reminders. When you add/edit a Person in the regular list, the Person in the birthday reminder list should also change, but it does not. Am I correct? 
You may want to find out whether the problem is with the UI or the logic. When you add/edit a Person, does it change in the birthday list, just that it's not shown in UI? Or is it not added/updated at all, which means the logic is missing?

**Comment by Justinhoejj** [comment]
> So you have two lists of Persons, one is the regular one, one is for those with birthday reminders. When you add/edit a Person in the regular list, the Person in the birthday reminder list should also change, but it does not. Am I correct? 

Yes your understanding of the problem are correct, I have tested that both of them share the same person by using a == comparator to compare memory addresses. Unless the address book creates a new person completely when it edits?

> You may want to find out whether the problem is with the UI or the logic. When you add/edit a Person, does it change in the birthday list, just that it's not shown in UI? Or is it not added/updated at all, which means the logic is missing?

The problem is likely with the logic for "listening". When reading the developer guide it says that the UI listens to the model. But I cannot identify the code that support this mechanism of UI listening to the model. Hence the question of how does the UI respond to changes in the model?
![image](https://user-images.githubusercontent.com/68779715/138043384-54ea31d2-54cf-41d9-813f-94e99e3cb194.png)

**Comment by marcuspeh** [comment]
> Yes your understanding of the problem are correct, I have tested that both of them share the same person by using a == comparator to compare memory addresses. Unless the address book creates a new person completely when it edits?

Iirc address book creates a new person to replace the original object. I cant exactly remember how it works but its something like adding or replacing a new object in the underlying list will make the ui update

**Comment by Justinhoejj** [comment]
> adding or replacing a new object in the underlying list

I see can I clarify the meaning of underlying list, does it refer to the list in the model manager or the list in the addressbook or somewhere deeper?

**Comment by marcuspeh** [comment]
> > adding or replacing a new object in the underlying list
> 
> I see can I clarify the meaning of underlying list, does it refer to the list in the model manager or the list in the addressbook or somewhere deeper?

For ab3, if you trace through the codes, you will realize that the order goes like this:
1. MainWindow.java gets filtered list from Logic.java
2. LogicManager gets the filtered list from Model.java
3. ModelManager returns a filtered list that is stored in it. But how about the data in the filtered list? ModelManger got the innner list from AddressBook.java
4. AddressBook return UniquePersonList.asUnmodifiableObservableList()
5. Now, this unmodifiable observable list comes from the internalList in UniquePersonList.java

So, you can see that the `filteredList` has a `UnmodifiableObservableList`. This `UnmodifiableObservableList` will update whenever the `internalList` updates. This update will kinda update the `filteredList` and the UI will show it up. 

I dont really know exactly how this FilteredList and ObservableList works but thats how AB3 updates the UI

**Comment by charliemoweng** [comment]
Just to add on what @marcuspeh mentioned, `internalList` is `FXCollections.observableArrayList()`. And if you go and follow the docs, it actually says something like this:
<img width="822" alt="Screenshot 2021-10-20 at 4 12 09 PM" src="https://user-images.githubusercontent.com/68073477/138054264-442cd8f6-7c79-4d28-a7ec-8cb9d236556a.png">
[Here](https://docs.oracle.com/javase/8/javafx/api/javafx/collections/package-summary.html) is the link to the java docs for that package. Can take a look.

**Comment by Justinhoejj** [comment]
I see, thanks a lot for the insights @charliemoweng @marcuspeh I will look into the internal list, and work from there!

**Comment by Justinhoejj** [comment]
Had a look at ObservableList and indeed as long as changes are made to the observable list the UI. The UI updates successfully now thank you all for the advice!
