### ISSUE TITLE
how to change the observable list

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#329]
hi,
at the start of project, how do we change the content of an observable list? set all and clear of observable list gives me unsupported operation exception,though the java orcale said it's ok.
![image](https://user-images.githubusercontent.com/77196303/138079354-e6e025e1-a63a-4b44-bc27-fcece585d7ae.png)
![image](https://user-images.githubusercontent.com/77196303/138079393-28dfad8f-f9ad-4253-bcd3-ebb9e6a4f36b.png)
![image](https://user-images.githubusercontent.com/77196303/138079421-0c7331e6-f650-4540-b487-a2db2ecb553f.png)

![image](https://user-images.githubusercontent.com/77196303/138079603-5409528f-56cc-46c8-b697-0d75a181e69f.png)

**Comment by charliemoweng** [comment]
`FilteredList` and `ObservableList` are two different things.
[Here](https://docs.oracle.com/javase/8/javafx/api/javafx/collections/ObservableList.html) is the docs for ObservableList.
[Here](https://docs.oracle.com/javase/8/javafx/api/javafx/collections/transformation/FilteredList.html) is the docs for FilteredList.

**Comment by marcuspeh** [comment]
FilteredList and ObservableList is different. FilteredList is not able to be modified, neither is UnmodifiableObservableList. However, you can modify ObservableList. For ab3, its in the UniquePersonList class

**Comment by qinguorui2001** [comment]
thx marcus!
