### ISSUE TITLE
Ref frame for class diagram?

### ISSUE THREAD

**Issue by marcuspeh** [nus-cs2103-AY2122S1/forum#330]
Hi all, does anyone know what is the standard way of breaking up a class diagram if it is too complicated? Could we do something like this to show that ViewPanel belongs to Ui?
![image](https://user-images.githubusercontent.com/54053213/138109355-2fd62ff9-2fa8-4403-bd51-860fb7ec90f1.png)

**Comment by damithc** [comment]
> Could we do something like this to show that ViewPanel belongs to Ui?

Yes @marcuspeh that works.

**Comment by marcuspeh** [comment]
> > Could we do something like this to show that ViewPanel belongs to Ui?
> 
> Yes @marcuspeh that works.

Alright thanks Prof
