### ISSUE TITLE
Mass update Issues to new milestone💡

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#335]
1. Select all issues (top left checkbox)
2. Select new milestone (under milestones tab)

![telegram-cloud-photo-size-5-6307766602619268544-y](https://user-images.githubusercontent.com/40263305/138314937-4cce7be5-419c-4b8a-ae30-c8423f73e525.jpg)

**Comment by charliemoweng** [comment]
Thanks Allard!
