### ISSUE TITLE
Unable to merge a PR due to failing tests

### ISSUE THREAD

**Issue by Agentum07** [nus-cs2103-AY2122S1/forum#336]
Hello everybody, for my tP I opened a PR to push a feature.
The PR passed all tests in intelliJ, however the ubuntu build says that it fails to tests. When I run the two tests in intelliJ, they pass. I am stumped, please help. 
[This](https://github.com/AY2122S1-CS2103T-F12-1/tp/pull/54) is the PR.
[This](https://github.com/AY2122S1-CS2103T-F12-1/tp/pull/54/checks) is the CI tab containing the logs.

**Comment by damithc** [comment]
@Agentum07 `gradlew test` passes on your computer? Which OS are you using?

**Comment by andrewbaruch** [comment]
First of all, it seems that you have conflicts in your PR `SmartNusParser`. You should fix this first.

**Comment by andrewbaruch** [comment]
Next, your branch seems to be behind the master branch. I recommend fetching, pulling, then merging to the branch to replicate the issue.

**Comment by andrewbaruch** [comment]
On that note, also make sure you want to merge from your rep and not the branch you made on the organsation. (Sorry for the piece by piece comment)

**Comment by Agentum07** [comment]
Hi @damithc , I am using windows 10.
I updated one class and everything works.

@LeopardMerkava 
1. Yes I saw the merge conflicts, thank you for pointing that out.
2. That was not the issue.
3. Yes, there was a problem with how my remotes were set up. I fixed it now!

The issue has been resolved, I am not quite sure it exactly was.
