### ISSUE TITLE
Intellij cannot resolve other classes

### ISSUE THREAD

**Issue by yucheng11122017** [nus-cs2103-AY2122S1/forum#338]
Hello! I am not sure why I am getting this error where almost all my import statements are lit up in red. According to intellij, it says it "Cannot resolve symbol ___". For some reason, it can still run though. 
Would appreciate any help with this thank you!
![image](https://user-images.githubusercontent.com/77204346/138440793-5563856f-234f-493f-811d-28ea44ad96a2.png)

**Comment by vimuthm** [comment]
I had the exact same issue, but for just one package. Invalidating cache and restarting worked for me, hope it does for you too!

**Comment by yucheng11122017** [comment]
@VimuthM Sorry what do you mean by invalidating cache and restarting? Thank you!

**Comment by vimuthm** [comment]
Sorry for not being specific, it's an option that can be found here;

![image](https://user-images.githubusercontent.com/62249192/138448273-f09e3ef9-52d9-473c-8fda-d91eed8dc9ee.png)

**Comment by yucheng11122017** [comment]
@VimuthM Thank you so much you are legit a life saver!

**Comment by charliemoweng** [comment]
Encountered the same problem and managed to solve it using the solution you suggested. Thank you!
