### ISSUE TITLE
Use of Generic class/Monad in AB3 for carrying additional information from logic to UI components

### ISSUE THREAD

**Issue by hmanhduc2k** [nus-cs2103-AY2122S1/forum#339]
Hi guys, I have a question with regards to what is considered good programming practice in this case.

Basically, I wanted to carry additional information (other than feedback to users) in the CommandResult class, and this additional information can be of any types, might be another String, might be a list,.. Because of that, the class will have another field that stores an Optional object to wrap the additional information mentioned above.

Because of that, I wanted to use Optional<? extends Object> to wrap the information. However, is it considered acceptable, considering that I'm not using raw type and using <? extends Object> is too generalized, and that might not be a good design pattern (considering that anyone can pass null in)? What are the upsides and downsides of using Optional<? extends Object> as a local final field and as parameter in CommandResult?

Much appreciate any help :D

**Comment by bharathcs** [comment]
Not sure if this would fit your use case, but we chose to add an additional field to `CommandResult` that contains the necessary method calls and passing the required parameters (in your case, a string or list etc). Its a fairly clean way to cover any possible side effect on Ui that we want to happen on execution. Here's an example of how it could look like:

```java
public class CommandResult {
  private final Consumer<Ui> uiAction;
  CommandResult(String feedbackToUser, Consumer<Ui> uiAction) { /*...*/ }
}
```

So if you need to pass a string to a particular method `changeTitle` in `Ui`:
```java
public class ChangeTitleCommand {
  public CommandResult execute() {
    // ...
    String newTitle = "jsfsdfsd";
    return new CommandResult(feedback, ui -> ui.changeTitle(newTitle));
  }
```

So if you need to pass a List<Integer> to a particular method `takeNewNums` in `Ui`:
```java
public class ChangeTitleCommand {
  public CommandResult execute() {
    // ...
    List<Integer> nums = List.of(1,2,3);
    return new CommandResult(feedback, ui -> ui.takeNewNums(nums));
  }
```

Then when you actually execute the `CommandResult`, just remember to run the `uiAction.accept(ui)` to perform the logic.

**Comment by SkyBlaise99** [comment]
Maybe you can create a generic class to wrap the object you want to pass in, and use `requireNonNull()` to reject for `null` inputs?

``` java
import java.util.Objects;

public class Information<T> {
    private final T info;

    public Information(T info) {
        this.info = Objects.requireNonNull(info);
    }

    public T getInfo() {
        return info;
    }

    // other methods
}

```

**Comment by hmanhduc2k** [comment]
I see, creating a new generic class is also the approach I'm doing for my case as well. 
Thanks for all of you guys' help, the opinion is really useful for my case. :)
