### ISSUE TITLE
💡 Fixing trailing whitespace errors (IntelliJ & ./runtest.sh)

### ISSUE THREAD

**Issue by bharathcs** [nus-cs2103-AY2122S1/forum#34]
If you are getting test failures using the `runtest.sh` tool that look something like this:
```
2c2
<  ____        _
---
>  ____        _     
Test result: FAILED
```

It could be due to trailing spaces being removed by IntelliJ automatically. (If you select the text above you'll see the second line has spaces after the last underscore but the first doesn't.)

I originally put the spaces in for _`expected.txt`_ and only realised later that IntelliJ was trimming all trailing white spaces every time I saved the file. Unfortunately `diff` (in Mac at least) does not support ignoring trailing white spaces so I went to IntelliJ and disabled their function.

In IntelliJ, go to Preferences > Editor > General:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/7360964/129831501-1e25128b-d5fd-494a-8c1e-fa1e524c9e2b.png">

**Comment by zzybluebell** [comment]
Thx a lot. it fixed by this way
