### ISSUE TITLE
Plant UML visibility character style

### ISSUE THREAD

**Issue by wangpalex** [nus-cs2103-AY2122S1/forum#340]
Hi, is there a way to let plant UML to display the visibility characters as it is (i.e. +, -, #, ~) instead of the fancy icons?
<img width="629" alt="Screen Shot 2021-10-25 at 19 25 30" src="https://user-images.githubusercontent.com/49505301/138686924-13ab6f3c-90bf-403b-9a60-1efc634ae0fc.png">

**Comment by NicolasCwy** [comment]
Can check out [this](https://plantuml.com/class-diagram)

```
@startuml
skinparam classAttributeIconSize 0
class Dummy {
 -field1
 #field2
 ~method1()
 +method2()
}

@enduml

```

On mobile currently apologies for the short response

**Comment by wangpalex** [comment]
Thanks, I got it.
