### ISSUE TITLE
UML Format for initialising a class in a reference frame

### ISSUE THREAD

**Issue by chrus-chong** [nus-cs2103-AY2122S1/forum#342]
Hi all, my group was intending on using reference frames within our sequence diagrams to avoid a situation where the diagram is too cluttered and messy. However, we were wondering how we should represent the creation of a class object within a reference frame. 

![image](https://user-images.githubusercontent.com/85006125/138843916-c695d146-48aa-47a1-b5a7-4f8ec887d107.png)

For example, in the above picture, an instance of CreateGroupCommand is created within the reference frame (AweParser creates a CreateGroupCommandParser which creates a CreateGroupCommand so we want to leave these Low level details in a reference frame). A method from the CreateGroupCommand is subsequently called which is why it needs to be shown in this sequence diagram. Any help will be appreciated. Thank you very much.

**Comment by damithc** [comment]
@chrus-chong `ref` frames are tricky to use in some situations. Consider other ways of achieving the same. For example, you can show it as a normal constructor call, but instead of `CreateGroupCommand()`, you can use the text `create a CreateGroupCommand` and use a UML note to explain that details of the object creation is given in a separate diagram.

**Comment by chrus-chong** [comment]
Hi prof @damithc , thank you for your advice. We were wondering if the following diagram would be acceptable in line with what was suggested(even though AweParser actually creates a CommandGroupCommandParser which creates a CreateGroupCommand)?

![image](https://user-images.githubusercontent.com/85006125/139190184-c683c12d-5de6-4192-a6d1-edb47f0df4f9.png)

**Comment by damithc** [comment]
> Hi prof @damithc , thank you for your advice. We were wondering if the following diagram would be acceptable in line with what was suggested(even though AweParser actually creates a CommandGroupCommandParser which creates a CreateGroupCommand)?
> 
> ![image](https://user-images.githubusercontent.com/85006125/139190184-c683c12d-5de6-4192-a6d1-edb47f0df4f9.png)

I guess this is fine too. My earlier suggestion was to omit the frame altogether and use the comment only.

**Comment by chrus-chong** [comment]
thank you for your advice prof!
