### ISSUE TITLE
TP constraint: human editable file

### ISSUE THREAD

**Issue by huizhuansam** [nus-cs2103-AY2122S1/forum#345]
One of the constraints mentioned is that the program data should be human editable. Is it OK to have the program data be in an encrypted format, but also give the option for users to import data from a user-editable format? 

I would argue that it does not go against the spirit of the constraint because what would eventually become the program data is still very much user-editable.

**Comment by damithc** [comment]
Yes, it's fine @huizhuansam, as long as users can easily export the data to a user-editable format, and import the edited data back to the app.
