### ISSUE TITLE
W11.3c: Invalid values appear as a bigger font size instead of underlined

### ISSUE THREAD

**Issue by Smanmos** [nus-cs2103-AY2122S1/forum#346]

**Comment by Smanmos** [comment]
I'm not sure why I can't label this as a bug

**Comment by damithc** [comment]
> I'm not sure why I can't label this as a bug

@kawaiigabrielneko You have to choose the right issue template. Labels are attached to the issue template. Can't add/change labels afterwards.

Thanks for the bug report. Will fix soon.

**Comment by SkyBlaise99** [comment]
To add on, this part also seems to be repeated ([W11.7b](https://nus-cs2103-ay2122s1.github.io/website/schedule/week11/topics.html#design-modelling-modelling-behaviors-state-machine-diagrams))

![image](https://user-images.githubusercontent.com/69448615/139056935-fe499cb3-c88b-4c88-9d18-959ce4cc848b.png)

**Comment by damithc** [comment]
Thanks @SkyBlaise99 Will fix soon.

**Comment by damithc** [comment]
I've fixed both. Closing ...
