### ISSUE TITLE
tp Dashboard (indv) progress shows undone task after reorganising the docs/images directory

### ISSUE THREAD

**Issue by shermannws** [nus-cs2103-AY2122S1/forum#348]
After reorganising our `docs/images` directory and specifically creating a subdirectory `docs/images/team` to store our team members' photos for the `AboutUs.md` page, our tp dashboard (individual) for week 7 for the task `photo` is marked as undone.

![image](https://user-images.githubusercontent.com/77196403/139181587-1e0fffda-2cce-4a03-891b-18104436dd32.png)
![image](https://user-images.githubusercontent.com/77196403/139181872-7453be55-5af7-417e-a5ef-282ee52a78d0.png)

Can we check if such reorganisation is acceptable for this tp?

**Comment by damithc** [comment]
> Can we check if such reorganisation is acceptable for this tp?

@shermannws the dashboard script expects the photos to be in specific location. It will not be able to detect the photo otherwise.

**Comment by shermannws** [comment]
Ok! Thanks Prof @damithc.
We will revert the changes accordingly!
