### ISSUE TITLE
LumiNUS Survey: tP code reuse declaration

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#349]
Hi prof,

For Q2, I assume AB3 is not part of the reusing that this question is intended to ask, since all our tPs are based on it?

![image](https://user-images.githubusercontent.com/69448615/139183186-796fbc62-3a02-4586-bed4-46e42b7e954c.png)

**Comment by damithc** [comment]
Yes, AB3 code is  not considered 'reused', as the code was already in the project by the time you started working on it.

**Comment by SkyBlaise99** [comment]
Alright thx for the clarification prof
