### ISSUE TITLE
git stash error

### ISSUE THREAD

**Issue by jiarong15** [nus-cs2103-AY2122S1/forum#35]
I tried stashing a particular commit with tag A with command git stash store -, "Storing A" A.
Subsequently tried retrieving it with git stash show A but was met with this error: 
fatal: 'A' is not a stash-like commit

May I check what is wrong?

**Comment by waynetee** [comment]
You may find this helpful
https://git-scm.com/docs/git-stash#Documentation/git-stash.txt-store
https://git-scm.com/docs/git-stash#Documentation/git-stash.txt-ltstashgt

**Comment by simonjulianl** [comment]
[this](https://stackoverflow.com/questions/59762143/recovering-dropped-stash-is-not-a-stash-like-commit) might help you besides the documentation that Wayne points out!

on a side note, I don't think git stash store is a command that is used unless you are doing scripting (like creating the stash manually and storing it), usually, to stash a commit, people would use git stash / git stash save / git stash push (or use Intellij VCS or SourceTree to prevent such error)
