### ISSUE TITLE
Possible issue with UserGuide Jekyll template for Tables

### ISSUE THREAD

**Issue by rish-16** [nus-cs2103-AY2122S1/forum#350]
Hey folks,

So my team is almost done with our final `UserGuide.md` and we ran into a slight problem. The tables don't render properly even they perfectly display on GitHub markdown preview as well as IntelliJ. 

The tables end up looking like so:
![image](https://user-images.githubusercontent.com/20137995/139300669-91bd2994-c3ca-4169-bcab-5cfc6e054497.png)

But, on GitHub and IntelliJ, they look like so:

![image](https://user-images.githubusercontent.com/20137995/139300775-f4e643c2-8a50-43dc-85be-9249e8d32c25.png)

![image](https://user-images.githubusercontent.com/20137995/139300805-e19f7908-d115-4252-919e-df0ff48e32c8.png)

Any advice on how we can render them properly would be nice. You can find our UG here: [https://ay2122s1-cs2103-w14-1.github.io/tp/UserGuide.html#command-summary](https://ay2122s1-cs2103-w14-1.github.io/tp/UserGuide.html#command-summary).

CC Prof. @damithc 

Thank you!

**Comment by damithc** [comment]
@rish-16 tip: compare these broken tables with those that render properly e.g., the tables in the original AB3 render properly

![image](https://user-images.githubusercontent.com/1673303/139303373-a5f54bb4-8d04-4aa3-b405-801834030db3.png)

**Comment by AllardQuek** [comment]
Maybe try adding a new line below your headers?

**Comment by Jai2501** [comment]
Put a line break between the heading and where the table starts in the markup code.

Same issue as : [Issue #240](https://github.com/nus-cs2103-AY2122S1/forum/issues/240)

**Comment by rish-16** [comment]
Yup, I think we were able to fix it. Thank you Prof Damith _et al._ !!!
