### ISSUE TITLE
In-line git blame 💎

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#352]
Find [this](https://plugins.jetbrains.com/plugin/7499-gittoolbox) pretty useful for figuring who made what changes when 🐞  

![image](https://user-images.githubusercontent.com/40263305/139354293-d70f7649-094c-4cbf-8efd-f733dab312dc.png)

**Comment by charliemoweng** [comment]
Thanks Allard for the tip!
