### ISSUE TITLE
How does the GUI update?

### ISSUE THREAD

**Issue by Jay-luozhijie** [nus-cs2103-AY2122S1/forum#354]
In address book, when I type in find or list command, there is update in person list in GUI.  I can see that when command is typed in command box, it calls execute and then update the model, but when the model has been updated, I can't see it notifying the GUI. Then how does the GUI know that it need to be updated?
![image](https://user-images.githubusercontent.com/77223932/139377457-c3cd9de1-a5c4-4952-8e70-c10e87a50606.png)

**Comment by hmanhduc2k** [comment]
The CommandBox object is constructed in MainWindow I believe, which takes in the CommandExecutor (which in this case is the method execute() of type CommandResult) from the MainWindow. 
When you call in the method handleCommandEntered(), it executes the command not through CommandBox but through MainWindow instead - so the GUI updating is not done through CommandBox, it is rather done in MainWindow through the resultDisplay.setFeedbackToUser(text).

**Comment by Jay-luozhijie** [comment]
But isn't this only updating the command result? I think it doesn't update the person list panel.  when I delete `resultDisplay.setFeedbackToUser(text)` , and try find command, the person list can still be updated

**Comment by charliemoweng** [comment]
I'm not very sure what exactly you are asking but is it related to issue #328? Maybe you can take a look at that one.

**Comment by hmanhduc2k** [comment]
> But isn't this only updating the command result? I think it doesn't update the person list panel. when I delete `resultDisplay.setFeedbackToUser(text)` , and try find command, the person list can still be updated

That's because resultDisplay is setting the result, and not updating the list - it's done at the model when logic is executing the command.

As for person list update and changing, you can try modifying the two classes StudentCard and StudentListPanel to see the changes on them - model is interacting with these two classes directly.

I hope this helps.

**Comment by Jay-luozhijie** [comment]
Yeah it helps! Thank you!
