### ISSUE TITLE
Request to use Markdown FX (for a past v1.2 feature) and TestFX for GUI testing.

### ISSUE THREAD

**Issue by hmanhduc2k** [nus-cs2103-AY2122S1/forum#356]
## Library

[MDFX](https://github.com/JPro-one/markdown-javafx-renderer)
[TestFX](https://github.com/TestFX/TestFX)

## Purpose

Use for parsing Markdown File into a JavaFX view.
Use for GUI testing of the view

## License

[Apache](https://github.com/JPro-one/markdown-javafx-renderer/blob/master/LICENSE)
[EUPL](https://github.com/TestFX/TestFX/blob/master/LICENSE.txt)

## Rationale

Hi Prof, I deeply apologize for this late request and for my carelessness, due to myself not knowing that I have to request for permission before using any library. I initially thought that it is sufficient to acknowledge usage of third party library as a form of reusing code (which is detailed on week 12 website), but I have never known that I need to request a permission to use it until recently when I asked my tutor about using TestFX, reminding me that I have used another third party library before but haven't submitted any request.

May I ask you to grant a permission? What do I need to do at the moment considering that the feature I implemented using the library is on v1.2 rather than at the moment?

Thank you for your help.

**Comment by damithc** [comment]
Approved.
