### ISSUE TITLE
What happens when the user does not read the UG properly and reports a bug?

### ISSUE THREAD

**Issue by sivayogasubramanian** [nus-cs2103-AY2122S1/forum#357]
For example, 
![image](https://user-images.githubusercontent.com/53614454/139518540-4c11fbc8-362a-41aa-820d-2acae41f7d2f.png)
Our application has a lot of features and hence our UG is long by default. Does that mean it reduces testability?

Another example would be,
![image](https://user-images.githubusercontent.com/53614454/139518591-5a6c18d1-9bbe-4fbb-b1c1-072825b9241b.png)
Our application's user guide has a very detailed section on this `add-o` command
![image](https://user-images.githubusercontent.com/53614454/139518662-b4ba8582-2bb6-481c-b504-ee5c6207b3da.png)

**Comment by damithc** [comment]
@sivayogasubramanian It is entirely up to you how you use bugs received via the PE-D for the benefit of your project.

>Once you have received the bug reports for your product, you can decide whether you will act on reported issues before the final submission v1.4. For some issues, the correct decision could be to reject or postpone to a version beyond v1.4.
Reminder: There is no penalty for any of the bugs you received in the PE-D.

More details https://nus-cs2103-ay2122s1.github.io/website/admin/tp-pe.html#pe-d-after-the-session

**Comment by sivayogasubramanian** [comment]
@damithc Alright thanks prof!
