### ISSUE TITLE
JSON Edit and bug reporting

### ISSUE THREAD

**Issue by darrenhoon** [nus-cs2103-AY2122S1/forum#358]
Hi Prof @damithc , was wondering if editing the json file itself and causing the application to show unexpected outputs constitute as the application having a bug.

**Comment by zacharylwy** [comment]
Yeah our group also received a similar bug report Is this considered a bug...?

**Comment by damithc** [comment]
![image](https://user-images.githubusercontent.com/1673303/139523303-475e47e5-9fbd-4803-8971-6450afc9d02a.png)

What AB3 says:
![image](https://user-images.githubusercontent.com/1673303/139523328-63ed00fd-74ac-4f11-b249-c0699e819aab.png)

**Comment by darrenhoon** [comment]
thanks for the clarification Prof!
