### ISSUE TITLE
Labels not appearing on PED issues

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#359]
Is it possible to get labels for the raised issues so we can categorise them easily?

![image](https://user-images.githubusercontent.com/40263305/139529259-67d607e9-ff96-4065-b9b8-9625d4283aca.png)

**Comment by damithc** [comment]
@AllardQuek The bot transferring the issues is not a member of your team org, and therefore, will not be able to add labels to issues in your repo. That's why the labels are given at the bottom of the issue body, for your reference.

**Comment by AllardQuek** [comment]
I see, thank you!
