### ISSUE TITLE
What happens if you push commits with the wrong github account?

### ISSUE THREAD

**Issue by e0543403** [nus-cs2103-AY2122S1/forum#36]
Hello, I accidentally pushed a large number of commits using the wrong github account. Will this affect the grade for my iP and if so what should I do?

**Comment by damithc** [comment]
@e0543403 Were the commits done by you i.e., the Git author name (not the GitHub username) of the commits is yours?

**Comment by e0543403** [comment]
The Git author names should be mine but the github usernames are different.

**Comment by damithc** [comment]
> The commits were done by me, however, how to tell whether the git author names are different?

Did you set your git username as explained in https://nus-cs2103-ay2122s1.github.io/website/admin/tools.html#tool-git-for-revision-control ?

You can see the Git author name when you examine a commit. For example, this is how it looks in SourceTree

![image](https://user-images.githubusercontent.com/1673303/129847446-645dbcbe-044a-4a16-ab63-7cf06957f7e3.png)

It should be fine as long as the Git author name is yours, as we use the Git author name to determine the authorship.

**Comment by e0543403** [comment]
I think it changed when I swapped accounts.

**Comment by damithc** [comment]
Should be fine @e0543403 Try to use the same GitHub account and same Git author name in future.

**Comment by e0543403** [comment]
Thank you prof. I shall do that.
