### ISSUE TITLE
Further clarifications about what can be changed for v1.4

### ISSUE THREAD

**Issue by wpinrui** [nus-cs2103-AY2122S1/forum#360]
There are a quite a few bug reports about various aspects of our application (TutorAid - aimed at private tutors for tracking contacts, lessons and progress) and my team is concerned if we can do the following:

### Simplifying a feature
**Current implementation:** Add / remove a link between any number of students and any number of lessons
**Proposed implementation:** Add / remove a link between one student and one lesson
The rationale here is that the original feature seems rather buggy and most private tutors do not need to frequently add or remove students from lessons

### Add sanity checks for fields
**Current implementation:** Lesson timing can be any string
**Proposed implementation:** Lesson timing has to be of the format HH:MM - HH:MM, (dayOfWeek). Is this allowed? It was identified as a feature flaw by several testers as users can enter irrelevant things into the Timing field.

### Remove feature and edit scope
Our payment tracking system is very limited in functionality (doesn't reset at the end of the month). This is an oversight in our development process and it's too late to add this functionality now. Our program may not satisfy the value proposition identified (as payment tracking was one of the points identified). Are we allowed to remove this feature and exclude payment tracking from the scope?

**Comment by damithc** [comment]
@wpinrui my answers below:

> ### Simplifying a feature
> **Current implementation:** Add / remove a link between any number of students and any number of lessons **Proposed implementation:** Add / remove a link between one student and one lesson The rationale here is that the original feature seems rather buggy and most private tutors do not need to frequently add or remove students from lessons
> 

OK, assuming you are simply getting rid of the buggy parts of an existing feature.

> ### Add sanity checks for fields
> **Current implementation:** Lesson timing can be any string **Proposed implementation:** Lesson timing has to be of the format HH:MM - HH:MM, (dayOfWeek). Is this allowed? It was identified as a feature flaw by several testers as users can enter irrelevant things into the Timing field.

from https://nus-cs2103-ay2122s1.github.io/website/schedule/week12/project.html
![image](https://user-images.githubusercontent.com/1673303/139538241-9ae9c5fb-e23d-4dad-bb7d-e0b6669e5612.png)


> ### Remove feature and edit scope
> Our payment tracking system is very limited in functionality (doesn't reset at the end of the month). This is an oversight in our development process and it's too late to add this functionality now. Our program may not satisfy the value proposition identified (as payment tracking was one of the points identified). Are we allowed to remove this feature and exclude payment tracking from the scope?

OK to remove features (and reduce scope)

**Comment by wpinrui** [comment]
Thank you for the clarification! 😃
