### ISSUE TITLE
Clarification for PE

### ISSUE THREAD

**Issue by marcuspeh** [nus-cs2103-AY2122S1/forum#361]
Hi all, 

From my understanding, bugs that cannot be replicated is not considered bugs. How do we flag those bugs out?

And do we run the app in assertion mode `-jar -ea` or just standard `-jar`?

**Comment by damithc** [comment]
@marcuspeh To confirm, you are asking about PE and not PE-D?

**Comment by marcuspeh** [comment]
> @marcuspeh To confirm, you are asking about PE and not PE-D?

Yup that's right

**Comment by damithc** [comment]
> From my understanding, bugs that cannot be replicated is not considered bugs. How do we flag those bugs out?

@marcuspeh unlike the PE-D, the PE has two more phases, for dev team to respond for bugs received and for the tester to counter-respond. Both phases use CATcher. In the [developer response phase](https://nus-cs2103-ay2122s1.github.io/website/admin/tp-pe.html#pe-phase-2-developer-response-2), you'll be able to apply a `response.CannotReproduce` label to such issues.

> And do we run the app in assertion mode `-jar -ea` or just standard `-jar`?

No need to use `-ea` mode, as end users are not expected to use that mode.

**Comment by marcuspeh** [comment]
> > From my understanding, bugs that cannot be replicated is not considered bugs. How do we flag those bugs out?
> 
> @marcuspeh unlike the PE-D, the PE has two more phases, for dev team to respond for bugs received and for the tester to counter-respond. Both phases use CATcher. In the [developer response phase](https://nus-cs2103-ay2122s1.github.io/website/admin/tp-pe.html#pe-phase-2-developer-response-2), you'll be able to apply a `response.CannotReproduce` label to such issues.
> 
> > And do we run the app in assertion mode `-jar -ea` or just standard `-jar`?
> 
> No need to use `-ea` mode, as end users are not expected to use that mode.

Thanks for the clarification Prof
