### ISSUE TITLE
Feature which was added in v1.3 but without updating UG

### ISSUE THREAD

**Issue by xlzior** [nus-cs2103-AY2122S1/forum#364]
Hi Prof @damithc 

My team added a feature in v1.3b before PE-D. The PR for this feature's functional code was merged to master. However, due to an oversight, we did not merge the PR that updates the UG with instructions on how to use this feature. Hence, it was reported as a feature flaw (missing feature) during PE-D.

What should we do now? Are we allowed to add the feature into the UG at this point (which will look like a new feature although the functional code was merged last week)? Do we have to remove this feature?

Thank you

**Comment by damithc** [comment]
@xlzior please email me the links to the PRs in question.
