### ISSUE TITLE
Removing fixed cost in invoice

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#367]
Hi prof our app is currently generating an invoice with one of the rows being a fixed cost (a place holder). Would it be ok if we removed this row, since it is like removing part of a feature? One conditional would have to be added to the commands though.

**Comment by damithc** [comment]
@NicolasCwy I would like to know some more context about this feature. What does it currently do (give a screenshot) and why you want to remove it. You may email me directly as discussing it here might be disadvantageous to your team at the PE.

**Comment by NicolasCwy** [comment]
Sure prof
