### ISSUE TITLE
Changing command validation

### ISSUE THREAD

**Issue by Xiaoyunnn** [nus-cs2103-AY2122S1/forum#368]
Hi Prof,

Are we allowed to add command validation if it was reported as a bug by our tester in PE-D?

e.g. The tester reported that "next back back" or "month year day" are treated as valid "next" and "month" commands respectively even though the full string is not valid. So can we change command validation such that "next back back" or "month year day" will be considered invalid?

Thank you!

**Comment by damithc** [comment]
@Xiaoyunnn see if this applies:

![image](https://user-images.githubusercontent.com/1673303/139852441-b389e47d-09e4-4efe-a643-1ff142cae391.png)
