### ISSUE TITLE
Sourcetree unable to push to GitHub

### ISSUE THREAD

**Issue by tanjoewel** [nus-cs2103-AY2122S1/forum#37]
Hi everyone, I'm having issues pushing my commit into GitHub. When i try to push it it seems to work at first, but the push never goes through and when i press cancel this message appears:

<img width="592" alt="Screenshot 2021-08-18 at 2 44 13 PM" src="https://user-images.githubusercontent.com/88360651/129850988-5843534a-9440-41a3-9c9c-97205427da94.png">

I have tried looking online and other issues here for help but i havent seen this particular issue anywhere. Does anyone know whats wrong? Thanks in advance!

**Comment by marcuspeh** [comment]
Have you tried the things mention [here]?(https://github.com/nus-cs2103-AY2122S1/forum/issues/25)

**Comment by tanjoewel** [comment]
Thanks Marcus! I realized that this particular issue is because I accidentally set the protocol to SSH instead of HTTPS, but then when I changed it I ran into problems which the thread helped solve!
