### ISSUE TITLE
Explain code that makes use of external library in DG

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#370]
Should features that are largely based off external libraries be mentioned in the DG?

Asking this question as my feature (creating an invoice) mainly uses an external library and I am not sure if I should include it in the DG. I understand that for others in my group using my class, we are able to treat my code as a black box in our Sequence diagrams, but what about this feature on its own?

Here is a short code snippet
```
       // Initialize document
        PdfWriter writer = new PdfWriter(dest);
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);

        PdfFont font = PdfFontFactory.createFont(StandardFonts.TIMES_ROMAN);
        PdfFont boldFont = PdfFontFactory.createFont(StandardFonts.TIMES_BOLD);

        // Add headers and page numbers
        pdf.addEventHandler(PdfDocumentEvent.END_PAGE, new InvoiceNewPageHandler());

        // Add guest details
        Paragraph guestDetails = new Paragraph("Bill to: " + g.getName() + "\nRoom Number: " + g.getRoomNumber());
        guestDetails.setTextAlignment(TextAlignment.CENTER).setFont(boldFont);
        document.add(guestDetails);
```

**Comment by damithc** [comment]
> Should features that are largely based off external libraries be mentioned in the DG?

@NicolasCwy there is no rule against it. Whether to include it depends on whether you think the inclusion will help future developers (as they are the target audience for the DG).

**Comment by NicolasCwy** [comment]
Alright thanks prof!
