### ISSUE TITLE
The dependency between ParserUtil and Prefix in addressBook DG

### ISSUE THREAD

**Issue by Jay-luozhijie** [nus-cs2103-AY2122S1/forum#371]
ParserUtil doesn't use any prefix, all the parse commands in ParserUtil take in only a String, why does it depend on Prefix?
![prefix](https://user-images.githubusercontent.com/77223932/140066560-f56799c6-87d0-41df-b10c-fe7068a02116.jpg)
![prefix ParserUtil](https://user-images.githubusercontent.com/77223932/140066711-3c9bba6b-2520-47c8-aa51-8e0687d47481.jpg)
Is it because in XYZCommandParser, the input String for ParserUtil depends on Prefix?
![prefix in command Parser](https://user-images.githubusercontent.com/77223932/140067351-c2a651f9-2471-407a-9db7-91aa244467d8.jpg)
Then does it mean that ParserUtil also depend on ArgumentMultimap? But why is it not shown in the diagram?

**Comment by damithc** [comment]
Good catch @LuoZhijie-tom Looks like a bug in the diagram. Perhaps there was such a dependency at first but it got removed at some point. You can go ahead and remove it from the diagram.
