### ISSUE TITLE
Wondering why some UML sequence diagrams look much more blurry than others

### ISSUE THREAD

**Issue by BryannYeap** [nus-cs2103-AY2122S1/forum#373]
For example, this diagram is much bigger and clearer:
![image](https://user-images.githubusercontent.com/77266823/140293964-eb51524c-4431-42af-81cc-d47ecc9c2f69.png)

While this diagram is very small and blurry:
![image](https://user-images.githubusercontent.com/77266823/140293894-51477774-6819-40fe-adc5-c2adfa7706bb.png)

**Comment by BryannYeap** [comment]
I resolved the issue by saving the png from the [PlantUML server link](http://www.plantuml.com/plantuml/uml/pLLHRzis47xdhxWb3yiU7CjjWzf2PiHnuksXNequnHwoOM34iqIO8ZMIMkqM---JPBeHGtbUDWoeNaJTVVVTwRuZUMKirRRC1Vc6uOfBX0_BsxlVfk_VlR-3qwXv235hBWkgQGxND5cdMfMIJPLG6avdkwUDMMQKgOzSfh2Ymc3RDHNK6FXCe7fcIbgFfB5UAyrGtsSyMKkii8EMDKGlBMfKTbjWDrjj_Odc21FDgI1_jckP9BP2VmxudnhGk4BZ4Tub_bwYJD1Hpz4Ock94y5H2WjAYTYatDSkIVq8ONEnD2yfOtRceZNdPVosejZpX1PNsGASToJxNgyWdc7FPwFGpPpQ3YwYRUnyzY0vBt_BSu8gMmjxZnZQjo55QruuMgg39cgQuj5k1S8U9fJ8LI4Z66S9AAVkeDhkF7FD7r6RtaN2TrB3A2-zKoXCudGwdmzc45ArcdCIDRqvbbKAV03NGDi3fw-gPldaMCs5Cep7NIgqNL1iN65WFHqzLdbF9l63Vs1rxUPdKAep7lyY9JikwOVTgZP9_SZI1zMWDpx8Vm3ll7PfIs2R4ito9megXrgDf-rmn5DLyZTuEXeDdX8sl8NAeqKqK3Lxvg0ArKJ9UDAy6l5lkqK_f7dfZNxWOS8D9QV6CowAqtn6QMFu7jUZ1Y5ILHU3Anj3Wu7iueOo1xDzi1PLGz4TlHwFXnN00s6UrwHotMrLUfJdbuZnHEUZ-WWjb0Mr_LWe1bkS8fl_w8ef0z1VP3MpxRqu8ySghoWt79OQYNhZE1eK70OGa6ft76nuIG5r23mLnO3hpq_ca923eTVq6OVWt7D_-o1b32LHhzH6iWa8PRhcIO3C4XiPgjOMSwZLgU4HHWMf7BRHQDKj7NeSyKdtUKTL3rkJujQkw6Au_p6RLmJs_NIudFzpk9a3pDBCnKBTxJ3q6_yCC7DF5duEpB-MyK9Lnnp4GWtNhbiOXZf0mj1VMw8iSalZmWxz9DIuqhlW6JVKsAErB1_18QO7FxHXtZdJLwLmGkqMx8XT57EHOTWSFT-cH_dWRywneM3hxqkx8iMh-nVRz2dOhSJc2F-lSIzubu6iHe8C3kPMYTNlyWxwFtHKMGqQD6vf0j0P2o0xfInMA511JnluhiHj2xzhsi_a-bo488TvdcF50c9SglApr3iMmiziFbxtU8M4z-nLALkRYBm00)

The image is much bigger and clearer now.

**Comment by damithc** [comment]
@BryannYeap Our of curiosity, what did you use to generate the blurred image?

**Comment by BryannYeap** [comment]
> @BryannYeap Our of curiosity, what did you use to generate the blurred image?

I just right clicked the image in IntelliJ and pressed save.

**Comment by damithc** [comment]
> I just right clicked the image in IntelliJ and pressed save.

Got it. Thanks for the info @BryannYeap

**Comment by BryannYeap** [comment]
> > I just right clicked the image in IntelliJ and pressed save.
> 
> Got it. Thanks for the info @BryannYeap

No problem!
