### ISSUE TITLE
Possible JavaFX testing ?? TestFX

### ISSUE THREAD

**Issue by pss-coder** [nus-cs2103-AY2122S1/forum#374]
Hi everyone,

From #363 and if iirc from lecture, GUI Testing is quite a pain to do.
I tried looking up possiblities of having GUI Testing, and 1 which I came across specifically for JavaFX, was TestFX [here](https://github.com/TestFX/TestFX).

Not sure if we can use it, any thoughts prof @damithc?

There is also a medium article on how to get started (though the article is a couple years back, some things may have changed) [here](https://medium.com/@mglover/java-fx-testing-with-testfx-c3858b571320).

I understand it might be a little late introducing this, but I thought it might still be possible for any who are keen to try or wondering about it too. 😄 

`Also, wasn't too sure whether we could use TestFX, that's why I labelled this as a question and not a tip.`

**Comment by damithc** [comment]
FYI, [AB4](https://github.com/se-edu/addressbook-level4) uses TestFX to automate GUI testing.
I believe https://github.com/nus-cs2103-AY2122S1/forum/issues/363 is from someone trying to use TestFX in tP.

**Comment by pss-coder** [comment]
Oh wow, that's interesting, will take a look. Thanks prof!
