### ISSUE TITLE
Enum types in Sequence Diagrams

### ISSUE THREAD

**Issue by BryannYeap** [nus-cs2103-AY2122S1/forum#375]
I'm not sure how to represent a specific enum type in Sequence Diagrams, as I want to call a method from the enum type (and not a static method from the enum class itself). 

Lets say I have an enum called `ValidFilterInterviewArgs`, which contains the types PAST and FUTURE.
How to I represent ValidFilterInterviewArgs.PAST?

These are a few ones I was deciding between:

![image](https://user-images.githubusercontent.com/77266823/140336336-ebef309d-fc2a-4504-b48f-a6d529318fa8.png)

![image](https://user-images.githubusercontent.com/77266823/140336406-af456229-b86f-4f5c-9298-c28c233e3ce1.png)

Or should I just omit the type completely and do this:

![image](https://user-images.githubusercontent.com/77266823/140336778-a2f29895-3d28-4f19-9afd-9d5f3a83275a.png)

**Comment by damithc** [comment]
Enumerations having methods is a Java quirk. As far as I know, there is no standard way to show it.
If omitting `PAST` doesn't cause a loss of important information, you can go with the third one.

If you want to show `PAST` too, you can go with one of the two choices, but use it consistently across the whole project.

**Comment by BryannYeap** [comment]
Oh okay, thank you!
