### ISSUE TITLE
Do we need to include all commands in the implemention section of the DG?

### ISSUE THREAD

**Issue by junghon3709** [nus-cs2103-AY2122S1/forum#377]
It says that the implementation section should include noteworthy details about how commands are implemented. Does that mean that we do not have to include all commands, but rather just a subset of commands whose implementation details we feel should be highlighted to other developers?

![image](https://user-images.githubusercontent.com/50390582/140461778-0a8f21ba-a2e8-4190-8eca-3e899620fce2.png)

**Comment by damithc** [comment]
@junghon3709 that's correct. 👍

**Comment by junghon3709** [comment]
Alright thanks!
