### ISSUE TITLE
reference to Predicate class

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#378]
hi,
if one class has some reference to predicate class wrapped around Person object , is it ok to draw following to show association?
![image](https://user-images.githubusercontent.com/77196303/140505535-d2499ee1-59eb-4a1a-85ad-4b009e20da7c.png)

**Comment by damithc** [comment]
@qinguorui2001 did you mean `Predicate<Person>`?

You can use one of these:
```
class Predicate<Person>
class "Predicate<Person>"
```

![image](https://user-images.githubusercontent.com/1673303/140524083-3970f7ae-ddd0-4ea5-99bb-bc46792e7e8b.png)

**Comment by qinguorui2001** [comment]
yes, prof, i mean this, so could we draw the diagram i mentioned above to show this asscociation?

**Comment by damithc** [comment]
> yes, prof, i mean this, so could we draw the diagram i mentioned above to show this asscociation?

Hard to say as it's not entirely clear what you are trying to do. Perhaps you can  share the relevant code and the corresponding diagram?

**Comment by qinguorui2001** [comment]
![image](https://user-images.githubusercontent.com/77196303/140540566-5154c6ee-5088-4048-93cb-8521f2d31af5.png)
![image](https://user-images.githubusercontent.com/77196303/140540739-0fd7a1da-1638-4b29-a23d-d969bfe3b4c1.png)

hi,prof
for the class diagram, i have such, how could we draw the class diagram if i use the arrow to represent the association instead?

**Comment by qinguorui2001** [comment]
do we need to draw arrow from address book to predicate generic class with type parameter person?

**Comment by damithc** [comment]
> do we need to draw arrow from address book to predicate generic class with type parameter person?

Only if you think it is useful for a future developer reading the DG. If not, you can either show it as an attributes, or omit it entirely.

**Comment by qinguorui2001** [comment]
thx,prof
