### ISSUE TITLE
Use cases in development guide: To underline or not to underline?

### ISSUE THREAD

**Issue by kaixin-hc** [nus-cs2103-AY2122S1/forum#379]
According to the textbook: https://nus-cs2103-ay2122s1.github.io/website/se-book-adapted/chapters/specifyingRequirements.html#use-cases, use cases when referenced in other use cases should be underlined. However, markdown does not natively support underlining as underlining is generally used for links.

Should we use HTML to underline use cases when they are referenced, or should we adopt our own convention?

**Comment by damithc** [comment]
> Should we use HTML to underline use cases when they are referenced, or should we adopt our own convention?

@kaixin-hc Try using HTML.

**Comment by kaixin-hc** [comment]
Okay, we will do so. Thanks Prof!
