### ISSUE TITLE
Is it ok if we dont use enums for the A-Enums part?

### ISSUE THREAD

**Issue by eezj35** [nus-cs2103-AY2122S1/forum#38]
Is it ok if i dont use enums in any part of my code? since A-Enums says to use enums only if applicable

**Comment by chrus-chong** [comment]
Yes it is alright. You can take a closer look at the iP grading [here](https://nus-cs2103-ay2122s1.github.io/website/admin/ip-grading.html) but essentially it states that "Requirements marked as optional or if-applicable are not counted when calculating the percentage of deliverables."

**Comment by damithc** [comment]
> Yes it is alright. You can take a closer look at the iP grading [here](https://nus-cs2103-ay2122s1.github.io/website/admin/ip-grading.html) but essentially it states that "Requirements marked as optional or if-applicable are not counted when calculating the percentage of deliverables."

Yup. Thanks for the reply/pointer @chrus-chong
