### ISSUE TITLE
Alternate paths in activity diagrams: when to include?

### ISSUE THREAD

**Issue by nicole-luo-exe** [nus-cs2103-AY2122S1/forum#380]
Could I clarify that activity diagrams are only supposed to depict possible workflows for that particular scenario? I.e. in the case where one of the alternate paths will never be taken in that situation, should it be left out?
For example, should the "Throw TaskException" even be included here?
![Screenshot 2021-11-06 at 2 30 17 AM](https://user-images.githubusercontent.com/77181384/140560991-2bcd004e-ec72-4646-a1b6-9d29609c24e2.png)

**Comment by damithc** [comment]
@nicole-luo-exe it's up to you. The path is in the code for a reason, so it is fine to include in the diagram too. However, it is also fine to omit it if you think it is not that useful for the reader to see it.
