### ISSUE TITLE
tp DG use cases: how many should we have?

### ISSUE THREAD

**Issue by fans2619** [nus-cs2103-AY2122S1/forum#381]
The possible DG bugs section on the module website does not mention something like "important use cases missing". **Does this mean there is no need to have all use cases in DG? Can we skip some important use cases?**

![image](https://user-images.githubusercontent.com/68739475/140604285-e4a41c04-769b-4598-ad2d-ae013290861e.png)

**Comment by damithc** [comment]
@fans2619 Must contain all information that might be useful to future devs, which includes any important use cases. While it goes without saying, I'll add it in to the list to make it more explicit.

**Comment by fans2619** [comment]
Well, okay.
