### ISSUE TITLE
Workflow runs failing for MacOS only

### ISSUE THREAD

**Issue by chunweii** [nus-cs2103-AY2122S1/forum#382]
I was updating test cases for storage, which passed on my Windows machine, but when I pushed to Github, the workflow run failed due to `NullPointerException` for MacOS, but not for Windows or Ubuntu. None of my team members own a Mac. How do I even resolve such an issue? [See here](https://github.com/AY2122S1-CS2103T-W15-3/tp/runs/4125930672?check_suite_focus=true)

This is the line producing the `NullPointerException`:
`jsonAddressBookStorage.saveAddressBook(original, filePath);`

**Comment by damithc** [comment]
@chunweii Is [this](https://github.com/AY2122S1-CS2103T-W15-3/tp/pull/224/commits/e90c1cb334af55af8ac73cb0ef5a501757b95258) the commit that started failing first? Is this a new test or was it an existing test that passed before?

Normally, one would locate the commit that made the CI to fail then look at the diff of that commit to figure out what exactly caused the problem. For that to work, commits should be small, but this commit is too big to do that. 

One strategy you can try is to start a new PR but push one small commit at a time.

**Comment by chunweii** [comment]
Hi Prof, that was an old test that already existed in the original AB3. My changes were indeed too big to locate the exact problem.

Anyways, I found a few more bugs with regards to other parts of my project and somehow, the MacOS workflow succeeded. The mystery still remains.. why MacOS?
