### ISSUE TITLE
Request permission for third-party libraries

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#384]
#### License: [Apache License](http://opencsv.sourceforge.net/licenses.html)

**Comment by damithc** [comment]
@AllardQuek You are going to start using these libraries _now_?

**Comment by AllardQuek** [comment]
No, we started using them before v1.3 but only just saw the requirement that we should ask for permission on the forum. Hope it's not too late!

**Comment by damithc** [comment]
Approved.

**Comment by AllardQuek** [comment]
Thank you @damithc !
