### ISSUE TITLE
object deletion in UML

### ISSUE THREAD

**Issue by tianyue58** [nus-cs2103-AY2122S1/forum#385]
<img width="1063" alt="Screenshot 2021-11-07 at 8 32 18 PM" src="https://user-images.githubusercontent.com/77108843/140645349-63360f0a-5bbc-48a7-a35f-17272f359155.png">
Here is a screenshot of uml diagram in original ab3. May I check if we are supposed to include crosses to show deletion of other objects such as d and the command result? Thank you!

**Comment by damithc** [comment]
> Here is a screenshot of uml diagram in original ab3. May I check if we are supposed to include crosses to show deletion of other objects such as d and the command result?

If they are no longer referenced by other objects, you can show the `X`. Can still be omitted if you think it doesn't help the reader much.

**Comment by tianyue58** [comment]
Thank prof
