### ISSUE TITLE
Plantuml: How to name a component with generics

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#386]
Am trying to declare a `UiPart<Stage>` component, but it does not render in the preview. Does anyone have any tips on how to resolve this?

Tried removing the space between UiPart and <Stage> but still got the same result.

![image](https://user-images.githubusercontent.com/40263305/140645394-d6217708-834f-4bbe-8135-1df0c63d7f85.png)

**Comment by damithc** [comment]
It's actually rendered but everything is in white color.
![image](https://user-images.githubusercontent.com/1673303/140646095-65c9ba1a-2cc9-4a18-9483-0ce09dfc8f7e.png)

**Comment by AllardQuek** [comment]
How can I fix the alignment here? It seems the angled brackets are not showing too.

![image](https://user-images.githubusercontent.com/40263305/140647079-2169d63b-ff29-4775-972c-ff304ff1a125.png)

**Comment by damithc** [comment]
> How can I fix the alignment here? It seems the angled brackets are not showing too.

Isn't this how the type parameter to a generic class is supposed to be shown?

**Comment by AllardQuek** [comment]
I see, it looked a bit off to me. Thanks prof!
