### ISSUE TITLE
What happens if testers or users runs jar file in java 14 or other java version unknowingly?

### ISSUE THREAD

**Issue by pss-coder** [nus-cs2103-AY2122S1/forum#387]
Hi Prof @damithc , 

For my team tP, during testing, I realised the application crashes when I run the jar file application in java 14. How we knew this was because, in my terminal, I have 2 Java version 14 and 11 and initially the jar applications were running in the java version 14 and it crashes after a certain point, but not in java 11.

Should we then explicitly mention in our UG or DG, that testers or users wanting to run our application has to ensure that they are running the jar files on a java 11 jar version?? If so, do we need to also share in our UG how users can change their java version to version 11 in their terminals?

This is might be worrisome as users may highlight ours or even other groups application as broken if they can't even open the application in the first place. Only to not realise they are running in java 14 or some other version when running the jar file in their terminal or java launcher.

**Comment by pss-coder** [comment]
Also, I wasn't sure to label this as a bug or just a question.

**Comment by damithc** [comment]
@pss-coder Our PE instructions have that already. Any bugs reported caused by using other Java versions can be rejected.

![image](https://user-images.githubusercontent.com/1673303/140657166-0d28d5ac-d15f-4e15-809f-fa145f1a74be.png)

**Comment by pss-coder** [comment]
Oh okay, I see thanks again Prof!
