### ISSUE TITLE
Issue with TextUiTesting

### ISSUE THREAD

**Issue by Wilfredwongkc** [nus-cs2103-AY2122S1/forum#39]
Hello everyone, I am facing some issues with the part on TextUiTesting. 

I have prepared my input.txt file with multiple lines of inputs. However, when I run the .bat file, it only takes in the first line. 

Here's my "input.txt" file:
```text
todo borrow book
list
deadline return book /by sunday
event project meeting /at Mon 2-4pm
list
bye
```

This is my "actual.txt" file created:
```text
 ____        _        
|  _ \ _   _| | _____ 
| | | | | | | |/ / _ \
| |_| | |_| |   <  __/
|____/ \__,_|_|\_\___|

___________________________________________
Hello! I'm Duke
What can I do for you?
___________________________________________
___________________________________________
Got it. I've added this task:
	[T][ ] borrow book
Now you have 1 tasks in the list.
___________________________________________
```

Am I doing something wrong with the I/O redirection technique such that it only takes in the first line of input? Also, according to the recorded lecture video on testing, the "actual.txt" shows that input by the user but mine does not. Is that also normal?

Thanks!

**Comment by xlzior** [comment]
Did you reinitialise the scanner multiple times? It seems like this could be the same issue as #11

**Comment by Wilfredwongkc** [comment]
> Did you reinitialise the scanner multiple times? It seems like this could be the same issue as #11

Ah. It works now. Thanks for your help! Didn't realize it is the same issue as the issue that you directed me to due to the title naming.

> My actual.txt also does not show the user inputs. In the lecture video, it might be that the program prints out the user's command again which is why it shows up in actual.txt.

Oh ok. Thanks once again.
