### ISSUE TITLE
Which version of UG and DG are used during PE evaluation

### ISSUE THREAD

**Issue by Nature711** [nus-cs2103-AY2122S1/forum#390]
Hi prof, our team discovered a bug in DG after yesterday's submission deadline. We've just made the change, but the DG we submitted to LumiNUS yesterday was still the buggy one. We decided not to resubmit as the potential marks gained due to such refinement may not worth the marks deducted for late submission, but we'd like to know which version of DG is used during PE evaluation: is it the PDF version we submitted, or the latest version we updated to project website? 
Thanks a lot!

**Comment by damithc** [comment]
@Nature711 We use the version submitted to LumiNUS.

**Comment by Nature711** [comment]
OK I see, thanks prof!
