### ISSUE TITLE
[PE] Clarification on software allowed

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#391]
1. Regarding the allowed software, may I clarify if a PDF Reader like Notability is allowed?
Reason: I personally use it to read the textbook.

2. Additionally, for the allowed text editors, is Notion allowed as well?
Reason: I use it for my note-taking.

![image](https://user-images.githubusercontent.com/40263305/141046174-bfa5e0af-eb1e-4b35-a9de-678071acf527.png)

**Comment by damithc** [comment]
> 1. Regarding the allowed software, may I clarify if a PDF Reader like Notability is allowed?
>    Reason: I personally use it to read the textbook.

Yes, allowed, as long as it is used only for working with the PDF file locally. Please do not use any feature that involves communicating with other computers e.g., cloud storage.

> 2. Additionally, for the allowed text editors, is Notion allowed as well?
>    Reason: I use it for my note-taking.
> 
> ![image](https://user-images.githubusercontent.com/40263305/141046174-bfa5e0af-eb1e-4b35-a9de-678071acf527.png)

Similar to above, only if it is used for local text editing.

**Comment by AllardQuek** [comment]
Got it, thank you!
