### ISSUE TITLE
[PE] Clarification on Usage of GitHub Releases

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#392]
It is mentioned in the PE instructions not to visit GitHub. However, it is also mentioned later:

![image](https://user-images.githubusercontent.com/40263305/141046314-9c087940-d218-4901-b830-97320cd6e63b.png)

1. Can I confirm in this case we will not need to seek permission for this?
2. I didn't realize we could provide extra files to download on the releases page. Is it still allowed for teams to upload files to their releases page to help testers test a certain feature?

**Comment by damithc** [comment]
> It is mentioned in the PE instructions not to visit GitHub. However, it is also mentioned later:
> 
> ![image](https://user-images.githubusercontent.com/40263305/141046314-9c087940-d218-4901-b830-97320cd6e63b.png)

@AllardQuek Yup, the rule is 'visits GitHub is not allowed', except in the case mentioned above. Visiting other GitHub pages is still not allowed.

> * Can I confirm in this case we will not need to seek permission for this?

No need.

> * I didn't realize we could provide extra files to download on the releases page. Is it still allowed for teams to upload files to their releases page to help testers test a certain feature?

Even if you upload files to GitHub now, you will not be able to update the DG to point the tester towards those files.
Providing such extra files is rare, to be done only when unavoidable. e.g., to provide a big data file needed to activate a certain feature of the software.

**Comment by AllardQuek** [comment]
I see, thank you for clarifying prof!
