### ISSUE TITLE
Can I refer to my own notes (hardcopy or text file or PDF) during the PE?

### ISSUE THREAD

**Issue by xlzior** [nus-cs2103-AY2122S1/forum#394]
![image](https://user-images.githubusercontent.com/30801910/141058937-d633cf1f-b884-40d6-a0f8-7b4151ee71c3.png)

I would like to prepare a list of reminders for myself / list of things to try testing. This will either be a hardcopy sheet of paper, or a text file / PDF stored locally. Is this allowed?

**Comment by damithc** [comment]
> I would like to prepare a list of reminders for myself / list of things to try testing. This will either be a hardcopy sheet of paper, or a text file / PDF stored locally. Is this allowed?

Yes, that is perfectly fine @xlzior
