### ISSUE TITLE
Behavior of JAR file different from Intellij

### ISSUE THREAD

**Issue by Nature711** [nus-cs2103-AY2122S1/forum#396]
To prevent text overflow, our design limited the `Company Name` to 40 characters, which is exactly enough to fit into the Ui design to ensure the name won't be cut off. Below is a screenshot of running our product in Intellij. It is clear that the name `very very very very very long name` is within 40 characters and thus can be fully displayed. 

![image](https://user-images.githubusercontent.com/77217430/141610044-913d17ac-08e1-4a87-99c5-3b4f33c75ff8.png)

However, when we try to run the exact same command using the JAR version of our product, the name `very very very very very long name` gets cut off in the Ui display as shown in the screenshot below. 

![image](https://user-images.githubusercontent.com/77217430/141610166-eabc0e83-ed50-4fbd-8ccf-8c03b3fef17b.png)

We're really not sure why the behavior of JAR file is different from Intellij, and whether this should be considered as our feature flaw.

**Comment by damithc** [comment]
@Nature711 what matters to the user is the software behavior in the actual environment not the development environment. So, the product will have to be judged based on how it behaves normally, not how it behaves inside Intellij. 
But yes, it's curious why the behaviors differ.

**Comment by Nature711** [comment]
OK I see, thanks prof for the clarification!

**Comment by SkyBlaise99** [comment]
Is it because of the default window size? When the app first launches it follow the default window size as no `preference.json` is present. While on Intellij you might have resized the window sometimes before.

P.S. this is assuming you guys use the same as AB3
