### ISSUE TITLE
Content Question: Association vs Navigability vs Dependency

### ISSUE THREAD

**Issue by wpinrui** [nus-cs2103-AY2122S1/forum#399]
The textbook mentions that classes that are associated do not necessarily have a reference to each other, and if they do it is navigability. My question is: can there be an association in which neither side has navigability to the other, or is this just a dependency?

**Comment by adamozh** [comment]
Maybe its when both classes depend on each other, perhaps something like this?

```
class Man {
    marry(Woman woman {
        ...
    }
}
```

```
class Woman {
    marry(Man man {
        ...
    }
}
```

But not sure whether to draw this as 2 dependencies or a single association

**Comment by yucheng11122017** [comment]
Off the top of my head, can't really think of anything that will do this. Eg. if there is an association means it is stored within the fields and hence must have access to it. 
I think @moreTriangles example is more of a dependency rather than an association

**Comment by adamozh** [comment]
@yucheng11122017 is right, just noticed that the textbook mentions that dependencies like the one I mentioned (non-obvious / temporary reference) are not considered associations

**Comment by fans2619** [comment]
@wpinrui I'm guessing the focus of `classes that are associated do not necessarily have a reference to each other` is more on `each other` and that is why we use navigability? So from my understanding, an association requires at least one class has a reference to the other class? I'm also inferring from the dependency part but I'm not 100% sure. @damithc 
![image](https://user-images.githubusercontent.com/68739475/142392463-18f7ba99-5201-4823-99c2-00e98b7b4400.png)

**Comment by damithc** [comment]
> So from my understanding, an association requires at least one class has a reference to the other class?

Yes that is correct, at least for an implementation environment like Java where navigability is achieved using references. 
So, an association should be navigable in at least one direction, if not in both directions.

**Comment by fans2619** [comment]
Thanks prof

**Comment by wpinrui** [comment]
Thank you all!
