### ISSUE TITLE
Git conventions

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#4]
According to [Git conventions](https://se-education.org/guides/conventions/git.html), Add README.md is preferred than Added README.md. Is there some rational behind this because I find it more natural to write `I did this this this` as a comment for a commit.

**Comment by xlzior** [comment]
The reason I'm aware of for the preference for present tense is to be consistent with Git's automatically generated commit messages e.g. **Merge** branch 'XXX' into 'master'.

Although you're not alone in thinking past tense is more intuitive, I found this interesting [Stackoverflow thread](https://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages)

**Comment by VimuthM** [comment]
A quick google search shows that developers in general seem to be divided on this haha. One possible reason for using the imperative tense is that from the POV of a code reviewer/approver, the message will imply what will happen after merge.

I'm shifting towards the imperative, because it helps me keep it short and be more precise. Regardless of what you like, I think what's important is to maintain consistency in tense within a project.

**Comment by SkyBlaise99** [comment]
I see, thx guys.

**Comment by rish-16** [comment]
I spoke to some seniors last sem on this very topic who've interned at some great places. They've all told me to use imperative present tense. It seems to be the convention for a lot of Singapore-based companies and startups. A positive argument is that such commit messages are a lot more cleaner and concise. 

Check out this [article](https://chris.beams.io/posts/git-commit/) for more clarity!

**Comment by softmagnet** [comment]
hi just to confirm, using imperative present tense is only for subject line right, meaning in body i can still use past tense?

**Comment by damithc** [comment]
> hi just to confirm, using imperative present tense is only for subject line right, meaning in body i can still use past tense?

@softmagnet As of now, we have not imposed any conventions for git commit message. These conventions will be imposed in a later week. When that happens, these are the requirements to follow https://nus-cs2103-ay2122s1.github.io/website/admin/standardsAndConventions.html

As per that, it is optional to follow the given convention for the commit body.
