### ISSUE TITLE
test failures using the runtest.sh

### ISSUE THREAD

**Issue by tianyue58** [nus-cs2103-AY2122S1/forum#40]
Hi everyone! I encountered test failure when running runtest.sh. However, my output for EXPECTED.TXT and ACTUAL.TXT appears to be the same. I have already fixed the trailing whitespace issues in intellij as suggested by issue #34. 

I have tried running "cp ACTUAL.txt EXPECTED.txt" to copy the exact content over and the test failure can be solved. 

Attached is a screenshot of change occurred before and after I run "cp ACTUAL.txt EXPECTED.txt".

Just wondering what is the issue here and how to solve it. Any help appreciated!

<img width="904" alt="Screenshot 2021-08-19 at 12 54 44 PM" src="https://user-images.githubusercontent.com/77108843/130016350-2e228a3a-5a75-469e-be6f-7b28030d50f6.png">

**Comment by rohit0718** [comment]
you seem to have trailing whitespace in your print statements themselves https://github.com/tianyue58/ip/blob/master/src/main/java/Duke.java#L20.

**Comment by marcuspeh** [comment]
You might have print trailing whitespaces in your programme. So the actual have trailing white spaces but expected did not put trailing white space

**Comment by tianyue58** [comment]
thanks for the suggestions! I have removed the trailing whitespace in print statement on line 20, but the issue still exists. 

Here's the screenshot on my intelliJ after running runtest.sh
https://drive.google.com/file/d/1ffdY8SzaIKX6_ee77Xo11cLNZu0mqjg7/view?usp=sharing

**Comment by rohit0718** [comment]
this is cause u need to add a newline for ur last line!

**Comment by tianyue58** [comment]
> this is cause u need to add a newline for ur last line!

do i add a new line using "\n"? I tried this way, but it's still not working

**Comment by marcuspeh** [comment]
> > this is cause u need to add a newline for ur last line!
> 
> do i add a new line using "\n"? I tried this way, but it's still not working

Just press enter at the end of ur expected.txt

**Comment by rohit0718** [comment]
oops sry my bad! meant to say that the `EXPECTED.TXT` needs a new line

**Comment by tianyue58** [comment]
Thank you guys! It's finally working for me. I shall close the issue now.
