### ISSUE TITLE
Question about use case in AB3 DG

### ISSUE THREAD

**Issue by marcuspeh** [nus-cs2103-AY2122S1/forum#402]
Hi, for extension 3a, is it safe to assume that we cannot replace `use case resumes at step 2` with `use case resumes at step 3` at the extension at 3a. My logic is that putting use case resumes at step 3 seems like the program will always be stuck at step 3 unless the user enter a correct input.

And also, what's the reasoning behind `use case resumes at step 2`. Would it be better if it is simply `use case ends.` since it is the end of the use case after the error message?

![image](https://user-images.githubusercontent.com/54053213/141685836-7c26a1bf-b27f-446f-9c8a-fc478cfb8c35.png)

**Comment by yucheng11122017** [comment]
I thought it should be resume at step 3 actually according to currently implementation because yeah the use case will continue until the user enters the correct input or exits the use case all together.

**Comment by marcuspeh** [comment]
> I thought it should be resume at step 3 actually according to currently implementation because yeah the use case will continue until the user enters the correct input or exits the use case all together.

But if that is the case, shouldn't it be `use case ends`. since entering the correct output is kindof like entering the use case again?

**Comment by damithc** [comment]
@marcuspeh As @yucheng11122017, the current use case is written in a way it continues until a correct index is given.

> But if that is the case, shouldn't it be `use case ends`. since entering the correct output is kindof like entering the use case again?

Can, but not exactly the same. If you do that, steps 1 will have to be repeated every time. In the current way, they are not repeated. 

It's a choice the team have to make -- i.e., which way the flow of the interaction should be. Both are legitimate choices.

**Comment by yucheng11122017** [comment]
@marcuspeh I didn't see it as use case ends because the user just edits instead of reentering I guess haha

**Comment by marcuspeh** [comment]
> @marcuspeh As @yucheng11122017, the current use case is written in a way it continues until a correct index is given.
> 
> > But if that is the case, shouldn't it be `use case ends`. since entering the correct output is kindof like entering the use case again?
> 
> Can, but not exactly the same. If you do that, steps 1 will have to be repeated every time. In the current way, they are not repeated.
> 
> It's a choice the team have to make -- i.e., which way the flow of the interaction should be. Both are legitimate choices.

So just to clarify, if let's say there is no step 1 and 2, we have to use `use case ends` and not `use case resumes at step 3`?

**Comment by damithc** [comment]
> So just to clarify, if let's say there is no step 1 and 2, we have to use `use case ends` and not `use case resumes at step 3`?

@marcuspeh While that may be technically equivalent, given this is not code but meant for human readers, I think it depends more on whether you want the user to start over or keep trying upon entering an invalid index. The actual UI design might vary depending on which option you choose.

**Comment by marcuspeh** [comment]
> @marcuspeh While that may be technically equivalent, given this is not code but meant for human readers, I think it depends more on whether you want the user to start over or keep trying upon entering an invalid index. The actual UI design might vary depending on which option you choose.

> @marcuspeh I didn't see it as use case ends because the user just edits instead of reentering I guess haha

Alright. Got it! Thanks @damithc @yucheng11122017
