### ISSUE TITLE
PE: Will a tutor look at responses accepted?

### ISSUE THREAD

**Issue by fans2619** [nus-cs2103-AY2122S1/forum#403]
**For example, if a tester reported a bug as Low severity and the dev team accepted the bug as Low severity, will the tutor look at the bug later and change it to Medium severity?**

![image](https://user-images.githubusercontent.com/68739475/141692946-3e4855db-c3bd-43b5-92c5-57672669b7b6.png)

**Comment by damithc** [comment]
@fans2619 Only cases of the dev team and the tester disagreeing will be considered in the moderation phase.
Also note, 
![image](https://user-images.githubusercontent.com/1673303/141719187-110ada25-c20f-4688-a60e-ea28e1b4382c.png)

**Comment by fans2619** [comment]
Thanks!
