### ISSUE TITLE
Inputs required for PE bug #1816

### ISSUE THREAD

**Issue by limzk126** [nus-cs2103-AY2122S1/forum#404]
Hi teaching team,

Our team is not sure if this is considered a bug. The tester mentioned that if the user accidentally makes wrong inputs to a large JSON file, it would make the app almost '_unusable_' as the user has to scroll through thousands of LOC to find the error to fix it before he can launch the data properly. I think the tester is implicitly telling us that we should have given an error message to indicate which lines of code have an error in it so the user can direct himself to those lines. Are we actually required to do this or is this considered as a whole new functionality by itself?

**Note:** the behaviour of our current app when the JSON file format is invalid is same as AB3.

**Comment by damithc** [comment]
This is our stance:
![image](https://user-images.githubusercontent.com/1673303/141720493-f0579245-e1da-4c9c-8b58-6941c02b2d1f.png)

AB3 support:
![image](https://user-images.githubusercontent.com/1673303/141720564-cfcd75f4-f074-4a54-9ed8-099953121420.png)

i.e., Users are not required to edit the data file, and doing so is 'at your own risk'. Therefore, making the editing easier/better is optional. 
However, if your UG promises more support for editing the data file, or your app increases the need for the user to edit the data file, you'll have to increase the support for it too.
