### ISSUE TITLE
Inputs required for PE bug #5163

### ISSUE THREAD

**Issue by tanhuakun** [nus-cs2103-AY2122S1/forum#405]
I am unsure if this inconsistency is a legitimate bug, for example it may be implemented in a way that follows the model given since it is a suggestion for future implementation.

Link to [#5163](https://github.com/nus-cs2103-AY2122S1/pe-dev-response/issues/5163)

**Comment by damithc** [comment]
In this case, the tester is questioning why one is composition while other is not. Was it a deliberate design decision or a mistake in drawing the diagram? I know this diagram is from AB3, but it can still be flawed.
