### ISSUE TITLE
Inputs required for PE bug #4001

### ISSUE THREAD

**Issue by limzk126** [nus-cs2103-AY2122S1/forum#406]
As mentioned by Tester that some macOS users may encounter warning popups when double-clicking the application. Are we obliged to actually teach users how to resolve this problem, since this is an OS problem and there are many elements to the OS and we cannot possibly list all sorts of problems and provide solutions to all of them.

**Comment by damithc** [comment]
@limzk126 good to, but not required to (as this is a general OS issue).

**Comment by limzk126** [comment]
Thanks prof
