### ISSUE TITLE
What can be considered under "important user stories mssing"?

### ISSUE THREAD

**Issue by fans2619** [nus-cs2103-AY2122S1/forum#407]
Just using a random example here: sorting. If an app can sort persons both by name and by age, but DG only mentions sort by name in user story, is this considered "important user stories missing"? Or there are some other requirements for it to qualify as "important user stories missing"?

**Comment by damithc** [comment]
@fans2619 if it was important enough to be implemented, you can consider is important enough to be documented :-)
