### ISSUE TITLE
Documentation bugs relating to AB3 tutorials

### ISSUE THREAD

**Issue by kleonang** [nus-cs2103-AY2122S1/forum#408]
Are documentation bugs relating to the tutorials provided in the original AB3 repo (e.g. [`Tutorial: Tracing code`](https://se-education.org/addressbook-level3/tutorials/TracingCode.html)) considered in the scope of our PE?

**Comment by damithc** [comment]
For the DG, only the PDF file content are within the scope of the PE. If the bug is not inside the PDF file, it can be considered 'not in scope'

**Comment by kleonang** [comment]
@damithc Noted, thanks for the clarification!
