### ISSUE TITLE
Issue with Javac not recognise still persist

### ISSUE THREAD

**Issue by Gordon25** [nus-cs2103-AY2122S1/forum#41]
u need to add java binaries to your path. check out https://stackoverflow.com/questions/7709041/javac-is-not-recognized-as-an-internal-or-external-command-operable-program-or.

_Originally posted by @rohit0718 in https://github.com/nus-cs2103-AY2122S1/forum/issues/27#issuecomment-900110765_

Refering to above, i added java binaries to my path, however when i tried running the runtest file in the terminal in intellij (set to cmd.exe), i still get the below error.

**Comment by Gordon25** [comment]
![image](https://user-images.githubusercontent.com/73068242/130016876-c00c563d-8530-486b-98a2-194a163cad70.png)

**Comment by rohit0718** [comment]
does javac work in your command prompt `cmd` (not the one inside intellij)?

**Comment by Gordon25** [comment]
Yes it works

**Comment by rohit0718** [comment]
can you run `set` in the terminal inside intellij? you should see the path to the java binaries as one of the entries.

**Comment by simonjulianl** [comment]
I think besides setting your `JAVA_HOME` variable and javapath to `Path`, you can try invalidating cache and restart IntelliJ, it resolves my problem last time

**Comment by Gordon25** [comment]
It works in the Intellij cmd now, thanks guys!
