### ISSUE TITLE
Wrong edit of functional code after deadline

### ISSUE THREAD

**Issue by Xiaoyunnn** [nus-cs2103-AY2122S1/forum#410]
Hi Prof, when I was editing the user guide for CS2103 submission before the deadline, I added a full stop to line 13 in the screenshot but this PR was not merged at that time. So when I was editing the user guide for CS2101 submission, I reverted this line back to how it is in the `jar` version we submitted (without fullstop) but this edit was recorded in reposense as an edit of the functional code after the deadline, will I be penalised for this?
![image](https://user-images.githubusercontent.com/76084739/141818326-aa14a629-9f7b-4505-8085-9fa2a800a924.png)

**Comment by damithc** [comment]
Noted. It's OK @Xiaoyunnn
