### ISSUE TITLE
Doubt from LUMINUS Quiz

### ISSUE THREAD

**Issue by ramapriyan912001** [nus-cs2103-AY2122S1/forum#411]
Where do I find the code that they're referring to in this question?
Also, should there not be a PE part 2 quiz on luminus?
I understand it's just for drawing ungraded diagrams, but aren't those necessary for part 3 to make sense?

![image](https://user-images.githubusercontent.com/64624151/141935539-53eb8971-b22a-462a-ad68-43207b37b18e.png)

Prof @damithc apologies if I've missed out on something obvious here.

**Comment by andrewbaruch** [comment]
You can find the part 2 in LumiNUS Files -> Handouts
