### ISSUE TITLE
Is this considered a documentation bug - Features that are not implemented but is still listed in User Stories? 

### ISSUE THREAD

**Issue by erwinqxy** [nus-cs2103-AY2122S1/forum#412]
Hi, I was wondering if a feature that is not implemented and yet it appeared in the user stories considered a bug?

**Comment by damithc** [comment]
> Hi, I was wondering if a feature that is not implemented and yet it appeared in the user stories considered a bug?

@erwinqxy No. User stories are requirements, which may not be implemented yet. They need to be in the DG for the benefit of future developers.

**Comment by erwinqxy** [comment]
@damithc ah i see. Thank you prof
