### ISSUE TITLE
Is it possible to change the type of bug after the developer's response?

### ISSUE THREAD

**Issue by kaixin-hc** [nus-cs2103-AY2122S1/forum#416]
For one of the bugs the developers responded to, they rejected the bug and downgraded the severity, explaining that they did support similar functionality. However, this functionality was not clearly documented, hence I believe that the problem I described is still extremely likely to happen. 

With their explanation, I'm inclined to think that the bug was actually a documentation bug instead of a feature flaw. Is it possible to change the bug type during this phases?

**Comment by damithc** [comment]
@kaixin-hc yes it is possible. More details:
![image](https://user-images.githubusercontent.com/1673303/142127513-44263144-3ad0-4625-8091-01ac1d493998.png)

**Comment by kaixin-hc** [comment]
Thanks!
