### ISSUE TITLE
Not all my bugs are imported yet

### ISSUE THREAD

**Issue by kevinchua6** [nus-cs2103-AY2122S1/forum#417]
I only see 15 bugs in catcher, yet I have reported 20. I have noted certain bugs which are in the github but not in Catcher.  

Not sure if I should report this under the Catcher issues or here, because the email stated that the transfer of bugs are "completed".

**Comment by andrewbaruch** [comment]
I believe that means 5 of your bugs are accepted as is.

**Comment by kevinchua6** [comment]
Ah I see, thanks! Haha I'm dumb
