### ISSUE TITLE
Multiple end nodes in an activity diagram

### ISSUE THREAD

**Issue by fans2619** [nus-cs2103-AY2122S1/forum#419]
Hi I just want to confirm multiple end notes are allowed in an activity diagram? What are some reasons for having this?

**Comment by yucheng11122017** [comment]
Are they allowed..? Seems rather odd to have multiple end points with only one start point

**Comment by qinguorui2001** [comment]
even multi thread leads to one end node

**Comment by damithc** [comment]
OK to have multiple end nodes :-)

Remember this diagram from Tutorial 10?

![image](https://user-images.githubusercontent.com/1673303/142168150-5d0d882d-4b9d-468f-9013-2c62aa8e341f.png)

Imagine dragging all the end nodes to one place -- it doesn't change the meaning of the diagram other than making the diagram uglier (and more complicated).
If it's not allowed, it should have come up during that tutorial.

> Seems rather odd to have multiple end points with only one start point

Think of how methods are executed. They have one entry point but can have multiple exit points e.g., guard conditions.

**Comment by fans2619** [comment]
Hmmm thanks

**Comment by yucheng11122017** [comment]
Oh thank you Prof! I think generally have still presented it as one end point for guard clauses so that didn't occur to me
