### ISSUE TITLE
Are we supposed to remove the test folder in git ignore. 

### ISSUE THREAD

**Issue by Bluntsord** [nus-cs2103-AY2122S1/forum#42]
In the git ignore in the provided files, the test files are included. This makes us unable to push ACTUAL OUTPUT AND EXPECTED OUTPUT  text files.  If I'm not wrong, we should be removing this for the purposes of the A-TESTING stage

**Comment by zzybluebell** [comment]
I think it is only to push input.txt or expected.txt (or if u have found or fixed some error in another file:） thanks
