### ISSUE TITLE
question related to sequence diagram

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#422]
hi,
could i know why it's true? since the arrow from run() call doesn't match the edge of activation bar of play()
![image](https://user-images.githubusercontent.com/77196303/142214658-b037dab6-ce60-461d-a178-5b6d4165f448.png)

**Comment by yucheng11122017** [comment]
run() is called by play() there is no need to match the edge. Only if the method is being called then need to match. Eg. if activation bar was drawn for run() then there is a need to match the arrow to the start of the activation bar.

**Comment by qinguorui2001** [comment]
good explanation, thank you!
