### ISSUE TITLE
Sequence diagram object deletion

### ISSUE THREAD

**Issue by fans2619** [nus-cs2103-AY2122S1/forum#424]
Am I right to say the `delete` here is **not** a method call?
![image](https://user-images.githubusercontent.com/68739475/142418936-ff2365d8-2d88-4cdf-be2e-1b99bc0147a8.png)

**Comment by damithc** [comment]
@fans2619 it _could_ be, if the programming language supports object deletion (Java doesn't).

**Comment by fans2619** [comment]
Ah okay I see! Thanks prof!
