### ISSUE TITLE
Practice paper part 1

### ISSUE THREAD

**Issue by fans2619** [nus-cs2103-AY2122S1/forum#426]
Why must table have exactly one door? Erm I just think the comment is weird.
![image](https://user-images.githubusercontent.com/68739475/142583447-daefe5b5-9717-4067-aaa6-223b02c8f6ed.png)
![image](https://user-images.githubusercontent.com/68739475/142583485-27ed42f6-b689-464d-86c1-c3f2b4b98596.png)

**Comment by andrewbaruch** [comment]
I think the comment means that in C, all table must have exactly 1 door (according to the multiplicity) and the object diagram shows that table has no connection to any door.

**Comment by fans2619** [comment]
Oh I think I get the idea. Thank you!
