### ISSUE TITLE
Justification for Mock exam

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#427]
Hi prof, I just attempted the mock exam on LumiNUS and looked at the comments given.

For example in Q2

![image](https://user-images.githubusercontent.com/69448615/142584943-ecbf8ae9-14db-4600-9dbd-a26e99044c99.png)

![image](https://user-images.githubusercontent.com/69448615/142585644-6be9b718-baef-4dc2-8ee6-98c8d97cb762.png)

The justification asks for `what's` the violation. But the comment only says `Should be readLines()`. Are these general comments the sample justifications or just for us to refer to?

I feel that the justification should state clearly `what` are the violations.

My response was: `the method name should be in camelCase, in this case "readLines()" is a better name.`

**Comment by damithc** [comment]
General comments given are not exactly sample justifications. The justification you've given is good enough, as it shows you have the right understanding about the question at hand.

**Comment by SkyBlaise99** [comment]
Alright thx for the clarification prof
