### ISSUE TITLE
Dead link in module website

### ISSUE THREAD

**Issue by uyencfi** [nus-cs2103-AY2122S1/forum#428]
I noticed a dead link in [this section](https://nus-cs2103-ay2122s1.github.io/website/schedule/week3/topics.html#quality-assurance-testing-unit-testing-what) of Week 3's topics. It's the first link under the `Resources` tab at the end of the section, titled "The three pillars of unit testing".

![Screenshot 2021-11-20 at 2 31 03 AM](https://user-images.githubusercontent.com/77076051/142673798-b6fa82bc-c223-4975-bc23-0b5f4bec9536.png)

**Comment by damithc** [comment]
Thanks for the bug report @uyencfi Will remove it soon.
