### ISSUE TITLE
Does implicit alternative paths need to be included in activity diagrams> 

### ISSUE THREAD

**Issue by yucheng11122017** [nus-cs2103-AY2122S1/forum#429]
Do we have to include implicit alternative paths? For example for the question below, do we have to draw the fact that couriers might reject the order?
![image](https://user-images.githubusercontent.com/77204346/142714124-be134b0e-dfc6-49c5-94a5-ad6500f1320e.png)

**Comment by damithc** [comment]
@yucheng11122017 In a real project, depends on whether that path is relevant to the purpose of the diagram.
In the exam, the question will have some indication if that path is important. The screenshot is not from a question I've set for CS2103/T.

**Comment by yucheng11122017** [comment]
@damithc Thank you prof! It was from a set of past year papers that was sent around
[1819SEM2-CS2103-T.pdf](https://github.com/nus-cs2103-AY2122S1/forum/files/7574199/1819SEM2-CS2103-T.pdf)
.
