### ISSUE TITLE
Final exam: Is both nus-cs2103-ay2122s1.github.io and /se-education.org considered 'Module Website'?

### ISSUE THREAD

**Issue by kaixin-hc** [nus-cs2103-AY2122S1/forum#431]
As written in the question title, for the purposes of the final exam. 

I'm mostly wondering about pages like [the coding standard](https://se-education.org/guides/conventions/java/intermediate.html) and [git conventions](https://se-education.org/guides/conventions/git.html), especially because of the question in the mock exam on coding standard.

**Comment by damithc** [comment]
@kaixin-hc Yes, se-education.org pages are allowed too.

**Comment by kaixin-hc** [comment]
Thank you!
