### ISSUE TITLE
Notation for alternative paths in sequence diagram

### ISSUE THREAD

**Issue by Imranr2** [nus-cs2103-AY2122S1/forum#433]
Hello all, is it considered wrong notation if the `alt frame` only specifies 1 condition i.e. missing the else portion as shown below? I know that we should use an `opt frame` instead but just wondering if the image below is considered wrong in this module.

![image](https://user-images.githubusercontent.com/48386167/142751715-a23946a3-d4f0-47d1-a35d-0620cbdfe2b5.png)

**Comment by CheongYeeMing** [comment]
The notation above should be perfectly fine as specifications require that you have **at least one operand per fragment**. But yes, it'll be much clearer to use `opt` in this case.

**Comment by vimuthm** [comment]
Since there has to be exactly one true alternative, I would argue that if either the question or the sequence diagram guarantees that x is positive when it reaches this alt, then this should technically be correct.

**Comment by damithc** [comment]
@Imranr2 `opt` is preferred for this case. UML diagrams are meant for human consumption -- I can't see a good justification for using another notation when there is a more suitable one.

**Comment by Imranr2** [comment]
@damithc Thanks prof for the clarification! Thank you for the responses as well! @VimuthM @CheongYeeMing

**Comment by waynetee** [comment]
> Since there has to be exactly one true alternative, I would argue that if either the question or the sequence diagram guarantees that x is positive when it reaches this alt, then this should technically be correct.

@VimuthM I don't think there has to be exactly one true alternative for sequence diagram

**Comment by vimuthm** [comment]
@waynetee yes, thank you! I realize I mixed up this alt and  the branch nodes in activity diagrams :")
