### ISSUE TITLE
coverage issue

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#435]
100% path coverage -> 100% condition coverage?
100% condition coverage -> 100% branch coverage?
100% branch coverage -> 100% statement coverage?

**Comment by yucheng11122017** [comment]
I would think so but might be wrong

**Comment by AllardQuek** [comment]
Seems correct except maybe the last statement? 
> 100% branch coverage -> 100% statement coverage?

Looking at the definition from the textbook:
> Decision/branch coverage : based on the decision points exercised e.g., an if statement evaluated to both true and false with separate test cases during testing is considered 'covered'.

I think it's possible that the tester might cover all the branches but not necessarily all the statements (i.e. lines of code). 

For example, if the code only contains 1 `if` statement in a large program, branch coverage could be 100% but statement coverage could in fact be very low.

**Comment by qinguorui2001** [comment]
> For example, if the code only contains 1 `if` statement in a large program, branch coverage could be 100% but statement coverage could in fact be very low.

sounds reasonable, but i don't think that's true, suppose `if` occurred in a method, we can write tests about this method to test its branching, and whole method runs once, some statements are covered already,when 100% branches are covered, this means the method had been run for several times to cover all if else statements, and common code has been covered several times,so all lines of code had been covered

**Comment by kaixin-hc** [comment]
I don't think it necessarily means all lines of code can be covered -- what about a try-catch block? Lets say the error is never thrown. Then any code in the catch block would never be run or tested, but you could still achieve 100% branch coverage because all decisions were tested.

**Comment by qinguorui2001** [comment]
not cover catch section-> 100% branch coverage?

**Comment by kaixin-hc** [comment]
I'm pretty sure catch is not a **decision**?

**Comment by qinguorui2001** [comment]
branch coverage should include this , try intellij

**Comment by kaixin-hc** [comment]
seems i misunderstood what decision meant, thanks! some googling revealed multiple sources that agreed you're right that 100% branch coverage means 100% statement coverage.
