### ISSUE TITLE
Omission of param type for class diagrams

### ISSUE THREAD

**Issue by kevinchua6** [nus-cs2103-AY2122S1/forum#437]
![image](https://user-images.githubusercontent.com/45702380/142771373-a9eecb16-bd22-4aa3-8f16-92303d28a979.png)
Sorry if this has been asked before, but is it okay if we omit the param type: `copy()` instead of `copy(int)`?  

Also do correct me if I'm wrong but `copy(int)` is correct right?

**Comment by damithc** [comment]
> Sorry if this has been asked before, but is it okay if we omit the param type: `copy()` instead of `copy(int)`?

Those two are two different methods.


> Also do correct me if I'm wrong but `copy(int)` is correct right?

Can you elaborate more?

**Comment by kevinchua6** [comment]
Thanks for the reply for the first part! I understand now.  

Sorry for being unclear. I meant that is it okay to omit the param name: writing `copy(int)` instead of `copy(int count)` for the copy method shown above

**Comment by yucheng11122017** [comment]
Yup i think it is ok to omit the param name but not the type :)

**Comment by kevinchua6** [comment]
I see ok thanks!
