### ISSUE TITLE
Doubt on example for breadth-first approach

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#438]
Why is "[adding a new feature fully](https://nus-cs2103-ay2122s1.github.io/website/schedule/week2/topics.html#project-management-sdlc-process-models-introduction-iterative-models)" considered a breadth-first approach?

![image](https://user-images.githubusercontent.com/40263305/142773105-74614f1a-0a15-41e1-a058-c8b7f33ad744.png)

**Comment by damithc** [comment]
> Why is "[adding a new feature fully](https://nus-cs2103-ay2122s1.github.io/website/schedule/week2/topics.html#project-management-sdlc-process-models-introduction-iterative-models)" considered a breadth-first approach?

The focus is on the feature (i.e., update whichever components needed for the feature), not the components (i.e., update backend components only) -- the latter is depth-first.

**Comment by AllardQuek** [comment]
Thanks Prof!
