### ISSUE TITLE
Fix bug in previous levels

### ISSUE THREAD

**Issue by nniiggeell** [nus-cs2103-AY2122S1/forum#44]
Hi. For example, Ive committed and tagged level-3 submission and pushed to github. Now when I am working on level-6 submission I realise theres an edge case I had not considered. I fix the bug, add the features and commit and push all the changes to Level-6.

Is this okay? Should I go back to level-3 and fix the bug there? Or is fixing it now (at level-6) fine?

**Comment by damithc** [comment]
It's fine to fix bugs or do other improvements as you go @nniiggeell. No need to edit past commits or move tags. A tag is simply a self-declaration of the first time you _thought_ you are done with a particular increment. We only use it to track your progress (as self declared by you). We don't test/grade the code at each tag.

**Comment by nniiggeell** [comment]
Thanks prof!
