### ISSUE TITLE
If two classes depend on each other, what should we draw?

### ISSUE THREAD

**Issue by kevinchua6** [nus-cs2103-AY2122S1/forum#441]
```
class Player {
    doSomething(Status status {
        ...
    }
}

class Status {
    doSomething(Player player {
        ...
    }
}
```

In the case of something like this, do we draw a double headed dashed line or do we draw a dashed line with no arrowheads?
![image](https://user-images.githubusercontent.com/45702380/142788058-a9d7a2be-dbdb-4c47-8a07-3fa190a57ee2.png)
![image](https://user-images.githubusercontent.com/45702380/142788087-1ad91441-4d0c-45de-b851-8c2883127eb0.png)

Or do we draw two dashed lines pointing to each other?
![image](https://user-images.githubusercontent.com/45702380/142788101-d6391b77-1995-4b19-81f1-1fa5254d2e69.png)

**Comment by fans2619** [comment]
Probably both are okay (not the one with no arrow head) but circular dependency is not good.

**Comment by yucheng11122017** [comment]
I believe the first one is the best.

**Comment by damithc** [comment]
This one.

> ![image](https://user-images.githubusercontent.com/45702380/142788101-d6391b77-1995-4b19-81f1-1fa5254d2e69.png)

Dependency is uni-directional. There are no bi-directional dependency arrows.

**Comment by kevinchua6** [comment]
Ok thank you prof!
