### ISSUE TITLE
Using implicit shorthands to refer to Quiz options for justifications

### ISSUE THREAD

**Issue by yyhangz** [nus-cs2103-AY2122S1/forum#442]
Apologies if this has been asked before.

Luminus quizzes tend not to have enumerations for their options (like A,B,C,D or 1,2,3,4), unless it is embedded manually into the options themselves by the designer of the quiz. 

When writing the justification for each question, would it be okay if we implicitly assigned a shorthand for each option (maybe 1 for the top-most option, 4 for the bottom-most option for a 4-Options question), and used them for easier reference in our justifications segment?

For instance, with reference to the example below, can we say something like "Option 1 is not a FR since it is not a function that the user can carry out in the software.", when writing our justification?

![image](https://user-images.githubusercontent.com/48285332/142797487-9df3f1b8-4567-4628-85cd-64ccdfda45aa.png)

**Comment by damithc** [comment]
@yyhangz Don't use numbers/letters to identify options unless the question itself specifies them. Reason: the options are often configured to appear in random order.

**Comment by yyhangz** [comment]
Ok thanks prof @damithc !
