### ISSUE TITLE
Final's Tool

### ISSUE THREAD

**Issue by hungkhoaitay** [nus-cs2103-AY2122S1/forum#443]
Hi prof, is it allowed to use the [module website](https://nus-cs2103-ay2122s1.github.io/website/index.html) during finals?

**Comment by chunweii** [comment]
It's allowed. See [point 9](https://nus-cs2103-ay2122s1.github.io/website/admin/exams.html#sop-deviations-refinements). Also see #431.

Disclaimer: Not the prof, but I am certain that it is allowed

**Comment by hungkhoaitay** [comment]
Thanks @chunweii
