### ISSUE TITLE
Part 1 of practice paper code quality vs coding standard

### ISSUE THREAD

**Issue by s7u4rt99** [nus-cs2103-AY2122S1/forum#445]
![IMAGE 2021-11-22 16:31:23](https://user-images.githubusercontent.com/77237808/142828260-a56d6d7c-ded0-486a-8ce7-3bf41d32d54f.jpg)

May I know why is the answer 1 for this, and not 3? I assumed that `10`(line 2) and `"reading"`(line 6) could potentially be magic values, and thus included them. Is that a valid answer?

I was wondering if it could be due to the fact that they are Code quality violations and not Coding standard violations? (magic values are not mentioned in the [Java Coding Standard](https://se-education.org/guides/conventions/java/intermediate.html) page, only in the [Code Quality](https://nus-cs2103-ay2122s1.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-magic-numbers) page). Do we have to treat them differently in the final exam?

**Comment by damithc** [comment]
> I was wondering if it could be due to the fact that they are Code quality violations and not Coding standard violations? (magic values are not mentioned in the [Java Coding Standard](https://se-education.org/guides/conventions/java/intermediate.html) page, only in the [Code Quality](https://nus-cs2103-ay2122s1.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-magic-numbers) page). Do we have to treat them differently in the final exam?

@s7u4rt99 That's correct. They are different things, not just for the exam but for real projects too. One is more concrete and easier to enforce/automate but not the other.

**Comment by s7u4rt99** [comment]
I see, thanks for the explanation prof @damithc !
