### ISSUE TITLE
Mock exam coding standard violation question. 

### ISSUE THREAD

**Issue by Smanmos** [nus-cs2103-AY2122S1/forum#448]
Shouldn't line 3 also be considered a violation since it uses a magic constant string?

**Comment by dannylty** [comment]
That's code quality, not coding standard.

**Comment by ntwbruce** [comment]
Similarly discussed in [#445](https://github.com/nus-cs2103-AY2122S1/forum/issues/445)!

**Comment by Smanmos** [comment]
I see! Thank you.
