### ISSUE TITLE
Multiplicities for bi-directional associations

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#449]
If we were to add multiplicities, would it be acceptable to put `0..1` in the middle of the bi-directional arrow on Category? 

Not too sure how to capture the fact that if a Category object is related to another Category object each of them will have a reference to the other. 

![image](https://user-images.githubusercontent.com/40263305/142914643-098be970-0db8-41ab-b545-bc35b81deb7c.png)

**Comment by fans2619** [comment]
Like this?

<img src="https://user-images.githubusercontent.com/68739475/142958665-e53644b7-0da2-454b-b2dd-b80603a46b4b.png" width="350" />

**Comment by qinguorui2001** [comment]
same

**Comment by AllardQuek** [comment]
Would that imply that a Category object can be related to 0 other Category objects?

**Comment by AllardQuek** [comment]
Thanks @fans2619 and @qinguorui2001!
