### ISSUE TITLE
Class Naming Requirement

### ISSUE THREAD

**Issue by HolmesJJ** [nus-cs2103-AY2122S1/forum#45]
May I please ask if I must follow the naming of the class mentioned on the website as shown below? Since I found that I have created some other classes based on the OOP paradigm like `TaskManager.java`. But I think it is similar with the `TaskList.java` in the next Level.

<img width="752" alt="Screenshot 2021-08-19 at 6 39 48 PM" src="https://user-images.githubusercontent.com/62185825/130056262-be5e54e8-066b-4744-b875-37bc626488eb.png">
<br>
<img width="744" alt="Screenshot 2021-08-19 at 5 10 59 PM" src="https://user-images.githubusercontent.com/62185825/130056244-a46bb477-012b-4472-a285-3553d4355826.png">

**Comment by damithc** [comment]
@HolmesJJ You can add more classes, and name them suitably. While it is not a strict requirement to name the classes exactly as given, it may make things easier for evaluators if you use the given names. If you think your `TaskManager` does a similar role as `TaskList` class given in the iP description, you can simply rename your class as `TaskList`. 
BTW, Intellij can help you rename a class with just a few clicks (see https://www.jetbrains.com/help/idea/rename-refactorings.html#invoke-rename-refactoring)
