### ISSUE TITLE
Question about Class Diagram dependency

### ISSUE THREAD

**Issue by kevinchua6** [nus-cs2103-AY2122S1/forum#452]
![image](https://user-images.githubusercontent.com/45702380/142975512-2441946e-fd13-468a-9037-f331bdb66c43.png)
Referencing the above diagram, if the Model interface has a dependency to the Urgency Enumeration, shouldn't ModelManager also have a dependency to Urgency because ModelManager implements Model?

**Comment by damithc** [comment]
> Referencing the above diagram, if the Model interface has a dependency to the Urgency Enumeration, shouldn't ModelManager also have a dependency to Urgency because ModelManager implements Model?

Not necessarily, the `Urgency` might not appear in any of the method signatures of `Model` (e.g., it could be a constant defined in `Model`). Plus, we only show what we think is important to the purpose of the diagram. It doesn't have to show every dependency.

**Comment by kevinchua6** [comment]
Ah I see! Thanks Prof @damithc!
