### ISSUE TITLE
when to use assertion

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#453]
hi,
for this , i can only think it as exception, i forgot how it can be assertion as well as mentioned by prof in lecture
![image](https://user-images.githubusercontent.com/77196303/142980364-63f8ff05-b13f-4762-b388-6119d63b5420.png)

**Comment by rohit0718** [comment]
if the dev designed the method under the assumption that it is only called with non-empty strings, then perhaps he can include asserts to ensure other devs are using it properly

**Comment by qinguorui2001** [comment]
> if the dev designed the method under the assumption that it is only called with non-empty strings, then perhaps he can include asserts to ensure other devs are using it properly

thank you, rohit, i realized this question doesn't specify the situation that product delivered or not.
