### ISSUE TITLE
Transaction processing and event driven architectural style 

### ISSUE THREAD

**Issue by marcuspeh** [nus-cs2103-AY2122S1/forum#454]
How is transaction processing architectural style different from event-driven architectural style? Is transaction processing kind of automated whereas event requires some input?

**Comment by rohit0718** [comment]
i feel that many of the styles given are not strictly mutually exclusive. imo, event driven style seems to be a more specific form of transactional style (where the events are the transactions).

**Comment by damithc** [comment]
Transactions are entities that are passed along and eventually, processed e.g., a new data item originates in the GUI, passed along to the storage layer, and saved in the database.
Events are 'happenings' others subscribe to, and react to e.g., several components of a GUI might change when a user clicks on a button.

**Comment by marcuspeh** [comment]
Thanks for explaining Prof!
