### ISSUE TITLE
When omitting attributes or using minimal notation, must it be consistent

### ISSUE THREAD

**Issue by tanhuakun** [nus-cs2103-AY2122S1/forum#455]
In object diagrams, we can choose to omit attributes, and in sequence diagrams we can use minimal notation.

Must this be consistent for every object drawn in the same diagram? Meaning that if we omit one attribute then we must omit all attributes, or can we do it selectively?

**Comment by damithc** [comment]
> Must this be consistent for every object drawn in the same diagram? Meaning that if we omit one attribute then we must omit all attributes, or can we do it selectively?

Can do selectively.
