### ISSUE TITLE
How to add related packages to javac in.bat file

### ISSUE THREAD

**Issue by jiarong15** [nus-cs2103-AY2122S1/forum#47]
Whats the proper way of adding more packages in the the .bat file
javac  -cp ..\src\main\java; ..\src\main\java\commands  -Xlint:none -d ..\bin ..\src\main\java\*.java; ..\src\main\java\commands\*.java

gives me a build failure

**Comment by darrenhoon** [comment]
I ran into this similar issue earlier and what worked for me was to manually write down all the import statements in the file that has the public static void main(String[] args) function.

ie instead of:
`import main.java.*;`

do:
```
import main.java.Engine;
import main.java.Task;
```

**Comment by kevin9foong** [comment]
I'm assuming you're referring to the text-ui-test's bat file. 
With additional packages, you can just leave it as: `javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java`
and it will still work. 

Hope this helps!

**Comment by jiarong15** [comment]
Thanks! But am still facing these errors below. 

Exception in thread "main" java.lang.NoClassDefFoundError: exceptions/NoSuchCommandException
        at LaunchDuke.main(LaunchDuke.java:6)
Caused by: java.lang.ClassNotFoundException: exceptions.NoSuchCommandException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 1 more

Though on the bat file, I've specified the correct class that starts trigger the entire operation.
java -classpath ..\bin LaunchDuke < input.txt > ACTUAL.TXT

My LaunchDuke class is as such:
import java.util.Scanner;

public class LaunchDuke {
    
    public static void main(String[] args) {
        System.out.println(Duke.dukeStart());
        Scanner scanner = new Scanner(System.in);
        Duke.runDukeBot(scanner);
        scanner.close();
    }

**Comment by damithc** [comment]
@jiarong15 perhaps you can give the full content of the .bat file in concern?

**Comment by jiarong15** [comment]
@ECHO OFF

REM create bin directory if it doesn't exist
if not exist ..\bin mkdir ..\bin

REM delete output from previous run
if exist ACTUAL.TXT del ACTUAL.TXT

REM compile the code into the bin folder
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java
IF ERRORLEVEL 1 (
    echo ********** BUILD FAILURE **********
    exit /b 1
)
REM no error here, errorlevel == 0

REM run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
java -classpath ..\bin LaunchDuke < input.txt > ACTUAL.TXT

REM compare the output to the expected output
FC ACTUAL.TXT EXPECTED.TXT

**Comment by damithc** [comment]
@jiarong15 For the line `javac -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java*.java`,
try following @kevin9foong's suggestion given above.

**Comment by SkyBlaise99** [comment]
> javac -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java*.java
You perhaps forgot a `\` at the end? `..\src\main\java\*.java`

**Comment by jiarong15** [comment]
my bad I accidentally delete the \ over there. However, that isn't the issue that is causing the same exception to be thrown :(

**Comment by waynetee** [comment]
If you have java files in subdirectories, I believe you have to specify them as well

**Comment by jiarong15** [comment]
I see.. how do you do so?

**Comment by jiarong15** [comment]
> If you have java files in subdirectories, I believe you have to specify them as well

I see.. how do you do so? :)

**Comment by waynetee** [comment]
`javac -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java   ..\src\main\java\package\*.java `
Just keep appending at the end

**Comment by jiarong15** [comment]
okay finally works! thanks all :)

**Comment by SkyBlaise99** [comment]
Just a note if you do not want to update it manually I got a script here that it might work. Refer to #52.
