### ISSUE TITLE
The commit contribution in green graph Github 

### ISSUE THREAD

**Issue by zzybluebell** [nus-cs2103-AY2122S1/forum#48]
Hi all, I have a few questions not related to cs2103t this module, but related to git/Github please help me clarify:

I have noticed that when push commits to GitHub, it will have a record to the contribution record in the green graph.
But these days' commits have not been displayed in the green contribution graph.

May I check what is the reason? Is it because the forked project won't be displayed?
Thank you so much

**Comment by xlzior** [comment]
Yes, you are right, forked projects don't count towards the contribution graph unfortunately. 

Here's a link that goes into greater detail about what counts and doesn't count: https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

**Comment by VimuthM** [comment]
Once a pull request to the original repo is merged, the contributions count iirc.

**Comment by zzybluebell** [comment]
Thank you so much I got it
