### ISSUE TITLE
Windows cannot recognize FC in runtest.bat

### ISSUE THREAD

**Issue by Harry-Gao-H** [nus-cs2103-AY2122S1/forum#49]
I encountered the following problem when I ran the runtest.bat in the terminal. 
```
'FC' is not recognized as an internal or external command,
operable program or batch file.
```
![Capture](https://user-images.githubusercontent.com/59434153/130216057-2380e09b-e80f-44dc-a6bf-f08bee08b301.PNG)

I am on Windows 10 and the environment variables have already been set up.

**Comment by damithc** [comment]
@Harry-Gao-H did you modify the PATH variable? It's possible that you accidentally removed FC's location from the PATH while modifying it. Otherwise Windows should be able to find it automatically, unless Microsoft changed something very recently.

**Comment by Harry-Gao-H** [comment]
@damithc I did modify the PATH variable by deleting the original path which was linked to outdated Java 8 and adding the new PATH. How can I recover FC functionality if I removed its location?

**Comment by damithc** [comment]
Oops... be careful with that variable, as it is what Windows use to find executables. :-p
I think `FC.exe` is usually found in the `C:\Windows\System32` folder. If it is, ensure your `PATH` variable includes that folder.

**Comment by Harry-Gao-H** [comment]
> Oops... be careful with that variable, as it is what Windows use to find executables. :-p
> I think `FC.exe` is usually found in the `C:\Windows\System32` folder. If it is, ensure your `PATH` variable includes that folder.

Oh I see. I should have append path of java to the original PATH variable instead of creating a new one. Thank you so much prof!
