### ISSUE TITLE
💡 Using IntelliJ built-in Git Capability 

### ISSUE THREAD

**Issue by pss-coder** [nus-cs2103-AY2122S1/forum#53]
Hi, not sure if you've noticed yet but that IntelliJ has their own built-in Git Capability. Though nothing wrong using SourceTree and command line. I thought perhaps using the built-in Git on IntelliJ could better provide a "quicker" workflow when pushing our repos to github, rather than having to use another software or typing in command line.

Here are some screenshot, of where you could access it (these are screenshots for the Mac version of IntelliJ, I believe windows should be similar as well): 

![Screenshot 2021-08-21 at 5 39 47 PM](https://user-images.githubusercontent.com/22881285/130317800-e7860d01-08bb-4a15-9860-75f20ca24cf6.png)

Top right corner:  (pull, commit and push in respective to the icons)
![Screenshot 2021-08-21 at 5 31 26 PM](https://user-images.githubusercontent.com/22881285/130317588-47c28cc3-ca86-4be3-8d70-e91dee743c7a.png)

Bottom left of intelliJ (you can also add tags in it too): 
![Screenshot 2021-08-21 at 5 31 10 PM](https://user-images.githubusercontent.com/22881285/130317613-2bdda605-5136-4da7-b83c-bd7389e84090.png)

I hope this helps.

Here's some sources online for references too: 
https://www.jetbrains.com/help/idea/commit-and-push-changes.html#commit
https://purdueusb.com/wiki/git-and-intellij

**Comment by Yukun99** [comment]
I use this more for staging/committing, then do the more advanced parts of it either in SourceTree or CLI. Definitely recommended for simple tasks.

**Comment by pss-coder** [comment]
Feel free to add more intelli-J git tips here! Closing this issue to keep the forum clean.
