### ISSUE TITLE
Accidently submitted an empty quiz

### ISSUE THREAD

**Issue by rehmmann** [nus-cs2103-AY2122S1/forum#55]
Hi
For my week 2 quiz, I accidentally submitted an empty quiz in my second attempt which led to 0 marks. Would that mean that my second attempt is counted or my first(Higher score)?
Thanks in advance!

**Comment by SkyBlaise99** [comment]
You can check your score at [here](https://nus-cs2103-ay2122s1.github.io/dashboards/contents/participation.html)

**Comment by damithc** [comment]
We take the best attempt, not the latest attempt.

**Comment by rehmmann** [comment]
I see thanks!
