### ISSUE TITLE
git push vs git push origin <branch name>

### ISSUE THREAD

**Issue by rickyaandrew** [nus-cs2103-AY2122S1/forum#57]
have some simple questions on this git push command

1) so was just trying out pushing my code from the local repo to the remote repo and noticed that "git push" seems to be working the same just like "git push origin {branch name}" is there any specific difference to this?

2) understand that "origin" supposed to be the repo name. is it by default "origin"? because it seems like all my repo is named origin.

**Comment by NicolasCwy** [comment]
Hi ricky, I did a quick search and found the following

1. > branch.*.remote configuration for the current branch is consulted to determine where to push. If the configuration is missing, it defaults to origin.
Git push origin is more specific and I am assuming would allow you to specify other branches that you would like to push to your remote repository, not necessarily the branch you are currently on.
[git push](https://git-scm.com/docs/git-push) 

2. When you clone a repository, the repo that you clone from would be added as a remote repo and for convenience be named as origin for a shorthand. Therefore at this point, in the mod, we would usually be working with origin as we are working on our own repo. 
Use `git remote -v` to see the connection between "origin" and the URL of your repo

[git clone](https://www.atlassian.com/git/tutorials/setting-up-a-repository/git-clone#:~:text=git%20clone%20is%20primarily%20used,copies%20an%20existing%20Git%20repository.)

**Comment by rickyaandrew** [comment]
ahh okok got it thanks alot
