### ISSUE TITLE
Completing future weeks project tasks

### ISSUE THREAD

**Issue by Imranr2** [nus-cs2103-AY2122S1/forum#6]
If we are done with this week's tasks and are interested in starting on the future weeks tasks. Will the grading script grade the latest commit or does it grade based on the commit tags?

**Comment by damithc** [comment]
In general, we discourage you from getting too far ahead of the schedule @Imranr2 although going a tiny bit ahead is OK. It shouldn't affect grading as long as you do _some_ commits in _most_ weeks.

Quoting from [this page](https://nus-cs2103-ay2122s1.github.io/website/schedule/week2/project.html):

![image](https://user-images.githubusercontent.com/1673303/129471664-dd98a2bf-a4a6-499a-950b-a00981bcd9a6.png)

**Comment by Imranr2** [comment]
Thank you for the clarification Prof.
