### ISSUE TITLE
how much code to write in switch body 

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#60]
what is the best practice surrounding using the switch structure with regards the amount of code for each case? Specifically:

switch (var) {
case 1:
  ....
   how much code should you write here? is it recommended to keep it short here or 
   you can write as much as you want? 
   .....
   break
   .
   .
   . 
}

**Comment by FergusMok** [comment]
Hello, if you are worried about the readability in the switch statement, wrapping everything into a method to handle that particular case would be very useful. For example, for case Done command, I would have a one-liner handleDone(..) method. 
Others reading your code will be able to easily understand the purpose of the switch at a glance, and refer to the method if they need to see the implementation.

**Comment by simonjulianl** [comment]
What FergusMok wrote was actually really nice! but besides the modularity, I think one other disadvantage that you might face with a very huge chunk of the switch statement is the burden in your IDE (IntelliJ in this case I believe), if your file becomes very huge to the point exceeding ~2k lines, when your ide tries to do syntax analysis and indexing of the file, it will take very long.
