### ISSUE TITLE
File not found when reading in the txt file

### ISSUE THREAD

**Issue by jiarong15** [nus-cs2103-AY2122S1/forum#61]
Below is the main method in an attempt to read in text files from my folder for level 7.
below is my LaunchDuke class.
My folder directory is as such:
where LaunchDuke is the java folder and duke.txt is in the inner data folder. Even though the .txt file
is there, the main method still throws FileNotFoundException
- main
     - java
         - data
                  - duke.txt
         - LaunchDuke.java

public class LaunchDuke {
    
    public static void main(String[] args) throws FileNotFoundException {
        File f = new File("./data/duke.txt");
        try {
            Scanner scanner = new Scanner(f);
            while (scanner.hasNext()) {
                System.out.println(scanner.nextLine());
            }
            scanner.close();
        } catch (FileNotFoundException e) {
            System.out.println("File not found");
        }
    }
}

**Comment by marcuspeh** [comment]
./data is based on your project directory. So data shld be at the same level as your src folder

**Comment by jiarong15** [comment]
thanks!
