### ISSUE TITLE
Save on exit instead of saving the tasks whenever the task list changes.

### ISSUE THREAD

**Issue by Chesterwongz** [nus-cs2103-AY2122S1/forum#62]
Can we implement save to only write the file when the user chooses to exit Duke instead of what is stated here?
![image](https://user-images.githubusercontent.com/70138507/130355300-6981423c-1ae9-4f94-8335-5f7010855ba4.png)
I feel there's simply no need to write whenever the list changes, since the file is only used when Duke is starting up. This might also help keep Duke interactions snappy and quick.

**Comment by damithc** [comment]
> I feel there's simply no need to write whenever the list changes, since the file is only used when Duke is starting up. This might also help keep Duke interactions snappy and quick.

Any downsides to 'save only on exit' strategy?

**Comment by marcuspeh** [comment]
What if the program crashes? Or force stopped

**Comment by Chesterwongz** [comment]
I see! I just realized that as well, thanks!
