### ISSUE TITLE
How to use input out redirection between consecutive runs of the program

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#63]
I want to set up my test so that it can do some testing for level 7: 
when i update the tasks and then end the program, it should write the new list to the output file and when i run the program again and use the "list" command, it should give me some expected output that i should be able to test. However, it seems that the input output redirection ends once the program exits after my "bye" command.

Is there any way to do what i intended?

**Comment by SkyBlaise99** [comment]
I believe you are testing for the load and save function. What I did is that I have a `data.txt` which is already filled with some stuff to test my `load()`, after which follows normal testing and lastly, delete all tasks in the list (can also test delete during this time) and add back the tasks that was initially in `data.txt`.

Hence if my `store()` is working correctly, the 2nd round of script should still show `no diff` for `FC`.
