### ISSUE TITLE
On saving data to .txt file after each command-reply cycle in Duke

### ISSUE THREAD

**Issue by hmanhduc2k** [nus-cs2103-AY2122S1/forum#64]
Hi guys, I would like to ask a question on saving task list modification in Duke, specifically on efficiency and runtime.

Is runtime important? In trying to save changes in the list of task, I decided to rewrite the file all over again, as in, iterate through the task List and manually rewrite the file from begin to end.

Is this an acceptable approach to Level-7?
Or do I have to trace which task has changed, then search through .txt file for the task that matches and modify only that specific line? Would that be possible?

**Comment by SkyBlaise99** [comment]
I would say that's the easy way, which is wut I did, is to just overwrite the file. Imo, the more efficient way is to only write to the file before the program ends, whether normally or due to some exceptions.

I'm not sure if there is a way to just remove some lines from a text file, most of the time people would just read the file and filter the list and output it.

**Comment by hmanhduc2k** [comment]
> I would say that's the easy way, which is wut I did, is to just overwrite the file. Imo, the more efficient way is to only write to the file before the program ends, whether normally or due to some exceptions.
> 
> I'm not sure if there is a way to just remove some lines from a text file, most of the time people would just read the file and filter the list and output it.

Ah okay thanks, so it is acceptable to rewrite the entire file only after the exit command, and I don't need to update the file after each command-reply cycle?

**Comment by damithc** [comment]
> so it is acceptable to rewrite the entire file only after the exit command, and I don't need to update the file after each command-reply cycle?

@hmanhduc2k relevant issue #62

**Comment by hmanhduc2k** [comment]
Thanks for the help!
