### ISSUE TITLE
Question about Testing Topic

### ISSUE THREAD

**Issue by HolmesJJ** [nus-cs2103-AY2122S1/forum#65]
May I please ask what is relationship between software under test (SUT), Unit testing, Regression Testing, Test Automation, Test Driver, Stub (There are the contents under testing topic)?

This is my understanding below:

The developer 
1. need to perform testing (Developer Testing) for the software (SUT). 
2. can use JUnit to make testing automation. (When using the Junit framework, does it mean that dont need to implement the test driver class?)
3. need to implement unit testing for each function, and need to implement Stub for the tested function to isolate dependencies if the logic in the function depends on other functions.
4. need to run all the test cases (Regression Testing) again after bug fixed.

And I dont quite understand the question 29: "A stub is an alternative implementation of an SUT; by having two alternative implementations, we reduce the risk of bugs."

I think the first part of the sentence "A stub is an alternative implementation of an SUT" is correct right? Then what is the meaning of "by having two alternative implementations"?

**Comment by damithc** [comment]
> I think the first part of the sentence "A stub is an alternative implementation of an SUT" is correct right? Then what is the meaning of "by having two alternative implementations"?

I'll answer this part first and leave the rest for discussion.
Having alternative implementations is a technique used for reducing bugs in critical software i.e., for example, suppose there is a very complex algorithm that controls the dosage of a medicine being pumped into a patient. You can get three developers to do independent implementations of that algorithm and incorporate all three into the system. When the time comes for the dosage to change, the software can execute all three algorithms and proceed with the actual change of the dosage only if all three algorithms give the same result. 

And no, stubs are not really 'alternative' implementations. Stubs are just 'pretending' to be the implementation they replace.

**Comment by tlylt** [comment]
> This is my understanding below:
> 
> The developer
> 
> 1. need to perform testing (Developer Testing) for the software (SUT).
> 2. can use JUnit to make testing automation. (When using the Junit framework, does it mean that dont need to implement the test driver class?)
> 3. need to implement unit testing for each function, and need to implement Stub for the tested function to isolate dependencies if the logic in the function depends on other functions.
> 4. need to run all the test cases (Regression Testing) again after bug fixed.

Hello, 
for the 3rd point on unit testing: 
- I think it is not realistic to unit test each and every function. So perhaps the most effective approach is to unit test the more critical building blocks of software (e.g. functions that handle transaction logic in banking applications). There is also a general sentiment that we should not test private functions/methods so as to not test implementation details and keep test cases durable.
- Also, while functions are usually the "unit" in unit test, sometimes it can refer to something more general, i.e. an isolated piece of code that can be either a function, a class, or a component. As opposed to integration testing, unit testing is about verifying that individual pieces of code work as intended (hence the reason why we might want to isolate them).

for the 4th point on regression testing:
- as described by the textbook:
>Regression testing is the re-testing of the software to detect regressions. Note that to detect regressions, you need to retest all related components, even if they had been tested before.
- When there is a modification (can be fixing bugs or adding a new feature), there is a chance that the changes result in regression (What used to work no longer works). So perhaps it's more accurate to say "need to rerun all the test cases (Regression Testing) again after a modification is completed".

**Comment by damithc** [comment]
@HolmesJJ some of the doubts you had will get cleared up as we go through the module. Feel free to reopen and ask again if there are remaining doubts.
