### ISSUE TITLE
AddressBook Level 3 (AB3) User Interface Not Displaying Correctly

### ISSUE THREAD

**Issue by ziqing26** [nus-cs2103-AY2122S1/forum#66]
Hello guys! After I downloaded AB3 from the latest release in the [User Guide](https://se-education.org/addressbook-level3/UserGuide.html), the font is not showing properly. I have java version 11.0.12 installed on the M1 Mac Big Sur. May I ask what could be done about this? Thanks in advance!

![image](https://user-images.githubusercontent.com/69516975/130361624-5bca3014-0341-402b-b1dc-4a1c7e6b3136.png)

**Comment by damithc** [comment]
Oops. Thanks for reporting this @ziqing26 Let's see if other M1 users face the same problem and if someone can figure out a way around it.

**Comment by damithc** [comment]
AB3 uses `Segoe` family of fonts by the way, in case you are able to install it.

**Comment by sivayogasubramanian** [comment]
I use a M1 mac too and I have the same problem. I downloaded `Segoe` font and it seems to fix it partially. Is `Segoe` the only font used?

[Font Download](https://www.cufonfonts.com/font/segoe-ui-4)

<img width="740" alt="Screenshot 2021-08-23 at 10 33 31 AM" src="https://user-images.githubusercontent.com/53614454/130382118-bb3f66ef-421f-4714-9b9c-3a333353c8b0.png">

**Comment by damithc** [comment]
AB3 uses several members of the Segoe font family. This file mentions the fonts used by AB3 https://github.com/se-edu/addressbook-level3/blob/master/src/main/resources/view/DarkTheme.css

**Comment by waynetee** [comment]
Wouldn't it be better if AB uses a more compatible font such as Arial?

**Comment by damithc** [comment]
> Wouldn't it be better if AB uses a more compatible font such as Arial?

Yes, now that we face this problem (it wasn't a problem until now), we should indeed switch to a more common front.

**Comment by ziqing26** [comment]
> I use a M1 mac too and I have the same problem. I downloaded `Segoe` font and it seems to fix it partially. Is `Segoe` the only font used?
> 
> [Font Download](https://www.cufonfonts.com/font/segoe-ui-4)
> 
> <img alt="Screenshot 2021-08-23 at 10 33 31 AM" width="740" src="https://user-images.githubusercontent.com/53614454/130382118-bb3f66ef-421f-4714-9b9c-3a333353c8b0.png">

Same, I also face this issue after install `Segoe` font family including the light and semibold ones.

**Comment by damithc** [comment]
Guys, I've asked se-edu devs to see if we can fix this issue soon. Will keep you posted here.

**Comment by damithc** [comment]
Those facing font issues on M1 Macs, can you try this JAR file and let me know if it solves the problem?

[AB3-with-fonts.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7036583/AB3-with-fonts.zip)

**Comment by sivayogasubramanian** [comment]
Yes it does! Thanks Prof

<img width="740" alt="Screenshot 2021-08-24 at 1 49 56 PM" src="https://user-images.githubusercontent.com/53614454/130563084-3b01a67d-9c45-4b3f-93d3-52b5275652b1.png">

**Comment by damithc** [comment]
Thanks for confirming @sivayogasubramanian

**Comment by ziqing26** [comment]
Thank you, it works for me as well!

**Comment by kaixin-hc** [comment]
Thanks for the quick solution prof, I also faced this issue. However, while most of the programme appears to be fixed, the help file is still not fixed. 
<img width="739" alt="Screenshot 2021-08-25 at 9 06 17 AM" src="https://user-images.githubusercontent.com/59471320/130709647-648dad8c-5e9a-4c85-96d4-1f33c3809576.png">

**Comment by damithc** [comment]
> Thanks for the quick solution prof, I also faced this issue. However, while most of the programme appears to be fixed, the help file is still not fixed.
> <img alt="Screenshot 2021-08-25 at 9 06 17 AM" width="739" src="https://user-images.githubusercontent.com/59471320/130709647-648dad8c-5e9a-4c85-96d4-1f33c3809576.png">

Thanks for the heads up @kaixin-hc Will convey to the AB3 dev team.

**Comment by crypto-code** [comment]
Finally found a fix for the help window also. It was simply because the help window's fxml didn't initialize the CSS file. The avoid duplicates the fix is available here: #112.

**Comment by damithc** [comment]
Guys, please help me check the attached JAR file to see if it fixes the problem for M1 Mac, including the help window.

[ab3-with-fonts-v2.zip](https://github.com/nus-cs2103-AY2122S1/forum/files/7070339/ab3-with-fonts-v2.zip)

**Comment by NicolasCwy** [comment]
@damithc Works for me prof! (Intel chip, that wasn't working previously)

**Comment by sivayogasubramanian** [comment]
@damithc Works for M1 macs too! Thanks Prof!
