### ISSUE TITLE
Handling delete and complete tasks in Data file

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#67]
Hi all, adding new tasks to the data file is a simple write with an append option to a file. Whilst an operation like delete or complete task requires you to somehow search the file and amend/ delete the line.

One way I could think of is to rewrite the whole file with all the tasks that are still in the list when delete/ complete a task is called, but this seems to inefficient. Thoughts?

**Comment by damithc** [comment]
Related issue: https://github.com/nus-cs2103-AY2122S1/forum/issues/64
