### ISSUE TITLE
Move commits for certain files to another branch

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#68]
I have 2 branches A and B. I have worked on branch A making commits to it and finished a feature. I am now on branch B, where I realised some of the files on branch A share identical logic which I can just copy over. How can I bring over certain lines for these files? 

From what I understand, cherrypicking in git is for whole commits, but since branch B only requires  **specific code** in **specific files** I am not sure what is a good way to do this.

For more context this is because, level-7 introduces a subclass that level-8 can use ! And just copy pasting it over feels wrong

**Comment by huizhuansam** [comment]
I think this [thread](https://stackoverflow.com/questions/1526044/partly-cherry-picking-a-commit-with-git) answers your question, but I got confused just 2 replies in eksdee

**Comment by SkyBlaise99** [comment]
How about u merge A and B lol? By this you get the code in A, resolves merge conflict early and not later when you merge back to master

**Comment by NicolasCwy** [comment]
@huizhuansam Will check it out!

@SkyBlaise99 I think for this iP that would be the obvious choice, but this will probably me more applicable if the code implemented in A was a major feature that is not ready to be merged with B, especially since I only need some common code from A to be in B and not all of it.

But yes in this case it does seem tedious

**Comment by NicolasCwy** [comment]
Haven't tried @huizhuansam solution. I just wrote some code that made it work and merged it later.

Closing this for now
