### ISSUE TITLE
How to separate two merged branches?

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#69]
Hi
i use sourcetree to perform merge, but unfortunately, i did a fast forward merge (merge branch level 7 to master branch without creating a new commit), how do i separate these two and re-merge correctly? thx

**Comment by cookiedan42** [comment]
You can revert master branch to the commit before merge, then remerge the level 7 branch into master

**Comment by qinguorui2001** [comment]
thx, i got it.
