### ISSUE TITLE
Uncommitted changes on detached head

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#7]
https://mediaweb.ap.panopto.com/Panopto/Pages/Viewer.aspx?id=f16e2d7f-5f78-455c-830e-ac0900b7a747&start=119.115112

How do we end up in this scenario where there is an uncommitted change on an older commit? Shouldn't changes always be stashed(if it not on the HEAD) or committed?

**Comment by huizhuansam** [comment]
Let's use the time-travelling analogy:

1. The tip of the branch is the present.
2. Checking out previous commits is like travelling back in time in a time machine.
3. The .gitignore is like the stuff you bring along with the time machine that is not affected by the time travel, everything else that is not in .gitignore will be "reversed" in time.
4. At some point in your time travelling, you will meet two copies (versions) of the same stuff: `file_a` you brought with you in your time travel and `file_a` of the past.
5. If these 2 copies have not been changed between the present and the past, the situation you mentioned will not happen. 
6. However, if between the present and past there were some changes made to `file_a`, git will tell you that "I found 2 versions of the same file", so it will appear as unstaged changes.

This took me a while to understand, and even longer to explain LOL. Hope this helps.

**Comment by NicolasCwy** [comment]
This is interesting and unexpected. The temp file is committed sometime in the past(we shall call this point A) and only ignored later(Point B), why doesn't git use the .gitignore at Point A and show the temp file at Point A?

**Comment by huizhuansam** [comment]
> why doesn't git use the .gitignore at Point A and show the temp file at Point A
Git does use the `.gitignore` at Point A. Because the temp file is still being tracked at Point A, git notices the difference and sees it as a change. Conversely, if you check out any commit made after Point B, git does not care.

> given that we are committing the .gitignore file everytime we make a revision?
That is not the case, the `.gitignore` file is committed like any other file in git unless specified.

**Comment by damithc** [comment]
Thanks for the detailed explanation @huizhuansam 👍 
@NicolasCwy yes, it's a bit feels 'unexpected' at first. It will not happen if the file was git-ignored from the start (which is the more common case).

**Comment by NicolasCwy** [comment]
@huizhuansam @damithc Thank you both, it is clearer now.
