### ISSUE TITLE
Configuring git/Intellij to ignore generated files (such as ./data/duke.txt)

### ISSUE THREAD

**Issue by vigneshsankariyer1234567890** [nus-cs2103-AY2122S1/forum#70]
Hey guys, currently can't find any way to configure git/Intellij to ignore the generated files, such as the ./data/duke.txt file. I do not want to add it to my repository as it should not be present when the application is first run. Any ideas on how to do this?  

I tried adding the folder and the file to .gitignore but data/duke.txt is still detected by SourceTree or GitHubDesktop.
<img width="1252" alt="Screenshot 2021-08-23 at 4 08 13 PM" src="https://user-images.githubusercontent.com/68676914/130413103-67b1c38f-cf8c-46bd-ad84-3796217b5104.png">

I would optimally like to ignore all generated files. Any ideas on how to do so?

**Comment by NicolasCwy** [comment]
I think it would ignore the files after you commit your .gitignore file first

**Comment by SkyBlaise99** [comment]
Also remove the files from your github, or else even if you write it in `gitignore` it still get commited.

**Comment by VimuthM** [comment]
To add on, within IntelliJ, you can go configure options in Setttings -> Version Control -> Confirmation -> When to add files.

**Comment by vigneshsankariyer1234567890** [comment]
Hey guys, thank you for the help. I created a new commit to check if the files were still being added and thankfully it wasn't, so I did not have to remove the files from Github. I'll be trying out @VimuthM 's solution for a more permanent fix than simply adding to my .gitignore, thank you!
