### ISSUE TITLE
Intellij indentation configuration for switch statements

### ISSUE THREAD

**Issue by clyveycui** [nus-cs2103-AY2122S1/forum#71]
Regarding the java style guide as laid out here: https://se-education.org/guides/conventions/java/intermediate.htm

It is stated that
```
 The switch statement should have the following form: Note there is no indentation for case clauses.
 Configure your IDE to follow this style instead.
```

```java
switch (condition) {
case ABC:
    statements;
    // Fallthrough
case DEF:
    statements;
    break;
case XYZ:
    statements;
    break;
default:
    statements;
    break;
}
```

This is not the default indentation behavior of the Intellij IDE, and upon checking the settings, I couldn't find a way to configure the indentation rules such that it will follow this style. 

Does anyone know of a way to configure the settings such that the above style is followed?

**Comment by Chesterwongz** [comment]
Go to file > settings > Code Style > Java > Wrapping and Braces then scroll down to 'switch' statements.
![image](https://user-images.githubusercontent.com/70138507/130429583-bd5c3f73-f328-4be5-bb22-7f36560fc942.png)

**Comment by clyveycui** [comment]
Thank you! Guess I just didn't look hard enough...
