### ISSUE TITLE
Conventions about importing Sub-packages

### ISSUE THREAD

**Issue by BryannYeap** [nus-cs2103-AY2122S1/forum#73]
I'm trying to separate the classes further into sub-packages, but some classes from one sub-package uses instances of classes (sometimes many) from another sub-package.

1) Am I supposed to import them from 1 sub-package to another? Feels kind of weird.

2) Usually the convention is to not use * in imports. For example, we shouldn't use `java.util.*`, but how about importing other sub-packages? For example can I use `import duke.task.*;` , especially when I want to use all of the classes in that sub-package.

3) How should I order these imports? For example should the imports from other sub-packages within the same package come before the other imports like from `java.util`? And should they be separated by a blank line? I could not find these in the CS2103T website conventions.

**Comment by damithc** [comment]
> 3\. How should I order these imports? For example should the imports from other sub-packages within the same package come before the other imports like from `java.util`? And should they be separated by a blank line? I could not find these in the CS2103T website conventions.

@BryannYeap This is the import order used by AB3 https://se-education.org/guides/tutorials/intellijCodeStyle.html#tweak-import-order 
You can follow the same for the iP as well.

> 2\. Usually the convention is to not use * in imports. For example, we shouldn't use `java.util.*`, but how about importing other sub-packages? For example can I use `import duke.task.*;` , especially when I want to use all of the classes in that sub-package.

That rule in the coding standard applies to your own packages as well. So, wild card imports should not be used in this case as well.

> 1\. Am I supposed to import them from 1 sub-package to another? Feels kind of weird.

I guess you have to :-) If certain classes are meant to be used together, you can consider putting them in the same package.

**Comment by BryannYeap** [comment]
I see, thank you!
