### ISSUE TITLE
Convention for creating JUnit tests

### ISSUE THREAD

**Issue by houtenteo** [nus-cs2103-AY2122S1/forum#74]
Is there a convention where JUnit test classes should be created in the same package as the class it is testing? Or does it not matter where the JUnit test class is located?

**Comment by damithc** [comment]
@houtenteo I think this link has some guidelines:
![image](https://user-images.githubusercontent.com/1673303/130452924-f451e976-2c76-40ff-8943-c33b53d0e507.png)

**Comment by houtenteo** [comment]
@damithc Woops I somehow missed that. Thx prof.
