### ISSUE TITLE
How to move my commit to the right branch?

### ISSUE THREAD

**Issue by sueann-chua** [nus-cs2103-AY2122S1/forum#76]
I accidentally committed my changes to master branch instead, how can I move my commit to the right branch? (I have not pushed the commit yet)

**Comment by marcuspeh** [comment]
You can try if reset works. Have a look at [this](https://stackoverflow.com/questions/17429091/git-move-locally-committed-changes-to-the-new-branch-and-push). If it doesn't work, i guess u can always delete the commit and commit again

**Comment by VimuthM** [comment]
Try out marcus' link, I'll just give a high level view of what needs to be done:

 - Checkout a new branch (Now both master and newbranch are at the latest commit)
 - Move the master branch pointer HEAD back by n commits (Now master is outdated and only newbranch has the new commits)
 - Checkout master and force push to remote (The force push is required if your remote master is already updated to the later commits)
 - Checkout newbranch, set upstream and push

**Comment by sueann-chua** [comment]
can the steps provided in Marcus' link be applied if I had previously already created a branch called branch-Level-7? Or will I have to checkout a new branch

**Comment by marcuspeh** [comment]
> can the steps provided in Marcus' link be applied if I had previously already created a branch called branch-Level-7? Or will I have to checkout a new branch

Have u done anything in the branch? If not, it probs will still work

**Comment by sueann-chua** [comment]
yes, I did make a commit to the branch previously

**Comment by sueann-chua** [comment]
I also got this message when trying to checkout
![Screenshot 2021-08-24 at 11 59 08 AM](https://user-images.githubusercontent.com/77190772/130553723-d0ab9ef5-2a19-4a00-a7bb-59f9771ca8bc.png)

**Comment by sueann-chua** [comment]
> yes, I did make a commit to the branch previously

**Comment by marcuspeh** [comment]
> yes, I did make a commit to the branch previously

I guess you could only merge from master to the branch since reset will get rids of all previous commit in the branch (correct me if im wrong)

> I also got this message when trying to checkout
> ![Screenshot 2021-08-24 at 11 59 08 AM](https://user-images.githubusercontent.com/77190772/130553723-d0ab9ef5-2a19-4a00-a7bb-59f9771ca8bc.png)

U need remove the -b since u are not creating a new branch

**Comment by NicolasCwy** [comment]
@sueann-chua Not really following this thread but for git branching, including the -b flag means that you are trying to create a branch and then perform a checkout. I am assuming you are trying to checkout an existing branch so use
`git checkout branch-level-7` instead

Find out more here: [git checkout](https://git-scm.com/docs/git-checkout)

**Comment by sueann-chua** [comment]
Do I follow the suggestion to set remote as upstream? 
![Screenshot 2021-08-24 at 12 06 36 PM](https://user-images.githubusercontent.com/77190772/130554231-9d999891-b7ea-4457-b59d-e0c0acd75a41.png)

**Comment by damithc** [comment]
@sueann-chua this may be useful https://nus-cs2103-ay2122s1.github.io/website/schedule/week3/topics.html#pushing-a-branch-to-a-remote-repo
`-u` is the short form of `--set-upstream`
![image](https://user-images.githubusercontent.com/1673303/130554610-651ee822-f9f0-48c8-bb38-0dbf96f84088.png)

**Comment by marcuspeh** [comment]
> Do I follow the suggestion to set remote as upstream?
> ![Screenshot 2021-08-24 at 12 06 36 PM](https://user-images.githubusercontent.com/77190772/130554231-9d999891-b7ea-4457-b59d-e0c0acd75a41.png)

Yup if not it will not be pushed to github. Or you can do what Prof said

**Comment by sueann-chua** [comment]
After following the steps, my latest commit has disappeared and I can't find the changes I made. What do I do?

**Comment by marcuspeh** [comment]
What does git status show?

**Comment by sueann-chua** [comment]
I couldn't find the latest commit, but I had a separate copy saved so I made a new commit. Thanks for the help!

> What does git status show?
> 
> edit: maybe its cuz u are in the branch and the latest commit is in master
