### ISSUE TITLE
runtest.sh runs only the first line of input

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#78]
The runtest.sh runs only the first line of input and doesn't run rest of the inputs. When i run the program manually and enter the inputs, they all work which proves the problem lies in the test.

Anyone able to help?
Also given this problem, can i still submit my code.

**Comment by marcuspeh** [comment]
Did u create a new scanner everytime you codes get an input?

**Comment by softmagnet** [comment]
Yep right on the nail! Thanks Marcus! May i ask why is this happening though, what is going on with the scanner class and the test file.

**Comment by damithc** [comment]
> **May i ask why is this happening though, what is going on with the scanner class and the test file?**

@softmagnet I'm repeating your question for better visibility, in case someone would like to take a crack at it.

**Comment by bharathcs** [comment]
I'm just guessing here, how `System` actually works is beyond me, so please take this with a grain of salt:

`System.in` is a stream, and for every `Scanner` object you create it will take in `System.in` and try to read the next few bytes of the user input. Problem is, Java streams are meant to be consumed and cannot be reused. If you use up a position on a stream, you can't reread it, and the only way forward is to take up the next step in the stream.

Maybe if multiple Scanners try to read the same `System.in`, only the first one manages to move the position to the next point in the stream, and the rest are in an unreadable position?

**Comment by softmagnet** [comment]
thanks @bharathcs my man for helping to explain! I will close this thread now
