### ISSUE TITLE
Reverse commit error

### ISSUE THREAD

**Issue by weichang18** [nus-cs2103-AY2122S1/forum#79]
I did not read the question properly and did my level 8 on the master branch instead of a separate branch and have merged it with my level 7, is there a way to undo this mistake without losing all the deconflicting I have made. Also I tried to reverse commit and got this error
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks revert --no-edit 7e671d2dd048289f7870718506f06d5ba7318291
error: commit 7e671d2dd048289f7870718506f06d5ba7318291 is a merge but no -m option was given.
fatal: revert failed
Completed with errors, see above.

**Comment by damithc** [comment]
@weichang18 It's OK to leave as is. To satisfy the dashboard, you can create a branch (with the missing branch name), do some changes in that branch, and merge it back to master.

**Comment by weichang18** [comment]
Alright! Thank you so much prof!
