### ISSUE TITLE
Do public constructors need JavaDocs comments?

### ISSUE THREAD

**Issue by Chesterwongz** [nus-cs2103-AY2122S1/forum#82]
If so, what should we write?

**Comment by damithc** [comment]
I had a Java project open at the time, so I clicked on a call to the the`StringBuilder()`  constructor and pressed <kbd>Ctrl+Q</kbd> (the intellij shortcut for viewing documentation). The documentation that pops up is generated based on the JavaDoc comment of that constructor. You can follow that example in your code too.
![image](https://user-images.githubusercontent.com/1673303/130624146-1a1b6cd4-7a95-43c2-bd31-b16e2f24682d.png)
