### ISSUE TITLE
Javadoc coding standard

### ISSUE THREAD

**Issue by houtenteo** [nus-cs2103-AY2122S1/forum#83]
If for example my description for an @return or @param is too long, which format should I use? Can't seem to find anything mentioning this in the coding standard.

![image](https://user-images.githubusercontent.com/77191381/130624982-55d6cdc2-a570-40b1-aae5-800fe6776acc.png)
![image](https://user-images.githubusercontent.com/77191381/130625036-dc726901-e950-48d4-acb3-4eead96aec42.png)

**Comment by damithc** [comment]
When something is not covered by the given coding standard, you are free to choose which style you want to follow for that, but try to be consistent with the existing code (if any) and ensure everyone in the team follows the same (if it is a team project).

**Comment by houtenteo** [comment]
@damithc alright thx prof
