### ISSUE TITLE
fatal: Tag does not appear to be a git repository

### ISSUE THREAD

**Issue by jiarong15** [nus-cs2103-AY2122S1/forum#84]
Was trying to push my tag (Level-7) but encountered the above error. 
My commit is currently 1 commit ahead of the origin/master, origin/HEAD. That commit is tagged as Level-7

**Comment by Yukun99** [comment]
got any details like what steps you took to push, etc?

**Comment by jiarong15** [comment]
I made a new branch form the master called branch-Level-7 then proceeded to code the solutions and thereafter, git add . -> git commit -m "message" -> git tag Level-7 and then tried pushing

**Comment by Yukun99** [comment]
what was the command you used to push?

**Comment by damithc** [comment]
> and then tried pushing

What command did you use to push?

**Comment by jiarong15** [comment]
git push Level-7

**Comment by Yukun99** [comment]
> git push Level-7

try to google how the git push command works. Level-7 is not the remote you're pushing to, it's the tag name. git push takes in the remote as the first parameter

**Comment by jiarong15** [comment]
I see thanks!
