### ISSUE TITLE
JUnit testing

### ISSUE THREAD

**Issue by eezj35** [nus-cs2103-AY2122S1/forum#85]
Hi everyone, just to confirm, for the JUnit testing portion of the iP, is the minimum requirement just to create more than 2 tests in 1 test class? so if i have 2 test classes, each testing 3 public methods from 2 separate classes, will that meet the minimum requirement

**Comment by damithc** [comment]
> Hi everyone, just to confirm, for the JUnit testing portion of the iP, is the minimum requirement just to create more than 2 tests in 1 test class? so if i have 2 test classes, each testing 3 public methods from 2 separate classes, will that meet the minimum requirement

Yes, that's right @eezj35

**Comment by eezj35** [comment]
ok thanks so much prof! @damithc
