### ISSUE TITLE
Cannot run Duke.main() - Error: Could not find or load main class Duke

### ISSUE THREAD

**Issue by Jai2501** [nus-cs2103-AY2122S1/forum#9]
I have set up IntelliJ with JDK 11 from Oracle. I am still unable to run the Duke file.
Development Environment details: MacOS, Java Version 11.0.12

The Error Message Shown:
```
Error: Could not find or load main class Duke
Caused by: java.lang.ClassNotFoundException: Duke

Process finished with exit code 1
```

Resources visited for help (but didn't work):
[stackoverflow-1](https://stackoverflow.com/questions/42660125/java-lang-classnotfoundexception-when-running-in-intellij-idea/42660624#42660624)
[stackoverflow-2](https://stackoverflow.com/questions/10654120/error-could-not-find-or-load-main-class-in-intellij-ide)
[stackoverflow-3](https://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean)

**Comment by Yukun99** [comment]
Have you moved your classes into their own packages? I had the same problem after I did.

**Comment by Jai2501** [comment]
No, I haven't modified/moved any files.

**Comment by Yukun99** [comment]
Do you have a screenshot of how the project is setup in IntelliJ right now?

**Comment by Jai2501** [comment]
![image](https://user-images.githubusercontent.com/52578354/129479020-d8bd88dc-cf3b-45f7-bf32-26d126140ac6.png)

**Comment by Yukun99** [comment]
Try building your project from the top menu bar on the right, it's the green hammer icon.

**Comment by Jai2501** [comment]
That didn't work.

**Comment by damithc** [comment]
@Jai2501 some things you can try:
1. Do a small change in the code e.g., add an extra space and try again
2. try File -> Invalidate Caches 
3. Assuming you haven't started coding yet, no harm trying all the steps again with a fresh clone of the repo, **paying extra attention to the set up guide along the way** to ensure you are doing the steps exactly as specified.

**Comment by waynetee** [comment]
@Jai2501 I suggest you avoid having special characters such as colons and even spaces in your file/directory names

**Comment by Jai2501** [comment]
> @Jai2501 some things you can try:
> 
> 1. Do a small change in the code e.g., add an extra space and try again
> 2. try File -> Invalidate Caches
> 3. Assuming you haven't started coding yet, no harm trying all the steps again with a fresh clone of the repo, **paying extra attention to the set up guide along the way** to ensure you are doing the steps exactly as specified.

Prof, I tried the above mentioned steps, but the issue still persists.

**Comment by Jai2501** [comment]
> @Jai2501 I suggest you avoid having special characters such as colons and even spaces in your file/directory names

Let me try a different directory keeping this in mind.

**Comment by marcuspeh** [comment]
Maybe you can try if the green play button beside the main method works. If you have a ss of your configuration, can send it here too.

**Comment by Jai2501** [comment]
> Maybe you can try if the green play button beside the main method works. If you have a ss of your configuration, can send it here too.

that also did not work.

![image](https://user-images.githubusercontent.com/52578354/129485627-39d8a36e-73e7-40c9-8e64-5f92c735052c.png)

**Comment by damithc** [comment]
> > @Jai2501 I suggest you avoid having special characters such as colons and even spaces in your file/directory names
> 
> Let me try a different directory keeping this in mind.

Did this work?

**Comment by simonjulianl** [comment]
Hi, I suggest checking this post out [stack-overflow](https://stackoverflow.com/questions/17300318/error-classnotfoundexception-in-intellij-idea), if it's not possible, for me personally I just use File > New > Project from Version Control (and connect it to your GitHub) and let Intellij configure the paths. 

Hope this help

**Comment by Jai2501** [comment]
> > > @Jai2501 I suggest you avoid having special characters such as colons and even spaces in your file/directory names
> > 
> > 
> > Let me try a different directory keeping this in mind.
> 
> Did this work?

Yes! Finally this worked. Thank You Everyone!
@waynetee @damithc @Yukun99 @marcuspeh @simonjulianl

**Comment by damithc** [comment]
Good to hear that @Jai2501 
Special kudos to @waynetee for spotting the colon in the file path. 💯
