### ISSUE TITLE
Unclear about fork and branch workflow

### ISSUE THREAD

**Issue by ngsengleng** [nus-cs2103-AY2122S1/forum#90]
For week 3 i think we are supposed to follow a workflow as follows:
do changes in 7, do changes in 8, go to master, merge 7, tag 7, merge 8, tag 8, push master push branches push tags
but i did something along the lines of:
changes in 7, push to branch 7, changes in 8, push to branch 8, go to master merge 7 and 8, push master, push tags.
is this considered acceptable and if not how am i supposed to undo it (or do it correctly)?

**Comment by radiankrisno** [comment]
Hi, can you clarify what you mean by the push to branch 7, you can check whether you do it correctly or not by checking the git tree and see whether both the branches branch from the same commit or not!

**Comment by ngsengleng** [comment]
<img width="1025" alt="Screenshot 2021-08-25 at 11 02 18 AM" src="https://user-images.githubusercontent.com/48010218/130719378-f0f24609-a7f2-45f5-acea-df8b0f7c1087.png">

does this look right? push to branch 7 means im pushing to the remote branch labelled branch-level-7

**Comment by luffingluffy** [comment]
It doesn't really matter when you push as what you are doing when you push is just updating the copy on GitHub with your local copy. And yep, when you do a `git push` you are pushing to your remote branch on GitHub (you can check which branch you are on using `git status`).

**Comment by damithc** [comment]
@luffingluffy is right. It's fine as long as you push eventually (_when_ doesn't matter). You can also check the iP progress dashboard to see if your branches have been deteted.

**Comment by ngsengleng** [comment]
ok thanks for the clarification!
