### ISSUE TITLE
Importance of preventing fast forward merge

### ISSUE THREAD

**Issue by Justinhoejj** [nus-cs2103-AY2122S1/forum#91]
Just noticed I did not prevent fast forward merge on branch-Level-7, can I clarify if I have to ensure that the merge of branc-Level-7 is not fast forward? Additionally, what are the benefits of non fast forward merge and how can I remedy an already fast forwarded merge?

![image](https://user-images.githubusercontent.com/68779715/130719001-dabc656a-87ee-48ab-a2f4-9df094be4f54.png)

**Comment by damithc** [comment]
> Just noticed I did not prevent fast forward merge on branch-Level-7, can I clarify if I have to ensure that the merge of branc-Level-7 is not fast forward?

It's fine to leave as it is.

> Additionally, what are the benefits of non fast forward merge and how can I remedy an already fast forwarded merge?

One benefit is it is easy to see the start and end of the branch visually. Plus, the merge commit shows the total effect of the branch.

**Comment by luffingluffy** [comment]
@Justinhoejj Also to add on, but the main difference is that FF merge will not create a merge commit (it simply moves the tip of the current branch to the target branch). And as Prof mentioned, the advantage is of non-ff merge is to be able to see branches clearly. 

And for future reference, you can move the HEAD down to before you merged by using `git reset --hard HEAD~<number of commit>` then from there you can remerge the branches again (not sure if theres a more efficient way of doing this but that's what I did).

**Comment by AllardQuek** [comment]
Why doesn't Git set the non fast forward merge as the default? Are there any disadvantages to using it?

**Comment by damithc** [comment]
> Why doesn't Git set the non fast forward merge as the default? Are there any disadvantages to using it?

@AllardQuek This issue is closed. You might want to post this as a new issue for better visibility.

**Comment by AllardQuek** [comment]
Sure, thanks for letting me know!
