### ISSUE TITLE
Unable to build dependencies and import packages from main folder to test folder for JUnit

### ISSUE THREAD

**Issue by chengseong** [nus-cs2103-AY2122S1/forum#92]
I am currently using Intellij IDEA community edition 2021.2.1

I am currently stuck on the JUnit test as trying to import packages from the main folder to use with my ParserTest results in an error. "Cannot Resolve 'Task' Symbol". 

I am also unable to build dependencies in my code as clicking on "search for dependencies" does nothing.

The code i am trying to test with is below

```java
package duke;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import duke.task.ToDo;

public class ParserTest {
    @Test
    public void testParse() {
        String command1 = "todo read book";
        assertEquals(new ToDo("read book").toString(), Parser.parse(command1));
    }
}

```

**Comment by damithc** [comment]
@chengseong when you go to `File` -> `Project structure` and click on `Modules`, do you see modules `main` and `test` like this?
![image](https://user-images.githubusercontent.com/1673303/130751606-79e9024c-78f2-406a-9c52-a17156214571.png)

If not, what do you see?

**Comment by chengseong** [comment]
Oh no i don't. I only see test
![image](https://user-images.githubusercontent.com/65647738/130755116-228d4dd2-9cf8-4055-b6d2-15b0b7f0f5b1.png)

**Comment by damithc** [comment]
@chengseong in that case, first create a `main` module the same way you created the `test` module.

**Comment by damithc** [comment]
You should choose the `src\main` folder (not `src\main\java`) when creating the `main` module.

**Comment by chengseong** [comment]
Okay I have done so and it now looks like this
![image](https://user-images.githubusercontent.com/65647738/130756484-69aa3c44-345f-4d9c-b3ae-34b938f81669.png)

But I am still having the same issue with not being able to resolve symbols

**Comment by damithc** [comment]
Now, intellij should allow you to set `main` module as a dependency of the `test` module. (Step 8 in the JUnit tutorial).

**Comment by chengseong** [comment]
Oh i think it works now. Thank you!
