### ISSUE TITLE
Deleted iP module

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#93]
Hi everyone I accidentally deleted the module named iP which was found here. I tried adding iP back as a module but it imported test and main instead
<img width="907" alt="image" src="https://user-images.githubusercontent.com/25302138/130775451-d9629cd9-b40e-421d-8d32-9cb48f8835a7.png">

Because of that I am unable to see other files in the iP directory such as bin and text-ui-test although it exists
<img width="310" alt="image" src="https://user-images.githubusercontent.com/25302138/130775553-cf9796ec-9f8c-467c-bfac-3420ac8a01ac.png">
<img width="745" alt="image" src="https://user-images.githubusercontent.com/25302138/130775573-1bbbcaf7-c064-4c1d-b166-f6c62f4b8e4b.png">

**Comment by damithc** [comment]
@NicolasCwy Try selecting `Project files` here:
![image](https://user-images.githubusercontent.com/1673303/130776923-4651e84f-76b1-4365-a6d0-b812b99b3fdf.png)

**Comment by NicolasCwy** [comment]
@damithc Worked like a charm 🎉 Thanks prof!
