### ISSUE TITLE
Branch not detected on iP dashboard

### ISSUE THREAD

**Issue by wilburrito** [nus-cs2103-AY2122S1/forum#94]
As the title suggests, my branch-Level-7 and branch-Level-8 are not marked as done despite me having merged them a few days ago. How can I resolve this? I am already at step 5 of the tasks (A-CodingStandard, etc.). Should I be worried?

Thanks in advance for the replies.

**Comment by marcuspeh** [comment]
Did u push both branch to github

**Comment by damithc** [comment]
@wilburrito  Make sure you've pushed the master branch AND the other two branches, _AFTER_ you've merged them to master (the dashboard only counts merged branches) and wait for the next dashboard update. Last time we checked, the branches were unmerged.
![image](https://user-images.githubusercontent.com/1673303/130777569-0c6ac577-147b-4a6f-943d-8702043cd48a.png)

**Comment by wilburrito** [comment]
@marcuspeh perhaps I missed that out... Thanks for the reply.

@damithc Thanks for the reply prof, I'm actually quite lost on how to rectify this. Do I need to revert my commits in order to do so?

**Comment by damithc** [comment]
@wilburrito how does the version tree looks like in your SourceTree?

**Comment by wilburrito** [comment]
@damithc I am using CLI, unfortunately. Attached is the version tree produced by doing gitk --all:

![cb0e0abe622f523eeae63a008dfdb6f8](https://user-images.githubusercontent.com/77230639/130784316-3748faad-78de-4b6a-8074-5b82eaf3183e.png)

**Comment by damithc** [comment]
Try pushing the two branches again (most likely you didn't push those branches after you merged them). Note that pushing the master branch doesn't automatically push the branches already merged to it. You have to push the branches separately.

**Comment by wilburrito** [comment]
Okay, it is telling me to pull before I am allowed to push. I suppose I have to do so? 

![84c2ee2a306c2a2fbf922a3c6da9e7d6](https://user-images.githubusercontent.com/77230639/130787065-d68d9ad9-4f56-4c93-9216-0f3c7e772963.png)

**Comment by wilburrito** [comment]
Okay, I have pushed the branches separately. Thanks for the help prof.

**Comment by GabrielSimbingyang** [comment]
Hi @wilburrito . 

This is Gabriel from your senior batch. If this issue has been resolved, please remember to close this thread in order to keep the forums neat and tidy. However, if it isn't , could you give us an update on the situation?

Thanks!

Gabriel

**Comment by wilburrito** [comment]
Hi @GabrielSimbingyang, I am currently still trying to resolve the issue. Will provide an update soon! Apologies for the late reply.
