### ISSUE TITLE
Forgot to disable fast forward when merging branch

### ISSUE THREAD

**Issue by kawaiigabrielneko** [nus-cs2103-AY2122S1/forum#95]
I forgot how to turn off fast forward when merging branch. I do not know how to restore it to its state before merging.

**Comment by damithc** [comment]
Assuming you are on the master branch and you haven't added any more commits after the incorrect merge, on SourceTree,
1. Right-click on the last commit of original master branch (i.e., before merging the new branch)
2. Choose 'reset current branch to this commit', and choose a hard reset in the next dialog

Now you should be where you were before you merged the branch.

**Comment by kawaiigabrielneko** [comment]
Thank you for the advice. However, I have already merged the other branch (properly) and resolved the merge conflict.

**Comment by damithc** [comment]
Then, just leave it be. It doesn't affect grading.

**Comment by GabrielSimbingyang** [comment]
Hi @kawaiigabrielneko ,

This is Gabriel from your senior batch. If this issue has been resolved, please remember to close this thread in order to keep the forums neat and tidy. However, if it isn't, could you give us an update on the situation?

Thanks!

Gabriel

**Comment by damithc** [comment]
Closing, as @kawaiigabrielneko hasn't responded.
